### ISSUE TITLE
Lack of example for canonical mapping use case

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#10]
[Use Case #17 - Canonical mapping of CSV](http://w3c.github.io/csvw/use-cases-and-requirements/index.html#UC-CanonicalMappingOfCSV)

This use case lacks a concrete example to further illustrate the concerns. Whilst the concerns outlined above are relevant for a gamut of open data publication, it would be useful to include an example dataset here - which might be subsequently used in test suites relating to the motivating requirements of this use case.

It may be appropriate to merge this use case with [UC-IntelligentlyPreviewingCSVFiles](http://w3c.github.io/csvw/use-cases-and-requirements/#UC-IntelligentlyPreviewingCSVFiles) as that is concerned with using an interim JSON encoding to support intelligent preview of unannotated tabular data.

**Comment by JeniT** [comment]
@6a6d74 Suggest we decide that it's fine as is and close the issue.

**Comment by 6a6d74** [comment]
Agreed. No further action required.
