### ISSUE TITLE
`predicateUrl`, `urlTemplate` and `default` as additional Inherited Properties?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#101]
Properties `predicateUrl`, `urlTemplate` and `default` have been mooted in discussions during and since the F2F meeting as additional Inherited Properties. These do not yet appear in the metadata vocabulary document.

**Comment by JeniT** [comment]
`urlTemplate` was there at http://w3c.github.io/csvw/metadata/#schema-urlTemplate but I have also just added `predicateUrl` and `default`. If that's OK, please close the issue.

**Comment by 6a6d74** [comment]
We also talked about being able to set a `urlTemplate` for the cell value (via the column description) in addition to the row (via the schema). Given the use of `urlTemplate` for both schema and column, the property can't be an inherited property.

See the example below ...

Snippet from column description:

```
{
      "name": "species",
      "title": "Species",
      "dc:description": "The species of the tree.",
      "urlTemplate": "http://example.org/species/{species}",
      "datatype": "anyURI"
}
```

So let's say that a row of my tree data says:

```
GID,On Street,Species,Trim Cycle,Inventory Date
1,ADDISON AV,Celtis australis,Large Tree Routine Prune,10/18/2010
{snip}
```

then evaluating the URI Template `http://example.org/species/{species}` gives me http://example.org/species/Celtis%20australis which, in my make believe world, is a definition for the species "Celtis australis" (commonly known as the european nettle tree - says Google!).

See requirement [R-AssociationOfCodeValuesWithExternalDefinitions](http://w3c.github.io/csvw/use-cases-and-requirements/#R-AssociationOfCodeValuesWithExternalDefinitions) and its dependent requirement [R-URIMapping](http://w3c.github.io/csvw/use-cases-and-requirements/#R-URIMapping).

(this discussion is somewhat related to ISSUE #96 where I ask if `urlTemplate` could be treated more like a datatype)

**Comment by iherman** [comment]
I think you are right. We have 3 different URI setting (template or not) and they should all have different names...

Ivan

> On 16 Dec 2014, at 15:29 , Jeremy Tandy notifications@github.com wrote:
> 
> We also talked about being able to set a urlTemplate for the cell value (via the column description) in addition to the row (via the schema). Given the use of urlTemplate for both schema and column, the property can't be an inherited property.
> 
> See the example below ...
> 
> Snippet from column description:
> 
> {
>       "name": "species",
>       "title": "Species",
>       "dc:description": "The species of the tree.",
>       "urlTemplate": "http://example.org/species/{species}",
>       "datatype": "anyURI"
> }
> 
> So let's say that a row of my tree data says:
> 
> GID,On Street,Species,Trim Cycle,Inventory Date
> 1,ADDISON AV,Celtis australis,Large Tree Routine Prune,10/18/2010
> {snip}
> 
> then evaluating the URI Template http://example.org/species/{species} gives me http://example.org/species/Celtis%20australis which, in my make believe world, is a definition for the species "Celtis australis" (commonly known as the european nettle tree - says Google!).
> 
> See requirement R-AssociationOfCodeValuesWithExternalDefinitions and its dependent requirement R-URIMapping.
> 
> (this discussion is somewhat related to ISSUE #96 where I ask if urlTemplate could be treated more like a datatype)
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
Just to reinforce this: I have read through the RDF conversion document, and I got confused by the usage of `urlTemplate`. There are two usages for this:
1. When in a column description, it establishes the URI Resource identifying a row's id
2. When in row processing, it sets the value of the object as a URI Resource

We should not conflate these two usages.

**Comment by 6a6d74** [comment]
Can we have different names then?

**Comment by iherman** [comment]
What about:

subjectUrlTemplate
propertyUrl
objectUrlTemplate

Ivan

> On 17 Dec 2014, at 15:50 , Jeremy Tandy notifications@github.com wrote:
> 
> Can we have different names then?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
See #96

**Comment by gkellogg** [comment]
RESOLUTION: resolve #98 and #101 as Gregg suggests (from http://www.w3.org/2015/01/28-csvw-minutes.html).
