### ISSUE TITLE
Should text-directionality be enforced in mapping output?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#102]
Where cell values do not indicate a _strong type_ (as defined in [UNICODE-BIDI](http://unicode.org/reports/tr9/)) and `text-direction` is set to either `rtl` or `ltr`, should unicode text direction control characters be added to the string value used in the output graph in order to maintain the explicit text directionality specified in the metadata?
- if `text-direction` is set to `rtl`, then the unicode character `RLI` (RIGHT-TO-LEFT ISOLATE) `U+2067` shall be prepended to the cell value to set direction right-to-left
- if `text-direction` is set to `ltr`, then the unicode character `LRI` (LEFT-TO-RIGHT ISOLATE) `U+2066` shall be prepended to the cell value to set direction left-to-right
- the unicode character `PDI` (POP DIRECTIONAL ISOLATE) `U+2069` shall be appended to the cell value to terminate the range set by `RLI` or `LRI`

Additionally, where cell values _do_ include a _strong type_, should the unicode character `FSI` (FIRST STRONG ISOLATE) `U+2068` be prepended to the cell value to set direction according to the first strong character - along with appending unicode character `PDI` (POP DIRECTIONAL ISOLATE) `U+2069` to terminate the range set by `FSI`?

**Comment by iherman** [comment]
Hm. I am not really familiar with all these details but, instinctively, I would be scared to massage the unicode encoding of the output. My instinct would be, at this moment, to output the cell value as is, and we can then cross check with the I18N people to see if they see some problems.

My 2 cents...

Ivan

> On 11 Dec 2014, at 16:11 , Jeremy Tandy notifications@github.com wrote:
> 
> Where cell values do not indicate a strong type (as defined in UNICODE-BIDI) and text-direction is set to either rtl or ltr, shouldunicode text direction control characters be added to the string value used in the output graph in order to maintain the explicit text directionality specified in the metadata?
> 
>   • if text-direction is set to rtl, then the unicode character RLI (RIGHT-TO-LEFT ISOLATE) U+2067 shall be prepended to the cell value to set direction right-to-left
>   • if text-direction is set to ltr, then the unicode character LRI (LEFT-TO-RIGHT ISOLATE) U+2066 shall be prepended to the cell value to set direction left-to-right
>   • the unicode character PDI (POP DIRECTIONAL ISOLATE) U+2069 shall be appended to the cell value to terminate the range set by RLI or LRI
> Additionally, where cell values do include a strong type, should the unicode character FSI (FIRST STRONG ISOLATE) U+2068 be prepended to the cell value to set direction according to the first strong character - along with appending unicode character PDI (POP DIRECTIONAL ISOLATE) U+2069 to terminate the range set by FSI?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
I agree with @iherman that we shouldn't manipulate the Unicode values.

**Comment by 6a6d74** [comment]
OK - I've removed this section from both mapping documents.

`text-direction` is no longer listed as an inherited property that the mapping docs care about.

In case we want to add this back later, I've pasted the HTML from the doc below:

---

```
      <dt id="metadata-property-text-direction"><code>text-direction</code></dt>
      <dd>
        <p>Where <a href="http://www.w3.org/TR/tabular-data-model/#dfn-string-value">cell values</a> do not indicate a <em>strong type</em> (as defined in [[!UNICODE-BIDI]]) and metadata property <code>text-direction</code> is set to either <code>rtl</code> or <code>ltr</code> then unicode text direction control characters will be added to the string value used in the <a title="output graph">output graph</a> in order to maintain the explicit text directionality specified in the metadata:</p>
          <ul>
            <li>if <code>text-direction</code> is set to <code>rtl</code>, then the unicode character RLI (RIGHT-TO-LEFT ISOLATE) <code>U+2067</code> SHALL be prepended to the <a href="http://www.w3.org/TR/tabular-data-model/#dfn-string-value">cell value</a> to set direction right-to-left</li>
            <li>if <code>text-direction</code> is set to <code>ltr</code>, then the unicode character LRI (LEFT-TO-RIGHT ISOLATE) <code>U+2066</code> SHALL be prepended to the <a href="http://www.w3.org/TR/tabular-data-model/#dfn-string-value">cell value</a> to set direction left-to-right</li>
            <li>the unicode character PDI (POP DIRECTIONAL ISOLATE) <code>U+2069</code> SHALL be appended to the <a href="http://www.w3.org/TR/tabular-data-model/#dfn-string-value">cell value</a> to terminate the range set by RLI or LRI</li>
          </ul>
        <p class="issue" data-number="102">Should text-directionality be enforced in mapping output?</p>
      </dd>
```
