### ISSUE TITLE
Possibility to declare the type of a row?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#104]
(Issue raised by Tim Robertson on [email](http://lists.w3.org/Archives/Public/public-csv-wg/2014Dec/0041.html))

> Is there any scope to declare the type of a row?  E.g. each row is an instance of <SomeClass>.  
> 
> It’s one of the things that the standard behind use case case 21 (Darwin Core Archives) supports, but we’ve been discussing whether we should have strongly typed rows or let the values contained in the properties define it in the future, and perhaps using Owl (or similar) to document the classes.
> 
> Have you any insight as to whether that is being discussed, perhaps in the RDF serialisation work, or if it has any place here?

**Comment by iherman** [comment]
I tried to look up previous discussions, but I did not see any written trace of this (although I may have missed something).

There are two different case that we have to separate
1. Possibility to assign _one_ common type for each row
2. Possibility to assign a specific type for each row

No. 1 is relatively easy to do, of course, because it can be managed with a schema level term, much like we do to specify the URL for a row using a URL Template. Actually, if we allow the possibility of a template instead of a fixed URL, we do some sort of a No.2-lite, without too much additional problems.

A full blown No.2 is 'covered' by a more general issue that we discussed at the F2F. Indeed, there is a resolution, whereby:

"RESOLUTION: We drop the ability in the schema to specify metadata at the row or cell level: schemas are only used to define columns"

see

http://www.w3.org/2014/10/28-csvw-minutes.html#res3

which makes it pretty much impossible to do No.2 (except for the No.2-lite).

(Copy of the [email answer to the original mail](http://lists.w3.org/Archives/Public/public-csv-wg/2014Dec/0043.html))

**Comment by JeniT** [comment]
@iherman I don't think the resolution that you quote covers this case. We're not talking about metadata for row 9 in every table adhering to a particular schema, but rather the case where there's something like:

```
file,type,owner
A.txt,Text,Bob
B.jpeg,Image,Jane
```

and you want to say that the type of `A.txt` is `Text` and the type of `B.jpeg` is `Image`.

I think we ought to have a `typeUrlTemplate` property for this, which could either be set to a static URL or to one based on the values of particular columns in the table.

**Comment by iherman** [comment]
@JeniT I think this is what I called 'No.2-lite' in my comment. And yes, I think adding that is easy and simple with the mechanism we already have, and there is already an existing use case for it...

**Comment by timrobertson100** [comment]
I think there are still 2 cases here:
1. Where metadata can declare that each row in a table is of "type x" (use 21 does exactly that with the `rowType` in the table metadata)
2. Where a field in a row can indicate the type expected by the row (as per @JeniT example above)

Both of these could be references out to a schema.  

Use case 21 does 1) where the rowType is `http://rs.tdwg.org/dwc/terms/Occurrence` for which there is a registered schema of `http://rs.gbif.org/core/dwc_occurrence.xml`.  This is of course domain specific, and I was hoping this group could provide recommendations such that you could either register a URI to an Owl class or similar, so that csv readers could configure themselves upfront knowing what they would expect as they start reading the files, with the schema also informing any validators one might write.

Use case 21 includes the situation where conceivably 2 CSVs might be identical in structure (e.g. identical columns) and content, but one is documenting evidence of existence of a species while the other documents how a taxonomist might place the species in a names hierarchy / taxonomy.  The DwC-A standard allows you to register `rowType=http://rs.tdwg.org/dwc/terms/Occurrence` and `rowType=http://rs.tdwg.org/dwc/terms/Taxon` on the table metadata to distinguish between this.

**Comment by iherman** [comment]
Unless I miss something, I think both cases are covered by the introduction of `typeURLTemplate`, as proposed by @JeniT.
1. Your Use case (1) is directly covered by providing a suitable value in the metadata
2. Your use case (2) is indirectly covered by the fact that there is a hierarchy of metadata, whose merge is what will, at the end of the day, determine the final value. Ie, if the identical columns (and other data) are described through some generic metadata file in the, say, directory where the data are stored, and the table specific values are in specific files related to a specific dataset, then the latter may (a) refer to the former for the general data and (b) include a specific value for the type.

I may miss something, though.

**Comment by timrobertson100** [comment]
Thanks @iherman - relating to your "...by providing a suitable value in the metadata..."

Where in [the metadata](http://w3c.github.io/csvw/metadata/index.html) would you do that please?  The [example for use case 21](https://github.com/w3c/csvw/blob/gh-pages/examples/use-case-data-files/use-case-21--publication-biodiversity-information-from-gbif-using-darwin-core-archive-standard/sinfonevada-example.json) has `@type=http://rs.tdwg.org/dwc/terms/Occurrence` while the metadata guide says `@type must be set to "Table"`.  If I can understand it, I'd like to work up a more complete example, and submit it for verification.  Thanks

**Comment by iherman** [comment]
If I use the latest proposal of @JeniT, the metadata would look something like

```
 "schema": {
   "typeUrlTemplate" : "http://rs.tdwg.org/dwc/terms/Occurrence",
    "columns": [{
      "name": "GID",
      "title": [
        "GID",
        "Generic Identifier"
      ],
      "dc:description": "An identifier for the operation on a tree.",
      "datatype": "string",
      "required": true,
      "unique": true
    }, {
     ...
```

and the conversion algorithm would take the value of `typeUrlTemplate` to generate a value for each row.

**Comment by timrobertson100** [comment]
Are there any expectations or restrictions on what typeUrlTemplate would / could return if resolved?

To which term/property would the value be assigned?  (it can't be assumed as DublinCore:type, as that can genuinely exist in the row already).

**Comment by iherman** [comment]
Tim,

I am not absolutely sure I understand your questions. I will try to answer nevertheless:-)
- the value of typeUrlTemplate can be any URI; the value is either a constant, like now, or can be a template whose variable are the column names and will be expanded to the value of the specific column.
- the value is used as an object for the predicate rdf:type

So if the data is

name1, name2, name3
val11,  val12,  val13
val21,  val22,  val23

and the value of typeUrlTemplate is "http://example.org

then the generated RDF will be something like

<URIforRow1> rdf:type "http://example.org ;
   <PredicateForName1> "val11" ;
   <PredicateForName1> "val12" ;
   <PredicateForName1> "val13" .
<URIforRow2> rdf:type "http://example.org ;
   <PredicateForName1> "val21" ;
   <PredicateForName1> "val22" ;
   <PredicateForName1> "val23" .

(the URIs and predicate uri-s are defined by other metadata entries, not given here).

Alternatively, if the template is "http://example.org/{name1}" then we get

<URIforRow1> rdf:type "http://example.org/val11 ;
   <PredicateForName1> "val11" ;
   <PredicateForName1> "val12" ;
   <PredicateForName1> "val13" .
<URIforRow2> rdf:type "http://example.org/val21 ;
   <PredicateForName1> "val21" ;
   <PredicateForName1> "val22" ;
   <PredicateForName1> "val23" .

Is this what you are looking for? (@JeniT, I hope my interpretation is the same as yours...)

Ivan

> On 15 Dec 2014, at 15:15 , timrobertson100 notifications@github.com wrote:
> 
> Are there any expectations or restrictions on what typeUrlTemplate would / could return if resolved?
> 
> To which term/property would the value be assigned? (it can't be assumed as DublinCore:type, as that can genuinely exist in the row already).
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by timrobertson100** [comment]
Thanks for bearing with me @iherman that is _really_ helpful. 

This leads me back to the original question on the mailing list, in that this isn't reflected in [the JSON serialization proposal](http://w3c.github.io/csvw/csv2json/) (presumably because the concept was first introduced above) and I think it should be so that CSV to JSON to CSV to RDF to CSV can be done reliably and without loosing information along the way.

**Comment by iherman** [comment]
> On 15 Dec 2014, at 16:30 , timrobertson100 notifications@github.com wrote:
> 
> Thanks for bearing with me @iherman that is really helpful.
> 
> This leads me back to the original question on the mailing list, in that this isn't reflected in the JSON serialization proposal (presumably because the concept was first introduced above) and I think it should be so that CSV to JSON to CSV to RDF to CSV can be done reliably and without loosing information along the way.

Indeed, because this came up only now:-)

I am not even sure it will and indeed it should go into the FPWD verision; we would like to get it out as soon as possible. A FPWD is by no means complete, nor is the intention it should be. Being on the issue list means that this is something we will have to pick up eventually.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
Hi. See ISSUE #82. I was thinking about need of Darwin Core to specify the type of object for a row when I wrote it ...

(apologies if this is a duplicate posting; long thread, little time :-) )

**Comment by iherman** [comment]
I propose to close this issue. The resolution of #26 gives the possibility to use URL templates for defining row types; although that may not cover all the cases but it covers some, and we decided not to have row level metadata.

**Comment by JeniT** [comment]
Closing as duplicate.
