### ISSUE TITLE
Should there be an option for unordered lists in RDF mapping?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#107]
Lists are created when a cell value is parsed because metadata property `separator` has been specified for the column. These lists are implicitly ordered. Our use cases include the example of a list of authors for scientific journal papers - and these guys very much care about the order in which each author gets included!

In the RDF mapping, we can use RDF List [RDF Schema 1.1, Section 5.2.1 rdf:List](http://www.w3.org/TR/rdf-schema/#ch_list) to express the ordered nature of the list. However, given the moderate overhead of RDF's list model, should there be an option for unordered lists?

**Comment by iherman** [comment]
> On 16 Dec 2014, at 12:36 , Jeremy Tandy notifications@github.com wrote:
> 
> Lists are created when a cell value is parsed because metadata property separator has been specified for the column. These lists are implicitly ordered. Our use cases include the example of a list of authors for scientific journal papers - and these guys very much care about the order in which each author gets included!
> 
> In the RDF mapping, we can use RDF List RDF Schema 1.1, Section 5.2.1 rdf:List to express the ordered nature of the list. However, given the moderate overhead of RDF's list model, should there be an option for unordered lists?

Let us try to leave this open for now, and let us go for lists. We can always come back to this later if the use cases and the community wants that.

Lists in RDF are awful when they are spelled out (much like LISP structures) but both JSON-LD and Turtle (and, actually, even RDFa 1.1) has decent syntaxes for it that makes them perfectly readable and fine.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
Agreed.

**Comment by gkellogg** [comment]
Perhaps this can come from a term description in the metadata context indicating if the `@container` model for the term associated with the column property is `@list` or not.

**Comment by JeniT** [comment]
Suggested resolution: cell values that are sequences are always mapped to `rdf:List`s.

Alternative resolution: we introduce a `ordered` property to the metadata document (defaulting to `false`) and use that to determine whether to create a `rdf:List` or multiple triples.

**Comment by gkellogg** [comment]
Makes sense to me.

**Comment by iherman** [comment]
Let us make it simple: they are lists.

Ivan

> On 04 Feb 2015, at 18:07 , Jeni Tennison notifications@github.com wrote:
> 
> Suggested resolution: cell values that are sequences are always mapped to rdf:Lists.
> 
> Alternative resolution: we introduce a ordered property to the metadata document (defaulting to false) and use that to determine whether to create a rdf:List or multiple triples.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
Resolved at Feb F2F. We introduce an `ordered` property. When a column defines a `separator`, cell values are converted to a `rdf:List` if `ordered` is `true`, and to multiple values for the same property if `ordered` is `false`; the default is that `ordered` is `false`.

**Comment by 6a6d74** [comment]
csv2rdf doc now has a clause about when to use `rdf:List` or repeated triples based on value of `ordered` property. csv2json doc says that JSON ignores the `ordered` property as JSON arrays are implicitly ordered.

**Comment by 6a6d74** [comment]
(oops; premature close ... think this is still pending editor action on metadata doc)
