### ISSUE TITLE
How to determine language encoding

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#11]
[Use Case #19 - Supporting Right to Left (RTL) Directionality](http://w3c.github.io/csvw/use-cases-and-requirements/index.html#UC-SupportingRightToLeftDirectionality)

From internationalization perspective how is the proper language encoding is determined?

**Comment by JeniT** [comment]
Does this question have to be addressed by the Use Case Document? I think it's fine as it is. Can't we close @6a6d74?

**Comment by 6a6d74** [comment]
There is now a valid discussion in both syntax and metadata documents
