### ISSUE TITLE
Restructuring mapping docs with common table-level processing

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#112]
[from @iherman by email]

another thing that I realized since I sent my previous mail. To emphasize again, I do not think this should be done _now_, but to consider it after the FPWD publication.

Several steps in 4.1.1. are not JSON specific, namely the creation of what you called column description objects. Although you have not published the RDF mapping yet, I would expect that to include the very same steps. The reason is that, in fact, the generation of JSON is based on what I would also call an expanded metadata, which essentially means the fully expanded version of the core metadata with all the inherited properties being added so that the column description objects would correspond to the "schema" part of the metadata.

I think it might be a better way of presenting this if we could somehow factor this out in the document and, actually, among the conversion documents. I see two viable possibilities
1. As a separate section in each conversion document that would be exactly identical
2. As a separate section in the metadata document (hence my explicit cc to Jeni:-)

(2) would have the advantage of making the procedures clear for other applications than conversions, but it may not fit the overall goals of the metadata document. If we go (1), we may end up with a version hell. Fortunately, respec may come to our rescue for (2): the data inclusion possibility ([1], or possibly [2]) may take care of that.

I think I am more in favour of (1) at this point, but only mildly; (2) may also work.

**Comment by 6a6d74** [comment]
There are some small differences between the JSON and RDF processing - because the RDF mapping can take advantage of more properties in the metadata document.

Let's review this again after FPWD.

**Comment by iherman** [comment]
> On 16 Dec 2014, at 18:48, Jeremy Tandy notifications@github.com wrote:
> 
> There are some small differences between the JSON and RDF processing - because the RDF mapping can take advantage of more properties in the metadata document.
> 
> Ok. But we may still have a common text with some remarks that those properties are unnecessary for json. If these are 1-2 in number, that should be ok.
> Let's review this again after FPWD.
> 
> Absolutely. We just got ourselves an open issue:-)

Ivan

**Comment by JeniT** [comment]
Editor action: the conversion specifications should be based on processing that is described within the metadata document, not repeat it.

**Comment by 6a6d74** [comment]
csv2rdf and csv2json docs updated as per resolution. Much clearer now ...
