### ISSUE TITLE
predicate relating table to provenance?

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#114]
The CSV2RDF document specifies the form of the URL describing table provenance. This seems rather anti-RDF. If, instead, `prov:activity`, or `prov:wasGeneratedBy` related the table to the prov data, and it had the type `prov:Activity` this would use traditional semantic meaning, rather than URL specificity.

For example:

```
<> a csvw:Table;
  prov:activity [
    a prov:Activity;
    prov:startedAtTime [Start Time];
    prov:endedAtTime [End Time];
    prov:generated <[RDF Output Location]>;
    prov:qualifiedUsage [
      a prov:Usage ;
      prov:Entity <[CSV Location]> ;
      prov:hadRole csvw:csvEncodedTabularData
    ]
  ];
  ...
```

**Comment by iherman** [comment]
My problem with this is: how would I know the `<[RDF OUTPUT Location]>`? A conversion processor would, for example, produce a (serialization of a) graph to its standard output and it is the user who would then put it into a specific graph. 

I suggest that line is optional.

**Comment by 6a6d74** [comment]
@gkellogg:  I think you're suggesting use of a blank node for the `prov:Activity`? Fair enough!

@iherman: I agree that you don't always know the location of the generated output. This should be optional.
