### ISSUE TITLE
Make the datatype mapping more precise

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#117]
The current text in the RDF mapping says:

> Where metadata property datatype is defined, the triple included in the output graph for this cell shall assert the datatype of the cell value using the value of the datatype property.

I think we should be more precise than that. The metadata document lists the equivalent xsd datatypes, but the _value_ of the datatype in the metadata document is just, say, `string` and not `xsd:string`, whereas the RDF output should be `xsd:string`. Ie, there should be some text explicitly referring to the XML Schema equivalents for those datatypes.

That actually does not work for three datatypes listed in the metadata document: `json`, `xml`, and `html`. We should make it clear, in the document, that `xml` is mapped onto `rdf:XMLLiteral`, and `html` to `rdf:HTML`. I am not sure what to do with `json`, to be honest.

An additional complication is that, in the RDF 1.1. Concept document, `rdf:HTML` is _not_ a standard datatype insofar as it is not normative. It is not because there is not (yet) a standard unequivocally deciding whether two HTML fragments are equal or not. As a consequence, the latest RDFa Recommendation (just issued a PER) was forced to declare the generation of `rdf:HTML` as non-normative (with a note making the reasons clear). We may be forced to do something similar.

**Comment by 6a6d74** [comment]
Good point. Suggest that we resolve this after FPWD?

**Comment by iherman** [comment]
> On 17 Dec 2014, at 15:53 , Jeremy Tandy notifications@github.com wrote:
> 
> Good point. Suggest that we resolve this after FPWD?

Agreed

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
@iherman said:

> That actually does not work for three datatypes listed in the metadata document: json, xml, and html. We should make it clear, in the document, that xml is mapped onto rdf:XMLLiteral, and html to rdf:HTML. I am not sure what to do with json, to be honest.

The context defines xml, html as you suggest. Json is defined as csvw:json. I believe all the XSD terms are defined to xsd. Is this not adequate?

**Comment by iherman** [comment]
> On 17 Dec 2014, at 17:00 , Gregg Kellogg notifications@github.com wrote:
> 
> @iherman said:
> 
> That actually does not work for three datatypes listed in the metadata document: json, xml, and html. We should make it clear, in the document, that xml is mapped onto rdf:XMLLiteral, and html to rdf:HTML. I am not sure what to do with json, to be honest.
> 
> The context defines xml, html as you suggest. Json is defined as csvw:json. I believe all the XSD terms are defined to xsd. Is this not adequate?

You know and understand from the context, I understand from the context, but not everyone does:-) It is not clearly specified in the document and it should.

As for csvw:json: does it mean that we will formally define a new datatype for JSON content? While this is probably a good idea, it is actually of a wider possible use than just CSV, so I am not 100% sure that is the right way to do that...

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
Suggested resolution:
- if the `datatype` is `xml` then the output is an `rdf:XMLLiteral` literal
- if the `datatype` is `html` then the output is a `rdf:HTML` literal
- if the `datatype` is `json` then the value is processed in the same way as common properties (see #142)
- otherwise conversion to RDF should use the XSD datatypes as specified in the metadata document

An alternative resolution, in the case the `datatype` is `json`, is to invent a new `rdf:JSON` literal (it doesn't make a lot of sense to have that in the `csvw` namespace) and create one of those. Or just treat it as a `xsd:string` of course.

**Comment by iherman** [comment]
> On 04 Feb 2015, at 18:26 , Jeni Tennison notifications@github.com wrote:
> 
> Suggested resolution:
> 
>   • if the datatype is xml then the output is an rdf:XMLLiteral literal
>   • if the datatype is html then the output is a rdf:HTML literal
>   • if the datatype is json then the value is processed in the same way as common properties (see #142)

The essence of the rdf:XMLLiteral and rdf:HTML is that RDF does _not_ interpret these strings, just stores them. In this sense I do not agree that the value should be processed. It should just be copied verbatim, essentially

>   • otherwise conversion to RDF should use the XSD datatypes as specified in the metadata document
> An alternative resolution, in the case the datatype is json, is to invent a new rdf:JSON literal (it doesn't make a lot of sense to have that in the csvw namespace) and create one of those. Or just treat it as a xsd:string of course.

I am not sure we should go into the rathole of defining a datatype in the RDF namespace (although it would make a lot of sense:-). Probably xsd:string is pragmatic approach

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
Note that if went down the road of defining `rdf:JSON`, we would have to define a canonical JSON. Is there such a thing? (I guess one could define that easily, using sorting of the keys...)

**Comment by iherman** [comment]
I have made some inquires around the possibility of a `rdf:JSON` (or `csvm:JSON`) datatype. To define a datatype (see, for example the case of [`rdf:HTML`](http://www.w3.org/TR/rdf11-concepts/#section-html)) one has to establish what it means that two elements in the value space of a literal are considered to be equal. That means some sort of a canonicalization of the values in the lexical space, i.e., some sort of a canonical JSON format.

I have asked around my colleagues. The outcome:

> I searched a bit more in the archives of the IETF JOSE WG and  they noted several JSON C14n attempts. I'm afraid it's like  JSON schema, nothing concrete and no consensus on getting work done in a single place.

(The complication comes from UTF and number format equivalences.) With that it mind, I believe this WG should keep away from that; as a consequence, the only viable solution is to map a JSON text or fragment onto `xsd:string`.

**Comment by JeniT** [comment]
Resolved at Feb F2F. `datatype`: `json` gets mapped to RDF literal with a datatype of `csvw:JSON` which is a subtype of `xsd:string`.

**Comment by 6a6d74** [comment]
csv2rdf doc updated as per resolution.

However, can you confirm that you're happy for content marked as `json` datatype to be expressed as a string in the JSON conversion? Should the JSON conversion process simply insert the embedded JSON from the cell value into the JSON output?

**Comment by iherman** [comment]
I think that a json datatype should indeed appear as a string. The context for that JSON piece may be totally different than the (meta)data itself, so a direct inclusion may lead to a major semantic problem.

**Comment by gkellogg** [comment]
In agree, it is a literal, so a string representation seems right. OTOH, XML liiterals are XML in RDF/XML and HTML in HTML+RDFa, same with HTML literal. But our JSON serialization is not RDF, and a JSON literal in JSON-LD would be a string.

**Comment by JeniT** [comment]
I also think it should be a string, because we have no way of validating that JSON so we could have values that are labelled as JSON but are in fact complete garbage.

**Comment by 6a6d74** [comment]
OK. That's three +1s to "leave embedded JSON literal as a string in JSON output" ... will keep the csv2json doc as it is & close this issue.
