### ISSUE TITLE
Verify GeoJSON-LD example

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#12]
[Use Case #21 - Publication of Biodiversity Information from GBIF using the Darwin Core Archive Standard](http://w3c.github.io/csvw/use-cases-and-requirements/index.html#UC-PublicationOfBiodiversityInformation)

The example "GeoJSON-LD" needs to be verified as correct.

**Comment by JeniT** [comment]
Tested OK with http://geojsonlint.com/
