### ISSUE TITLE
Relation between the core and the annotated tabular data in the conversion documents

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#122]
At least for implementers, but maybe for users, too, it maybe helpful to realize that the handling of core tabular data is really just a special case of an annotated data. Ie, an implementation strategy may be, for a core tabular data, to (conceptually) create an annotated tabular data with a specific header line and no extra metadata, and then 'fall back' to the case of the annotated data. Something like that, in an non-normative appendix, may be a good idea.

**Comment by JeniT** [comment]
Closing as overtaken by #170
