### ISSUE TITLE
We should have at least a minimal ns doc 

### ISSUE THREAD

**Issue by danbri** [w3c/csvw#127]
See post from Ivan, http://lists.w3.org/Archives/Public/public-csv-wg/2014Dec/0052.html

"A practicality: to avoid publication checker issues, we should have something at http://www.w3.org/ns/csvw#

It can be a placeholder, or it can be a simple set of terms defined in some form (to be improved later). It can also be the json-ld context with vocabulary that gregg produced. But something should be there..."

**Comment by danbri** [comment]
Needed at least for CSV2RDF, metadata doc, others?

**Comment by danbri** [comment]
proposal: a 1 line HTML/5 page for now saying work-in-progress and pointing at the WG homepage and specs.

**Comment by iherman** [comment]
A minimal document has been put to:

http://www.w3.org/ns/csvw

To be updated when the time comes.

**Comment by gkellogg** [comment]
I have an open issue to create an html document from the vocabulary. Pending that, it should probably be the JSON-LD contex. However, I can get one created before the publication date,

**Comment by iherman** [comment]
I have created a placeholder, do not worry about that. If a bona fide vocabulary file can be created by the time of the publication, that is of course fine, but no pressure!

ivan

> On 17 Dec 2014, at 17:15 , Gregg Kellogg notifications@github.com wrote:
> 
> I have an open issue to create an html document from the vocabulary. Pending that, it should probably be the JSON-LD contex. However, I can get one created before the publication date,
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704
