### ISSUE TITLE
language term ambigious

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#128]
We specify `csvw:language` as a property of a Column, and define a `language` term accordingly. We also say we want terms for all xsd types, including `xsd:language`. This creates an ambiguity. Perhaps the use of `xsd` types in a metadata document should always use the CURIE form, as we've already created specific aliases (such as `any`) for important datatypes.

**Comment by gkellogg** [comment]
To clarify:

The issue is that we define a `language` property (`csvw:language`), but we also say that all terms from xsd are imported, for example `anyUri` is a term which is equivalent to `xsd:anyUri`. Similarly, this would imply that `language` is a term that expands to `xsd:language`, but this would be inconsistent. I was proposing that we make an exception for `xsd:language` and stick with the `csvw:language` term association.

**Comment by iherman** [comment]
I do not really see a problem. If "language" appears as a value of "datatype", then it is clearly "xsd:language". If it appears as a property, then it is csvw:language. As a metadata user I do not see a reason for confusion...

**Comment by gkellogg** [comment]
The problem comes with the context definition for the terms. To do what you want would require something like the following:

```
{
  "@context": {
    ...
    "language": {"@id": "csvw:language", "@language": null},
    "language": "xsd:language",
    ..
  }
}
```

Having two entries in a JSON object with the same key is illegal. That is the gist of what I'm saying, is that we can't define both terms in the context.

However, you're talking about the value of the `datatype` property; I think the property definition makes  this confusing:

> An atomic property that contains a single string that is the main datatype of the values of the cell. ...

In reality, the value is expected to denote the datatype, and should be expanded to a URI. This means the term definition should be the following:

```
"datatype": {"@id": "csvw:datatype", "@type": "@vocab"}
```

meaning that the values are expanded as vocabulary terms. So, saying `"datatype: "anyUri"` means that `anyUri` is expanded as a vocabulary term, which would make it the same as `xsd:anyUri`. You can see where the problem is using the value `language` in this case.

An alternative interpretation is that the value of `datatype` _is_ a string, but then some mechanism for mapping that string value to a datatype URI is needed which would have to be CSVW-specific, rather than making use of the JSON-LD mechanism. This seems like adding needless complexity to CSVW and questions the purpose of using JSON-LD as the basis for metadata in the first place.

**Comment by iherman** [comment]
> On 23 Jan 2015, at 17:42 , Gregg Kellogg notifications@github.com wrote:
> 
> The problem comes with the context definition for the terms. To do what you want would require something like the following:
> 
> {
>   "@context": {
>     ...
>     "language": {"@id": "csvw:language", "@language": null},
>     "language": "xsd:language",
>     ..
>   }
> }
> 
> Having two entries in a JSON object with the same key is illegal. That is the gist of what I'm saying, is that we can't define both terms in the context.

O.k. I see the problem.

So: what about using "lang" instead of "language" in csvw? That would solve the issue...

Ivan

> However, you're talking about the value of the datatype property; I think the property definition makes this confusing:
> 
> An atomic property that contains a single string that is the main datatype of the values of the cell. ...
> 
> In reality, the value is expected to denote the datatype, and should be expanded to a URI. This means the term definition should be the following:
> 
> "datatype": {"@id": "csvw:datatype", "@type": "@vocab"}
> 
> meaning that the values are expanded as vocabulary terms. So, saying "datatype: "anyUri" means that anyUri is expanded as a vocabulary term, which would make it the same as xsd:anyUri. You can see where the problem is using the value language in this case.
> 
> An alternative interpretation is that the value of datatype is a string, but then some mechanism for mapping that string value to a datatype URI is needed which would have to be CSVW-specific, rather than making use of the JSON-LD mechanism. This seems like adding needless complexity to CSVW and questions the purpose of using JSON-LD as the basis for metadata in the first place.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
+1 to using `lang` instead of `language` to make the JSON-LD work. (So that we can support `"datatype": "language"` for columns that hold language codes.)

**Comment by rufuspollock** [comment]
@JeniT strictly wouldn't it be `"@datatype": "language"` or similar - given that "datatype" has a restricted set of values.

**Comment by danbri** [comment]
see http://www.w3.org/2015/01/28-csvw-irc#T15-54-01

**Comment by gkellogg** [comment]
@rgrp: JSON-LD does not have a `@datatype` keyword, it uses `@type` for both resource types and literal datatypes depending on the context.

**Comment by gkellogg** [comment]
RESOLUTION: #128 change ‘language’ to ‘lang’ so we can keep ‘language’ as meaning ‘xsd:language’
