### ISSUE TITLE
Should the Dialect description be related to the dcat:Distribution of the Table?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#129]
In ISSUE #93 I suggest that we adopt the DCAT terminology to distinguish between the Table (the abstract data; `dcat:Dataset`) and the CSV encoded file containing that data (the `dcat:Distribution`).

_If_ we adopt this then the Dialect description currently described in the metadata vocabulary should be a sub-resource of the `dcat:Distribution` as this is the CSV-encoded part. The `csvw:Table` (proposed as a sub-Class of `dcat:Dataset`) is already _decoded_.

**Comment by iherman** [comment]
> On 18 Dec 2014, at 09:54 , Jeremy Tandy notifications@github.com wrote:
> 
> In ISSUE #93 I suggest that we adopt the DCAT terminology to distinguish between the Table (the abstract data; dcat:Dataset) and the CSV encoded file containing that data (the dcat:Distribution).
> 
> If we adopt this then the Dialect description currently described in the metadata vocabulary should be a sub-resource of the dcat:Distribution as this is the CSV-encoded part. The csvw:Table (proposed as a sub-Class of dcat:Dataset) is already decoded.

I think that makes indeed sense.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
I think this is only an issue for the mapping to RDF, where people care about such things (and it's important for the provenance trail). Let's discuss at the F2F how much it's useful to capture in the generated RDF.

**Comment by JeniT** [comment]
Resolved at Feb F2F. See resolution for #177.

**Comment by 6a6d74** [comment]
References to DCAT are now removed from the csv2rdf doc. It is now an implementation decision if such information is to be included in the output.
