### ISSUE TITLE
Alternate structure in JSON mapping output graph if Primary Key is specified

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#130]
(from Alain Couthures by [email](http://lists.w3.org/Archives/Public/public-csv-wg/2014Dec/0055.html))

Hello!

I have been processing CSV files recently and I decided to store them in an extended DOM structure with arrays, maps and entries nodes (as XPath 3.1 will support them).

This work of mine sounds to me similar with JSON mapping and please let me describe what I added for performance purposes:

Adding a way to specify a column as a unique key (I use the media type for parameters such as header or separator too) allows to map the CSV data into a JSON object where key values are distinct properties:

```
key,a,b
1,alpha,beta
2,alpha2,beta2
```

becomes

```
{
  key:
    {
       "1": {a: "alpha", b: "beta"},
       "2": {a: "alpha2", b: "beta2"}
    }
}
```

This is a very efficient way to access data within a Javascript program. I successfully processed within a browser more than 30000 rows against filtering maps in few seconds.

What do you think?

Kind regards,

Alain Couthures
agenceXML

**Comment by 6a6d74** [comment]
This seems a worthy proposal. 

My feeling is that _if_ the `primaryKey` metadata property is set then this should force the JSON mapping output graph to follow the structure proposed by Alain.

Looking at the [**Tree Operations** example](http://w3c.github.io/csvw/csv2json/#map-annotated-tab-examples-2-input) (example 5) in the JSON mapping document, with [metadata description](http://w3c.github.io/csvw/csv2json/#map-annotated-tab-examples-2-metadata) (example 6) indicating that the `primaryKey` is given by the column `GID`, then the JSON output might look like:

```
{
  "url": "tree-ops"
  "distribution": {
    "downloadURL": "http://example.org/tree-ops.csv"
  },
  "dc:title": "Tree Operations",
  "dc:keywords": ["tree", "street", "maintenance"],
  "dc:publisher": [{
    "schema:name": "Example Municipality",
    "schema:web": "http://example.org"
  }],
  "dc:license": "http://opendefinition.org/licenses/cc-by/",
  "dc:modified": "2010-12-31",
  "GID": {
    "1": {
      "url": "http://example.org/tree-ops.csv#gid-1",
      "on-street": "ADDISON AV",
      "species": "Celtis australis",
      "trim-cycle": "Large Tree Routine Prune",
      "inventory-date": "10/18/2010"
    },
    "2": {
      "url": "http://example.org/tree-ops.csv#gid-2",
      "on-street": "EMERSON ST",
      "species": "Liquidambar styraciflua",
      "trim-cycle": "Large Tree Routine Prune",
      "inventory-date": "6/2/2010"
    },
    "3": {
      "url": "http://example.org/tree-ops.csv#gid-3",
      "on-street": "EMERSON ST",
      "species": "Liquidambar styraciflua",
      "trim-cycle": "Large Tree Routine Prune",
      "inventory-date": "6/2/2010"
    }
  },
  "describedBy": "http://example.org/tree-ops.csv-metadata.json"
}
```

Note how the `row` array in the [output](http://w3c.github.io/csvw/csv2json/#map-annotated-tab-examples-2-output) suggested in the JSON mapping doc (example 7) is replaced by an indexed object whose _name_ is specified as the `primaryKey` (`GID`) and that the `primaryKey` property no longer appears inside the row-level objects.

**Comment by 6a6d74** [comment]
Might provision of this indexed array using the `primaryKey` property also be relevant for RDF mapping?

**Comment by timrobertson100** [comment]
I vote -1 on this.
1. This implies that you need different parsing code to handle JSON coming from CSV data annotated with or without a primary key.   
2. This structure would not support compound primary keys on a CSV (e.g. 2 or 3 columns combined provide the PK) which is required to support legacy CSV datasets, or certain DB exports.

What is presented here one of several ways you might reformat a JSON document with an indexing structure for specific applications.  I would suggest this not be in the standard JSON serialization format.  Note that transposing the original into an index like this is so simple it can even be done on the fly during serialization to the client.

**Comment by 6a6d74** [comment]
@timrobertson100: noted and thanks.

**Comment by iherman** [comment]
I am a bit concerned that the result would lead us very far from the R2RML Direct Mapping approach that we are supposed to be compatible with.

(Which is still true in spirit, though not in all details, but I believe a suitable metadata might lead us to the same results as the Direct Mapping. But that is a separate issue.)

Ivan

> On 18 Dec 2014, at 10:59 , Jeremy Tandy notifications@github.com wrote:
> 
> Might provision of this indexed array using the primaryKey property also be relevant for RDF mapping?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by AlainCouthures** [comment]
Supporting compound primary keys would not be difficult: the values for the indexed object would be the corresponding concatenation with the separator. As an option, It might be interesting to duplicate the corresponding cells so all the row cells are always present.

**Comment by danbri** [comment]
See http://www.w3.org/2015/02/13-csvw-irc#T10-27-52

**Comment by JeniT** [comment]
Resolved at Feb F2F. We only want to define one kind of JSON output, not lots of possibilities (though the extension conversion hooks we provide should enable different outputs). An indexed output doesn't always make sense (eg when there's no primary key), and the `aboutUrl` role means that this becomes more complicated to do. So we're sticking with the current output which is an array of objects.
