### ISSUE TITLE
Slight confusion with arrays an atomic values in the proposed metadata merge scheme

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#136]
This is related to issue #105 .

The algorithm makes a difference between `atomic value`-s and, in general, `array`-s. This is the case, for example, in the last portion of the algorithm for properties not defined by this specification. However, the definition of an `atomic value` (elsewhere in the document) is a value that may be a string, a boolean, a number, or an array of any of these. 

I believe that, for this algorithm, what counts is when the values are strings, booleans, or numbers, i.e., arrays have to be treated differently.

**Comment by gkellogg** [comment]
Indeed, we may consider the difference between an _atomic property_ and an _atomic value_, where an _atomic property_ takes an _atomic value_ or an array of _atomic values_. However, the only case of an _atomic property_ which accepts an array of values is `null`, and I don't see a good reason for that, so we may just restrict `null` to taking a single _atomic value_, and re-define an _atomic value_ to be _numbers_, _booleans_ or _strings_.

**Comment by JeniT** [comment]
Suggested resolution: Limit the `null` property to taking a single value, such that in a column you can have `X` being a null value but not `X` and `XX`.

**Comment by JeniT** [comment]
Editor action to resolve.

**Comment by JeniT** [comment]
Closing in favour of #218
