### ISSUE TITLE
Reference to the template itself

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#138]
The current specification of templates in the metadata requires the properties `templateFormat` and `targetFormat`, and defines the terms `title`, `source`, and `@type` as optionals. However, I would expect almost all template languages to require a separate _template file_ itself, e.g., an XSLT script, a mustache template, etc. It is of course true that, as the text says,

> The template specification may contain any common properties [...] to provide extra metadata about the transformation.

but I believe it may be better to add a common, optional property to denote the template itself. Something like `templateDefinition`.

(The `templateDefinition` should be a "link single" property, to ensure that only one URI is present even after a metadata import.)

**Comment by JeniT** [comment]
Doh. I think I was assuming `@id`.
