### ISSUE TITLE
'delimieter' / 'delimiter' typo?

### ISSUE THREAD

**Issue by westurner** [w3c/csvw#139]
https://github.com/w3c/csvw/search?utf8=%E2%9C%93&q=delimieter

Which file should I edit here?

**Comment by iherman** [comment]
Wes,

I took care of these. 

In general, the 'core' file is the _vocab.csv file, and the other files are generated using a ruby process that Gregg manages. I have made the necessary changes.

Thanks for the report!

**Comment by westurner** [comment]
Thanks!

**Comment by westurner** [comment]
... https://github.com/w3c/csvw/blob/gh-pages/ns/_vocab.csv
