### ISSUE TITLE
Open and/or Closed validation requirement

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#14]
[R-CsvValidation](http://w3c.github.io/csvw/use-cases-and-requirements/index.html#R-CsvValidation)

David Booth suggests:

"It sounds like the R-CsvValidation requirement may need to be split into two separate validation requirements:

R-CsvOpenValidation: Does the data in the CSV conform to the metadata, ignoring inapplicable metadata? For example, is every column in the CSV described by some metadata?

R-CsvClosedValidation: Does the metadata describe anything that does NOT appear in the CSV?

I suppose if the metadata had a notion of optional columns then both of these cases could be covered at once."

However, at this point the use cases only appear to relate to the closed validation case. Do we need another use case to support open validation?

**Comment by afs** [comment]
This sounds more like a mode of checking/validating tool as to whether to treat the metadata as complete or not.

**Comment by JeniT** [comment]
I think it would be useful to explicitly call this out in the Use Case Document. I've added Editor Action on the Metadata document to flag that validators should run in 'open' or 'closed' modes.

**Comment by JeniT** [comment]
Note that the PR #225 now does not support having two validation modes, only a form of closed validation.
