### ISSUE TITLE
respec-w3c-common is http instead of https

### ISSUE THREAD

**Issue by edsu** [w3c/csvw#140]
The respec-w3c-common JavaScript library is loaded over HTTP but github.io is HTTPS so it fails to load, which results in a not so pretty display, e.g. https://w3c.github.io/csvw/syntax/index.html

![screen shot 2014-12-31 at 3 44 48 am](https://cloud.githubusercontent.com/assets/33829/5586831/815e3ac0-909f-11e4-990b-299f56996f7d.png)

**Comment by iherman** [comment]
Ed,

indeed, this is a problem _on chrome and opera_; as far as I can see, it is not an issue for Safari and for Firefox (I do not have access to IE). It is a result of the inconsistent behavior of browsers with such mixed http/https contents. I do not have any particular problems accepting your pull request with that change, but I would prefer to wait to see if somebody else in the group has any experience with such a change backfiring... (E.g., I tested the html content on `http://localhost/` with `https` for the access of `respec`; this type of mixed content seems to work all right, as expected.)

B.t.w., both on Chrome and on Opera the content _can_ be displayed albeit through an extra step (i.e., with some extra pain:-). A shield-like logo appears on the address bar for Chrome, and an explicit "blocked" notice on Opera; by clicking on those one can instruct the respective browsers to load what they perceive as unsafe content (i.e., the `respec` library). Unfortunately, this information is not cached, i.e., every time one looks at the file, this step must be repeated.

Thanks

Ivan

**Comment by iherman** [comment]
Pull request has been processed.
