### ISSUE TITLE
Value space of Common Properties

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#142]
The Meta data document defines [Common Properties](http://w3c.github.io/csvw/metadata/#common-properties) to simply be those from a pre-defined prefix space or absolute URLs. It does not say anything about the value space.

To be consistent with JSON-LD, values which are not supposed to be language-tagged literals should either be in JSON-LD expanded form, or specific properties should have the `@type` defined (which would be overreaching, IMO). The `@context` of the metadata could potentially include an external context (such as from schema.org), but non-JSON-LD aware processors would be at a disadvantage.

Expanded representations might be such as the following:

```
{
  "dc:title": "String value with possible language from `@context`",
  "dc:description": {"@value": "String value with no language"},
  "schema:name": {"@value": "String value with explicit language", "@language": "en"},
  "schema:url": {"@id": "http://example.com/"},
  "schema:valueRequired": true,
  "foaf:age": 18.5,
}
```

Presumably, we don't want to do deeper structures with embedded nodes, or lists, but arrays of values should be fine.

**Comment by gkellogg** [comment]
Given the ambivalence towards JSON-LD, this is likely a controversial take on the values for common properties. However, without an alternative, the result would only allow literal values for common properties. As an alternative, we could expand the default JSON-LD context to be explicit about `@type` mappings for all terms from vocabularies for which we define a prefix. Note even using expanded representation, transformation of expanded values to RDF or JSON can probably still be done without requiring a JSON-LD processor.

**Comment by iherman** [comment]
I am not sure what you mean: would the metadata document include such `@type` definition for a number of known properties, or do you mean that the `@context` section MAY include such definitions, and it is up to the author of the metadata to decide whether those are included?

I have a problem with the former: we get back to the issue we tried to avoid on what are the 'known properties'. I wonder whether we should not simply leave it to implementations what they do for terms that we do not define ourselves (and that is really the issue with the merge algorithm, this is also issue #150...)

Ivan

> On 11 Jan 2015, at 24:32 , Gregg Kellogg notifications@github.com wrote:
> 
> Given the ambivalence towards JSON-LD, this is likely a controversial take on the values for common properties. However, without an alternative, the result would only allow literal values for common properties. As an alternative, we could expand the default JSON-LD context to be explicit about @type mappings for all terms from vocabularies for which we define a prefix. Note even using expanded representation, transformation of expanded values to RDF or JSON can probably still be done without requiring a JSON-LD processor.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
> I am not sure what you mean: would the metadata document include such `@type` definition for a number of known properties,

That is certainly possible, but I think it is an over-reach for us to include such information from other vocabularies in our own context.

> or do you mean that the `@context` section MAY include such definitions, and it is up to the author of the metadata to decide whether those are included?

That's also possible, but then creates tool-chain requirements for CSVW processors to be able to get these from the context, essentially requiring the use of a JSON-LD processor, which we've been trying to avoid.

I think the simplest path is to allow limited JSON-LD in expanded form (essentially), which can be processed reasonably easy to get desired literal/IRI forms without requiring a JSON-LD processor.

But, I note that Example 3 in the syntax uses an embedded node:

```
"dc:publisher": [{
  "sch:name": "Example Municipality",
  "sch:web": "http://example.org"
}],
```

This would seem to require a JSON-LD processor, as the generated turtle for this is something like the following:

```
<base> dc:publisher [ sch:name "Example Municipality; sch:web "http://example.org/" ] .
```

This still can't get the `http://example.org` as an IRI without knowing the type of `sch:web`, or using a more expanded form. To enable this use-case may require the use of a JSON-LD processor.

> I have a problem with the former: we get back to the issue we tried to avoid on what are the 'known properties'.

I agree that we should avoid the former, but it seems that the later does impose a JSON-LD workflow.

> I wonder whether we should not simply leave it to implementations what they do for terms that we do not define ourselves (and that is really the issue with the merge algorithm, this is also issue #150...)

Of course, my main concern is interoperability and testability, so just leaving it up to implementations doesn't seem to sit well with that.

**Comment by iherman** [comment]
> On 12 Jan 2015, at 08:44 , Gregg Kellogg notifications@github.com wrote:
> 
> > I am not sure what you mean: would the metadata document include such @type definition for a number of known properties,
> 
> That is certainly possible, but I think it is an over-reach for us to include such information from other vocabularies in our own context.
> 
> > or do you mean that the @context section MAY include such definitions, and it is up to the author of the metadata to decide whether those are included?
> 
> That's also possible, but then creates tool-chain requirements for CSVW processors to be able to get these from the context, essentially requiring the use of a JSON-LD processor, which we've been trying to avoid.
> 
> I think the simplest path is to allow limited JSON-LD in expanded form (essentially), which can be processed reasonably easy to get desired literal/IRI forms without requiring a JSON-LD processor.

Can you give clear examples of what you mean?

(I am, when my time permits, playing with an implementation, and I am already bothered by the spaghetti code needed to manage the different alternatives in the metadata. Each is relatively simple to handle, but it really piles up!)

> But, I note that Example 3 in the syntax uses an embedded node:
> 
> "dc:publisher": [{
>   "sch:name": "Example Municipality",
>   "sch:web": "http://example.org"
> }],
> 
> This would seem to require a JSON-LD processor, as the generated turtle for this is something like the following:
> 
> <base> dc:publisher [ sch:name "Example Municipality; sch:web "http://example.org/" ] .
> 
> This still can't get the http://example.org as an IRI without knowing the type of sch:web, or using a more expanded form. To enable this use-case may require the use of a JSON-LD processor.
> 
> > I have a problem with the former: we get back to the issue we tried to avoid on what are the 'known properties'.
> 
> I agree that we should avoid the former, but it seems that the later does impose a JSON-LD workflow.
> 
> > I wonder whether we should not simply leave it to implementations what they do for terms that we do not define ourselves (and that is really the issue with the merge algorithm, this is also issue #150...)
> 
> Of course, my main concern is interoperability and testability, so just leaving it up to implementations doesn't seem to sit well with that.

Yes, I see that. But see my comment above... The RDF generation is meant to be a _simple_ mapping. Ideally, what this also means is that, possibly, other processors (SPIN, whatever) will follow the simple mapping if they want to tweak the results. In other words, I am not sure it is a major problems if the intricacies of external vocabularies are left open in the simple mapping.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
> Can you give clear examples of what you mean?

The the examples in the beginning of this issue. However, this might not be adequate for our needs; for the JSON mapping, it's simply a matter of copying the values of the common properties over to the JSON output. For RDF, you really need the RDF output, and an example such as the "dc:publisher" shown above is a reasonable annotation to apply, but to turn it into RDF really requires expansion and running the `toRdf` algorithm from JSON-LD.

```
{
  "dc:title": "String value with possible language from `@context`",
  "dc:description": {"@value": "String value with no language"},
  "schema:name": {"@value": "String value with explicit language", "@language": "en"},
  "schema:url": {"@id": "http://example.com/"},
  "schema:valueRequired": true,
  "foaf:age": 18.5,
}
```

Supposing that the Metadata had set `@language` to "fr", this would yield the following triples:

```
[
  dc:title "String value with possible language from `@context`"@fr;
  dc:description "String value with no language";
  schema:name  "String value with explicit language"@en;
  schema:url <http://example.com/>;
  schema:valueRequired "true"^^xsd:boolean;
  foaf:age "18.5"^^xsd:double;
]
```

IMO, such transformation is fairly easy for an implementation without relying on an external JSON-LD processor.

> (I am, when my time permits, playing with an implementation, and I am already bothered by the spaghetti code needed to manage the different alternatives in the metadata. Each is relatively simple to handle, but it really piles up!)

Indeed, Metadata processing is where most of the work is. My own Metadata class has over 1200 lines of code! Extracting embedded metadata is quite complicated (based on my interpretation, anyway). Also, creating a TableGroup from a Table (required for merge), and extracting just the Table from a Table group (required for transformation of a given CSV) had a number of complications, at least the way I chose to implement it.

I need to re-write the metadata import section to metadata merge, and merging is certainly fairly complicated.

> >  Of course, my main concern is interoperability and testability, so just leaving it up to implementations doesn't seem to sit well with that.
> 
> Yes, I see that. But see my comment above... The RDF generation is meant to be a _simple_ mapping. Ideally, what this also means is that, possibly, other processors (SPIN, whatever) will follow the simple mapping if they want to tweak the results. In other words, I am not sure it is a major problems if the intricacies of external vocabularies are left open in the simple mapping.

This really comes down to how we may want to limit the values of common properties. Otherwise, after Metadata processing, RDF generation is pretty simple. And, if the use of a JSON-LD processor is not a step to far (we have different opinions on this), then neither are flexible common property values. So, the issue really comes down to how the group decides to restrict the value range of common properties.

**Comment by iherman** [comment]
To explain my reticence which underlines why I want rather to restrict the values of common properties, if needed, rather than going down the JSON-LD line: the (afaik, only) json-ld library in Javascript is over 7000 lines long, it introduces yet another level of asynchronous behavior, if my interpretation of the (very shallow) documentation is right; to be forced to use such a heavy tool for external vocabularies simply seem over the top as far as I am concerned...

**Comment by iherman** [comment]
I have given some more thoughts to the original message/proposal of Gregg. I am, after all, o.k. with it: common properties may have one of those 6 forms that are in the original format. That can be parsed directly.

However... one question does remain. Whilst it is obvious what the output of those will be for RDF, I am not sure what it should be for 'plain old JSON'. I think what we should say is that
- boolean and numbers are stored as boolean and numbers
- all other forms will be stored as plain strings without any further structure

The other alternative would be to copy those verbatim, but that seems to be too complex for good old JSON...

**Comment by gkellogg** [comment]
The JSON output already has many JSON-LD based elements in it, and copying them verbatim is what I currently implement and seems simplest. Of course, it's entirely up to the Metadata author to control that, and presumably they're in the best place to know what the form of JSON is they desire, and if it should include these expanded forms.

**Comment by iherman** [comment]
I am not sure. The Good Old JSON serialization aims at simple JSON processing, not JSON-LD complexity level processing. Just as many other datatypes things in the metadata are ignored at that level, I am not sure why we would not flatten these structures to their bare bone (i.e., strings) for GOJ.

**Comment by gkellogg** [comment]
I'm fine with just using the simple values of common properties in the JSON output. However, note that this could lead to having a property with multiple values, each in a different language, but with no indication what the language is.

**Comment by JeniT** [comment]
I think there are three separate decisions here:
1. Do we restrict (in the metadata document) what people are allowed to provide as values to common properties. I suggest that we don't as I think that if we do restrict what they are allowed to provide this will limit the room for manoeuvre for implementations and authors.
2. How are values of common properties mapped into JSON? I suggest that they are simply mapped verbatim.
3. How are the values of common properties mapped into RDF? I suggest that they follow JSON-LD rules, and that that could be done by reference to the JSON-LD specification. The alternative (if expecting RDF converters to support JSON-LD is too much) would be to list particular types of recognised patterns as @gkellogg has listed, and say that anything other than that becomes a JSONLiteral object in the RDF.

**Comment by iherman** [comment]
> On 28 Jan 2015, at 14:51 , Jeni Tennison notifications@github.com wrote:
> 
> I think there are three separate decisions here:
> 
>   • Do we restrict (in the metadata document) what people are allowed to provide as values to common properties. I suggest that we don't as I think that if we do restrict what they are allowed to provide this will limit the room for manoeuvre for implementations and authors.
> 
>   • How are values of common properties mapped into JSON? I suggest that they are simply mapped verbatim.
> 
>   • How are the values of common properties mapped into RDF? I suggest that they follow JSON-LD rules, and that that could be done by reference to the JSON-LD specification. The alternative (if expecting RDF converters to support JSON-LD is too much) would be to list particular types of recognised patterns as @gkellogg has listed, and say that anything other than that becomes a JSONLiteral object in the RDF.

This is what I have a problem with. What this means is that a conforming RDF transformation processor should, in essence, be also a full JSON-LD processor. In view of the complexity of JSON-LD, that is quite a tall order. That means quite a major load on implementations and/or a dependency on external tools. There aren't such a large number of JSON-LD parsers around...

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
Suggested resolution: Authors may supply any legal JSON values for common properties. These are mapped verbatim when converting to JSON. Converters to RDF should perform the following processing on the (JSON) values of common properties:
- `null` is mapped to `rdf:nil`
- string values are mapped to literals, with a language provided by `@language` from the `@context` if there is one (otherwise with no language)
- boolean values are mapped to boolean values
- numeric values are mapped to integers if they are integers, otherwise to doubles
- objects with an `@id` property are mapped to a resource with that URI; other properties on those objects are processed as if they were common properties
- objects with a `@value` property are mapped to literals with that value; if a `@language` property is present this provides the language for the literal; if a `@datatype` property is present this provides the datatype for the literal; other properties on such objects are ignored
- other objects are mapped to blank nodes, with their properties processed as if they were common properties
- arrays create multiple triples with the same property, with each value in the array processed as described above

**Comment by iherman** [comment]
> On 04 Feb 2015, at 17:26 , Jeni Tennison notifications@github.com wrote:
> 
> Suggested resolution: Authors may supply any legal JSON values for common properties. These are mapped verbatim when converting to JSON. Converters to RDF should perform the following processing on the (JSON) values of common properties:
> 
>   • null is mapped to rdf:nil
>   • string values are mapped to literals, with a language provided by @language from the @context if there is one (otherwise with no language)
>   • boolean values are mapped to boolean values
>   • numeric values are mapped to integers if they are integers, otherwise to doubles
>   • objects with an @id property are mapped to a resource with that URI; other properties on those objects are processed as if they were common properties
>   • objects with a @value property are mapped to literals with that value; if a @language property is present this provides the language for the literal; if a @datatype property is present this provides the datatype for the literal; other properties on such objects are ignored
>   • other objects are mapped to blank nodes, with their properties processed as if they were common properties
>   • arrays create multiple triples with the same property, with each value in the array processed as described above

Hm. We are slowly building in a full JSON-LD processing here, something that I was always uneasy about... Gregg's original proposal[1] put a cap on it insofar as the object property had a more restricted range. For example, your scheme about allows for a recursivity: "other properties on those objects are processed as if they were common properties" (for objects with '@id"), and I have not really thought through all the consequences yet...

Ivan

[1] https://github.com/w3c/csvw/issues/142#issuecomment-70137008

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
My opinion is that this is nothing like full JSON-LD processing (there's no `@context` to worry about, for a start). And the recursion should be easy enough because it's just using exactly the same logic on the properties of the objects.

@gkellogg's suggestion would turn something like:

```
"dc:publisher": {
  "@id": "http://ons.gov.uk",
  "schema:name": "Office of National Statistics"
}
```

into:

```
_:table
  dc:publisher """{
  "@id": "http://ons.gov.uk",
  "schema:name": "Office of National Statistics"
}""" ;
```

when with just a little bit more intelligence it could be:

```
_:table
  dc:publisher <http://ons.gov.uk> .

<http://ons.gov.uk>
  schema:name "Office of National Statistics" .
```

which is _so_ much more useful.

**Comment by iherman** [comment]
Actually...

> On 04 Feb 2015, at 20:33, Jeni Tennison notifications@github.com wrote:
> 
> My opinion is that this is nothing like full JSON-LD processing (there's no @context to worry about, for a start). And the recursion should be easy enough because it's just using exactly the same logic on the properties of the objects.
> 
> @gkellogg's suggestion would turn something like:
> 
> "dc:publisher": {
>   "@id": "http://ons.gov.uk",
>   "schema:name": "Office of National Statistics"
> }
> into:
> 
> _:table
>   dc:publisher """{
>   "@id": "http://ons.gov.uk",
>   "schema:name": "Office of National Statistics"
> }""" ;
> I don't think so. My understanding of Gregg's proposal is that this would be the result

_:table dc:publisher http://ons.gov.uk.

ie, the difference is that Gregg limits the accepted forms. (Although indeed his proposal doesn't say that unrecognized entries are ignored, but would be logical thing to do...)

Ivan

**Comment by gkellogg** [comment]
My proposal was to just support single values, and not embedded nodes, since this can quite easily get into full JSON-LD, and trying to specify a subset that works consistently is only likely to create corner cases.

What I'd really like to see is that common property values are simply JSON-LD, importing the context from the metadata scope. @iherman had an issue with this, so I suggested something less complete, but the decision should be driven by requirements and use cases. As JSON-LD is a W3C recommendation with numerous (and growing) implementations, IMO using it for this purpose in CSVW shouldn't be a problem, but we do need a consensus result. Obviously something to tackle at the F2F.

There is one thing that implementations need to consider, though: If the value is an object without `@id`, (or with a BNode `@id`) JSON-LD will normalize the BNode identifiers. This means that the subject of these triples will be "_:b0", which my implementation replaces with the table subject. Just something to be consider and may need a note.

**Comment by danbri** [comment]
discussion http://www.w3.org/2015/02/12-csvw-irc#T16-54-30

**Comment by JeniT** [comment]
Discussed at Feb F2F. Finally persuaded @iherman (sort of, grudgingly) that recursion into objects would be useful.

Principle that processing by a JSON-LD processor will give the same results; where this is not true (eg if there is a `@context` property), that should be detected and the processor must issue a warning.

The `notes` property is treated in exactly the same way.

Things that generate warnings and may be ignored are:
- `@context` property
- `@list` property
- `@set` property
- combination of `@id` and `@value` or `@language` may cause `@value` and `@language` to be ignored
- `@id` with a blank node identifier
- `@type` or `@id` with a value whose prefix isn't recognised

Recognised things:
- `null` is mapped to no property (no value so doesn't generate anything)
- string values are mapped to literals, with a language provided by `@language` from the `@context` if there is one (otherwise with no language)
- boolean values are mapped to boolean values
- numeric values are mapped to integers if they are integers, otherwise to doubles
- objects with an `@id` property are mapped to a resource with that URI; if a `@type` is present then this maps to a `rdf:type` property (the value of `@type` is expanded based on prefixes); other properties on those objects are processed as if they were common properties
- objects with a `@value` property are mapped to literals with that value; if a `@language` property is present this provides the language for the literal; if a `@type` property is present this provides the datatype for the literal (the value of `@type` is expanded based on prefixes); if there's no `@language` or `@type` then the result is a string without language, even if there is a default language from the metadata `@context`; other properties on such objects are ignored
- other objects are mapped to blank nodes, with their properties processed as if they were common properties
- arrays create multiple triples with the same property, with each value in the array processed as described above

---

```
Common property:


"dc:publisher": {
    "@id": "http://ons.gov.uk",
    "schema:name": "Office of National Statistics",
    "schema:url": "http://ons.gov.uk"
},
"dc:keywords": ["A", "B", "C"]
"dc:creator": "dc:foo"

Converts to RDF:

1. Ivan's Proposal:

_:table dc:publisher <http://ons.gov.uk> ;

2. Jeni's Proposal:

_:table
  dc:publisher <http://ons.gov.uk> .

<http://ons.gov.uk>
  schema:name "Office of National Statistics" ;
  schema:url: "http://ons.gov.uk" .

---

"notes": [{
    "oa:target": "example.csv#row=2",
    "oa:body": "blah blah blah"
}]

---

"dc:description": {
    "en": "blah blah",
    "fr": "er"
}

maps to:

_:table dc:description [] .

authors would have to do:

"dc:description": [
  { "@value": "blah blah", "@language": "en" },
  { "@value": "er", "@language": "fr" }
]

which would map to:

_:table
  dc:description "blah blah"@en ;
  dc:description "er"@fr .

"dc:description": [
  { "@id": "example.csv"; @value": "blah blah", "@language": "en" },
  { "@value": "er", "@language": "fr" }
]

produces warning because this isn't valid JSON-LD

---

"dc:creator": [{
    "schema:name": "Jeni"
}, {
    "schema:name": "Gregg"
}]

_:table
  dc:creator [ schema:name "Jeni" ] ;
  dc:creator [ schema:name "Gregg" ] .


"dc:creator": {
  "@list": [{
    "schema:name": "Jeni"
  }, {
    "schema:name": "Gregg"
  }]
}
```

**Comment by iherman** [comment]
I believe there is small mistake in the processing steps. It now says:

> - other objects are mapped to blank nodes, with their properties processed as if they were common properties

but, I presume, the `@type` value should be treated separately, just as when the object has a `@id` (i.e., 5th bullet item).

**Comment by iherman** [comment]
Another point to make more precise in the processing steps:

> objects with a @value property are mapped to literals with that value; if a @language property is present this provides the language for the literal; if a @type property is present this provides the datatype for the literal (the value of @type is expanded based on prefixes); if there's no @language or @type then the result is a string without language, even if there is a default language from the metadata @context; other properties on such objects are ignored

Question: what should happen if _both_ "@language" and "@type" properties are present?

The JSON-LD spec includes the following note:

> Language associations are only applied to plain strings. Typed values or values that are subject to type coercion are not language tagged.

What this seems to suggest that "@type" has the upper hand; if so, this must be stated. (And, possibly, a warning should be issued.)

**Comment by gkellogg** [comment]
> Question: what should happen if both "@language" and "@type" properties are present?

From [JSON-LD 1.1 Lists and Sets](http://www.w3.org/TR/json-ld/#value-objects):

> A value object must be a JSON object containing the `@value` key. It may also contain an `@type`, an `@language`, an `@index`, or an `@context` key but must not contain both an `@type` and an `@language` key at the same time. A value object must not contain any other keys that expand to an absolute IRI or keyword.

In our case, we should ensure that a value object can only contain the keys `@value`, `@type` and `@language` but not both `@type` and `@language`. The value of `@type` must be an absolute URL or a prefixed name with a prefix defined in our context. The value of `@language` must conform to BCP47. Anything else would be invalid and not useful for transformations.

**Comment by iherman** [comment]
And what does/should happen if an object contains both "@type" and "@language"? Is the value ignored?

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by gkellogg** [comment]
A JSON-LD processor MUST raise an `invalid value object` exception if it detects this, so this would halt processing. The implication is that as part of validating metadata, the value of common properties must be validated to ensure that they conform to our restrictions, as well as being valid JSON-LD.

From the Expansion Algorithm:

> If result contains the key @value: The result must not contain any keys other than @value, @language, @type, and @index. It must not contain both the @language key and the @type key. Otherwise, an invalid value object error has been detected and processing is aborted.

This will be consistent with our subsetted processing rules. It may be an open question if this is done when processing the metadata (which it doesn't now), or when doing a transformation. An RDF transformation will need to go through these steps, while a JSON transformation likely just copies the values in place. It may be that we can defer this to transformation, when a processor MUST raise an error if common properties are invalid. Note that a common property may contain something which doesn't expand to RDF, but would still be valid (for instance, if a key is used which doesn't expand using our context).

**Comment by gkellogg** [comment]
Regarding this question from @iherman:

> The JSON-LD spec includes the following note:
> 
> > Language associations are only applied to plain strings. Typed values or values that are subject to type coercion are not language tagged.
> 
> What this seems to suggest that "@type" has the upper hand; if so, this must be stated. (And, possibly, a warning should be issued.)

This is referring to the value of a property being a string, not a value object. In this case, the in-scope `@language` is applied to the string. There is no in-scope `@type`. Note that value objects of specific processing rules separate from node definitions.

**Comment by iherman** [comment]
I am o.k. stating that having both of them being an error is the right way to go and that is why validators would should raise an exception.

I am still not sure how an RDF conversion processor should react, though (and this is a more general issue: how should an RDF/JSON processor react in case there is an error?). There has been much criticism in the Web Developers' community for the "draconian error handling" behavior of XML processors; the community clearly favors a more graceful behavior. I am a bit concerned going down this draconian line for the converters, too, and I would prefer to explore a more graceful approach. In this case, for example, issuing a Literal without any datatype or language, for example.

Should we raise a more general issue on the error handling principles of converters?

Ivan

> On 19 Feb 2015, at 23:58 , Gregg Kellogg notifications@github.com wrote:
> 
> Regarding this question from @iherman:
> 
> The JSON-LD spec includes the following note:
> 
> Language associations are only applied to plain strings. Typed values or values that are subject to type coercion are not language tagged.
> 
> What this seems to suggest that "@type" has the upper hand; if so, this must be stated. (And, possibly, a warning should be issued.)
> 
> This is referring to the value of a property being a string, not a value object. In this case, the in-scope @language is applied to the string. There is no in-scope @type. Note that value objects of specific processing rules separate from node definitions.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
The last commit should ensure that invalid content results in warnings, but that processing may proceed.
