### ISSUE TITLE
initial prefixes in the metadata document?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#146]
The current draft includes the full '@context', which also includes the predefined prefixes. The latter comes from the rdfa default context. However, by putting this list into the document we would, eventually, cast this list in concrete (in a /TR document). This contradicts the rdfa default context file, which is a living document with new prefixes added time-to-time. 

In my view the spec should include the 'csvw' terms only, and refer to the namespace document where the additional prefixes would be listed (and updated if the rdfa context file is updated). Or something similar...

Ivan

**Comment by gkellogg** [comment]
Good point, perhaps it should just revert to a reference to http://www.w3.org/ns/csvw.jsonld. We can also reference just http://www.w3.org/ns/csvw, which defines all terms in csvw space, but also the pre-defined prefixes, but this can be kept current with changes downstream. This is consistent with how the RDFa context works.

**Comment by iherman** [comment]
... Or both. Referring to the `@context` explicitly makes sense, as well as referring to the overall namespace document for the default prefixes.

I have marked the issue as 'in progress' and 'editor action' for now.

**Comment by JeniT** [comment]
@gkellogg I've assigned this to you to take forward. Please make yourself officially an editor on the document too :)
