### ISSUE TITLE
Prov roles

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#147]
The CSV2RDF doc uses two values for `prov:hadRole`: `csvw:csvEncodedTabularData` and `csvw:tabularMetadata`. This need to be defined as instances of `prov:Role` in the namespace. Are there other instance types we need to define? TSV, XLS, HTML?

**Comment by 6a6d74** [comment]
FWIW, `csvw:csvEncodedTabularData` and `csvw:tabularMetadata` were just first guesses for names. Happy to have better ones suggested!

Haven't considered further resources along this line - but am sure there will be.

**Comment by JeniT** [comment]
I guess the issue is how many of these we need to define and how we encourage people to create new ones for different types of tabular data files.

**Comment by gkellogg** [comment]
Also see #174.

**Comment by JeniT** [comment]
Discussed at Feb F2F, @davideceolin & @iherman will come up with a list of appropriate roles & propose to the group.

**Comment by 6a6d74** [comment]
csv2rdf doc updated as per resolution; see http://w3c.github.io/csvw/csv2rdf/#provenance
