### ISSUE TITLE
Definition of @context should be more explicit

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#149]
The metadata document says, at this moment (in [section 3.2](http://w3c.github.io/csvw/metadata/index.html#top-level-properties)) that 

> The top-level object (whether it is a table group description or a table description) may have @context property. This holds an object that provides metadata for interpreting other properties, namely...

However, the example, in the [introduction](http://w3c.github.io/csvw/metadata/index.html#introduction) includes the example:

`
"@context": ["http://www.w3.org/ns/csvw", {"@language": "en"}],
`

The example, from JSON-LD point of view, is correct, because the [JSON-LD specification](http://www.w3.org/TR/json-ld/#node-objects) indeed says:

> If the node object contains the `@context` key, its value must be null, an absolute IRI, a relative IRI, a context definition, or an array composed of any of these

However, the metadata document should either stand on its own feet, and hence use the same definition, or should explicitly refer to JSON-LD. Because `@context` may include features that are important for the local processing of the metadata (`@base` and `@language`), I would actually prefer the former.

**Comment by gkellogg** [comment]
I think this shows the complexity of trying to do "JSON-LD Lite" where we try to use a JSON-LD-like mechanism. The cleanest would be to not try to re-interpret the context mechanism (or, indeed, other things used from JSON-LD), but instead reference the [context definition in JSON-LD](http://www.w3.org/TR/json-ld/#the-context). What we can do is proscribe the use within the document as being either a URL, or an array including a URL and an object where the only values allowed within that object are `@base` and `@language`.

I think we're on a slippery slope of trying to take the form of JSON-LD without the substance, and we may come to regret this. If the group really feels that making sure that the context can be processed as JSON-LD without csvw-specific rules, then the best would be to stick with the current wording, and only allow an object containing just `@base` and `@language`. My opinion, as I've stated before, is that we should make sure the documents are JSON-LD, including a reference to the context, and solicit feedback from the community to see if this is too much of a burden.

**Comment by iherman** [comment]
And we have a friendly disagreement on this, Gregg... I believe the document should stand on its feet by itself, and the implementations (e.g., conversions) should be doable without relying on a JSON-LD parser/interpreter. Yes, there may be some issues like this one, but it is fairly easy to handle this one, for example, by making it clear in the specification that an array of values is also allowed. Some others may come up that we will handle when the time comes.

On an implementation level the fact is that there are not that many JSON-LD interpreters around and, due to the complexity of JSON-LD, they may be bulky with their own idiosyncrasies. The specification of JSON-LD is also fairly complex (a bit too complex for my taste, to be very honest) and I think we would face massive rejection if the readers of the spec(s) should go and digest JSON-LD before understanding this one.

**Comment by gkellogg** [comment]
I agree that implementations shouldn't have to rely on a JSON-LD parser, and that's really one of the purposes of JSON-LD, so that the data can be accessed as JSON. But, when re-defining something like `@context`, we need to be wary of over-reach. I believe the way I defined it in the spec ensure that it can be processed as JSON-LD without placing too much of a burden on an implementation or publication. It may be that we end up making the default context implicit, and strictly limit the use of `@context` for defining only `@language` and `@base`, but I think it's premature to start there.

The complexity in JSON-LD I believe you're reacting to is for API implementations, not the language specification. The reference I added to the context definition is not overly complex IMO. The main thing needed to interpret a CSVW metadata document is to find language and base from the context, and not necessarily use the rest of the context for interpreting the surface JSON structure used for metadata.

The json-ld.org site shows 6 different implementations, and more seem to be on there way, as the mailing list remains fairly active. Anyway, these are for fully conforming implementations, and I'm not suggesting that these are necessary for our purposes. My own implementation makes use of just the context processing elements to avoid special-cases in interpreting values and expanding URLs.

**Comment by iherman** [comment]
Gregg,

first of all, forgive me for my ranting on the JSON-LD complexity in general; this is not the right place (I was not only referring to the API, b.t.w., but the language definition, too). Let us put that aside, or in a different mail thread if you prefer.

> On 09 Jan 2015, at 19:49 , Gregg Kellogg notifications@github.com wrote:
> 
> I agree that implementations shouldn't have to rely on a JSON-LD parser, and that's really one of the purposes of JSON-LD, so that the data can be accessed as JSON. But, when re-defining something like @context, we need to be wary of over-reach. I believe the way I defined it in the spec ensure that it can be processed as JSON-LD without placing too much of a burden on an implementation or publication. It may be that we end up making the default context implicit, and strictly limit the use of @context for defining only @language and @base, but I think it's premature to start there.

My view is the opposite: I believe that is where we should start. At the moment, we use only `@language` and `@base`; we should try to keep it at that for the moment. As for my original comment: I guess it is fairly easy to handle it without too much problems; our definition of `@context` should be:

`@context` may contain
- A URI
- An object containing, `@language` and `@base`
- An array consisting of one or more URI-s and a single object like above

With that definition we are JSON-LD compatible, but the readers (and the implementations) may ignore JSON-LD altogether if they wish. We may even go one step further and require that the value is _always_ an array, even if it contains only one single element.

We should also define the behaviour of `@context` with regard to the merge operation; I guess it should be considered to be an "array" property, meaning that the merge is defined specifically for this term, meaning:
- If both are single URI values, and those values are different, the result is an array of those values
- If both are single objects, then the objects should be merged in terms of the merge (currently 'import') algorithm
- Otherwise an array is created, containing the different URI-s, and A+B order, and, if applicable, a merge of the objects following the merge algorithm.

If we find another JSON-LD `@context` feature that we want to re-use, we can of course add it step by step. But, starting with the minimum, we will be forced to keep the final result as minimal as possible.

Ivan

> The complexity in JSON-LD I believe you're reacting to is for API implementations, not the language specification. The reference I added to the context definition is not overly complex IMO. The main thing needed to interpret a CSVW metadata document is to find language and base from the context, and not necessarily use the rest of the context for interpreting the surface JSON structure used for metadata.
> 
> The json-ld.org site shows 6 different implementations, and more seem to be on there way, as the mailing list remains fairly active. Anyway, these are for fully conforming implementations, and I'm not suggesting that these are necessary for our purposes. My own implementation makes use of just the context processing elements to avoid special-cases in interpreting values and expanding URLs.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
> As for my original comment: I guess it is fairly easy to handle it without too much problems; our definition of `@context` should be:
> 
> `@context` may contain
> - A URI
> - An object containing, `@language` and `@base`
> - An array consisting of one or more URI-s and a single object like above

I think we _are_ in agreement here.

> We should also define the behaviour of `@context` with regard to the merge operation; I guess it should be considered to be an "array" property, meaning that the merge is defined specifically for this term, meaning:
> - If both are single URI values, and those values are different, the result is an array of those values
> - If both are single objects, then the objects should be merged in terms of the merge (currently 'import') algorithm
> - Otherwise an array is created, containing the different URI-s, and A+B order, and, if applicable, a merge of the objects following the merge algorithm.

Yes, this is essentially my thinking, and I've been doing this in my implementation (although, I also maintain a parsed `@context` useful for my purposes).

**Comment by iherman** [comment]
Great! We seem to be settled as far as you and I are concerned. Let us see the others...

Cheers

Ivan

> On 10 Jan 2015, at 20:51 , Gregg Kellogg notifications@github.com wrote:
> 
> As for my original comment: I guess it is fairly easy to handle it without too much problems; our definition of @context should be:
> 
> @context may contain
> 
>   • A URI
>   • An object containing, @language and @base
>   • An array consisting of one or more URI-s and a single object like above
> I think we are in agreement here.
> 
> We should also define the behaviour of @context with regard to the merge operation; I guess it should be considered to be an "array" property, meaning that the merge is defined specifically for this term, meaning:
> 
>   • If both are single URI values, and those values are different, the result is an array of those values
>   • If both are single objects, then the objects should be merged in terms of the merge (currently 'import') algorithm
>   • Otherwise an array is created, containing the different URI-s, and A+B order, and, if applicable, a merge of the objects following the merge algorithm.
> Yes, this is essentially my thinking, and I've been doing this in my implementation (although, I also maintain a parsed @context useful for my purposes).
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
See #80.
