### ISSUE TITLE
Hooks for Call-back functions or Promises when parsing data?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#15]
[R-CellMicrosyntax](http://w3c.github.io/csvw/use-cases-and-requirements/index.html#CellMicrosyntax)

Do we want to provide a mechanism to hook user-defined call-back functions (or Promises) into the CSV parser to validate and process / convert embedded structured or semi-structured content?

**Comment by JeniT** [comment]
Think this issue has been overtaken by work on the metadata and conversion specs.
