### ISSUE TITLE
Security considerations of modifying path for metadata

### ISSUE THREAD

**Issue by scraperdragon** [w3c/csvw#154]
Surprised to not see a discussion on the tabular data model (http://www.w3.org/TR/tabular-data-model) of malicious metadata on websites where people might be able to publish to the same location: e.g. a  MediaWiki installation where users can't edit existing uploads might have a CSV file called http://upload.csvwiki.org/1/13/foo.csv with no metadata, but then this could be broken by a user uploading a file called http://upload.csvwiki.org/1/13/foo.csv-metadata.json .

(Granted, this only happens where there is no metadata available.)

(by analogy to https://upload.wikimedia.org/wikipedia/commons/1/13/Miura-Ori_CP.svg - crafting a metadata file with the same first md5sum byte (which is what I assume the 13 is) is trivial)

**Comment by iherman** [comment]
Doesn't this fall under the security section, as discussed by the (closed) #8? Maybe add this slightly more general security issue (compared to what is now in the draft) to the list? 

It is actually unclear whether the security should be addressed in one place (i.e., either the model or the metadata document) or in both.

**Comment by JeniT** [comment]
Looked at this during Feb F2F and think it's handled to the extent it needs to be in new security considerations section: http://w3c.github.io/csvw/metadata/#security-considerations

**Comment by danbri** [comment]
discussd somewhat at http://www.w3.org/2015/02/12-csvw-irc#T13-25-16 (but mixed with wider issues)
