### ISSUE TITLE
MAY NOT in Tabular Metadata confusing.

### ISSUE THREAD

**Issue by scraperdragon** [w3c/csvw#155]
http://www.w3.org/TR/tabular-metadata/#h-required-properties-2

`The targetFormat URL is intended as an informative identifier for the target format, and applications MAY NOT access the URL.` (also templateFormat)

'MAY NOT' is not an RFC 2119 requirement phrase; it's also incredibly confusing, since it's commonly synonymous with 'is not allowed to'.

I'd recommend '... applications MAY choose not to access ...' or '... applications SHOULD NOT access ...' depending on what was intended.

**Comment by gkellogg** [comment]
Closing this issue without prejudice.
