### ISSUE TITLE
Inconsistent naming of uriTemplate property

### ISSUE THREAD

**Issue by jaw111** [w3c/csvw#160]
The vocabulary defines the URI for the property as `http://www.w3.org/ns/csvw#uriTemplate`, but the property is referred to as "urlTemplate" at several points in the HTML documents:
- https://github.com/w3c/csvw/blob/gh-pages/csv2rdf/index.html#L750
- https://github.com/w3c/csvw/blob/gh-pages/csv2rdf/index.html#L881-L886
- https://github.com/w3c/csvw/blob/gh-pages/csv2rdf/index.html#L1108-L1110
- https://github.com/w3c/csvw/blob/gh-pages/csv2rdf/index.html#L1342
- https://github.com/w3c/csvw/blob/gh-pages/csv2json/index.html#L576
- https://github.com/w3c/csvw/blob/gh-pages/csv2json/index.html#L641
- https://github.com/w3c/csvw/blob/gh-pages/csv2json/index.html#L648
- https://github.com/w3c/csvw/blob/gh-pages/csv2json/index.html#L838-L840
- https://github.com/w3c/csvw/blob/gh-pages/csv2json/index.html#L1024

n.b. this is not an exhaustive list

**Comment by gkellogg** [comment]
All uses of uriTemplate have been changed to urlTemplate. Note that we still reference "URI Template" and have a "URI Template Property", but that is a separate recommendation.
