### ISSUE TITLE
Relation between ``separator`` and cell parsing

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#164]
The spec says that a possible `separator` property in a column description means that the cell's value is turned into a list of values. First of all, it is presumably so that, for example, each value in the array should then be parsed separately according to the datatype; it would be better to spell this out in the document. 

However, the issue arises if the cell is a URI, i.e., a `urlTemplate` is used. Would then the template be applied repeatedly for each value? What happens if a `urlTemplate` in another cell refers to this one? Ie, the data is

```
cell1, cell2
a;b;c, q
```

the separator character is `;`, and there is a url template for the column with the name `cell2` of the form, say, `http://www.example.org/{cell1}`. What happens when one generates the triple (or JSON object) for the value of `cell2`. Is it

`
http://www.example.org/a;b;c
`

or a list of 

`
[http://www.example.org/a,http://www.example.org/b,http://www.example.org/c]
`

Either approach is defendable, but the specification should spell it out.

**Comment by iherman** [comment]
It seems that this issue is actually solved by RFC6570. If I look at one of the [RFC6570 implementation's documentation](https://medialize.github.io/URI.js/uri-template.html) it actually has a table for what the RDC specifies what happens if the value of the variable is an array. Essentially, it just joins the array elements, with commas, and adds that to the URI. I.e., there is no real complication with that. Best to look at the table for the details!

**Comment by JeniT** [comment]
@iherman Are you happy to close this issue then?

**Comment by iherman** [comment]
Issue moot by virtue of RFC6570
