### ISSUE TITLE
Relative order of datatype handling and template expansion for cell values

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#166]
This is a bit more general than issue #164. The question is: when expanding a template that refers to another cell in the same row, what is exactly the value one has to use: before or after datatype handling? Eg, if the template is `http://example.org/{cname}`, and the cell referred to by `cname` is flagged with a `datatype` for date (and a formatting instruction is provided), is the value to be used in the template the raw cell value or the normalized date value? (This is currently not specified.)

Instinctively the reaction is probably to use the value after datatype handling. The issue, however, comes back to issue #164: if the "target" is actually a list of values after handling the cell, does it mean to generate many URI-s, i.e., (in the case of RDF) not one but many triples? (And this may be the right answer.)

In any case, this must be clearly described.

Ivan

**Comment by gkellogg** [comment]
Me feeling is that it is before format/datatype application, and certainly before separating sub-values using `separator`. However, it certainly needs to take at least `trim` into consideration.

**Comment by iherman** [comment]
Agree for `trim`. However, on whether it is before or after formatting: while doing template expansion on the raw values is really easier to implement, there may be some compelling use cases, e.g., if one wants to use ISO formatted dates in URI-s.  So I am not sure...

On the other hand, the usage of `separator` frightens me in this respect. It means that the expansion of a template would generate loads of results, mainly if there are several template variables, each pointing to lists...

**Comment by iherman** [comment]
As I just commented on issue #164 it seems that the `separator` issue for url templates is pretty much moot. If so, I would rather be in favor of defining the order by using the "generated" cell value as a variable replacement in the templates. It is not particularly complicated to do so, and there might be cases where this becomes useful...

(It still has to be documented, though!)

**Comment by JeniT** [comment]
I'm not sure how to use the post-conversion values but _before_ separating the values. If we have the cell value `"1;2;3"` with `separator=;` and `datatype=decimal` then the post-conversion value is an array of `[1.0, 2.0, 3.0]` &mdash; separation occurs prior to interpretation as decimal values. The only values that are captured in the data model are the string value (`"1;2;3"`) and the semantic value (the array `[1.0, 2.0, 3.0]`).

I think that in the URL templates we should be using the semantic value of the relevant cell rather than the string value. The URL template spec talks about how lists are processed; we just have to point out that the implementation should use the canonical serialisation of the relevant values in the list.

**Comment by iherman** [comment]
> On 28 Jan 2015, at 15:02 , Jeni Tennison notifications@github.com wrote:
> 
> I'm not sure how to use the post-conversion values but before separating the values. If we have the cell value "1;2;3" with separator=; and datatype=decimal then the post-conversion value is an array of [1.0, 2.0, 3.0] — separation occurs prior to interpretation as decimal values. The only values that are captured in the data model are the string value ("1;2;3") and the semantic value (the array [1.0, 2.0, 3.0]).

That is correct.

> I think that in the URL templates we should be using the semantic value of the relevant cell rather than the string value. The URL template spec talks about how lists are processed; we just have to point out that the implementation should use the canonical serialisation of the relevant values in the list.

Right. So if the name of the column with your example above is 'jname', and the template is "http://www.ex.org/{jname}" then the generated URI, per template definition and with that order will be "http://www.ex.org/1.0,2.0,3.0". This is what I realized and commented in:

https://github.com/w3c/csvw/issues/164#issuecomment-70283989

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
Editor actions:
- [x] ensure that resolution of URI template properties includes something about how eg date/numeric values are serialised into the template
- [x] add a worked example

**Comment by gkellogg** [comment]
@JeniT I realize we didn't completely resolve the need to both perform datatype mapping, where individual values may be delimited, and to pass on the non-delimited value for URI expansion. This seemed clear to you, so perhaps you could either take the editor action, or elaborate in this issue and I'll edit.

**Comment by iherman** [comment]
And... my impression was that the expansion happens with mapped values...

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by gkellogg** [comment]
Yes, I had a misunderstanding about this and thought that RFC6570 used comma-delimited values, but clearly it is an array of values, which is consistent with using the separated and converted values. I'll add an example to clarify this to PR #215 on the branch for issue #61.

**Comment by JeniT** [comment]
I'd thought that such examples would go better in the section on [URI template properties](http://w3c.github.io/csvw/metadata/#dfn-uri-template-property), what do you think? We also need examples that show what happens when the value is `null` though I think that the templates still get expanded with the `null` value, and it's then up to the conversion specifications to say "if the value of the cell is `null`, the property isn't generated".

**Comment by gkellogg** [comment]
To keep this from being overwhelming, maybe we should just start by creating example placeholders with a brief description of what the example should demonstrate. We can then go through and add them subsequently. As you know, each example takes time to create and write-up. Note that the example on virtual columns hits on URI templates, so maybe that can be de-composed and re-used in parts for different locations.
