### ISSUE TITLE
Restriction in the rfc6570 syntax to be documented

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#168]
The (RFC6570)[http://tools.ietf.org/html/rfc6570] template specification has a restriction on the variable syntax. Indeed, [Section 2.3](http://tools.ietf.org/html/rfc6570#section-2.3) in that spec says:

```
     variable-list =  varspec *( "," varspec )
     varspec       =  varname [ modifier-level4 ]
     varname       =  varchar *( ["."] varchar )
     varchar       =  ALPHA / DIGIT / "_" / pct-encoded
```

What this means that, to take our canonical example, that while the template `http://example.org/{GID}` is valid, `http://example.org/{inventory-date}` is not; `inventory-date` must be percent encoded.

This may be a drag for the user, but we may have to live with it. But this has to be documented somewhere, although probably through an informal note, and implementations must be careful about it...

**Comment by JeniT** [comment]
This is done at http://w3c.github.io/csvw/metadata/#column-name

**Comment by gkellogg** [comment]
I intend to go through examples in syntax and metadata to clean such things up. I did get `inventory-date`, I believe.
