### ISSUE TITLE
Is CSV packaging within scope?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#17]
[R-CsvAsSubsetOfLargerDataset](http://w3c.github.io/csvw/use-cases-and-requirements/index.html#R-CsvAsSubsetOfLargerDataset)

Ivan says:

"Hm. Do we define CSV packaging in this Working Group? Is this in scope? We could decide it is, though we should check this with the charter."

**Comment by JeniT** [comment]
We decided not to say anything about packaging formats.
