### ISSUE TITLE
Need default metadata

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#175]
When interpreting CSVs where there is no user-supplied, file-specific or directory-specific metadata, we need a default. This will be used to interpret the CSV and extract embedded metadata.

This is an offshoot of issue #144.

@iherman writes:

> We should look at the default metadata overall as a separate issue. Eg., there may be an approach to take the R2RML Direct Mapping as a starting point for the default metadata (wherever appropriate).

Another approach is to use essentially empty TableGroup:

```
{
  "@type": "TableGroup",
  "resources": []
}
```

**Comment by iherman** [comment]
> On 23 Jan 2015, at 17:54, Gregg Kellogg notifications@github.com wrote:
> 
> When interpreting CSVs where there is no user-supplied, file-specific or directory-specific metadata, we need a default. This will be used to interpret the CSV and extract embedded metadata.
> 
> There is no requirement that there must be an embedded metadata, right? Ie, the default should be defined for a completely "bare" CSV file, too.

Ivan

> This is an offshoot of issue #144.
>

**Comment by gkellogg** [comment]
If the default sets "header@ to false, then it would have that effect, but then the Content-Type header value would make no sense.

**Comment by iherman** [comment]
What I am saying is that if there is no built-in metadata, then

> {
>   "@type": "TableGroup",
>   "resources": []
> }

becomes meaningless. We have to provide a default metadata covering that case, too.

Ivan

> On 23 Jan 2015, at 19:37 , Gregg Kellogg notifications@github.com wrote:
> 
> If the default sets "header@ to false, then it would have that effect, but then the Content-Type header value would make no sense.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
No, it's not meaningless: it means to use the first row of the CSV as a header line to generate output. The first 10 tests in the test suite have no explicit metadata, but produce useful output: https://github.com/w3c/csvw/tree/test-updates/tests. For example test010:

```
@prefix :     <test010.csv#> .
@prefix csvw: <http://www.w3.org/ns/csvw#> .
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .

:country a rdf:Property ;
  rdfs:label "country" .

:name a rdf:Property ;
  rdfs:label "name" .

:table a csvw:Table ;
  dcat:distribution [
    a dcat:Distribution ;
    dcat:downloadURL <test010.csv> 
  ] ;
  csvw:row [
    :country "AD" ;
    :name "Andorra" ;
  ] , [
    :country "AF" ;
    :name "Afghanistan" ;
  ] , [
    :country "AI" ;
    :name "Anguilla" ;
  ] , [
    :country "AL" ;
    :name "Albania" ;
  ] ;
  .
```

Using `header=false` or `Content-Type: text/csv;header=absent` as in test019:

```
@prefix : <http://w3c.github.io/csvw/tests/test019.csv#> .
@prefix csvw: <http://www.w3.org/ns/csvw#> .
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

:table a csvw:Table;
   csvw:row [
     <http://w3c.github.io/csvw/tests/test019.csv#_col=1> "GID";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=2> "On Street";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=3> "Species";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=4> "Trim Cycle";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=5> "Inventory Date"
   ],  [
     <http://w3c.github.io/csvw/tests/test019.csv#_col=1> "1";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=2> "ADDISON AV";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=3> "Celtis australis";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=4> "Large Tree Routine Prune";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=5> "10/18/2010"
   ],  [
     <http://w3c.github.io/csvw/tests/test019.csv#_col=1> "2";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=2> "EMERSON ST";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=3> "Liquidambar styraciflua";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=4> "Large Tree Routine Prune";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=5> "6/2/2010"
   ],  [
     <http://w3c.github.io/csvw/tests/test019.csv#_col=1> "3";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=2> "EMERSON ST";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=3> "Liquidambar styraciflua";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=4> "Large Tree Routine Prune";
     <http://w3c.github.io/csvw/tests/test019.csv#_col=5> "6/2/2010"
   ];
   dcat:distribution [
     a dcat:Distribution;
     dcat:downloadURL <http://w3c.github.io/csvw/tests/test019.csv>
   ] .
```

**Comment by iherman** [comment]
Gregg,

I am really messed up by the different mails and issues. What you say means that you have a default metadata somewhere. What I want is to see that clearly written down somewhere in our documents so that we can cross check it. Spreading over several mails and issues messes me up.

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by JeniT** [comment]
After all the other editor actions, @iherman will look through the metadata document to see whether defaults are defined sufficiently.

**Comment by JeniT** [comment]
@iherman I think we've got to the point where you could look to see whether there's sufficient definition of defaults in the metadata document, please?

**Comment by iherman** [comment]
I think the documents are fine, but I still have one issue.

The most widespread option, I believe, is when a CSV file has its first row denoting the column titles. I had to dig down into the (informative) section 7 and find that default setting in 7.3.3.2. I think many of our readers will not get into the details of section 7 anyway (certainly not the metadata authors) while, nevertheless, this information is important.

I wonder whether this special case of embedded metadata should not be called out explicitly in the text. Actually, I wonder whether this could/should not be a normative case: if all the skip row and other dialect values are such that they indicate the first row being the only embedded metadata information, then the default metadata must be the one assigning those names.

/cc @gkellogg @JeniT

**Comment by iherman** [comment]
Discussed on 2015.3.18, agreed to add a simple example into the syntax document at section 4.2 showing a table with a single header line
