### ISSUE TITLE
Is the DCAT block useful in the RDF output.

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#177]
This issue is split out from issue #93:

The Table subject of the RDF output is either the location URL, or the location URL with the `#table` fragment identifier (choose). The `dcat:distribution` block describes much the same thing, but is of 
questionable use.  For example:

  [this is intended to show an RDF output represented as JSON-LD; imagine it as Turtle]

```
{
  “@id”: “tree-ops.csv#table”,
  “@type”: “Table”,
  “dcat:distribution”: {
    “@type”: “dcat:Distribution”,
    “dcat:downloadURL”: “tree-ops.csv",
    “dcat:mediaType”: “text/csv"
  } ,
  ...
}
```

Is this block useful enough to retain in the RDF mapping?

**Comment by JeniT** [comment]
Suggestion: don't add `dcat:distribution`, but do have, in the generated RDF output:

```
_:table csvw:url <tree-ops.csv> .
```

**Comment by danbri** [comment]
See http://www.w3.org/2015/02/13-csvw-irc#T15-38-53

**Comment by JeniT** [comment]
Resolved at Feb F2F. Including DCAT descriptions of provenance are (like Prov provenance) implementation defined. But we will have `csvw:url` properties added in the result of the RDF description.

**Comment by 6a6d74** [comment]
csv2rdf and csv2json docs updated as per resolution. No mention is made of DCAT; but we do use `csvw:url` to refer to the source CSV+ files.
