### ISSUE TITLE
Do we need "virtual" ("phantom") columns, i.e., columns with their own and separate 'aboutUrl' value?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#179]
This is a spin-off of issue #96 (and it allows closing #96).

The metadata allows for a `aboutUrl` template, that defines, both for the JSON and RDF mappings, the url for a row. This url binds together all cells in a row; for JSON, this manifests itself in an object for each row, in RDF as a series of triples sharing a common subject. As such, the natural place for the `aboutUrl` is the `tableSchema` level.

The question is whether it is allowed to define `aboutUrl` for an individual column, i.e., create a separate url for a specific cell in a role ("phantom" columns). If it is allowed, the question is how it translates in JSON and RDF.

@gkellogg has proposed a structure in https://github.com/w3c/csvw/issues/96#issuecomment-71960586. However, this looks fairly arbitrary to me. It makes sense for the data below, of course, but if I can have a separate subject for a column, well, a cell (by virtue of using a template) then those triples or JSON objects may, logically, be completely 'outside' the basic row structure (therein lies the complication!). Ie, we could simple remove the "row" relationship and have each columns and triples being loose, or having those out-of-band objects and triples being completely loose somehow tied to the table, or... I am not sure. 

We need to look at the use cases and see what structures there is (if any) for those cases to see where we go with this. At the moment, I am more in favor of disallowing `aboutUrl` in a column.

**Comment by gkellogg** [comment]
Let's look at an example from my old [CSV-LD proposal](https://github.com/w3c/csvw/blob/gh-pages/csv-ld/CSV-LD.md). Consider the following CSV:

```
doap_id,doap_name,foaf_id,foaf_name
http://rubygems.org/gems/json-ld,JSON::LD,http://greggkellogg.net/foaf#me,Gregg Kellogg
http://rubygems.org/gems/rdf,RDF.rb,http://greggkellogg.net/foaf#me,Gregg Kellogg
```

We can imagine the kind of result we might want to see. In RDF, we might want the following:

```
:table a csv:Table;
  csv:row <http://rubygems.org/gems/json-ld>,
   <http://rubygems.org/gems/rdf> .

<http://rubygems.org/gems/json-ld> doap:name "JSON::LD";
  doap:developer <http://greggkellogg.net/foaf#me> .

<http://rubygems.org/gems/rdf> doap:name "RDF.rb";
  doap:developer <http://greggkellogg.net/foaf#me> .

<http://greggkellogg.net/foaf#me> foaf:name "Gregg Kellogg" .
```

In JSON, perhaps something like the following:

```
{
  "row": [{
    "url": "http://rubygems.org/gems/json-ld",
    "name": "JSON::LD",
    "developer": {
      "url": "http://greggkellogg.net/foaf#me",
      "name": "Gregg Kellogg"
    }
  }, {
    "url": "http://rubygems.org/gems/rdf",
    "name": "RDF.rb",
    "developer": {
      "url": "http://greggkellogg.net/foaf#me",
      "name": "Gregg Kellogg"
    }
  }]
}
```

Then, we can think how the metadata might look to reproduce this:

```
{
  "url": "...",
  "schema": {
    "aboutUrl": "{doap_id}",
    "columns": [{
      "name": "doap_id",
      "supress": true,
    }, {
      "name": "doap_name",
      "propertyUrl": "http://usefulinc.com/ns/doap#name",
    }, {
      "name": "doap_name",
      "propertyUrl": "http://usefulinc.com/ns/doap#name",
    }, {
      "name": "foaf_id",
      "propertyUrl": "http://usefulinc.com/ns/doap#developer",
      "valueUrl": {foaf_id}
    }, {
      "name": "foaf_name",
      "aboutUrl": "{foaf_id}"
      "propertyUrl": "http://xmlns.com/foaf/0.1/name",
    }]
  }
}
```

If we eliminated the `doap_id` and `foaf_id` columns, we would need to introduce a phantom column to join the two together.

This might be useful for discussing requirements for RDF and JSON transformations and how they may need to behave.

**Comment by gkellogg** [comment]
Here's a version without the IDs. Consider the following CSV:

```
doap_name,foaf_name
JSON::LD,Gregg Kellogg
RDF.rb,Gregg Kellogg
```

If we wanted to keep the same structure, we might expect something like the following:owing:

```
:table a csv:Table;
  csv:row :_row.1, :_row.2 .

[doap:name "JSON::LD"; doap:developer :dev.Gregg%20Kellogg] .

[:_row.2 doap:name "RDF.rb"; doap:developer :dev.Gregg%20Kellogg] .

:dev.Gregg%20Kellogg foaf:name "Gregg Kellogg" .
```

In JSON, perhaps something like the following:

```
{
  "row": [{
    "name": "JSON::LD",
    "developer": {
      "url": "http://example.org/doap.csv#dev.Gregg%20Kellogg",
      "name": "Gregg Kellogg"
    }
  }, {
    "name": "RDF.rb",
    "developer": {
      "url": "http://example.org/doap.csv#dev.Gregg%20Kellogg",
      "name": "Gregg Kellogg"
    }
  }]
}
```

This requires a phantom column:

```
{
  "url": "http://example.org/doap.csv",
  "schema": {
      "name": "doap_name",
      "propertyUrl": "http://usefulinc.com/ns/doap#name",
    }, {
      "name": "doap_name",
      "propertyUrl": "http://usefulinc.com/ns/doap#name",
    }, {
      "name": "foaf_name",
      "aboutUrl": "#dev.{foaf_name}"
      "propertyUrl": "http://xmlns.com/foaf/0.1/name",
    }, {
      "name": "doap_foaf",
      "phantom": true,
      "propertyUrl": "http://usefulinc.com/ns/doap#developer",
      "valueUrl": "#dev.{foaf_name}"
    }]
  }
}
```

This shows that it might be useful to have a way for URI template to be treated like a BNode, which _might_ be possible without redefining URI template. Maybe something like `_:{foaf_name}` would give the pre-expansion form of `_:Gregg%20Kellogg`, and we could have wording which would construct a BNode identifier denoting the same BNode throughout the processor run across all rows, by recognizing that the pre-resolved URI has the form "_:.*".

**Comment by iherman** [comment]
Wait. We are conflating, again, two different issues.

# Having a column description in the schema that does not correspond to any column in the original data.

# Allowing the definition of an 'aboutUrl' template for a specific column, resulting in different subjects (in RDF) for different columns in the same row

If indeed we are talking about these two, can we, please, separate these two issues?

In general, I am fighting feature creep. Obviously, for any feature we may find bona fide data sets that would make use of it, but this version of what we do should deliberately be simple. We decided to delegate more advanced features to the generic, separate mechanism, and have added hooks into the metadata for that purpose; hence my opposition to both of these features up there, actually.

Ivan

> On 29 Jan 2015, at 23:37 , Gregg Kellogg notifications@github.com wrote:
> 
> Here's a version without the IDs. Consider the following CSV:
> 
> doap_name,foaf_name
> JSON::LD,Gregg Kellogg
> RDF.rb,Gregg Kellogg
> 
> If we wanted to keep the same structure, we might expect something like the following:owing:
> 
> :table a csv:Table;
>   csv:row :_row.1, :_row.2 .
> 
> [doap:name "JSON::LD"; doap:developer :dev.Gregg%20Kellogg] .
> 
> [:_row.2 doap:name "RDF.rb"; doap:developer :dev.Gregg%20Kellogg] .
> 
> :dev.Gregg%20Kellogg foaf:name "Gregg Kellogg" .
> 
> In JSON, perhaps something like the following:
> 
> {
>   "row": [{
>     "name": "JSON::LD",
>     "developer": {
>       "url": "http://example.org/doap.csv#dev.Gregg%20Kellogg",
>       "name": "Gregg Kellogg"
>     }
>   }, {
>     "name": "RDF.rb",
>     "developer": {
>       "url": "http://example.org/doap.csv#dev.Gregg%20Kellogg",
>       "name": "Gregg Kellogg"
>     }
>   }]
> }
> 
> This requires a phantom column:
> 
> {
>   "url": "http://example.org/doap.csv",
>   "schema": {
>       "name": "doap_name",
>       "propertyUrl": "http://usefulinc.com/ns/doap#name",
>     }, {
>       "name": "doap_name",
>       "propertyUrl": "http://usefulinc.com/ns/doap#name",
>     }, {
>       "name": "foaf_name",
>       "aboutUrl": "#dev.{foaf_name}"
>       "propertyUrl": "http://xmlns.com/foaf/0.1/name",
>     }, {
>       "name": "doap_foaf",
>       "phantom": true,
>       "propertyUrl": "http://usefulinc.com/ns/doap#developer",
>       "valueUrl": "#dev.{foaf_name}"
>     }]
>   }
> }
> 
> This shows that it might be useful to have a way for URI template to be treated like a BNode, which might be possible without redefining URI template. Maybe something like _:{foaf_name} would give the pre-expansion form of _:Gregg%20Kellogg, and we could have wording which would construct a BNode identifier denoting the same BNode throughout the processor run across all rows, by recognizing that the pre-resolved URI has the form "_:.*".
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
The use of a _phantom column_ comes about because of `aboutUrl` being a common property. That was done in issue #96, from which this was split out, so this issue pre-supposes that `aboutUrl`, `propertyUrl`, and `valueUrl`. The issue that necessitates the discussion of a _phantom property_ is how to handle column definitions having different `aboutUrl` values. In the first example above, this isn't necessary, as there is a `foaf_id` column which can be used to join the different subjects on that row. In the second example, there is no such id, and a _phantom column_ is required to create a relationship between the different subjects.

**Comment by iherman** [comment]
O.k. So this does not mean to introduce a column description that does not correspond to a real column in the data, then it is fine. In fact, the 'phantom property' may be a misleading name here...

Coming back to the original issue, and the structure you propose in #96 for the output: wouldn't it be simpler to say that if a column is having its own `aboutUrl`, then the corresponding triple, in RDF, is just related directly to the top level `table` through some extra property (and the corresponding k/v pair in JSON would hand directly on the root)? Say, in JSON, we could have something like:

```
{
  "row" : [ ... the usual objects we had so far ...],
 "extra" : [ ... a collection of extra objects ...]
}
```

After all, the intention of the extra `aboutUrl`, if introduced, is that the corresponding object is not really part of the row, but somehow separated...

Not sure, to be honest. Just musing... We should look again at the use case collection.

**Comment by gkellogg** [comment]
> O.k. So this does not mean to introduce a column description that does not correspond to a real column in the data, then it is fine. In fact, the 'phantom property' may be a misleading name here...

I don't see how you draw that conclusion. The example I used above needs this to join together different columns. The "doap_foaf" column is a phantom column that has a subject of the general `aboutUrl` and `valueUrl` the same as the `aboutUrl` of columns that are supposed to be in a FOAF entity referred to from the DOAP entity.

**Comment by iherman** [comment]
Well, sorry, I was misled by your formulation:

> The issue that necessitates the discussion of a phantom property is how to handle column definitions having different aboutUrl values.

But you are right in looking at the doap example. So back to what I said in https://github.com/w3c/csvw/issues/179#issuecomment-72167112 : we do have two, in my view, different issues:
1. Having a column description in the schema that does not correspond to any column in the original data.
2. Allowing the definition of an 'aboutUrl' template for a specific column, resulting in different subjects (in RDF) for different columns in the same row

And, at this moment, I am not enthusiastic to include any of these two features in what we call a _simple_ mapping.

I expect this to be discussed at the F2F.

**Comment by JeniT** [comment]
Resolved at Feb F2F. We will implement virtual columns for the next version of the spec, with an explicit request for comments about it as a feature.

**Comment by gkellogg** [comment]
Pirate Pad content: https://gist.github.com/gkellogg/738ccee76711b4432bb4

**Comment by rufuspollock** [comment]
I would comment that we are starting to add a lot of "rdf" complexity into the base spec.

I'm curious what the use case is for this (and whether it merits the additional complexity).

**Comment by gkellogg** [comment]
Reopening, as we resolved this to be an LCR issue.

**Comment by danbri** [comment]
With my Google hat on, we find immense value in this feature. It allows CSV to capture much more idiomatic structured data, especially common schema.org patterns that we are consuming. It also helps with Data Cube mappings into CSV.

**Comment by gkellogg** [comment]
Also, note that the features such as `aboutUrl` also affect the JSON representation, not just RDF, to quite good effect, IMO.

The `virtual` is a necessary result of that, as data needs to be inserted to relate different _abouts_ together, as well as introduce information such as entity type.

This also has a parallel in more more complex spreadsheet formats where calculated columns are commonly used, which could be considered a kind of virtual column.

**Comment by iherman** [comment]
Having looked at the [relationships to RDB2RDF's Direct mapping](https://github.com/w3c/csvw/wiki/Direct-mapping-vs.-CSV2RDF,-simple-case-with-foreign-keys) it turns out that the virtual column mechanism is necessary to have a compatibility. An interoperability with Direct Mapping is an important feature; I propose we close the issue and leave the feature in the document.

**Comment by iherman** [comment]
Closing the issue, also per [telcon discussion](http://www.w3.org/2015/04/22-csvw-minutes.html)
