### ISSUE TITLE
Change default for `name` from `"_col=[N]"`

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#180]
This value was originally established in the CSV2RDF spec, to generate column property identifiers if a column name is not established. The Metadata spec just picked this up as the default for `name`, which is then used to create `predicateUrl` if not established. However, this is unfriendly for many serialization formats unless escaped. Suggest to change to `"_col.[N]`, where `[N]` is the row number. Examples using something similar for `_row=[N]` should be changed similarly.

@jeniT suggested something like this, but wanted to pass by @iherman and @6a6d74.

**Comment by iherman** [comment]
I do not have strong feelings about this, to be honest... if `_col.[N]` works for all serializations, it works for me...

**Comment by gkellogg** [comment]
Once other outstanding PRs are merged, I'll do this (without objection), as well as instances of `#row=` to  use `#row.` in examples to avoid painful merge clashes.

**Comment by JeniT** [comment]
@gkellogg could you also update the description of the required syntax for `name` to allow `.`s please, because it should.
