### ISSUE TITLE
Definition of the natural language property value

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#181]
Section 3.1 describes, in a separate description item, the value of a natural language property, and it says:

> - if the metadata value is a string, that string
> - if the metadata value is an array, the strings in that array
> - if the metadata value is an object, the string or strings that are the value of the property of that object whose name is value of the lang inherited property on that description, or und if no lang is defined.

However, the role of the (inherited) `lang` property is meant to be used for the data and not for the metadata content. I believe the value to be considered is the (possible) `@language` value in the `@context`.

**Comment by gkellogg** [comment]
Yes, overly aggressive copy/paste. I'll change it back to `@language`.
