### ISSUE TITLE
Fall-back value of the `name` property?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#182]
The metadata document defines the fallback value of the `name` property as follows:

> The property value of name is that defined within metadata, if it exists. Otherwise, it is the first property value of title as a string without language, if any. Otherwise, it is the string "_col=[N]" where [N] is the column number.

The definition does not seem to be clear to me. The property value definition allows it to be an object of the sort 

```
  { "en" : "my title", "fr" : "mon titre"}
```

in which case the "first property value" does not make sense.  Also, take the following example for a metadata

```
 {
    "@context" : { "@language" : "en" }
    ...
       {
          "title" : { "en" : "my title", "fr" : "mon title" }
         ...
```

I presume we definitely want "my title" to be used as a "name". Wouldn't it be better to define this as something like:

> Otherwise, it is the first property value of title as a string with either the metadata's default language tag or (conceptually) "und", in case such default language tag is not defined. Otherwise...

See also [my comment on the mailing list](https://lists.w3.org/Archives/Public/public-csv-wg/2015Jan/0067.html) which may be relevant here (looking at an alternative of the 'property value' definition for natural language properties).

**Comment by gkellogg** [comment]
Yes, I think this is the right interpretation. I can make it so.

**Comment by gkellogg** [comment]
Actually, the wording is the following:

> The _property value_ of `name` is that defined within metadata, if it exists. Otherwise, it is the first _property value_ of `title` as a string without language, if any. Otherwise, it is the string "_col=[N]" where [N] is the column number.

As _property value_ takes into consideration the _default language_ (i.e. `@language), it has that effect already.

**Comment by JeniT** [comment]
Regarding normalisation, I note that the URI template allows percent encoding of characters in variable names, so suggest that characters that aren't in the set `[a-zA-Z0-9_.]` are percent encoded, as is any leading `.` (not allowed by URI template spec) or `_` (reserved by our spec).

**Comment by JeniT** [comment]
This is fixed in current wording (at Feb F2F). http://w3c.github.io/csvw/metadata/#columns

**Comment by danbri** [comment]
see http://www.w3.org/2015/02/12-csvw-irc#T11-38-23
