### ISSUE TITLE
Should we remove column metadata in RDF mapping

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#189]
Fresh issue based on discussion from #186.

Suggested resolution: we remove all column metadata from the RDF mapping.

**Comment by iherman** [comment]
I agree

**Comment by gkellogg** [comment]
Yes, I agree too. We should also consider what happens to Schema metadata, as you can have common properties defined on a Schema.

Are we saying that there should be no common properties on a Column? If not, then how does it appear in the RDF output?

**Comment by danbri** [comment]
See http://www.w3.org/2015/02/12-csvw-irc#T17-53-32

**Comment by JeniT** [comment]
Resolved at Feb F2F. In the RDF output there will only be descriptions of table groups and tables (not descriptions of columns, schemas, cells etc), alongside the data itself. Hence any common properties (eg descriptions) on columns, schemas, cells etc will not make it into the RDF output. There may be a link to the metadata.

**Comment by 6a6d74** [comment]
csv2rdf doc now updated as per resolution; column metadata is _gone_!
