### ISSUE TITLE
geopoint definition in metadata vocabulary needs more consideration

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#19]
The [datatypes](http://w3c.github.io/csvw/metadata/index.html#datatypes) section within the [Metadata Vocabulary for Tabular Data](http://w3c.github.io/csvw/metadata/index.html) defines `geopoint`:

"""
a comma-separated longitude and latitude (ie values that after stripping leading and trailing whitespace are in the format longitude\s_,\s_latitude)
"""

[GeoJSON defines "positions"](http://geojson.org/geojson-spec.html#positions) as the basic element of geometry and uses a JSON array to hold the individual coordinate values.

It's important to specify the coordinate reference system (CRS) within which the lon/lat are provided; a default CRS is typically [WGS](http://en.wikipedia.org/wiki/World_Geodetic_System) 84.

Normally, this is defined using [EPSG 4326](http://www.opengis.net/def/crs/EPSG/0/4326) with the coordinate tuples as [lat, lon]

Alternatively, one may also choose to include altitude (from the geoid surface) using [EPSG 4979](http://www.opengis.net/def/crs/EPSG/0/4979) which defines coordinate tuples as [lat, lon, alt].

[GeoJSON also allows the CRS](http://geojson.org/geojson-spec.html#coordinate-reference-system-objects) to be user defined with the `crs` object.

My concern is that the specification over trivializes the geometry constructs & more consideration needs to be taken to incorporate best practice from existing geo data specifications.

**Comment by rtroncy** [comment]
The question regarding the specification of a particular CRS (other than a default one such as WGS84) has been (and is still) largely discussed within the [locadd community group](http://www.w3.org/community/locadd/) and it is one of the core topic of the proposed [Geo Data on the Web Working Group](http://www.w3.org/2014/05/geo-charter). Indeed, a geopoint should be defined with more than a pair of lat/long values

**Comment by JeniT** [comment]
At our October 2014 F2F at TPAC, we resolved to not specify `geojson` as a datatype, so closing this issue.
