### ISSUE TITLE
Effect of tableSchema on both Table and TableGroup

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#195]
The spec doesn't say how to treat tableSchema when used both in a TableGroup or a Table. This may also come about because one Metadata file has a TableGroup/tableSchema and the other a Table/tableSchema.

There are two ways to handle this:
1. The effect is the same as merging two Schemas from different Metadata files that match on `url`, there the Table version is treated like `A` and the TableGroup version like `B`.
2. A Table with a tableSchema completely overrides the tableSchema from the TableGroup, so that a TableGroup/tableSchema only comes into play when a Table definition has no tableSchema entry.

I can see plusses and minuses for both interpretations.

**Comment by gkellogg** [comment]
Note that templates has a similar consideration, but presumably here it makes more sense to merge TableGroup templates into Table templates.

**Comment by JeniT** [comment]
I propose that the schema for a table completely overrides the schema defined for the table group.

**Comment by gkellogg** [comment]
+1 I reached the same conclusion. The implication is if you want to add metadata (such as different title languages), you do it in a separate metadata file, not in a TableGroup.

**Comment by danbri** [comment]
discussed -  http://www.w3.org/2015/02/18-csvw-irc#T15-06-30

**Comment by JeniT** [comment]
Editor action: follow https://github.com/w3c/csvw/issues/195#issuecomment-74710450
