### ISSUE TITLE
Is row by row processing sufficient?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#20]
In the [Processing Model of the Generating RDF from Tabular Data on the Web doc](http://w3c.github.io/csvw/csv2rdf/#processing), there is an issue raised stating:

"""
Independently processed rows - is this always the case?
"""

There are examples (see [Use Case #24 - Expressing a hierarchy within occupational listings](http://w3c.github.io/csvw/use-cases-and-requirements/#UC-ExpressingHierarchyWithinOccupationalListings)) where "blank" fields imply "ditto" to the field above (or the last time that field was not blank). At first glance, this seems pretty trivial, yet the example in the use case uses a multi-level hierarchy, and sometimes "blank" means "empty" (null) not "ditto". As such, the arbitrary processing required to "guess the behaviour applied to blank cells" is somewhat challenging.

As such, I recommend that we don't try to process this mode of behaviour during the transformation. If people have CSV data with "blanks that mean ditto", they need to fill in the blanks first.

Given that, I suggest that we stick with the model that processes each row independtly and does not require us to maintain state from row to row.

**Comment by stasinos** [comment]
Jeremy, all,

Merged cells in Spreadsheets are CSV serialized as empty cells that
mean "same as above" or "same as on the left", depending the range
that was merged. I think that this is common enough that it deserves
to be handled without expecting that the publisher massages their
data. In fact, the "same as on the left" case appears in the Excel
files of Use Case #8 - Analyzing Scientific Spreadsheets [1]

Furthermore, this is very similar to:

R-MissingValueDefinition: Ability to declare a "missing value" token
and, optionally, a reason for the value to be missing [2]

My proposal is to extend R-MissingValueDefinition to something along
the lines of:

Ability to declare a "missing value" token and, optionally, a reason
for the value to be missing or an action to be taken to fill in the
value. Actions to be taken should be selected from a closed vocabulary
to be specified by the WG; including "same as above" and "same as on
the left" (from UC-8).

Other interesting actions (e.g., "default value = V") might be found
in use cases if we look at them from this perspective.

In this case, UC-8 should also require R-MissingValueDefinition.

Best,
Stasinos

[1] http://w3c.github.io/csvw/use-cases-and-requirements/index.html#UC-AnalyzingScientificSpreadsheets
[2] http://w3c.github.io/csvw/use-cases-and-requirements/index.html#R-MissingValueDefinition

**Comment by 6a6d74** [comment]
Discussed in meeting 12-Nov-2014 ([Minutes](http://www.w3.org/2014/11/12-csvw-minutes.html)); summary ...

@6a6d74: "we discussed different alternatives, but agreed that the simple mapping is definitely row-by-row, but perhaps the templated mapping might want to consider holdover values from previous rows"

@JeniT: "perhaps a flag in the metadata saying take it from the previous row seems relatively simple, but I’m happy to keep it super-simple for now"

RESOLUTION: keep things simple - row by row processing only [for the simple mapping that is in scope of the Rec]

Issue not closed as the mapping doc is yet to be updated.

**Comment by 6a6d74** [comment]
csv2rdf and csv2json documents now updated. Simple row-by-row processing is the order of the day.
