### ISSUE TITLE
Simplify the merge algorithm description as much as possible

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#200]
Discussed at Feb F2F. Fall back on atomic behaviour where A overrides B as much as possible. 
- use normal object merge for language properties
- the array of extension templates definitions will be merged based on the `url` property (same as `resources`)
- `columns` are always matched by index
- when two metadata files don't have the same `name` for columns at the same index, raise an error
- otherwise, raise an error if there's no intersecting title
- add examples

examples we discussed:

```
CSV file:

A,B,C
1,2,3

generates the metadata:

[
  {
    title: "A"
  }, {
    title: "B"
  }, {
    title: "C"
  }
]


@language: "de"

[
  {
    title: "X"
  }, {
    title: "Y"
  }, {
    title: "Z"
  }
]

---

@language: "en"

[
  {
    title: "A"
  }, {
    title: "B"
  }, {
    title: ["D", "C"]
  }
]

---

Metadata file:

@language: "de"

[
  {
    title: {
      "de": "X",
      "en": "A"
    }
  }, {
    title: {
      "de": "Y",
      "en": "B"
    }
  }, {
    title: {
      "de": "Z",
      "en": "C"
    }
  }
]

Metadata file:

@language: "en"

[
  {
    title: "A"
  }, {
    title: "B"
  }, {
    title: ["D", "C"]
  }
]

---

Metadata file:

[
  {
    title: "A"
  }, {
    title: "B"
  }, {
    title: "D"
  }
]

ERROR because the titles are different for 3rd column ("D" != "C")
```

**Comment by JeniT** [comment]
Thinking about the discussion on #218, #223 and #224, perhaps this reworking should make the A overrides B the default and then specifically call out properties where that isn't the case, rather than trying to use the property type to determine the algorithm. At least if it were framed in that way we could easily see the places where we could reduce complexity by removing exceptions.

**Comment by iherman** [comment]
+1. Nay, +1000 :-)

Ivan

> On 17 Feb 2015, at 14:05 , Jeni Tennison notifications@github.com wrote:
> 
> Thinking about the discussion on #218, #223 and #224, perhaps this reworking should make the A overrides B the default and then specifically call out properties where that isn't the case, rather than trying to use the property type to determine the algorithm. At least if it were framed in that way we could easily see the places where we could reduce complexity by removing exceptions.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
Exceptions to that A overrides B that occur to me:
- `resources` and `tableSchema` needs to be merged through recursive descent as currently defined
- `templates`, `notes`, `foreignKeys` need to be merged through array append eliminating matches already in A
-  `columns` uses array append with error checking
-  `title` needs to be merged as currently defined

But, this seems to go a long way towards simplifying merge.

**Comment by JeniT** [comment]
schemas, table descriptions & column descriptions are merged property-by-property
