### ISSUE TITLE
Categories of null values

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#218]
In the example mentioned in #212, cells can contain different kinds of `null` values. http://www.education.gov.uk/schools/performance/ks5_abbr.html describes:
- `NEW`: New institution
- `NE`: No entries
- `NA`: Not applicable: figures are either not available for the year in question, or the data field is not applicable to this school or college.
- `SUPP`: Indicates that a school or college's figures have been suppressed because there are 5 or fewer pupils in the cohort.

Note that these values can appear in cells which are otherwise numeric. We support having a single `null` value (eg you can say `"null": "NA"`), but not having different ones with different meanings.

The options as I see it are:
1. we continue to only support one value
2. we enable the `null` property to take an array of values, all of which are treated as `null` (note that the **string value** of the cell will continue to hold the original code that was used for the null value, but this won't be generally exposed eg in conversions)
3. we add some structure to the `null` property to provide both the null code and a fuller description, and add a **null** annotation to hold the fuller description to the data model

In the final option, JSON-LD allowing, we could have something like:

```
"null": {
  "NEW": "New institution",
  "NE": "No entries",
  "NA": "Not applicable: figures are either not available for the year in question, or the data field is not applicable to this school or college.",
  "SUPP": "Indicates that a school or college's figures have been suppressed because there are 5 or fewer pupils in the cohort."
}
```

PROPOSAL: We support this requirement by adopting option 2 above, allowing `null` to take an array of values.

**Comment by gkellogg** [comment]
JSON-LD does have a [data indexing](http://www.w3.org/TR/json-ld/#data-indexing) capability, which might do for the third option. Interpreting it would be outside the RDF realm, though. I think it's probably going too fR thoug.

Really, I'd like to just stick with what we have now (option 1), but I could live with option 2.

**Comment by iherman** [comment]
I am not sure I understand. At the moment, the [metadata document says](http://w3c.github.io/csvw/metadata/index.html#inherited-properties-1):

> null
> An atomic property giving the string or strings used for null values within the data. If the string value of the cell is equal to this value, the cell value is null. If not specified, the default for the null property is the empty string.

Isn't it the same as your option 2 already? 

(B.t.w, shouldn't the text say "if the string value of the cell is equal to one of these values"?)

**Comment by gkellogg** [comment]
@iherman is correct, although note the following comment from #223:

> Although, issue #136 suggests making `null` only take a single value (see #218), and by correlary, this would go against making `datatype` take an array in order to simplify merge. This comes down to functionality vs singularity.

**Comment by JeniT** [comment]
Given that the primary reason for only accepting a single `null` value was to make the merge easier, what about (contrary to #136), we allow for multiple `null` values but make `null` atomic when it comes to merge, ie don't merge the array if there is one.

**Comment by gkellogg** [comment]
Yes, I think that solves the complexity issue. In general, atomic properties may support an array form, but merging takes the first defined, without combining elements.

**Comment by iherman** [comment]
Well... on the one hand, I am all for reducing complexity, and this is a good way of doing so.

On the other hand, consistency requires to either handle `null` just as the others, or take the same approach to other entries. For example, if we adopt the proposal in #224, then the same approach should be taken for `datatype`. And we may want to revisit other properties, the reduce the complexity of merge.

Ivan

> On 16 Feb 2015, at 22:09 , Jeni Tennison notifications@github.com wrote:
> 
> Given that the primary reason for only accepting a single null value was to make the merge easier, what about (contrary to #136), we allow for multiple null values but make null atomic when it comes to merge, ie don't merge the array if there is one.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
Editor action: allow several null values, but merge in an atomic way (don’t merge arrays of null values).

**Comment by danbri** [comment]
See http://www.w3.org/2015/02/18-csvw-irc#T15-45-10
