### ISSUE TITLE
Move Processing Tables section from metadata to model document

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#220]
PROPOSAL: We should move the [Processing Tables](http://w3c.github.io/csvw/metadata/#processing-tables) section of the metadata document into the model document. This would help to reinforce that processing happens on the tabular data model, and the metadata is just used to help to create that model.

**Comment by gkellogg** [comment]
+1, but we need to be sure we have normative text for CSV parsing steps too.

**Comment by iherman** [comment]
+1

Ivan

> On 16 Feb 2015, at 24:22 , Jeni Tennison notifications@github.com wrote:
> 
> PROPOSAL: We should move the Processing Tables section of the metadata document into the model document. This would help to reinforce that processing happens on the tabular data model, and the metadata is just used to help to create that model.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
@gkellogg If you want to discuss having normative text for CSV parsing, please create a separate issue.

**Comment by danbri** [comment]
See http://www.w3.org/2015/02/18-csvw-irc#T15-10-50

**Comment by JeniT** [comment]
Editor action: move the section
