### ISSUE TITLE
Reworking structure for datatypes

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#224]
The current structure for datatypes has everything at the top level of the column description. For example, we might have things like:

```
{
  "name": "measure",
  "datatype": "decimal",
  "fractionDigits": 2,
  "minimum": 0,
  "maxExclusive": 100,
  "format": "\d+\.\d{2}"
}
```

This makes it hard to adopt union types (as suggested in #223) even if we wanted to, and is a strange structure if you think about it logically: what we're actually doing with the additional constraints (such as `fractionDigits`, `minimum` and `maxExclusive`) is creating a new specialised datatype derived from `decimal` with some additional constraints.

So I propose that we instead use a structure whereby the datatype is a new datatype description, as follows:

```
{
  "name": "measure",
  "datatype": {
    "base": "decimal",
    "fractionDigits": 2,
    "minimum": 0,
    "maxExclusive": 100,
    "format": "\d+\.\d{2}"
  }
}
```

This is more logically coherent and provides for the possibility of extension to both create union datatypes and define new datatypes with their own URLs in the future.

**Comment by gkellogg** [comment]
+1

BTW, what's the motivation for `fractionDigits` when you have a regular expression in the format?

**Comment by iherman** [comment]
It sounds more logical indeed. However, an additional thing: I think we should allow for

```
{
  "name" : "measure",
  "datatype": "decimal"
}
```

I.e., if only a simple datatype is used without facets, there should not be an obligation to create an unnecessary deeper structure. If the goal of the metadata is conversion and not validation, then the other facets are indeed (mostly) unused.

The downside is that it creates additional merge difficulties. Algorithmically this may be solved by declaring "datatype" to be atomic even if a structure is used; not sure whether this is o.k. as far as use cases go.

Ivan

> On 16 Feb 2015, at 22:07 , Jeni Tennison notifications@github.com wrote:
> 
> The current structure for datatypes has everything at the top level of the column description. For example, we might have things like:
> 
> {
>   "name": "measure",
>   "datatype": "decimal",
>   "fractionDigits": 2,
>   "minimum": 0,
>   "maxExclusive": 100,
>   "format": "\d+.\d{2}"
> }
> 
> This makes it hard to adopt union types (as suggested in #223) even if we wanted to, and is a strange structure if you think about it logically: what we're actually doing with the additional constraints (such as fractionDigits, minimum and maxExclusive) is creating a new specialised datatype derived from decimal with some additional constraints.
> 
> So I propose that we instead use a structure whereby the datatype is a new datatype description, as follows:
> 
> {
>   "name": "measure",
>   "datatype": {
>     "base": "decimal",
>     "fractionDigits": 2,
>     "minimum": 0,
>     "maxExclusive": 100,
>     "format": "\d+.\d{2}"
>   }
> }
> 
> This is more logically coherent and provides for the possibility of extension to both create union datatypes and define new datatypes with their own URLs in the future.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
Normalizing from a string-based `datatype` to the object form @JeniT proposes would be done in the pre-merge normalization process easily enough. It is a minor compilation there. Unfortunately, this would make `datatype` an object property, which has more complicated merge semantics. No free lunch :(.

**Comment by iherman** [comment]
> On 17 Feb 2015, at 08:05, Gregg Kellogg notifications@github.com wrote:
> 
> Normalizing from a string-based datatype to the object form @JeniT proposes would be done in the pre-merge normalization process easily enough. It is a minor compilation there. Unfortunately, this would make datatype an object property, which has more complicated merge semantics. No free lunch :(.
> 
> Unless we declare datatypes as atomic, as I proposed.

Ivan

**Comment by JeniT** [comment]
@iherman yes, I agree that we should also allow strings as simple references to existing types, and that we should declare datatypes as atomic wrt merging.

**Comment by gkellogg** [comment]
Yes, given this interpretation, I agree.

**Comment by iherman** [comment]
For the records: me too.

**Comment by JeniT** [comment]
Editor action: make it so.

**Comment by danbri** [comment]
See http://www.w3.org/2015/02/18-csvw-irc#T15-32-30

**Comment by JeniT** [comment]
Note that these should merge in an atomic way.
