### ISSUE TITLE
Support for totalDigits and fractionDigits

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#226]
(Prompted by https://github.com/w3c/csvw/issues/224#issuecomment-74586788)

XML Schema defines `totalDigits` and `fractionDigits` facets to provide another mechanism for controlling the acceptable values for decimals (and integers). It's possible to use a regular expression to provide the same level of control over acceptable values. We're not copying all the facets from XML Schema (eg we haven't replicated `whiteSpace` or `enumeration`). Given we're already picking and choosing then `totalDigits` and `fractionDigits` replicate existing functionality and we shouldn't have them.

I propose that we drop `totalDigits` and `fractionDigits` constraints as unnecessary.

**Comment by iherman** [comment]
+1

Ivan

> On 17 Feb 2015, at 24:33 , Jeni Tennison notifications@github.com wrote:
> 
> (Prompted by #224 (comment))
> 
> XML Schema defines totalDigits and fractionDigits facets to provide another mechanism for controlling the acceptable values for decimals (and integers). It's possible to use a regular expression to provide the same level of control over acceptable values. We're not copying all the facets from XML Schema (eg we haven't replicated whiteSpace or enumeration). Given we're already picking and choosing then totalDigits and fractionDigits replicate existing functionality and we shouldn't have them.
> 
> I propose that we drop totalDigits and fractionDigits constraints as unnecessary.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
+1

**Comment by danbri** [comment]
http://www.w3.org/2015/02/18-csvw-irc#T15-09-30

**Comment by JeniT** [comment]
Editor action: remove the two properties

**Comment by gkellogg** [comment]
Editor action: Update namespace to remove these definitions.

**Comment by JeniT** [comment]
Sorry, thought I'd removed them all from the namespace documents. What did I miss?

**Comment by gkellogg** [comment]
Yes, sorry, I missed that you had removed them.
