### ISSUE TITLE
Replace virtual columns by explicit templates?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#228]
I am sorry if this is, partially, reopening issue #179 on virtual (phantom) columns, but the discussion on issue #26, especially the example provided by @JeniT in https://github.com/w3c/csvw/issues/26#issuecomment-74569547 triggered some additional thoughts.

The discussion on #26 (see also [@gkellogg's reply](https://github.com/w3c/csvw/issues/26#issuecomment-74625971)) may converge to the fact that virtual columns are of interest for the RDF mapping only and are ignored for good old JSON output. A virtual column is, in fact, nothing else than a reification of an RDF triple, modulo the URL Template mechanism and the inherited `aboutUrl` value. I wonder whether it is not cleaner to separate this functionality altogether: instead of virtual columns, we would introduce, for a table schema, an "rdftemplate" property whose values are [an array of] strings, each encoding a portion of RDF. Let me show what I mean below, using Turtle, because I feel more comfortable in it (although that should probably be expressed as (quoted) minimal JSON-LD, essentially along the lines of what we defined for common properties). Taking the example of @JeniT, the schema could look as follows:

```
 "tableSchema": {
    "aboutUrl": "#gid-{GID}",
    "columns": [{
      "name": "GID",
      "title": "GID",
      "datatype": "string",
      "propertyUrl": "schema:url",
      "valueUrl": "#gid-{GID}"
    }, {
      ...
    }],
    "rdftemplate: "<#event-{inventory_date}> a schema:Event. <#location-{GID}> a schema:PostalAddress",
```

The semantics is what one would expect: every `<..>` is considered to be a URL template, and the result are simply RDF expressed (in this case) in Turtle and are supposed to be added to the outgoing graph.

I think this approach would make things much clearer to the metadata authors, who could happily ignore this portion of the template for non-RDF purposes (validators may also have a flag that ignore RDF specific part of the metadata), would make the merge of the columns part easier because a strict equality of the column names/titles could be used as now. There is a disadvantage for the RDF conversion implementers who would have to interpret the values; but if we try to use the algorithm that we already use for common properties, that can also be mitigated.

The biggest downside I see is that, afaik, it is not possible in JSON to have new lines in a string (:-(, meaning that each statement must be in one long line, or to be broken up in strings. That is fairly ugly, but still more readable (mainly for complex additional RDF) than a large number of reified RDF statements in the table schema...

What we are doing is re-introducing the templating issues of the past, albeit in a much more restricted way, using only URL templates and no mustache, for example. But the reality is that, functionally, this is what virtual columns have already done.

(B.t.w.... a more radical approach to the original use cases is really to rely on extensions and remove this functionality altogether. For example, it is quite obvious to add a SPARQL CONSTRUCT rule to add those additional triples as a post-processing steps. In my previous view _that_ would actually be the simplest approach:-)

**Comment by JeniT** [comment]
-1 - we have already established long ago that we don't want to specify templating languages within this group, and decided at the Feb F2F that the additional structuring made possible by phantom columns was worth investigating. Until we have it properly spec'd and published in a WD, with the note as we agreed in #179, I don't see any reason to revisit that decision.

**Comment by iherman** [comment]
Well, I could argue that the virtual columns are a template language...

Ivan

> On 17 Feb 2015, at 13:45 , Jeni Tennison notifications@github.com wrote:
> 
> -1 - we have already established long ago that we don't want to specify templating languages within this group, and decided at the Feb F2F that the additional structuring made possible by phantom columns was worth investigating. Until we have it properly spec'd and published in a WD, with the note as we agreed in #179, I don't see any reason to revisit that decision.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
I agree with @JeniT that this would actually just make things more complicated. We have a model for processing columns, and anyone who's seen a spreadsheet "knows" that there are more columns to the right that can easily be provided, who's nominal value is just empty. This is also a common place to add spreadsheet macros, so conceptually this should not be surprising.

**Comment by iherman** [comment]
Closing by virtue of general rejection...
