### ISSUE TITLE
CSV Dialect Description

### ISSUE THREAD

**Issue by rufuspollock** [w3c/csvw#23]
Do we want a way to describe the "dialect" of the CSV in the Metadata document (e.g. separator is ';')

Existing spec at http://dataprotocols.org/csv-dialect/ which we could reuse.

```
{
  "delimiter": ",",
  "doubleQuote": true,
  "lineTerminator": "\r\n",
  "quoteChar": "\"",
  "skipInitialSpace": true,
  "header": true
}
```

**Comment by 6a6d74** [comment]
I would say yes.
[Section 5 of the data model document](http://w3c.github.io/csvw/syntax/index.html#parsing) specifies a number of things that one would want to know about a CSV resource before attempting to work with. Your list of items is a partial subset of that set.
Other than putting this information in a HTTP header, I don't see where you could put these statements except in the metadata document.
(and the HTTP header case doesn't cover all of our examples)

For reference, the [use case document](http://w3c.github.io/csvw/use-cases-and-requirements/index.html) includes a number of requirements that match these elements; such as [R-NonStandardCellDelimiter](http://w3c.github.io/csvw/use-cases-and-requirements/index.html#R-NonStandardCellDelimiter).

**Comment by 6a6d74** [comment]
One thing that we might not need to include in the metadata document is a statement about directionality of the content. We could rely on the unicode control characters. Here's what is said if you can't rely on markup for controlling content directionality (from [W3C bidi markup article](http://www.w3.org/International/articles/inline-bidi-markup/Overview#nomarkup)):

> From Unicode version 6.3 onwards, the Unicode Standard contains new control codes (RLI, LRI, 
> FSI, PDI) to enable authors to express isolation at the same time as direction in inline bidirectional 
> text. The Unicode Consortium recommends that isolation be used as the default for all future inline 
> bidirectional text embeddings. To use these new control codes, however, it will be necessary to wait 
> until the browsers support them. The new control codes are:
> - RLI (RIGHT-TO-LEFT ISOLATE) U+2067 to set direction right-to-left
> - LRI (LEFT-TO-RIGHT ISOLATE) U+2066 to set direction left-to-right
> - FSI (FIRST STRONG ISOLATE) U+2068 to set direction according to the first strong character
> - PDI (POP DIRECTIONAL ISOLATE) U+2069 to terminate the range set by RLI, LRI or FSI

See [UC-SupportingRightToLeftDirectionality](http://w3c.github.io/csvw/use-cases-and-requirements/index.html#UC-SupportingRightToLeftDirectionality) for more information on the motivation for this.

**Comment by JeniT** [comment]
We now include dialect descriptions in metadata, see http://w3c.github.io/csvw/metadata/#dialect-descriptions - these are compatible with those in the csv-dialect that @rgrp references.

@6a6d74 I think we're now covering this at http://w3c.github.io/csvw/metadata/#bidirectional-tables (but I'd say this is a separate issue rather than about dialect).

**Comment by danbri** [comment]
+1 for the decision to include this

**Comment by danbri** [comment]
See http://www.w3.org/2014/11/12-csvw-irc#T15-42-14
