### ISSUE TITLE
Validation of html, xml and json datatypes

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#236]
What should happen with the validation of `html`, `xml` and `json` datatypes? Should we check that cells containing values of these types actually comply with those syntaxes, or not?

Propose: they don't get validated.

**Comment by danbri** [comment]
See http://www.w3.org/2015/02/18-csvw-irc#T15-40-46

**Comment by JeniT** [comment]
We won’t built-in recognise/validate html/xml/json, but add a note to say that authors can add a pattern if they want (through the `format` property)
