### ISSUE TITLE
There should be a "Fragment Model" section in the Data Model document

### ISSUE THREAD

**Issue by dret** [w3c/csvw#24]
This issue probably overlaps with #9 . Generally speaking, the data model document should have a section talking about the fragment model (or about the fact that the data model does not provide a fragment model, and that such a model is left as an exercise to later standardization). For RFC 4180, RFC 7111 defined a fragment model, and it went through a couple of iterations before it was finished. It would be good if CSV+ provided a fragment model, or explicitly said that it didn't (and then maybe even why).

**Comment by JeniT** [comment]
Copying a comment I accidentally made on #9 instead:

It looks like @yakovsh won't be defining a new media type for the update of CSV, so RFC7111 will still apply to the text/csv that's being published, and annotations could use RFC7111 to refer to rows/columns/cells through fragment identifiers. We'll probably remove the whole section on CSV syntax in the Model document once there's an updated I-D or RFC we can point to.

There are separate issues about how to best refer to columns/rows/cells in the tabular data model as opposed to the original CSV file it's created from: see #32 and #50.

**Comment by JeniT** [comment]
Suggested resolution: no action needed as we are not specifying a new media type.

**Comment by dret** [comment]
if the proposed document updates text/csv, then it still might be helpful to either point to RFC 7111, or (which at some point was also suggested, iirc) have an updated version of it and thus supersede it.

**Comment by iherman** [comment]
+1 to @JeniT; I do not think this Working Group is in position to define a fragment identifier for CSV. We do not define a new media type, and we are not chartered to (re-)define the CSV syntax. All relevant sections in our document are non-normative and the agreement is that there may be a new version of the IETF document at some point (but that is something @yakovsh can comment on), and this WG would be happy to contribute to that work, if needed.

**Comment by JeniT** [comment]
Discussed at Feb F2F. We will not define a fragment model on the abstract data model. The abstract data model will preserve (pending closing of #32) the original line and row number on the CSV file and therefore it is possible for pointers into the original CSV file (using RFC7111) to be mapped into pointers into the abstract data model.
