### ISSUE TITLE
Separate RDF savy implementations?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#245]
(This is a spin-off from #26, put into its own issue.)

Quoting from https://github.com/w3c/csvw/issues/26#issuecomment-75011755:

> " that this adds quite significant conceptual complexity to the spec solely to support a serialization to a specific output format which I imagine relatively few of our target user group may want. Every additional structure we add to the spec has to be supported by implementors of tooling and therefore should have a really strong reason for going in."

The comment was on virtual columns, but is may be more general. Hence the proposal: introduce a separate classes of implementations  "RDF aware"  and "not RDF aware". Ie, implementations (validators, converters) may define themselves as not handling the RDF specific features. The list of those will become clearer when the conversions document are done, but may involve virtual columns or some of the URL templates.

The right place of doing that is the conformance clause of the metadata document which can then define these features listing the RDF specific ones.

**Comment by iherman** [comment]
For the records, I am in favor of the idea.

**Comment by gkellogg** [comment]
I think this actually places more burdens on implementations, and as noted elsewhere, it's not clear that these metadata forms aren't useful for JSON or some other kind of transformation. So, I'm against adding such language.

Virtual columns are useful whenever data needs to be inserted into the output; this can't be done using common properties, and the notion is familiar with anyone using a spreadsheet. Conceptually, they're just more empty cells available for use in metadata specifications. I believe they are also useful (at least in some cases) in JSON output.

**Comment by JeniT** [comment]
I agree with @gkellogg.

**Comment by iherman** [comment]
@JeniT: I don't :-(

@gkellogg: see my comment https://github.com/w3c/csvw/issues/26#issuecomment-75203547 on issue #26. Yes, those features may be useful: if you need them, use JSON-LD as an output of a csv2rdf processor! But I believe reducing the overall complexity and cognitive load for those who want simple things and simple tools for JSON should not be jeopardized.

**Comment by 6a6d74** [comment]
My gut feeling is that I wouldn't want to close the door on features like 'virtual columns' for the (plain-old) JSON output. On the (long) list of things I need to do with the conversion documents is prep some examples. I'm thinking of using three:
- palo alto tree data (simple example)
- public sector salaries (table group example with keys and inter-table references)
- @danbri 's event example which needs the virtual columns

The third of these I will try to convert into plain-old JSON _as well as_ RDF; let's see what that looks like prior to deciding if we need a sub-set of conformance classes for RDF.

**Comment by iherman** [comment]
I am happy to delay the decision, to see where you get to. Obviously, my concern is not with this specific feature, but the overall complexity of what we produce...

Cheers

Ivan

> On 24 Feb 2015, at 10:03 , Jeremy Tandy notifications@github.com wrote:
> 
> My gut feeling is that I wouldn't want to close the door on features like 'virtual columns' for the (plain-old) JSON output. On the (long) list of things I need to do with the conversion documents is prep some examples. I'm thinking of using three:
> 
>   • palo alto tree data (simple example)
>   • public sector salaries (table group example with keys and inter-table references)
>   • @danbri 's event example which needs the virtual columns
> The third of these I will try to convert into plain-old JSON as well as RDF; let's see what that looks like prior to deciding if we need a sub-set of conformance classes for RDF.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
@iherman - examples are now available in the [revised csv2rdf doc](http://w3c.github.io/csvw/csv2rdf/#examples) ... do you think we need to progress any further with your suggestion?

**Comment by iherman** [comment]
I have been voted down on this issue... so I close it.
