### ISSUE TITLE
Addition of use case to support open validation

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#246]
ISSUE #14 identified the need for open and closed validation. PR #225 introduced multiple validation modes into the metadata vocabulary.

However, the Use Case document doesn't explicitly provide a case for this functionality. At present, the Use Cases only refer to closed validation. A new Use Case _should_ be added to discuss open validation. During the Feb F2F @JeniT noted that she might have such a use case.

Furthermore, the Requirement R-CsvValidation needs to be amended to describe the difference between open and closed validation - and the additional modes 'extension' and 'restriction' that have been added to the metadata vocabulary.

**Comment by JeniT** [comment]
The latest edit around validation removed all modes, so we don't have this any more. The example that I was thinking of wouldn't be supported, but then I think we'd need to support proper schema extension/restriction if we were to support it. I'll hook out the email anyway as it's good to have the use case recorded.
