### ISSUE TITLE
Create a JSON version of the test manifest

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#248]
@gkellogg please could you create a JSON version of the test manifest, to make it easier for non-RDFers to use the tests?

@iherman please could you add a `Test suite` label on to this repository so that we can start labelling issues for the test suite?

**Comment by iherman** [comment]
> On 20 Feb 2015, at 14:13 , Jeni Tennison notifications@github.com wrote:
> 
> @gkellogg please could you create a JSON version of the test manifest, to make it easier for non-RDFers to use the tests?
> 
> @iherman please could you add a Test suite label on to this repository so that we can start labelling issues for the test suite?

Done

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704
