### ISSUE TITLE
``commentPrefix`` default value missing + effect on row numbering

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#252]
The dialect description includes the flag `commentPrefix` in the metadata document. Two questions
- the default dialect (right before section 3.7) does not include a value for this. I would expect this to be the empty string `""`
- how does comment lines affect row numbering? Are these rows "invisible" altogether after parsing or do they remain in the parsed data. 
  - If the former, external CSV parser tools may take care of this, and the CSV+ tools can ignore that issue (apart from using the right options when invoking the external tools). 
  - If the latter, then the rest of the CSV+ tools must include them in their processing in keeping track of the proper row number

Although the first option (namely trust external tools and forget about the comment lines) seem to be really attractive, not sure if it is possible in view of the usage of 7111 (which, as agreed, refers 'back' to the original CSV file). I am not sure whether the tools have to be able to make the 7111 to Tabular Data conversion or not somewhere.

**Comment by gkellogg** [comment]
Note the definition of _comment prefix_ in the model document:

> A character that, when it appears at the beginning of a skipped row, indicates a comment that should be associated as a comment annotation to the table. The default is #.

The metadata document should be updated to add this default (which I'll do). However, comments only appear in skipped rows, so row numbering is only affected by `skipRows` and `headerRows`.

**Comment by gkellogg** [comment]
Note that that definition is non-normative, and these definitions probably need to be normative for CSV. Perhaps moving these definitions to section 3) makes more sense. @JeniT?

**Comment by iherman** [comment]
Hi Gregg,

is it really so that comment lines can only appear in the skipped rows? Can't one comment out any data line? I believe the CSV parsers may do that.

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by gkellogg** [comment]
That seems to be how it's defined. Perhaps @JeniT can weigh in.

FWIW, Removing commented data rows would seem to be fairly straight-forward, not sure about how it would affect row numbering; we do keep track of both `sourceRow` and model `row`, so it's traceable in the tabular model.

**Comment by iherman** [comment]
It is, technically, straightforward indeed. But there is a cost: we are moving one more step towards requiring an implementation to implement the full CSV parsing of its own or at least using external tools only on a basic level. Indeed, keeping track of the row numbering this way means that one cannot rely on existing external tools to handle such issues automatically (e.g., CSV's PapaParser, which is one of the general CSV parsers, may use this feature). So it is worth asking...

**Comment by JeniT** [comment]
As we've discussed many times, defining CSV parsing normatively is out of scope for us. All that we're able to do is provide an informative description about how it might work and a dialect description that can provide a mechanism for configuring parsers to try to do the right thing. Our normative job starts once the basic table model is created.

I believe that the upshot of this is that implementations should feel free to support all or some or none of the dialect description. They could simply guess the table model from the CSV files, completely ignoring the dialect description, and that would be conformant. I think all we can try to guarantee is that if someone publishes standard CSV files (ie with the defaults in place) then all implementations will parse those in the same way.

iirc, @hubgit did the original analysis of what options were offered by different parsers and what the algorithm should be, and that's where the comment prefix and its defined behaviour came from. We can make it say something different, but I'd like to see an analysis of how popular parsers work and whether they support commenting at all.

**Comment by iherman** [comment]
Jeni, I do not have any disagreement with anything you say. However, we (normatively) refer to the row numbers in the original file, as agreed at the face-to-face, thinking that reproducing that data can be done through the dialect data because we know the number of ignored started rows, for example. But the issues on comments may mess this up; some parser _do_ allow for comment lines anywhere in the table (that is the case for PapaParse on Javascript, that is how I ran into this question). At this moment I am not sure what the optimal solution is.
1. we may decide that comments are allowed only as part of the skipped rows at the beginning of the file but, then, I am not sure it is really meaningful to even talk about it (because those lines, comments or not, will be ignored altogether)
2. we may decide that comments are handled everywhere if the parser can do it, but our version of row numbering (ie, 7111) only refers to _real_ data
3. we may also decide to completely ditch the issue of comments altogether on our level (including in the dialect), which is a bit like the second option but leaves no ambiguity
4. we may also decide to ignore the parser's comment filtering possibility and we require all of our processing to take that into account somehow (this is dangerously close to us defining at least part of parsing!)

Having written these lines, I think I would opt for (3)

Ivan

> On 28 Feb 2015, at 15:56 , Jeni Tennison notifications@github.com wrote:
> 
> As we've discussed many times, defining CSV parsing normatively is out of scope for us. All that we're able to do is provide an informative description about how it might work and a dialect description that can provide a mechanism for configuring parsers to try to do the right thing. Our normative job starts once the basic table model is created.
> 
> I believe that the upshot of this is that implementations should feel free to support all or some or none of the dialect description. They could simply guess the table model from the CSV files, completely ignoring the dialect description, and that would be conformant. I think all we can try to guarantee is that if someone publishes standard CSV files (ie with the defaults in place) then all implementations will parse those in the same way.
> 
> iirc, @hubgit did the original analysis of what options were offered by different parsers and what the algorithm should be, and that's where the comment prefix and its defined behaviour came from. We can make it say something different, but I'd like to see an analysis of how popular parsers work and whether they support commenting at all.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
http://www.w3.org/2015/03/04-csvw-irc#T16-01-55 - we will respec to have comment characters for commenting out all kinds of rows (not just in skipRows) and flag up the issues this raises around row numbering
