### ISSUE TITLE
Suggested improvements on example of section 4 (merging)

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#256]
The normalization description in the text says:

> If the property is a URI template property, the value is turned into an absolute URI template property by expanding using the base URL.

However, somehow the example does not follow this, and I am not even sure the example is correct. Afaik, we did say that the templates should expand using the `@base` value of the file where they are, whereas the example makes a merge of the `@context`-s _first_ and then does the "absolutization" of the templates. That seems to be wrong.

I think it would be better if the example had a separate and explicit step showing the effect of  normalization both on A and B prior to merge, following the description of the algorithm.

(Maybe this issue is a bit premature because I am not sure section 4 is already meant to be the final or still has to undergo a simplification editing, though.)

**Comment by gkellogg** [comment]
This has changed, but the wording hasn't been updated yet, there's an open issue on simplifying merge that I haven't gotten to. uRI Template properties are not modifies during merge.

**Comment by iherman** [comment]
O.k. This issue is then pending. (Should we mark it as 'blocked'?)

Ivan

> On 24 Feb 2015, at 16:24 , Gregg Kellogg notifications@github.com wrote:
> 
> This has changed, but the wording hasn't been updated yet, there's an open issue on simplifying merge that I haven't gotten to. uRI Template properties are not modifies during merge.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
I'll work on merge simplification today and make sure this is covered.

**Comment by iherman** [comment]
If pull request #258 is accepted, then this issue can be closed. The changes relevant to this issue seem to have been taken care of.
