### ISSUE TITLE
Rich Column Classes / Types (@type / @datatype on column)

### ISSUE THREAD

**Issue by rufuspollock** [w3c/csvw#26]
Proposal: allow additional field (name to be determined but could be @datatype or @type) whose value could/would be a RDF class specifying the type of data in that column. This would complement the basic type stuff we have with datatype/type attribute (which is from xsd list).

```
schema: {
  columns: [
   {
     ...
     @(data)type: some-uri ...
   }
  ]
}
```

cf https://github.com/dataprotocols/dataprotocols/issues/89

**Comment by dataunity** [comment]
I don't think there is a @datatype keyword in JSON-LD so maybe avoid using that to keep things compatible.

http://www.w3.org/TR/json-ld/#syntax-tokens-and-keywords

**Comment by rufuspollock** [comment]
I should add that, as I understand it, @type usage in way proposed here conflicts with standard usage in JSON-LD (@type in JSON-LD would be describing the type of the object in the spec which is, of course, a Column object). See https://github.com/dataprotocols/dataprotocols/issues/89 for more on this.

**Comment by gkellogg** [comment]
`@type` in JSON-LD has two meanings, when used within a node definition, it is the `rdf:type` of the node, when used within an expanded value, it is the literal datatype. Also, when used in the context definition for an expanded term definition, it is either the literal datatype, or an indication that string values of this term should be interpreted as an IRI (relative to the document or vocabulary, depending on if the value is `@id` or `@vocab`).

If we're going to try stay close to JSON-LD, then IMO, the result should either be valid JSON-LD, or should be easily turned into valid JSON-LD. Otherwise, we may consider using a different keyword prefix

**Comment by rufuspollock** [comment]
Slightly tweaked issue description to make clearer the purpose and that this is about a new attribute for richer column type specification.

**Comment by JeniT** [comment]
@rgrp Is the idea here that you could have something like:

```
"columns": [{
  "name": "location",
  "type": "http://schema.org/Place"
}]
```

and that this would indicate that the `location` column held a URL that pointed to something that was a `schema:Place`? If that's not the intention, could you give an example?

**Comment by rufuspollock** [comment]
That's the idea though obviously using @type (if we can use type we should use that for the datatype field in line with JSON Table Schema). So example is:

```
"columns": [{
  "name": "location",
  "type": "geopoint" (or string or whatever if we don't have geopoint in special list of types)
  "@type": "http://schema.org/Place"
  # alternatively if we have datatype this would be ...
  # "datatype": "geopoint"
  # "@datatype": "http://schema.org/Place"
}]
```

**Comment by JeniT** [comment]
We can't use `@type` because that has a special meaning in JSON-LD: it means the type of the thing that's being described, so we expect things like:

```
  "@type": "Column"
```

or

```
  "@type": "Schema"
```

if `@type` is included at all (I suspect mostly it won't be).

---

Suggested resolution:

We define a `aboutTypeUrl` property that can appear on a schema or on a column description. It defines the type of the entity whose identifier is provided through the `aboutUrl` template (if there is one).

We also define a `valueTypeUrl` property that can appear on a schema or on a column description. It defines the type of the entity whose identifier is provided through the `valueUrl` template (if there is one).

So if we had CSV like this:

```
name,email,org,org url
Rufus Pollock,rufus.pollock@okfn.org,Open Knowledge,http://okfn.org
Jeni Tennison,jeni@theodi.org,Open Data Institute,http://theodi.org
```

then we might have something like (I've included the `@type` properties for clarity though I suspect they wouldn't normally be included by metadata authors):

```
"tableSchema": {
  "@type": "Schema",
  "aboutUrl": "mailto:{email}",
  "aboutTypeUrl": "schema:Person",
  "columns": [{
    "@type": "Column",
    "name": "name",
    "propertyUrl": "schema:name",
    "datatype": "string"
  }, {
    "@type": "Column",
    "name": "email",
    "propertyUrl": "schema:email",
    "datatype": "string"
  }, {
    "@type": "Column",
    "name": "org",
    "aboutUrl": "{org_url}",
    "propertyUrl": "schema:name",
    "datatype": "string"
  }, {
    "@type": "Column",
    "name": "org_url",
    "datatype": "anyURI",
    "propertyUrl": "schema:affiliation",
    "valueUrl": "{org_url}",
    "valueTypeUrl": "schema:Organization"
  }
}
```

and this would produce (as RDF) something like:

```
<mailto:rufus.pollock@okfn.org> a schema:Person
  schema:name "Rufus Pollock" ;
  schema:email "rufus.pollock@okfn.org" ;
  schema:affiliation <http://okfn.org> .

<http://okfn.org> a schema:Organization
  schema:name "Open Knowledge" .

<mail:jeni@theodi.org> a schema:Person
  schema:name "Jeni Tennison" ;
  schema:email "jeni@theodi.org" ;
  schema:affiliation <http://theodi.org> .

<http://theodi.org> a schema:Organization
  schema:name "Open Data Institute" .
```

**Comment by rufuspollock** [comment]
I sort of prefer @datatype - what do you think are pros/cons of simple @datatype vs this new approach?

**Comment by iherman** [comment]
@rgrp : in the current version of the metadata we end up using properties of the form `@...` for values that describe/characterize the metadata itself (essentially JSON-LD constructs). `@langauge` is a typical case, opposed to the `lang` key, that is to assign a key to the data. In this sense, I would agree with @JeniT to use a property that is not of the `@...` form.

That being said: we can simply use `aboutType` and `valueType`. I am not sure the "Url" adds too much and makes the property simple.

**Comment by iherman** [comment]
A question on the proposed resolution: are `aboutTypeUrl` and `valueTypeUrl` proposed as strings for a URL, or are they Url templates? I tend to opt for the latter for consistency's sake; we have templates everywhere else, why not having it for this case, too?

**Comment by JeniT** [comment]
I was thinking URI templates: it's not uncommon for a column in a table to include the specialised type of the entity that the row is describing. Hence using the `xxxUrl` naming convention for consistency with the other URI template properties.

**Comment by iherman** [comment]
> On 04 Feb 2015, at 14:53 , Jeni Tennison notifications@github.com wrote:
> 
> I was thinking URI templates: it's not uncommon for a column in a table to include the specialised type of the entity that the row is describing. Hence using the xxxUrl naming convention for consistency with the other URI template properties.

O.k. and the consistency is indeed relevant. We are in agreement then, and +1 from me on the proposed resolution.

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
Note that additional data could be added to the output using the concept of a phantom column, as described in issue #179. In this case, something like the following:

```
"tableSchema": {
  "@type": "Schema",
  "aboutUrl": "mailto:{email}",
  "columns": [{
    "@type": "Column",
    "name": "name",
    "propertyUrl": "schema:name",
    "datatype": "string"
  }, {
    "@type": "Column",
    "name": "email",
    "propertyUrl": "schema:email",
    "datatype": "string"
  }, {
    "@type": "Column",
    "name": "org",
    "aboutUrl": "{org_url}",
    "propertyUrl": "schema:name",
    "datatype": "string"
  }, {
    "@type": "Column",
    "name": "org_url",
    "datatype": "anyURI",
    "propertyUrl": "schema:affiliation",
    "valueUrl": "{org_url}"
  }, {
    "@type": "Column",
    "name": "aboutType",
    "phantom": true,
    "propertyUrl": "rdf:type",
    "valueUrl": "schema:Person"
  }, {
    "@type": "Column",
    "name": "orgType",
    "phantom": true,
    "aboutUrl": "{org_url}",
    "propertyUrl": "rdf:type",
    "valueUrl": "schema:Organization"
  }]
}
```

The general purpose of this is to apply missing data, which to me seems better than just creating new properties.

**Comment by JeniT** [comment]
Discussed at Feb F2F. Our direction of travel is the use of virtual columns for all additional data generated out of a single column, see #179. Keeping this open for now in case the virtual column idea doesn't come off.

**Comment by JeniT** [comment]
I worry that column specifications like:

```
{
  "name": "type",
  "virtual": true,
  "propertyUrl": "rdf:type",
  "valueUrl": "schema:Person"
}
```

mention RDF (in `rdf:type`). Should we alias `rdf:type` to `type` or `a` to avoid the mention or am I being too sensitive?

**Comment by gkellogg** [comment]
The `rdf` prefix is in our context, so that will work properly, unless the smell of "rdf" is too unappealing. But, anyone who plans to do this is clearly looking for RDF output, so I don't think I share that particular concern. However, an alias of `a` to `rdf:type` probably doesn't do much harm, but it might be considered pandering.

**Comment by rufuspollock** [comment]
I'm not clear why we can not have a simple single property for this (whether it has @ as prefix or not). e.g.

`richSchemaType`

For people who then concerned about prefixes, I'd argue that was up to them to sort out in their JSON-LD mapping rather than the core spec. Overall, I'm concerned that direction of travel is introducing a lot of complexity into the base spec without a concomitant gain in power.

**Comment by iherman** [comment]
+1

Ivan

> On 16 Feb 2015, at 05:18 , Gregg Kellogg notifications@github.com wrote:
> 
> The rdf prefix is in our context, so that will work properly, unless the smell of "rdf" is too unappealing. But, anyone who plans to do this is clearly looking for RDF output, so I don't think I share that particular concern. However, an alias of a to rdf:type probably doesn't do much harm, but it might be considered pandering.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
Rufus,

in general, I agree with your concerns of increasing complexity. However, I think, the present proposal actually simplifies things. The predicate `propertyUrl` can be used for many different things, _among other things_ can be used to set the type if the only reason of using that column is to set the type for the row. At this time I expect this feature to be used in virtual columns and by RDF savy people only, i.e., it about 10% of our users... (o.k., let us but it 25%...:)

The question that does arise, though, is whether this typing information has any value for JSON-only usage, ie, whether it has an importance for the plain old JSON mapping. I cannot answer this question; however, _if_ there is a need for it in that realm, than maybe we want to think again...

At this point, I would propose to go ahead as proposed, and put a user feedback request in the document on whether the JSON mapping should use that typing information, too.

Ivan

> On 16 Feb 2015, at 08:59 , Rufus Pollock notifications@github.com wrote:
> 
> I'm not clear why we can not have a simple single property for this (whether it has @ as prefix or not). e.g.
> 
> richSchemaType
> 
> For people who then concerned about prefixes, I'd argue that was up to them to sort out in their JSON-LD mapping rather than the core spec. Overall, I'm concerned that direction of travel is introducing a lot of complexity into the base spec without a concomitant gain in power.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
The example at http://w3c.github.io/csvw/metadata/#use-of-virtual-columns shows the direction that we're taking (and asking for feedback on). @iherman, it also shows how I'm expecting the type information etc to be used in the JSON output.

**Comment by iherman** [comment]
Well...

The RDF mapping is fairly clear, because the virtual columns are, in fact, RDF triples encoded in JSON. (B.t.w., there is a tiny mistake: in the turtle code it should say `<#event-2010-10-18>` instead of `<#event-1>` I believe.)

However, I do not see, algorithmically, how the plain json mapping operates. To get to your example, I presume the conversion code should
    - understand the `"propertyUrl": "rdf:type"`, meaning understanding, for example, that `rdf:type` (more exactly the absolute URL form thereof) is, well `@type`
    - that there should be a 'link' between a `valueUrl` and another column's `aboutUrl`
    - possibly other things...

This significantly complicates the plain json conversion, which is supposed to remain very simple. Your generated example is, essentially, the RDF conversion result encoded in JSON-LD, which we agreed is a separate thing...

I am tempted to say that the JSON conversion should ignore virtual columns altogether. They are really meant to provide a richer, very RDF-like set of information... (Note that postprocessing JSON is way easier than, say, postprocessing RDF, ie, any more complex issue could be handled by extensions...)

Ivan

> On 16 Feb 2015, at 21:43 , Jeni Tennison notifications@github.com wrote:
> 
> The example at http://w3c.github.io/csvw/metadata/#use-of-virtual-columns shows the direction that we're taking (and asking for feedback on). @iherman, it also shows how I'm expecting the type information etc to be used in the JSON output.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
@iherman said:

> I am tempted to say that the JSON conversion should ignore virtual columns altogether. They are really meant to provide a richer, very RDF-like set of information... (Note that postprocessing JSON is way easier than, say, postprocessing RDF, ie, any more complex issue could be handled by extensions...)

This is probably the easiest thing to do. Getting the structured JSON output @JeniT suggested could be done by serializing RDF to JSON-LD with framing.

This really depends on if the data-insertion mechanism is driven by JSON needs, or just RDF.

**Comment by rufuspollock** [comment]
@JeniT do we have user stories / use cases on this. I'm struggling to grok this ...

**Comment by JeniT** [comment]
@rgrp yes, in particular @danbri has an example at https://github.com/w3c/csvw/tree/gh-pages/examples/tests/scenarios/events. The CSV is this:

```
Name, StartDate, location_name, location_address, ticket_url
B.B. King,2014-04-12T19:30,"Lupo’s Heartbreak Hotel", "79 Washington St., Providence, RI",https://www.etix.com/ticket/1771656
B.B. King,2014-04-13T20:00,"Lynn Auditorium","Lynn, MA, 01901",http://frontgatetickets.com/venue.php?id=11766
```

and he wants to generate a structure that looks like the following (in Turtle) for the first row:

```
[
  a schema:MusicEvent ;
  schema:name "B.B. King" ;
  schema:startDate "2014-04-12T19:30"^^schema:Date ;
  schema:location [
    a schema:Place ;
    schema:address "79 Washington St., Providence, RI" ;
    schema:name "Lupo’s Heartbreak Hotel" ;
  ] ;
  schema:offers [
    a schema:Offer ;
    schema:url <https://www.etix.com/ticket/1771656> ;
  ]
]
```

I think that if the RDF output can have that structure from the flag CSV, it should also be possible to generate structured JSON like this:

```
{
  "@type": "schema:MusicEvent",
  "schema:name": "B.B. King",
  "schema:startDate": "2014-04-12T19:30",
  "schema:location": {
    "@type": "schema:Place",
    "schema:address": "79 Washington St., Providence, RI",
    "schema:name": "Lupo’s Heartbreak Hotel"
  },
  "schema:offers": {
    "@type": "schema:Offer",
    "schema:url": "https://www.etix.com/ticket/1771656"
  }
}
```

Virtual columns are a way of ensuring we can generate that structure as well as the typing information for the generated entities that we agree that we would like to have.

**Comment by rufuspollock** [comment]
This seems very rdf-driven. Is it worth the complexity in the spec compared to the very simple option.

**Comment by JeniT** [comment]
@rgrp I'm curious, given you're keen to see the type of the entity being described by the row being specified in the metadata, how are you expecting that to be used?

**Comment by iherman** [comment]
@rgrp : the virtual column idea _is_ rdf-driven. Actually, my proposal was (I think this has not been formally accepted yet) that the pure and simple JSON conversion would completely skip these columns (the JSON example in the mail of @JeniT being a JSON-LD serialization of an RDF output). 

The question whether the original question, namely whether the typing information, is something that _is_ important for pure JSON. If the answer is yes, we may want to add an explicit "rowType" (or equivalent) shorthand that can be put into a description and that can be used verbatim in the JSON output. Use case?

Ivan

(Note that there is a separate "sister" issue on this, namely #35) 

> On 18 Feb 2015, at 19:33 , Rufus Pollock notifications@github.com wrote:
> 
> This seems very rdf-driven. Is it worth the complexity in the spec compared to the very simple option.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by rufuspollock** [comment]
@JeniT to be clear i'm fairly indifferent on the rich column support - I added the issue as it was discussed and it was likely there would be appetite / demand for it. I'm personally +0/-0 on it in the core spec (you can always allow people to extend).

@iherman my point is that this adds quite significant conceptual complexity to the spec solely to support a serialization to a specific output format which I imagine relatively few of our target user group may want. Every additional structure we add to the spec has to be supported by implementors of tooling and therefore should have a really strong reason for going in. It also why I'm currently a major -1 on the merge protocol stuff (which I acknowledge I missed when it was coming in and did not comment on at the time).

**Comment by iherman** [comment]
> On 19 Feb 2015, at 09:01 , Rufus Pollock notifications@github.com wrote:
> 
> @JeniT to be clear i'm fairly indifferent on the rich column support - I added the issue as it was discussed and it was likely there would be appetite / demand for it. I'm personally +0/-0 on it in the core spec (you can always allow people to extend).
> 
> @iherman my point is that this adds quite significant conceptual complexity to the spec solely to support a serialization to a specific output format which I imagine relatively few of our target user group may want. Every additional structure we add to the spec has to be supported by implementors of tooling and therefore should have a really strong reason for going in. It also why I'm currently a major -1 on the merge protocol stuff (which I acknowledge I missed when it was coming in and did not comment on at the time).

Rufus,

I understand the point. And, maybe, validators should have the possibility to say: "do not check RDF specific stuff". This would include, I guess, virtual columns, some (all?) of the URL settings, and maybe more. If we had that, then an implementation may decide not to handle the RDF specific features, and that would be perfectly fine. Just to handle that properly, I will raise a separate issue.

The merge is a bit different. We will have significantly simplified it. There are, however, some cases when the merge is not obvious: titles in different languages is probably the most obvious case.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
I really disagree with the idea that `aboutUrl`, `propertyUrl` and `valueUrl` are RDF-only features; they are only RDF-only if we choose to make them so, and my opinion is that URLs as identifiers for things are important whether you are using RDF or not. I will be very disappointed if the JSON conversion doesn't reflect those properties.

**Comment by iherman** [comment]
I ma agree for aboutUrl and valueUrl. But I am much less sure for the propertyUrl. Although it is not yet clear to me what it means, for json, to have a cell specific separate object...

But those were examples. Are there other RDF only features, beyond virtual columns? I would be surprised if everything else would really make sense in JSON, too.

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by gkellogg** [comment]
valueUrl certainly has use in the JSON output. propertyUrl would be useful, if the URL were turned back into a prefixed name. aboutUrl is more problematic, as it implies a different object. It certainly could be connected to that of the first cell using the same virtual column mechanism, but it does start resembling JSON-LD more. Note that embedded content is common in JSON without JSON-LD, which is really why JSON-LD adopted it. The question is, what do do if a property maps to rdf:type. The `@type` convention used by JSON-LD is simply a convention, using it doesn't make us JSON-LD, or we could adapt anything else that is legal JSON.

**Comment by JeniT** [comment]
I don't see any reason we can't use virtual columns in the JSON mapping, or adopt the convention of using `@type` in the output. It will still look pretty idiomatic even with those.

I don't see using virtual columns or nested/embedded structures as a problem to specify or implement. Rows can create one or more JSON objects (based on the `aboutUrl` of the columns) and then do some post-processing to either nest objects or turn/keep references to URLs into simple strings.

**Comment by iherman** [comment]
@JeniT: see @gkellogg's comment: "but it does start resembling JSON-LD more". And that is my fundamental issue. We had our discussion at the [F2F in Santa Clara](http://www.w3.org/2014/10/28-csvw-minutes.html#item01) on the role of the JSON processing vs. RDF processing (see also the [corresponding resolution](http://www.w3.org/2014/10/28-csvw-minutes.html#res2)). Although it was not stated in these words, my interpretation is that the CSV2JSON processing should be as simple as possible for metadata authors, converter implementations and the resulting output. 

Reusing those virtual columns, doing the type 'post-processing' to nest objects, giving some form an interpretation for `rdf:type`, turning back expanded `propertyUrl` templates into prefixed terms (if possible), etc., are all extra burden on simple JSON processors, while users can get all that for free by using the CSV2RDF processor instead, with a JSON-LD serialization of the output. We should keep the pure JSON aspect as simple as possible and make the advantages of a JSON-LD output more explicit for those who want those functionalities.

**Comment by 6a6d74** [comment]
csv2rdf and csv2json documents now updated to use `aboutUrl`, `propertyUrl` and `valueUrl`.

@JeniT - can we close this issue now?

**Comment by JeniT** [comment]
Yes, I think we've provided the facility in the specs.
