### ISSUE TITLE
Should `resources` be declared a "core annotation" for TableGroup

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#260]
[Section 2.1 of the model for tabular data doc](http://w3c.github.io/csvw/syntax/index.html#annotated-tabular-data-model) defines _core annotations_ for _annotated tables_. All good stuff. 

However, no _core annotations_ are defined for TableGroup resources. I wonder if the `resources` property should be declared as a core annotation; this is the only mandatory property in the TableGroup description.

**Comment by JeniT** [comment]
Editor action: introduce 'resources' as core annotation on table groups.
