### ISSUE TITLE
Add datetime format yyyy-MM-ddTHH:mm

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#264]
The [metadata vocabulary defines formats for dates, times and date-times](http://w3c.github.io/csvw/metadata/index.html#formats-for-dates-and-times). The full ISO 8601 date-time format is represented (`yyyy-MM-ddTHH:mm:ss`) - but it is very common for data to represent times to the nearest minute. 

Suggest adding `yyy-MM-ddTHH:mm` to the list of "blessed formats".

**Comment by iherman** [comment]
+1

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by gkellogg** [comment]
+1 I don't think this requires any telecon discussion, and can just be done by editor action.
