### ISSUE TITLE
Merging behaviour for common properties

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#270]
In the text in #258, common properties are always merged into arrays of values. I propose that we always treat them as having atomic values, ie to have A always override B.

**Comment by JeniT** [comment]
This text has been merged now, so see http://w3c.github.io/csvw/metadata/#merging

**Comment by iherman** [comment]
@JeniT, for the record, I agree with this, ie, +1

**Comment by gkellogg** [comment]
RESOLUTION: we always treat common properties as having atomic values (even if they are arrays), ie A overrides B
