### ISSUE TITLE
Media type for metadata files

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#274]
We currently mention a media type for metadata files in the [model document](http://w3c.github.io/csvw/syntax/#link-header) -- `application/csv-metadata+json` -- and in the [metadata document](http://w3c.github.io/csvw/metadata/#registration-of-application-csvm-json) -- `application/csvm+json`.

It's likely that people will ignore whatever we say about media type, and that they will find it hard to serve up the JSON files as anything but `application/json`. To help JSON-LD processors to recognise the metadata, there's an argument they should be served up as `application/ld+json`.

I propose that we:
1. aim to register the `application/csvm+json` media type, which is as defined in the metadata document
2. in the model document, say that implementations should recognise metadata files served up as any of `application/csvm+json`, `application/ld+json` or `application/json`

**Comment by iherman** [comment]
> On 01 Mar 2015, at 10:48 , Jeni Tennison notifications@github.com wrote:
> 
> We currently mention a media type for metadata files in the model document -- application/csv-metadata+json -- and in the metadata document -- application/csvm+json.
> 
> It's likely that people will ignore whatever we say about media type, and that they will find it hard to serve up the JSON files as anything but application/json. To help JSON-LD processors to recognise the metadata, there's an argument they should be served up as application/ld+json.
> 
> I propose that we:
> 
>   • aim to register the application/csvm+json media type, which is as defined in the metadata document
>   • in the model document, say that implementations should recognise metadata files served up as any of application/csvm+json, application/ld+json or application/json

I am fine with this.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
+1

**Comment by gkellogg** [comment]
+1
