### ISSUE TITLE
Conversion specifications in Model document

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#275]
The model document currently has a section on [conversion specifications](http://w3c.github.io/csvw/syntax/#converting-tables) which is intended to place constraints on the CSV-to-RDF, CSV-to-JSON and similar specifications for conversions. This is slightly confusing now that we've renamed the extensible (templating) mechanism [defined in the metadata document](http://w3c.github.io/csvw/metadata/#conversion-specifications) "conversion specifications" as well.

I propose we call the ones in the metadata document "Scripted Conversions" to make it clear that these things are distinct?

Related, in the model document it says:

> Conversion specifications should specify format-specific properties specifying external processing steps to provide more control to people defining conversions. If these are specified, the conversion specification must specify at what point in the processing this external processing takes place, and what it takes place on. Examples might be:
> - the URL of an XSLT file that is used to process XML after it is generated
> - a string containing a SPARQL CONSTRUCT pattern that is executed on RDF after it is generated
> - properties that contain definitions of Javascript callback functions that are used when processing particular columns or individual rows

I propose that now we have the extensible/scripted/templated conversion specifications as defined in the metadata document, we remove this.

**Comment by iherman** [comment]
> On 01 Mar 2015, at 11:48 , Jeni Tennison notifications@github.com wrote:
> 
> The model document currently has a section on conversion specifications which is intended to place constraints on the CSV-to-RDF, CSV-to-JSON and similar specifications for conversions. This is slightly confusing now that we've renamed the extensible (templating) mechanism defined in the metadata document "conversion specifications" as well.
> 
> I propose we call the ones in the metadata document "Scripted Conversions" to make it clear that these things are distinct?

Just to be picky:-) Implementation may choose to use a compiled program, originally written, say, in "C", which is usually not considered to be 'scripted'. What about something more neutral lie, say, 'external'? Alternatively, calling it "transformation"?

> Related, in the model document it says:
> 
> Conversion specifications should specify format-specific properties specifying external processing steps to provide more control to people defining conversions. If these are specified, the conversion specification must specify at what point in the processing this external processing takes place, and what it takes place on. Examples might be:
> 
>   • the URL of an XSLT file that is used to process XML after it is generated
>   • a string containing a SPARQL CONSTRUCT pattern that is executed on RDF after it is generated
>   • properties that contain definitions of Javascript callback functions that are used when processing particular columns or individual rows
> I propose that now we have the extensible/scripted/templated conversion specifications as defined in the metadata document, we remove this.

+1

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
+1 from me too.

**Comment by JeniT** [comment]
Please could someone else +1 this so that I can enact it?

**Comment by gkellogg** [comment]
+1
