### ISSUE TITLE
Tables should not have titles as an core optional property (use dc:title)

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#278]
When people want to provide a title for a table, they should use `dc:title`.

**Comment by 6a6d74** [comment]
agreed. I found this a little odd when working through my examples.

**Comment by gkellogg** [comment]
We only recently added `title` as an annotation on Table; previously, only on Column. Easy to take out. For column, the fact that it is a natural language property is important for processing; for Table, not so much.

**Comment by JeniT** [comment]
I'm counting the comments above as +1s. Can someone else +1 this so that I can enact it, or give a reason against?

**Comment by gkellogg** [comment]
RESOLUTION: we drop title as a built-in property on tables; people have to use dc:title instead
