### ISSUE TITLE
Should we create a default table group description for a single annotated table defined in isolation?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#285]
In re-writing the conversion specifications for  RDF and JSON it occurred to me that it is useful to define a "default" `TableGroup` for a `Table` if none is defined. This makes the processing a little simpler (one less `if` block ... ) and, in the JSON output actually makes it clearer that we're talking about `Table` objects.

**Comment by gkellogg** [comment]
This is, in fact, what the merge algorithm does: After a merge, the result is always a TableGroup. Since all processing uses a merge, this result is essentially guaranteed.

> If the top-level object of either of the metadata files are table descriptions, these are turned into table group descriptions containing a single table description (ie having a single resource property whose value is the same as the original table description). Ensure that @context definitions are moved from the table description to the table group description.

**Comment by 6a6d74** [comment]
That's great to confirm. I'll mark this issue as resolved & close it when I fix the issue in the doc.
