### ISSUE TITLE
Combining tables from multiple sources into a single TableGroup; use of relative URIs

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#286]
In the ["public sector roles and salaries" example in the (new version of the) RDF conversion document](http://w3c.github.io/csvw/csv2rdf/index.html#example-public-sector-roles-and-salaries), <code>professions.csv</code> is identified using a relative URL; it is supposed to be centrally published at a remote address (e.g. <code>http://example.org/conf/professions.csv</code>) and referenced from the metadata description file which is in the same directory as the <code>senior-roles.csv</code> and <code>junior-roles.csv</code> files published by the government department.

@gkellogg says: <em>"Need to pervasively use relative URLs as, at least for my implementation, using a separate local location vs. declared location doesn't work."</em>

This doesn't seem to support my case as I want to get <code>professions.csv</code> from another HTTP Host ...

**Comment by iherman** [comment]
> On 03 Mar 2015, at 19:58 , Jeremy Tandy notifications@github.com wrote:
> 
> In the ["public sector roles and salaries" example in the (new version of the) RDF conversion document], professions.csv is identified using a relative URL; it is supposed to be centrally published at a remote address (e.g. http://example.org/conf/professions.csv) and referenced from the metadata description file which is in the same directory as the senior-roles.csv and junior-roles.csv files published by the government department.
> 
> @gkellogg says: "Need to pervasively use relative URLs as, at least for my implementation, using a separate local location vs. declared location doesn't work."

I do not understand what you mean here, @gkellogg

Ivan

> This doesn't seem to support my case as I want to get professions.csv from another HTTP Host ...
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
If you actually want to run these examples, then suits out some trickery, they can't catually load from http://example.com. By using relative urls within metadata files, a processor can actually run the demos. So, if url="tree-ops.csv" within tree-ops.json, it will be able to find and open the file. If it's http://example.com/tree-ops.com, the load will fail. In a testing infrastructure, this can be mocked, but the spdesire was to be able to run examples from the git repo.

**Comment by JeniT** [comment]
http://www.w3.org/2015/03/04-csvw-irc#T15-24-37

**Comment by 6a6d74** [comment]
I have modified the text in the conversion specs to assert the following within a NOTE:

> In this example, the resource _gov.uk/professions.csv_ is identified using a relative URL to host _http://example.org_. In reality this resource would be published centrally by government and served from some remote host. Similarly, the metadata description resource _metadata.json_ would be also be centrally published. Government departments seeking to validate their role and salary data would download a copy of this metadata description and place it, without modification, in the same directory as their CSV+ files whose names MUST match those specified in the metadata description; _senior-roles.csv_ and _junior-roles.csv_.
