### ISSUE TITLE
Create simplified algorithm for turning normalized JSON-LD into RDF.

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#288]
Note that PR #281 lays the groundwork for this by describing the JSON-LD dialect we use and the process of normalizing common properties and notes.

**Comment by iherman** [comment]
Just noting that, in the current csv2rdf document the reference to the JSON-LD `toRDF` algorithm appears three times:
1. 3.1, definition of common properties
2. Step no. 3 in section 3.2
3. Step no. 4.4 in section 3.2

All of them must be changed to refer to the metadata document.

**Comment by 6a6d74** [comment]
@iherman, @gkellogg ... once we have a reference to this simplified "normalized JSON-LD to RDF" we can update the document. In fact, @gkellogg - would be happy for you to submit a PR with the correct reference :-)

**Comment by gkellogg** [comment]
As this layers on JSON-LD stuff in PR #281 I'm waiting for that to complete before I add the simplified to RDF steps. Might be best if I include the reference update in csv2rdf when I update the metadata doc.

**Comment by 6a6d74** [comment]
@gkellogg - seems sensible.

**Comment by gkellogg** [comment]
Fixed in 53ba5d3164506431bdf098fb045587953d66c6f2.
