### ISSUE TITLE
Should scripted conversions state if they work on `minimal` or `standard` mode?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#292]
The conversion specifications now provide two normative modes of operation: "Minimal" and "Standard.

[Section 3.7 of the metadata document](http://w3c.github.io/csvw/metadata/index.html#conversion-specifications) defines the vocab for describing "scripted conversions". The optional property `source` indicates whether the normative RDF or JSON conversion output (or something else) should be used.

It seems sensible to also reflect the conversion mode too ...

**Comment by JeniT** [comment]
http://www.w3.org/2015/03/04-csvw-irc#T15-33-46 - always use standard mode
