### ISSUE TITLE
What metadata is used when processing starting with a CSV vs a Metadata file

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#293]
Relative order of loading affects what metadata is loaded.

Starting with a CSV, the intention would be to just output triples for that CSV, not for all tables mentioned in the table group.

Potential for recursion on tables.

**Comment by JeniT** [comment]
I think that the decision about what to output data from is orthogonal to the question of where you start from: in other words, I think processors should probably offer the option to only output data from a single CSV file regardless of whether they've started from that CSV file (whose metadata file might point to several others) or from a metadata file that already references a bunch of CSV files.

The `suppressOutput` flag is the mechanism by which processors can prevent the output of a table. It could be set by an implementation on all but one CSV file. By the time we get to the mapping documents, you don't need to worry about it, only check whether the `suppressOutput` flag is set.

**Comment by 6a6d74** [comment]
@JeniT - this seems sensible to me.

**Comment by iherman** [comment]
@JeniT so, conceptually, the processor may offer a flag whereby in [section 4.1](http://w3c.github.io/csvw/syntax/index.html#creating-annotated-tables) of the syntax document is extended by one more step adding a `suppressOutput` flag to all tables except for a specific `csv` file. That makes the csv2\* specification simpler indeed, so that sounds sensible. I wonder, however, whether it is worth adding a note to that effect in that section to make this clear.

**Comment by gkellogg** [comment]
I would think that if processing started with a CSV then the default would be to limit output to that table.

However, note that this is not the entire complexity I was thinking of. If we start with a metadata file, we then merge it with user-specified metadata and then process each table, say dir1/A.csv and dir2/B.csv. When processing A, it uses that merged metadata as user-specified, and then loads dir1/A.csv-metadata.json and dir1/metadata.json, any of which could effectively modify the TableGroup adding more resources, or even the metadata of a different table. Presumably, during this processing step we create the annotated table. Then we go to B and do the process again, only this time, it could potentially change annotations on A as well.

You could even imagine a case where every new metadata file fouls references more resources so that the process goes on and on. How do we guard against this? This could also be considered an attack vector.

Perhaps starting with metadata means that only file-specific metadata from referenced tables is loaded, and not directory-metadata too, and possibly that file-specific metadata MUST start with a Table, which MUST have a url annotation referencing the file with which it is associated.

**Comment by iherman** [comment]
@gkellogg I understand the issue but I think it is better if we create a new issue for this. Indeed, while this problem has to be addressed, it seems that the csv2rdf and csv2json documents are not to be changed, i.e., this issue can actually be closed without further ado.

I will start a separate issue. All, can we close this one?

**Comment by JeniT** [comment]
@gkellogg I think that if, in your implementation, you want to set the default that starting with a CSV file means that `suppressOutput` is set on all other CSV files, that's your prerogative. Other implementations might or might not choose to do the same thing.

I propose simply an editor action to highlight this use case within the model document.

I've created a new issue #312 to continue the discussion about the complexity of continuing to retrieve metadata files for referenced CSV files.

**Comment by gkellogg** [comment]
@JeniT said:

> I think that if, in your implementation, you want to set the default that starting with a CSV file means that suppressOutput is set on all other CSV files, that's your prerogative. Other implementations might or might not choose to do the same thing.

This has implications for expected behavior, and how that might bear out in test results. If we create a test with CSV input and directory metadata, where the metadata references another CSV, we need to ensure that conforming processors will produce the same output. As I understand @iherman's meaning on RDF, a processor might always output more data, so two processors might be conforming if one outputs just the triples for one table while another outputs triples for all referenced tables, but I prefer a strict interpretation where triples can be matched exactly (subject to isomorphism, anyway), or that a SPARQL query could determine this; this is, of course, harder to do for JSON results.

This implies to me that we need to determine expected behavior when starting with a CSV and having discovered metadata reference other CSVs. I think we need to decide if starting with a CSV sets `suppressOutput` on other tables or not predictively, not simply subject to implementation choice. IMO, if a user says to process a CSV, they're looking for the table output for that CSV, otherwise, they would have started using the metadata, or multiple CSV input files.

**Comment by iherman** [comment]
The issue has migrated to #314 and the resolution will not affect the csv2json and csv2rdf documents (which will remain unchanged in this respect). I have therefore closed this issue.
