### ISSUE TITLE
On the RDF serialization

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#294]
The current document says:

> This document describes the processing of tabular data to create an RDF graph comprising subject-predicate-object triples [rdf11-concepts] referred to as the output graph. Since RDF is an abstract syntax, the output graph MUST be serialized in a concrete RDF syntax such as N-Triples [n-triples], Turtle [turtle], RDFa [rdfa-primer], JSON-LD [json-ld] or TriG [trig].

I do not think it is appropriate to use MUST for the serialization. Implementation may produce an RDF graph that they put into a triple store, is used as an input for other processes in some internal format, etc. I think that "MUST" should be changed to "MAY" but even a simple "may" is enough. 

Also, mentioning RDFa in this respect is a bit unnecessary. Though possible, I do not see why an implementation would take the trouble of generating a, say, HTML file with RDFa markup...

**Comment by gkellogg** [comment]
My version used "emit triple" rather than output graph. I believe we should be clear that this is abstract syntax and not a serialization. Running th algorithm should emit a set of triples that _could_ be manifest in an RDF Graph.

**Comment by iherman** [comment]
There are other places in the text where the term "output graph" works o.k.; the concept is that I generate an output graph into which I "emit" triples. I would propose not to make a radical change at this point, just change the reference to the serialization...

**Comment by gkellogg** [comment]
The only use of "serialization" I saw was in the introduction:

> Since RDF is an abstract syntax, the output graph must be serialized in a concrete RDF syntax such as N-Triples [n-triples], Turtle [turtle], RDFa [rdfa-primer], JSON-LD [json-ld] or TriG [trig].

Maybe it could just note that the transformation is in to the RDF Abstract Syntax as defined in RDF Concepts and leave it there.

**Comment by iherman** [comment]
> On 04 Mar 2015, at 20:53 , Gregg Kellogg notifications@github.com wrote:
> 
> The only use of "serialization" I saw was in the introduction:
> 
> Since RDF is an abstract syntax, the output graph must be serialized in a concrete RDF syntax such as N-Triples [n-triples], Turtle [turtle], RDFa [rdfa-primer], JSON-LD [json-ld] or TriG [trig].
> 
> Maybe it could just note that the transformation is in to the RDF Abstract Syntax as defined in RDF Concepts and leave it there.

I was considering that and it is indeed one way to solve this. Having said that, the differentiation between the serialization or the abstract syntax is clear for people on this group, may not be clear for others. Ie, having something on serialization is fine, but with a lower scale 'may'.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
Reference to "output graph" removed. We now just talk about "triples" and occasionally "RDF output".
