### ISSUE TITLE
Should the value of csvw:rownum be of type xsd:integer (in RDF)

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#296]
The subject tells it all... At the moment, the csv2rdf document defines it as simple (ie, string) literal.

**Comment by gkellogg** [comment]
The namespace gives it the range xsd:integer, is it does most other properties that use numbers (maxInclusive, etc...). We should at least reference the RDFS vocabulary document for such things, if not call them out specifically.

``` turtle
csvw:rownum a rdf:Property;
  rdfs:label "row number"@en;
  rdfs:comment """The position of the row amongst the rows of the Annotated Tabl, starting from 1 """@en;
  rdfs:range xsd:integer;
  rdfs:isDefinedBy csvw: .
```

**Comment by iherman** [comment]
Ah, o.k. Then the RDF conversion should really add the reference to the datatype.

Ivan

> On 04 Mar 2015, at 20:49 , Gregg Kellogg notifications@github.com wrote:
> 
> The namespace gives it the range xsd:integer, is it does most other properties that use numbers (maxInclusive, etc...). We should at least reference the RDFS vocabulary document for such things, if not call them out specifically.
> 
> csvw:rownum a
>  rdf:Property;
>   rdfs:label
> "row number"@en
> ;
>   rdfs:comment
> """The position of the row amongst the rows of the Annotated Tabl, starting from 1 """@en
> ;
>   rdfs:range xsd:integer;
>   rdfs:isDefinedBy csvw: .
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
Now fixed.
