### ISSUE TITLE
Usage of 'rel' and 'describes'

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#297]
The current csv2rdf document uses the `rel:describes`, where `rel` is the prefix for `http://www.iana.org/assignments/link-relations/`. 

The choice sounds about right if I look at the [Iana description](http://www.iana.org/assignments/link-relations/). However, I have two reasons to feel a bit uncomfortable:
1. I have never seen the Iana terms being used in the RDF context (and I do not think there is an RDF schema out there for it). That is of course not a reason _not_ to use it...
2. `rel` is certainly not part of the RDFa initial context that we rely on elsewhere. Again, that is not a strong reason not to use it, but made me thinking nevertheless

I must admit I do not have any alternative, and I am actually fine leaving it if we do not have anything better. But I thought I would raise this...

**Comment by iherman** [comment]
See also the [discussion](https://github.com/mnot/I-D/issues/39) among some of the players, without any final decision. 

Bottom line of what I see in that thread: this is a highly political discussion with no stable URI-s as of now, and proposals to have it at the microformat wiki, at w3id.org, as a w3c /ns,... What this tells me that we may have to find an alternative because we cannot use this as a normative predicate. Sigh…

**Comment by JeniT** [comment]
Hmm. I think [RFC4287](http://tools.ietf.org/search/rfc4287#section-4.2.7.2) gives a precedent for using `http://www.iana.org/assignments/relation/describes`. Options as I see it are:
1. `http://www.iana.org/assignments/relation/describes` (with a suggested prefix of `rel`)
2. `schema:about`
3. making up our own property

I prefer 1 but I could live with either of the other two.

**Comment by gkellogg** [comment]
I prefer 1.

**Comment by iherman** [comment]
To be clear: I would have also preferred  @JeniT 's 1. But:
- We are looking for a property to be used in RDF. In this sense, I do not think that RFC4287, ie, the definition of ATOM, is indeed a precedence; ATOM was never meant to be RDF.
- As an example for raising eyebrows, the URL `http://www.iana.org/assignments/relation/describes` leads to a 404 at this moment. This is a big no-no for RDF.
- I think this issue was exactly why the  [discussion](https://github.com/mnot/I-D/issues/39) started in the first place, look at the [opening question of Erik Wilde](https://github.com/mnot/I-D/issues/39#issue-23261858). And, as far as I could see, that issue is not closed. Actually, it turned out to be fairly controversial, involving the decision of the HTML WG to move away from IANA in favor of the microformat wiki for registering `rel` values in HTML5, the way `rel` values are registered, etc.  (Note that the [microformat wiki table](http://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions) does not seem to include `describes`, ie. the microformat route is not appropriate for us either for now.)
- `schema:about` is, alas!, not an option. Apart from the fact that there are issues on normatively referring to schema.org in a W3C standard (these issues may be solved soon, there are discussions between W3C and schema.org that may settle this), looking at the [definition of `schema:about`](https://schema.org/Thing) the "domain" of that property is `CreativeWork` or `CommunicateAction`, and not the generic `Thing`. I think, therefore, it is not appropriate for us to use it.

So, I believe, the options we really have are:
1. Chime in the thread started by Erik to try to get things solved
2. Use `csvw:describes` and get on with our lives
3. Put the question on hold until LCCR (leaving this issue open), hoping that the [issue](https://github.com/mnot/I-D/issues/39) on the IANA discussion gets solved; if not, we move to 2. at that point. (We may directly contact @mnot to see whether there is hope the issue would be solved within 1-2 months.)

Call me chicken, but I have no particular desire to do 1. The safe bet is to go 2.

**Comment by elf-pavlik** [comment]
FYI : during [next Social WG Face 2 Face](https://www.w3.org/wiki/Socialwg/2015-03-17) (next week at MIT)  we plan to discuss [normative use of Microformats in W3C specs](https://www.w3.org/Social/track/actions/41). Harry Halpin [mentioned yesterday](http://socialwg.indiewebcamp.com/irc/social/2015-03-10/line/1426007215129) discussing this issue with @wseltzer and @timbl

@iherman schema.org uses schema:domainIncludes (and schema:rangeIncludes) instead of rdfs:domain and rdfs:range . As I understand it, this acts just as a hint and has no formal consequences (no RDFS inference) @danbri 

https://github.com/schemaorg/schemaorg/blob/a27a4273891f9b313c0c6eb80cf2b6fe0b15357f/data/schema.rdfa#L4465-L4467

HTH

**Comment by iherman** [comment]
> On 11 Mar 2015, at 07:25 , ☮ elf Pavlik ☮ notifications@github.com wrote:
> 
> FYI : during next Social WG Face 2 Face (next week @MIT) we plan to discuss normative use of Microformats in W3C specs. Harry Halpin mentioned yesterday discussing this issue with @wseltzer and @timbl
> 
> @iherman schema.org uses schema:domainIncludes (and schema:rangeIncludes) instead of rdfs:domain and rdfs:range . As I understand it, this acts just as a hint and has no formal consequences (no RDFS inference) @danbri
> 
> https://github.com/schemaorg/schemaorg/blob/a27a4273891f9b313c0c6eb80cf2b6fe0b15357f/data/schema.rdfa#L4465-L4467
> 
> HTH
> 
> —
> Reply to this email directly or view it on GitHub.

Thanks for these information! I also had some discussions with Harry last week, but I do not know the outcome of the discussion with @wseltser and @timbl. Note that, in our case, the question is not microformats at large, but also whether we would use IANA URL-s or microformat wiki URL-s.

As for the schema.org issue: I actually did not look at rdfs:domain vs. schema:domainIncludes; I simply looked at the [definition of Thing](https://schema.org/Thing) which defines schema:about. The way I read it is that this property is meant to be used in conjunction with CreativeWork or CommunicateAction (regardless of any RDFS inference). Indeed, @danbri should tell us something about this but, in my reading, it is not really appropriate to use it for what we meant to use it for.

Cheers

Ivan

**Comment by gkellogg** [comment]
RESOLUTION: we define & use csvw:describes & get on with our lives

**Comment by gkellogg** [comment]
Leaving this active with an issue marker in case the TAG picks this up, but changing the usage to `csvw:describes`.

**Comment by gkellogg** [comment]
Nevermind, leaving the issue marker only muddies the waters further, and this can always be addressed further post LCCR if so directed.

**Comment by gkellogg** [comment]
Just adding this for future reference. The following metadata file will generate a reasonable RDFS vocabulary from the IANA CSV:

```
{
  "url": "http://www.iana.org/assignments/link-relations/link-relations-1.csv",
  "tableSchema": {
    "aboutUrl": "{name}",
    "lang": "en",
    "columns": [
      {"name": "name", "title": "Relation Name", "propertyUrl": "rdfs:label"},
      {"name": "comment", "title": "Description", "propertyUrl": "rdfs:comment"},
      {"name": "type", "title": "Reference", "propertyUrl": "rdf:type", "valueUrl": "rdf:Property"},
      {"title": "Notes", "suppressOutput": true}
    ]
  }
}
```

In a sense, this makes `http://www.iana.org/assignments/link-relations/` a reasonable basis for the IANA vocabulary, if this metadata were published as link-relations-1.csv-metadata.json, as it's pretty similar to a Turtle or RDF/XML file that might be published there.

**Comment by iherman** [comment]
@gkellogg it is good to have this, but it may be lost if it is just listed as part of this (closed) issue... Maybe worth storing it in some separate file on the repo.

**Comment by gkellogg** [comment]
I can add it to th examples directory. I will also likely use it to create a cache IANA vocabulary for my Ruby  RDF libraries, as users have been clamoring for this.

**Comment by iherman** [comment]
> On 06 Apr 2015, at 16:11 , Gregg Kellogg notifications@github.com wrote:
> 
> I can add it to th examples directory. I will also likely use it to create a cache IANA vocabulary for my Ruby RDF libraries, as users have been clamoring for this.

Sounds like a good idea!

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by elf-pavlik** [comment]
FYI
- https://github.com/mnot/I-D/issues/140 (Stable URIs for registered relation types)
- https://github.com/mnot/I-D/issues/144 (Requirements for IANA page)
