### ISSUE TITLE
How to interpret fixed string type values ("Table", "Row",...)

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#30]
It is not clear how to interpret these values (at the moment, they are `"@type": "Table"`, `"@type": "Column"`, and `"@type" : "Row"` to keep the JSON/RDF versions in sync. I see several possibilities:
- Assign URI-s in the form of `csv:Table`, etc., and these are the values in both RDF and JSON.
- Use a URI like above for RDF, and use a string for JSON; for the latter, we rely on a possible `@context` to make the two versions in sync.

At the moment the documents follow the second alternative.

**Comment by JeniT** [comment]
As we decided at the [October 2014 F2F at TPAC](http://www.w3.org/2014/10/28-csvw-minutes.html#item01), the simple JSON mapping should be for people who don't need to care about RDF; I agree with taking the second of the options as I think that's more natural for people who are used to JSON (although to be honest they likely don't need a `@type` at all, because they'll assume a type based on the context).

**Comment by iherman** [comment]
I will mark it as 'need telcon/decision' just to close the issue

**Comment by danbri** [comment]
See http://www.w3.org/2014/11/12-csvw-irc#T15-32-54

**Comment by 6a6d74** [comment]
Discussed in meeting 12-Nov-2014 ([Minutes](http://www.w3.org/2014/11/12-csvw-minutes.html)); summary ...

"we’re trying to make JSON as “brutally simple” as possible"

RESOLUTION: use a URI for RDF (e.g. `csv:Table`), and use a string for JSON; for the latter, we rely on a possible `@context` to make the two versions in sync.

However, further thought is required to determine whether things should be declared with `@type` for (plain old) JSON at all!

Issue not closed as mapping doc is yet to be updated.

**Comment by 6a6d74** [comment]
The csv2json document is now updated. Specific type information for `TableGroup` and `Table` is _NOT_ included in either _minimal_ or _standard_ mode.

The updated csv2rdf doc asserts that in _standard_ mode, `rdf:type` statements are _always_ included for `csvw:TableGroup` and `csvw:Table`.

Is this acceptable? Can we close this issue?

**Comment by iherman** [comment]
> On 05 Mar 2015, at 10:48 , Jeremy Tandy notifications@github.com wrote:
> 
> The csv2json document is now updated. Specific type information for TableGroup and Table is NOT included in either minimal or standard mode.
> 
> The updated csv2rdf doc asserts that in standard mode, rdf:type statements are always included for csvw:TableGroup and csvw:Table.
> 
> Is this acceptable? Can we close this issue?

Kill it:-)

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
Done.
