### ISSUE TITLE
The table annotations in the csv2* documents?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#306]
At the moment, it seems that the csv2rdf and csv2json documents contain the detailed annotations of the tables (in the examples) and they seem to be a repetition of the examples in the syntax document. That makes the examples really difficult to grasp. I would propose to
- either remove those examples altogether from the conversion document and refer to the syntax document itself
- or use some simple jQuery trick to hide, initially, those examples so that users can look into it only if it is necessary

Att. @6a6d74 : if the latter, we should use the [respec trick to include external data](http://www.w3.org/respec/ref.html#data-include) to avoid possible inconsistencies…

**Comment by 6a6d74** [comment]
@iherman - the example in the csv2\* docs are not the same as those in the syntax document; they're similar but not the same. I made sure that they covered many of the edge cases that impact the conversion.

I agree that consistency in examples across our suite of specifications would be a good thing. 

Should the data model / syntax doc be updated to use the examples in the csv2\* docs? @JeniT - what do you think?

**Comment by iherman** [comment]
> On 06 Mar 2015, at 05:37 , Jeremy Tandy notifications@github.com wrote:
> 
> @iherman - the example in the csv2\* docs are not the same as those in the syntax document; they're similar but not the same. I made sure that they covered many of the edge cases that impact the conversion.

O.k., I did not realize that...

> I agree that consistency in examples across our suite of specifications would be a good thing.
> 
> Should the data model / syntax doc be updated to use the examples in the csv2\* docs? @JeniT - what do you think?

In my view, they should be identical. And I am still not sure how to make it more readable; e.g., a button to hide/reveal it, or something like that.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
@6a6d74 I suggest breaking down the examples to highlight the salient features that you want to draw attention to (perhaps having the full examples in an appendix or something). I'd first show the full CSV files and then, for example, if you wanted to highlight the handling of sequences, show the relevant column description from the metadata, describe the cell as generated in the model, and show the relevant JSON/RDF that would be generated from that cell.

I do think that having separate files for these examples that could be brought into the other documents would be very useful. They'd need to be broken down a little (ie one file for each of the CSV examples, one for the metadata example) so that it was possible to wrap different narratives around them in the specs.

**Comment by 6a6d74** [comment]
@JeniT - this sounds like a good idea; I'll try to figure out how to break things down. I think that putting the full version of the examples into an appendix will be useful; something self-contained for folks to work through.

Regarding the second point, you will already find the CSVs, metadata descriptions and TTL / JSON output files in the csv2rdf / csv2json directories. CSVs and metadata are duplicated.

**Comment by gkellogg** [comment]
Perhaps all examples should go into a common examples directory. We can also have a task to verify that the expected results are correct.

**Comment by 6a6d74** [comment]
all - I will have very limited time this week now to make changes to the examples structure. Given that time is now short before we are hoping to publish the next set of WD's, please feel free to make some proposals / submit PRs about how to restructure. Thanks ...

**Comment by 6a6d74** [comment]
We have now restructured the algorithm(s) in the csv2json and csv2rdf docs ... do we still need to restructure the examples so that specific points can be illustrated with small examples and the full examples are added to an Annex?

**Comment by iherman** [comment]
Separately from the restructuring of the examples on the repo, I experimented with a small Javascript added to our document. See, in a separate branch:

https://rawgit.com/w3c/csvw/hiding-annotation-details/csv2json/index.html#example-countries

The detailed annotated table has been 'replaced' by a button that can be use to show or hide the details of the annotated tables. By default, it is hidden, ie, the reader sees the data and the two possible json outputs.

@gkellogg @6a6d74 @JeniT @danbri : feedback please whether you think it is worth using this approach. If yes, I am happy to mark up both conversion documents for all the tables.

**Comment by danbri** [comment]
See http://www.w3.org/2015/03/18-csvw-irc#T15-47-36

**Comment by gkellogg** [comment]
It's nice for the live view, but as I mentioned on the call, when printed it should be expanded. If I save to PDF now, all I see is the button. I think this can probably be done with some CSS magic selecting on media type, at least that's how Bootstrap.js would probably handle it.

**Comment by iherman** [comment]
What I know is that if I 'show' the tables and I then generate a PDF file, then I get whatever is on the screen. Ie, the user can choose; and, when we publish, we can make it sure to generate a PDF file this way.

I can also add yet another button somewhere towards the top that opens up _all_ examples in one step. That may help generating a PDF file.

Ivan

> On 18 Mar 2015, at 18:41 , Gregg Kellogg notifications@github.com wrote:
> 
> It's nice for the live view, but as I mentioned on the call, when printed it should be expanded. If I save to PDF now, all I see is the button. I think this can probably be done with some CSS magic selecting on media type, at least that's how Bootstrap.js would probably handle it.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
I think we may need something like [`window.matchMedia`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia). Or something to [trigger on print requests](http://tjvantoll.com/2012/06/15/detecting-print-requests-with-javascript/). I think relying on a user to click on the buttons to expect examples before printing is a real problem, otherwise.

**Comment by iherman** [comment]
Let me do the basic setup first, we can experiment with this later.

If window.matchMedia works, then I should be able to put the initial setup in conditional, and make everything visible by default for that (but does matchMedia return the equivalent of @print in CSS?)

Ivan

> On 18 Mar 2015, at 20:29 , Gregg Kellogg notifications@github.com wrote:
> 
> I think we may need something like window.matchMedia. Or something to trigger on print requests. I think relying on a user to click on the buttons to expect examples before printing is a real problem, otherwise.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
Requires more investigation, but the onprintrequest might be an alternative.

**Comment by 6a6d74** [comment]
see ISSUE #380; I think this closes everything discussed here. There's opportunity to further prettify the csv2\* docs after next WD publication. Right now, we've got the technical details sorted.

So I think this is also fixed by #381.

Closing issue.
