### ISSUE TITLE
conformance clauses in the metadata and model documents

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#308]
AFAIK we must have such a conformance clause. At the minimum, it should be the vanilla clause (I suspect this can be generated by `respec` through `<section id='conformance'>`. But I would think that
- we may want add a reference to CURIE-s eg like done in the csv2\* documents to the metadata document to at least make it clear what we mean in the common properties
- we may want to add different class of processors that we already referred to in our discussions, like validators or converters. This may be good because the csv2\* processors pretty much rely on valid (meta)data, ie, conceptually, the data has gone through a validator. 
- I am not sure whether there is anything to add in the model document beyond the standard text

**Comment by gkellogg** [comment]
It would make more sense to me to reference prefixed names from JSON-LD than CURIEs, since this is the basis of the metadata.

Note that a validator doesn't simply validate the metadata, but also the annotated tables, whereas a converter only needs the metadata itself to be valid.

**Comment by iherman** [comment]
> On 07 Mar 2015, at 11:31, Gregg Kellogg notifications@github.com wrote:
> 
> It would make more sense to me to reference prefixed names from JSON-LD than CURIEs, since this is the basis of the metadata.
> 
> That is also fine. But the csv2rdf document refers to RDFa; we should be consistent.

Ivan

**Comment by JeniT** [comment]
@iherman Can you point us to a spec where there's a well-written conformance clause please?

**Comment by iherman** [comment]
I think that [HTML5+RDFa](http://www.w3.org/TR/html-rdfa/#conformance) pretty o.k,, with different processors, albeit maybe a little bit verbose.

**Comment by gkellogg** [comment]
@6a6d74 we should probably use the same reference in CSV\* and model/syntax. I'll do a separate PR for those.

**Comment by gkellogg** [comment]
See 4c30373e770619bb40fcabf2a675550d0729fea6
