### ISSUE TITLE
The description of the metadata processing seems to be incomplete

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#314]
(This is a spin-off from #293, in particular @gkellogg 's comment on that issue https://github.com/w3c/csvw/issues/293#issuecomment-77696406).

I think the problem is that the [processing as defined in section 4.1 the model document](http://w3c.github.io/csvw/syntax/index.html#creating-annotated-tables) is incomplete, we have to go back there. In all cases the issue is, as @gkellogg describes, that through the merge algorithm, new tables may be added to the table group, and this has not been accounted for. 
1. The first part of the algorithm, ie, when we start with a CSV yields a table group; the question is: does the processing stop there, or should there be some sort of a "closure" of the table groups, ie, should the csv files whose reference have been added to the metadata trigger a new round. (Procedurally, the question is whether the metadata file should be input to the second part of the algorithm in the model dcoumen
   1. I think that it is sensible to say "no"; after all, the process has been started for a specific CSV file
      - Note that this may be the place to add the possibility for the `supressOutput` flag for the 'other' tables, as mentioned in https://github.com/w3c/csvw/issues/293#issuecomment-77689760
   2. Alternatively, we could say that the processor may have a flag deciding on this
2. The second part of the algorithm starts with a metadata where the closure is probably necessary. A possible _but incomplete_ algorithm could be something like:
   1. Retrieve the metadata file yielding the metadata `UM`
   2. M<sub>c</sub> := UM
   3. `tindex := 0`
   4. Take M<sub>c</sub>[tindex] if it exists, and run the steps for a tabular data file using the  `url` from the table description with M<sub>c</sub> playing the role of UM to create one or more annotated tables. That process yields M<sub>new</sub>.
   5. `tindex := tindex+1`
   6. If `tindex` does not refer to a table any more, the process stops and M<sub>new</sub> is the final metadata. Otherwise, M<sub>c</sub> = M<sub>new</sub> and the process starts again at 2.iv.

Because the merge is such that hitherto unknown tables are added to the end of the table array, that actually works _except_ that there is no halting condition. This may be a problem in setting up the system, or a malicious setup that would create a DOS attack of some sort. From @gkellogg 's mail:

> Perhaps starting with metadata means that only file-specific metadata from referenced tables is loaded, and not directory-metadata too, and possibly that file-specific metadata MUST start with a Table, which MUST have a url annotation referencing the file with which it is associated.

I am not sure that the removal of directory-metadata would help, because errors may also occur in file-specific metadata. I am not sure I understand what you propose in the second part, @gkellogg .

A simple but ugly approach is to say that the application sets a, possibly user definable limit on how many tables are accepted in a table group. If that value is reached in `tindex` above, the process stops...

A more radical approach is to look at the merge algorithm again. What if we restrict the merge algorithm such that _no new table_ is added to the metadata 'A'?  After all, I believe that if the user simply addresses a single CSV file than, most of the time, the extra tables are just noise; however, if he/she really wants to access several files, the user metadata may simply list those that are needed additionally to the starting CSV file or, alternatively the user can start with a Metadata file that may have the right list of tables. Such a change may require:
- `UM`, in the first part of the algorithm, is extended, if needed, with a single table for the CSV file at hand
- Modification of the merge algorithm for `resources`
- The second part of 4.1 in the model document remains unchanged

**Comment by JeniT** [comment]
(Copied my characterisation below from my duplicate #312, which I've closed.)

See #293.

Say you start with `A.csv`. You retrieve its associated metadata at `A.csv-metadata.json` and that file lists two other CSV files, `B.csv` and `C.csv`. There are foreign key references between these resources, so it's necessary to understand the metadata about `B.csv` and `C.csv`. To get the full picture, you need to get hold of `B.csv-metadata.json` and `C.csv-metadata.json` which provide more detail than is in `A.csv-metadata.json`. Each of those can similarly reference other files, `D.csv` and `E.csv` and so on it goes.

A similar scenario plays out if you start with a metadata file and then go to retrieve all the metadata from all the CSV files that are referenced in that metadata file.

There are several issues with this:
- the huge explosion of files that need to be retrieved to process the single CSV file
- the order in which the metadata files from different locations are merged
- the ability of any metadata file to affect the original processing of `A.csv`, which means you really have to get all of them before you can start

I think the only realistic option is to say that when you start from a CSV file, you only get the metadata associated with that CSV file (aside from the user-defined and embedded metadata that is). And that when you start with a metadata file, that's the only metadata you use (it acts as user-defined metadata and you don't then retrieve metadata through the other mechanisms).

**Comment by iherman** [comment]
> On 07 Mar 2015, at 16:56 , Jeni Tennison notifications@github.com wrote:
> 
> (Copied my characterisation below from my duplicate #312, which I've closed.)
> 
> See #293.
> 
> Say you start with A.csv. You retrieve its associated metadata at A.csv-metadata.json and that file lists two other CSV files, B.csv and C.csv. There are foreign key references between these resources, so it's necessary to understand the metadata about B.csv and C.csv. To get the full picture, you need to get hold of B.csv-metadata.json and C.csv-metadata.json which provide more detail than is in A.csv-metadata.json. Each of those can similarly reference other files, D.csv and E.csv and so on it goes.
> 
> A similar scenario plays out if you start with a metadata file and then go to retrieve all the metadata from all the CSV files that are referenced in that metadata file.
> 
> There are several issues with this:
> 
>   • the huge explosion of files that need to be retrieved to process the single CSV file
>   • the order in which the metadata files from different locations are merged
>   • the ability of any metadata file to affect the original processing of A.csv, which means you really have to get all of them before you can start
> I think the only realistic option is to say that when you start from a CSV file, you only get the metadata associated with that CSV file (aside from the user-defined and embedded metadata that is).

+1, this is essentially what I said

> And that when you start with a metadata file, that's the only metadata you use (it acts as user-defined metadata and you don't then retrieve metadata through the other mechanisms).

Do you mean there is no merge, nothing? I can live with that, too... (happily:-)

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
@iherman I'm suggesting that when you start from a metadata file there's still the merge of the embedded metadata from the CSV files themselves, but nothing beyond that.

**Comment by gkellogg** [comment]
So, is there a role for directory metadata anymore? Is linked metadata only used when starting with a CSV an not when starting with metadata (that seems consistent with @JeniT's suggestion).

I think we need to strive for simplicity and predictability here. So, intending to agree with all the above statements:
- When starting with a CSV, use only user-specified, embedded-, linked- and file-specific metadata limited to the table referencing that CSV only. This makes sense for transformations, but may cause problems with foreign-key relationships, which might simply be ignored when starting with a CSV.
- When starting with metadata, use only user-specified and that metadata processing all tables described within that merged metadata. Any metadata specifically associated with those files is not loaded and does not affect processing (embedded-, linked-, file-specific metadata).

I think this is the most straight-forward approach and does not lead to surprises related to possibly loading more discovered metadata in some other order.

**Comment by iherman** [comment]
This is where there is still a difference: @JeniT says:

> @iherman I'm suggesting that when you start from a metadata file there's still the merge of the embedded metadata from the CSV files themselves, but nothing beyond that.

whereas @gkellogg says:

> - When starting with metadata, use only user-specified and that metadata processing all tables described within that merged metadata. Any metadata specifically associated with those files is not loaded and does not affect processing (embedded-, linked-, file-specific metadata).

The difference being whether the embedded metadata is to be considered or not. I must admit I do not feel strong either way, although I have a sligth preference for @JeniT 's: if the implementation defines some meaningful additions in the embedded metadata, it makes sense to use it. This is mitigated by the fact that if the implementation only understand the 'first row provide titles' embedded metadata, than, by virtue of the merge algorithm, that merge is probably meaningless, because the merge of the columns will work only if the titles in the first row are already present in the starting metadata...

However: both cases mean that my [original (and admittingly more complex)](https://github.com/w3c/csvw/issues/314#issue-60226219) approach has some meat in it. Indeed, what is the use, in the merge algorithm, of adding new tables when merging table groups (ie, the value of "resource")? Isn't it correct that, in both cases, those additional table descriptions will be ignored? In the case of the 'start by CSV' because only the table description for that single CSV file will be considered; in the case of the 'start by Metadata' because that situation simply does not occur. Maybe worth simplifying the merge algorithm on that point?

**Comment by gkellogg** [comment]
RESOLVED: we encourage starting from metadata files (in which case that and embedded metadata are the only metadata that’s used). Otherwise, the first “proper” metadata file discovered is the only one that’s used (processor-specific flags and embedded metadata don’t count as proper metadata files; they are always used, but processing doesn’t stop when you use them)
