### ISSUE TITLE
What do to with conversion if no column name is given?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#33]
The current metadata document says that the `schema` property is optional, or, even if set, column, row, or cell properties are all optionals. What this means is that the names of the columns may _not_ be available. If so, the current RDF/JSON conversion algorithms fail. A possibility is to define (in the metadata document) a default fall-back for column naming if there is nothing providing them. (Or requiring the presense of `schema/column`).

The [discussion on a telco](http://www.w3.org/2014/10/01-csvw-minutes.html#item01) on the 1st of October put forward the approach of letting the conversion fail altogether; this is now reflected in the conversion documents.

**Comment by JeniT** [comment]
I think this is really about what to do when the whole schema is missing rather than the column name being missing (as `name` is required on a column specification and column specifications are required if there's a schema).

Note that if a CSV file has a header row then the columns _will_ have titles which I think should be used as the basis of the conversion. For example a basic conversion of the CSV file:

```
GID,On Street,Species,Trim Cycle,Inventory Date
1,ADDISON AV,Celtis australis,Large Tree Routine Prune,10/18/2010
2,EMERSON ST,Liquidambar styraciflua,Large Tree Routine Prune,6/2/2010
3,EMERSON ST,Liquidambar styraciflua,Large Tree Routine Prune,6/2/2010
```

should use the names `GID`, `On Street`, `Species` etc as the basis for column names even if the schema is missing.

My personal preference is to provide a default column naming convention (eg `#col=1`, `#col=2`) if there's neither a schema nor a header row, rather than failing altogether.

**Comment by iherman** [comment]
On 31 Oct 2014, at 15:45 , Jeni Tennison notifications@github.com wrote:

> I think this is really about what to do when the whole schema is missing rather than the column name being missing (as name is required on a column specification and column specifications are required if there's a schema).
> 
> Note that if a CSV file has a header row then the columns will have titles which I think should be used as the basis of the conversion. For example a basic conversion of the CSV file:
> 
> GID,On Street,Species,Trim Cycle,Inventory Date
> 1,ADDISON AV,Celtis australis,Large Tree Routine Prune,10/18/2010
> 2,EMERSON ST,Liquidambar styraciflua,Large Tree Routine Prune,6/2/2010
> 3,EMERSON ST,Liquidambar styraciflua,Large Tree Routine Prune,6/2/2010
> 
> should use the names GID, On Street, Species etc as the basis for column names even if the schema is missing.
> 
> My personal preference is to provide a default column naming convention (eg #col=1, #col=2) if there's neither a schema nor a header row, rather than failing altogether.

I am fine with that.

However, this should be described/defined in the syntax or the metadata document, and not in the mapping documents. It is, I believe, a general guideline that if a CSV has no metadata then, conceptually, there is a (virtual) metadata with those entries and those entries only. This is regardless of what processes the file.

(At some point such a default was part of the RDF conversion document which, I believe, is not the right place.)

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
GPG: 0x343F1A3D
WebID: http://www.ivan-herman.net/foaf#me

**Comment by iherman** [comment]
Just writing down the current status for column names. Here is what I found:
- The SoD section of the [syntax document](http://w3c.github.io/csvw/syntax/index.html#sod) says "Many CSV files embed metadata, for example in lines before the header row of the CSV document. This specification does not define any formats for embedding metadata within CSV files, aside from the names of columns in the header row."
- [Section 2.2 of the syntax document](http://w3c.github.io/csvw/syntax/index.html#annotated-tabular-data-model) talks about metadata added to a CSV document, but it does _not require_ that that metadata should include row names.
- [section 4.4.1 of the syntax document](http://w3c.github.io/csvw/syntax/index.html#headers) says: "The first line of a CSV+ file should contain a comma-separated list of names of columns. This is known as the header line and provides names for the columns. There are no constraints on these names.". But it also defines a way to return a file without that header (via `Content-Type`). But note that _this section is not normative_. 
- If one follows the [metadata document](http://w3c.github.io/csvw/metadata/index.html) one has:
  - [a 'table description' in section 3.5](http://w3c.github.io/csvw/metadata/index.html#tables), but its only required property is '@id'. It _may_ contain a 'schema'.
  - ['schema'](http://w3c.github.io/csvw/metadata/index.html#schemas) which says that all its properties are optional, but _may_ contain a 'column'
  - ['columns'](http://w3c.github.io/csvw/metadata/index.html#columns) which _requires_ the presence of the `name` property.

First of all a tiny issue is that what the status section says, sort of, incorrect. This specification does not define the content of the embedded metadata, and only refers to the column names in the first row in an non-normative section. That part of the sentence should probably be removed.

But, more importantly, what this all means is that I may have a 'conformant' CSV file (whatever that means, actually) which does not have any column names. This means that there should be, probably as part of the metadata document, a section describing the default column naming convention, ie, a minimal `schema` metadata entry. Alternatively, there should be a sequence of required metadata keys (`table description`->`schema`->`column`) to ensure the presence of the column names. 

Actually, the metadata document may want to emphasize that what is in that document is _not_ the format (in terms of "require") of the individual metadata files, but the combined metadata assigned to a CSV file as described in the syntax. Ie, only one of those metadata sources have to define the column names, not all of them...

**Comment by JeniT** [comment]
This is about defining what property is used when converting tabular data into RDF or JSON when a column name is missing, right? I'd say that should be defined in the conversion document(s). It has no impact of validation for example.

I think the conversion document should say something along the lines of

> The property name is constructed by taking:
> 1. The `name` of the column as specified in the metadata document, if there is one; or
> 2. The `title` annotation on the column (which might come from the header line of a CSV file, for example); or
> 3. A name constructed as `colN` where `N` is the number of the column (starting from 1)

**Comment by iherman** [comment]
That _almost_ works for me, except that the title attribute, at present, may be an array:-( We can of course concatenate all the strings in the array; cumbersome but we may have no choice.

Ivan

> On 29 Nov 2014, at 14:09 , Jeni Tennison notifications@github.com wrote:
> 
> This is about defining what property is used when converting tabular data into RDF or JSON when a column name is missing, right? I'd say that should be defined in the conversion document(s). It has no impact of validation for example.
> 
> I think the conversion document should say something along the lines of
> 
> The property name is constructed by taking:
> 
>   • The name of the column as specified in the metadata document, if there is one; or
>   • The title annotation on the column (which might come from the header line of a CSV file, for example); or
>   • A name constructed as colN where N is the number of the column (starting from 1)
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
Or use the first title from the array (which we can carefully define as being the one from the embedded header).

**Comment by 6a6d74** [comment]
OK - so I will add the following logic into the mapping docs:

1) if provided, the column header from the CSV file will provide the value of the `title` property for the column
2) if _both_ column header from CSV file and one or more `title` properties are provided in the metadata document then the column header will be provide the first value in an array of `title` properties (e.g. at index zero `column.title[0]`)
3) if property `name` is not provided for a column, the mapping algorithm will assume the value of the `name` property to be either the column title from the CSV header row, or, if not present, then `#col=n` (where `n` is the column number)

**Comment by iherman** [comment]
+1

Ivan

> On 01 Dec 2014, at 10:57 , Jeremy Tandy notifications@github.com wrote:
> 
> OK - so I will add the following logic into the mapping docs:
> 
> 1) if provided, the column header from the CSV file will provide the value of the title property for the column
> 2) if both column header from CSV file and one or more title properties are provided in the metadata document then the column header will be provide the first value in an array of title properties (e.g. at index zero column.title[0])
> 3) if property name is not provided for a column, the mapping algorithm will assume the value of the name property to be either the column title from the CSV header row, or, if not present, then #col=n (where n is the column number)
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
One more thought ...

[3.9 Columns](http://w3c.github.io/csvw/metadata/#columns) states that for the `name` property: “Names beginning with _ are reserved by this specification and must not be used.” Should the automatically assigned column name follow the pattern `_col=N` for consistency? Also, note that prefixing a column name with ‘#’ may incur unintended side-effects with the ‘#’ operator in URI Templates.

**Comment by iherman** [comment]
> On 09 Dec 2014, at 14:38 , Jeremy Tandy notifications@github.com wrote:
> 
> One more thought ...
> 
> 3.9 Columns states that for the name property: “Names beginning with _ are reserved by this specification and must not be used.” Should the automatically assigned column name follow the pattern _col=N for consistency? Also, note that prefixing a column name with ‘#’ may incur unintended side-effects with the ‘#’ operator in URI Templates.

Works for me. Your note on '#' is indeed relevant (and it also makes readers mix it up with fragments identifiers)

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
@iherman: can you indicate your preference for `col=N` or `_col=N`?

**Comment by iherman** [comment]
> On 09 Dec 2014, at 15:16 , Jeremy Tandy notifications@github.com wrote:
> 
> @iherman: can you indicate your preference for col=N or _col=N?

The only reason to go for col=N may be to be more in line with the RDB Direct mapping approach[1]

[1] http://www.w3.org/TR/rdb-direct-mapping/

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
For the time being I am going to choose `_col=N` because _our_ spec says that names beginning with `_` are sacrosanct. 

Also note that when working on the RDF mapping, it occurred to me that `_col=N` will actually become a predicate (a relative URL) in the output - making use of the `#` character even more likely to introduce errors.

**Comment by iherman** [comment]
O.k. These the type of small details that we can take care of later anyway. Let us keep this issue open for now.

Ivan

> On 16 Dec 2014, at 10:13 , Jeremy Tandy notifications@github.com wrote:
> 
> For the time being I am going to choose _col=N because our spec says that names beginning with _ are sacrosanct.
> 
> Also note that when working on the RDF mapping, it occurred to me that _col=N will actually become a predicate (a relative URL) in the output - making use of the # character even more likely to introduce errors.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
I've removed the CSV to JSON mapping and CSV to RDF mapping labels from this because the creation of default names should all be handled within the model & metadata documents, with the conversion documents simply picking up on the names that are given to them.

**Comment by JeniT** [comment]
Looking again, I think this is actually covered in the current document through the [definition of name](http://w3c.github.io/csvw/metadata/#column-name). There are a couple of extra things to do (see #180 & #53) but it does mean that `name` _always_ has a value.

So the remaining Editor actions are only on the conversion documents, which should just use the `name` property as appropriate.
