### ISSUE TITLE
Notes and Open Annotation

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#330]
Issue #288 has a comment suggesting that notes would be clearer if it included Open Annotation content, such as the following:

```
"notes": {
    "@type": "oa:Annotation",
    "oa:hasTarget": "http://example.org/tree-ops-ext",
    "oa:hasBody": {
      "@type": ["cnt:ContentAsText", "dctypes:Text"],
      "cnt:chars": "This is a very interesting comment about the table; it's a table!",
      "dc:format": {"@value": "text/plain"}
    }
}
```

Note that none of the prefixes "oa", "cnt" or ""dctypes" are in our context, as they're not in the RDFa initial context.

**Comment by 6a6d74** [comment]
Gotcha. Am in the process of adding `notes` example to csv2rdf and csv2json. 

I spotted the initial context issue.

**Comment by iherman** [comment]
> On 10 Mar 2015, at 13:34 , Gregg Kellogg notifications@github.com wrote:
> 
> Issue #288 has a comment suggesting that notes would be clearer if it included Open Annotation content, such as the following:
> 
> "notes": {
>     "@type": "oa:Annotation",
>     "oa:hasTarget": "http://example.org/tree-ops-ext",
>     "oa:hasBody": {
>       "@type": ["cnt:ContentAsText", "dctypes:Text"],
>       "cnt:chars": "This is a very interesting comment about the table; it's a table!",
>       "dc:format": {"@value": "text/plain"}
>     }
> }
> 
> Note that none of the prefixes "oa", "cnt" or ""dctypes" are in our context, as they're not in the RDFa initial context.

Indeed:-(

'oa', per our rules, eventually will (as soon as OA becomes a CR) and it is already flagged as one. 'dctypes'... well, it did not make it back then, for whatever reasons; I do not see any problems adding these two to our initial context now (although it is a bit of a problem that we have to add our own but, anyway).

'cnt' is a different animal. The corresponding spec[1] does not seem to go anywhere, so the now really authoritative version of oa[2] has dropped its usage. Ie, we should not do that either. B.t.w., it would be better to look at [2] for examples that we would reuse; one advantage is that the examples are (also) in JSON-LD...

Ivan

[1] http://www.w3.org/TR/Content-in-RDF10/
[2] http://www.w3.org/TR/annotation-model/

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
We should also add a prefix `rel: http://www.iana.org/assignments/link-relations/`, if that's what we've decided on.

**Comment by iherman** [comment]
That is definitely pending, see issue #297 !

**Comment by gkellogg** [comment]
This might be a better example, then:

```
 "notes": {
     "@type": "oa:Annotation",
     "oa:hasTarget": "http://example.org/tree-ops-ext",
     "oa:hasBody": {
       "@type": "oa:EmbeddedContent",
       "rdf:value": "This is a very interesting comment about the table; it's a table!",
       "dc:format": {"@value": "text/plain"}
     }
 }
```

Note that we could use `dc:language`, however we set `@language`, so this is implicit in the embedded value. I think `dc:language` might be more important for describing the language used in external media.

**Comment by iherman** [comment]
Yes, that looks good!

> On 10 Mar 2015, at 15:32 , Gregg Kellogg notifications@github.com wrote:
> 
> This might be a better example, then:
> 
>  "notes": {
>      "@type": "oa:Annotation",
>      "oa:hasTarget": "http://example.org/tree-ops-ext",
>      "oa:hasBody": {
>        "@type": "oa:EmbeddedContent",
>        "rdf:value": "This is a very interesting comment about the table; it's a table!",
>        "dc:format": {"@value": "text/plain"}
>      }
>  }
> 
> Note that we could use dc:language, however we set @language, so this is implicit in the embedded value. I think dc:language might be more important for describing the language used in external media.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
@6a6d74 I may have beaten you to it (notes examples) in #333; sorry if there's an overlap.

**Comment by JeniT** [comment]
Is this issue actually about a proposed technical change or purely editorial (ie about an example to use)? If the former, what's the proposed technical change?

**Comment by iherman** [comment]
It is editorial, except that some prefixes are added to the default context.

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by gkellogg** [comment]
Without objection, I'll simply merge.

**Comment by iherman** [comment]
go ahead

---

Ivan Herman
+31 641044153

(Written on my mobile. Excuses for brevity and frequent misspellings...)

**Comment by 6a6d74** [comment]
@gkellogg - I've added a bit more stuff to the csv2rdf and csv2json specs and merged; see PR #347

**Comment by 6a6d74** [comment]
can we close this issue now? I think that all the actions are done ...

**Comment by iherman** [comment]
having looked at the files I think yes

**Comment by 6a6d74** [comment]
thanks @iherman ... closing the issue.
