### ISSUE TITLE
Consolodate examples

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#334]
Examples seem to be repeated in each spec, either as an included file, or inline. We should move all examples under the /examples directory and use relative paths to include so that they are all consistent.

**Comment by JeniT** [comment]
I don't think this requires discussion, it's just Editor action surely?

**Comment by gkellogg** [comment]
Yes it is, but I didn't want to take unilateral action without the support of the other editors. @iherman @6a6d74? I'll do a PR and if no one objects, go ahead and merge that.

**Comment by iherman** [comment]
Sorry for the belated note, my schedule is a bit messed up with the travel... Of course I am happy with that! Thanks for doing it

**Comment by 6a6d74** [comment]
likewise - am happy with the consolidation
