### ISSUE TITLE
Two columns share the same propertyUrl (for json conversion)

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#337]
(This is a spin-off of #299)

It is possible that two columns share the same `aboutUrl` and `propertyUrl`, though with possibly different values. This is not a problem for the RDF case (just emit new triples) but should be explicitly handled in the JSON conversion. The obvious solution is to add an array of values for the shared key; this should be added to the document.

It is related to #299, which will need to re-write the relevant section anyway...

**Comment by 6a6d74** [comment]
I think this should be fixed by PR #369 ... pending review prior to merge. Check out step 2.4 of [Section 3.3 Generating Objects (from pending PR)](https://rawgit.com/w3c/csvw/b9cb28f0f72c7bb139628c39daf3182169a96669/csv2json/index.html#gen-subj-cells)

**Comment by 6a6d74** [comment]
fixed in PR #369
