### ISSUE TITLE
Should the "@type" information be reflected in the generated JSON/RDF?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#35]
The current conversion follows the metadata specification, insofar as, for example, the `"@type":"Row"` is set (in the JSON version) optionally, depending on whether the original metadata contains that `@type` or not. On the other hand, the value (`"Row"`, `"Column'`) are fixed strings (or URI-s in the RDF version), so it may be simpler to add that information unconditionally on the output.

**Comment by JeniT** [comment]
+1 to adding that information whether or not it appears in the metadata file, though note that the `@type` of `Column` within the metadata file actually refers to a **column description** (in a schema) rather than a **column** (in a table).

**Comment by iherman** [comment]
Oops. Jeni, I stand corrected. But, if so, then actually storing that key/value pair in JSON (or a triple in RDF) can be seen as an _error_, because it is a statement on the wrong subject. So... let me modify the proposal and say: _those metadata k/v pairs should be ignored by the transformation._

**Comment by JeniT** [comment]
We discussed during [2015-01-28 telcon](http://www.w3.org/2015/01/28-csvw-minutes.html) and resolved to retain `@type` as an optional property in the metadata.

@iherman Can you either close this issue or give it a title which is more in keeping with the actual issue that should be resolved here? Also, is this related to #189 about whether to keep/remove column metadata in the RDF file?

**Comment by iherman** [comment]
@JeniT I have changed the title. To reformulate the issue:
- we indeed agreed on the 28th of January that a `@type` property is allowed in the metadata, though not required
- it is unclear what to do in the RDF output. There seem to be three possibilities:
  1. `@type` is ignored altogether
  2. `if`@type`is present, a corresponding`rdf:type` is added
  3. a `rdf:type` is generated no matter what

However, by virtue of issue #26, the metadata author has an explicit means to assign type to a subject for a row, for example, i.e., I am in favor of going for (i).

**Comment by JeniT** [comment]
I think this is a different issue from #26 though, because it's about whether to generate `csvw:Column`, `csvw:Schema` etc types in the RDF, isn't it? Let's work through at the F2F what the RDF should include.

**Comment by iherman** [comment]
@JeniT why is it different? What https://github.com/w3c/csvw/issues/35#issuecomment-72860143 looks at whether there should be an automatic way of adding a 

```
<someUri> rdf:type csvw:Row ;
```

And #26 sys that there is a way for the user to add such a typing (and more) if he/she wants. The only question is automatism: do we want to do anything automatically, or let the metadata author decide? Clearly, using the, say, `rowTypeUrl`, such a triple can be added...

**Comment by JeniT** [comment]
Resolved at Feb F2F. Conversion will always add `rdf:type csvw:Table` in the RDF output.

**Comment by 6a6d74** [comment]
csv2rdf doc updated as per resolution at F2F.
