### ISSUE TITLE
URI Template with null variable doesn't evaluate to null

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#358]
Currently, the [public-sector-roles-and-salaries example](http://w3c.github.io/csvw/csv2rdf/#example-public-sector-roles-and-salaries) produces the following output for "Sir Alan" - even though the value of his `reportsTo` field is `null` (determined from the lexical cell value `"xx"`.

```
<http://example.org/senior-roles.csv#post-90334>
  dc:identifier "90334" ;
  foaf:name "Sir Alan Langlands" ;
  <http://example.org/def/reportsTo> <http://example.org/senior-roles.csv#post-> ;
  ...
```

But it is not the behaviour we want..

The algorithm states

> If the valueUrl for the current cell is not null, then valueUrl identifies a node Vurl that is related the current subject using the predicate P

My intent was that because "Sir Alan" has a null value for reportsTo then this triple would not get included. Of course, now that you point it out. the URI Template with a null value does get evaluated as you've shown above.

The algorithm needs amending.

**Comment by gkellogg** [comment]
Thinking about this, it would be good to have a way to say that a `valueUrl` is not generated in some cases. Perhaps if there's a datatype defined of type string with a `pattern`, and the pattern does not match then no `valueUrl` is created. Otherwise, the behavior is to create a plain literal.

Note that the valueUrl does not need to refer to the actual cell, and it can be used on a virtual column which would have a null value, so we need some way to escape out of this. Otherwise, as is, the valueUrl will always result in a URL.

The right place to handle this, IMO, is in the metadata document, not using special logic in a conversion document.

I can create a PR against the metadata document which does this, unless there's other discussion.

cc/ @JeniT @iherman

**Comment by iherman** [comment]
@gkellogg do we need such a complicated approach as what you have in PR #361? My initial reaction is to say (for all templates, not only for `valueUrl`) that if the template cannot be expanded for whatever reasons (eg, because a template variable is undefined) then the result is `null` meaning, unless a `default` is defined, nothing is emitted to the output.

**Comment by gkellogg** [comment]
That would require performing introspection into the template to identify the variables to see if any evaluate to null. In any case, in RFC 6570, null variables are ignored in expansion:

> A variable that is undefined (Section 2.3) has no value and is ignored by the expansion process.

There may be legitimate reasons to have a URI template referencing multiple variables where one of them evaluates to null, or even a single variable. I think trying to interpret URI Templates in this way is fraught with potential problems. The datatype format mechanism falls entirely into our own semantics, so seems safer.

**Comment by gkellogg** [comment]
It might be simpler to say that if there are any errors on the cell, when `valueUrl` is nil, as if the format doesn't match, it will generate an error.

**Comment by iherman** [comment]
> On 14 Mar 2015, at 18:32 , Gregg Kellogg notifications@github.com wrote:
> 
> That would require performing introspection into the template to identify the variables to see if any evaluate to null.

Hm. That is true.

> In any case, in RFC 6570, null variables are ignored in expansion:
> 
> A variable that is undefined (Section 2.3) has no value and is ignored by the expansion process.
> 
> There may be legitimate reasons to have a URI template referencing multiple variables where one of them evaluates to null, or even a single variable. I think trying to interpret URI Templates in this way is fraught with potential problems. The datatype format mechanism falls entirely into our own semantics, so seems safer.

What worries me, though, that this is yet another branch and property, etc, that the metadata author has to provide, and that the implementation has to take care of... we are getting into spaghetti code territory:-(

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
> On 14 Mar 2015, at 19:39 , Gregg Kellogg notifications@github.com wrote:
> 
> It might be simpler to say that if there are any errors on the cell, when valueUrl is nil, as if the format doesn't match, it will generate an error.

I am not sure how this answers to the original issue.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
I guess I don't find the process too complicated. I have a pass when I'm processing the cell where I set values for any of aboutUrl, propertyUrl and valueUrl. When setting valueUrl, if the cell has any errors on it (which need to be detected anyway as part of datatype matching), I just set `null` for valueUrl. IMO, this is not very complicated.

**Comment by iherman** [comment]
True, but it requires the metadata author to add some additional information into the metadata to detect, eg, the null value. This is what I am afraid of, less the implementation complexity.

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by JeniT** [comment]
@gkellogg I don't think that the approach that you're suggesting works. The scenario that @6a6d74 describes here isn't an error scenario: you wouldn't want a validator to raise an error as the use of a `null` value (`XX`) is as-designed.

In my opinion, the right approach is for the conversion documents to say that if a cell is `null` then no value is generated for that cell (even if the `valueUrl` is specified). If people want to generate a URL that includes a `null` value then they can create a virtual column to do so.

**Comment by gkellogg** [comment]
So, a null value in a non-virtual column does not generate a valueUrl, even if the valueUrl does not reference that string value. But a valueUrl in a virtual column always generates a value. I can live with that.

**Comment by 6a6d74** [comment]
+1 from me. I understand that if the cell is null within a non-virtual column, then don't evaluate the valueUrl URI Template. The metadata doc is where this behaviour is specified.

**Comment by iherman** [comment]
Ok, let us close it:-) Is there any editorial work to be done on it?

Ivan

> On 18 Mar 2015, at 10:25 , Jeremy Tandy notifications@github.com wrote:
> 
> +1 from me. I understand that if the cell is null within a non-virtual column, then don't evaluate the valueUrl URI Template. The metadata doc is where this behaviour is specified.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
I believe the PR has a commit that reflects this understanding.

**Comment by 6a6d74** [comment]
The outstanding PR should enable this issue to be closed.
