### ISSUE TITLE
The conversion should take into account the cell parsing rules for data

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#36]
At the moment, only the datatype is taken into account, and that is also vague, but some of the parsing rules, described in the [relevant section of the document](http://www.w3.org/TR/tabular-metadata/#parsing-cells) should also be incorporated. For example, the date value should be transformed to ISO format for RDF,

**Comment by JeniT** [comment]
@iherman can we close this? I think that we resolved that the conversion documents should reference (semantic) cell values rather than repeating the parsing logic which is already described within the metadata document.

**Comment by iherman** [comment]
Closed by virtue of those changes indeed.
