### ISSUE TITLE
Need for URL compaction

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#365]
(This issue is a spin-off from PR #362 ; I will try to reproduce the issue discussion in this note, and add my response in a separate one. 

@gkellogg in https://github.com/w3c/csvw/pull/362#issuecomment-80686059:

> Step 3.1 of Generating the Objects; propertyUrl is expanded in the metadata definition of URI Template Properties. These should be re-compacted to terms or prefixed names to be used as property names.

@gkellogg in https://github.com/w3c/csvw/pull/362#issuecomment-80734873

>  If propertyUrl is rdf:type, use @type for name, Compact values using the same mechanism for propertyUrl compaction.

@iherman https://github.com/w3c/csvw/pull/362#issuecomment-80943074

> I wonder how to do that properly, and whether this is not something to be described more generally somewhere. Indeed, compacting the URI may be relevant for aboutUrl-s and valueUrl-s as well; after all, if we do use compacted values, they may look better. Of course, propertyUrl-s are the place where it occurs the most often, but may also occur for the other two. Ie, wouldn't it be better to refer to this in the model document, saying that the value returns a full URI as well as a compacted URI when possible? Conversions may then use what they want.

@iherman https://github.com/w3c/csvw/pull/362#issuecomment-80944032

> See my [previous reply](https://github.com/w3c/csvw/pull/362#issuecomment-80943074): I think the compaction should be described at one place, then this can be incorporated. So not done for the moment.

@gkellogg https://github.com/w3c/csvw/pull/362#issuecomment-81174308

> Because of the differences in how values and properties are compacted (with or without being like @vocab in JSON-LD), it would be difficult to do this as part of the cell model. However, the algorithm is pretty simple, and I can create a section in CSV2JSON on compacting IRIs, but probably best to wait until outstanding PRs are merged.
> 
> Basically, for properties and values of @type:
> -  If the URL exactly matches a term in the context, replace the URL with that term.
> -  Otherwise, if the the context has a term who's URI definition is a prefix of the URL, replace the URL with a prefixed name formed from the term, a ':', and the remainder of the URL after the URL prefix.
> 
> For all other values which are a URL:
> -  If the the context has a term who's URI definition is a prefix of the URL, replace the URL with a prefixed name formed from the term, a ':', and the remainder of the URL after the URL prefix.
> 
> Note that this does not do any document-relative compaction of values.

@iherman https://github.com/w3c/csvw/pull/362#issuecomment-81200989

> Hm. I do not really understand why there would be a difference. We do not have a @vocab in the metadata; the compaction of the URI-s are the same everywhere and are based exclusively on the predefined prefixes that are known in advance. It is of course a question whether this would be useful for RDF (probably not), but may be for other conversions. 
> 
> Also, Do we allow for fragmentbid-s or URI-s with query parts to be compacted? I guess probably yes, but this should be made clear...  

@gkellogg https://github.com/w3c/csvw/pull/362#issuecomment-81399374

> Properties and @type are vocabulary-relative, @id is document-relative. @id cannot take a term as a value, only a URI or prefixed name. Properties and @type can take a type (obviously, as intended for properties in particular), or a URI or prefixed name. A relative URL in property/@type is relative to @vocab, if defined. On @id it's relative to the document. For the details, see JSON-LD.
> 
> As a result, a value of a property or @type can compact to a term, but not an @id (or other use of a valueUrl). That's just the way it is. We could of course, not compact to terms at all, in which case if we had http://www.w3.org/ns/csvw/Table, it would compact to 'Table:rather than justTable`, but that would be odd.
> 
> Currently, I don't specify compacting URLs to generally be document relative (CSV2JSON has a special case for this). But, there's no reason that fragment-ids or query parameters would be excluded here. If we choose to compact to relative URIs (not sure there's a need for this), then it would simply be by removing the document URL prefix, if it ends in "/" or "#"; otherwise, probably not worth doing. I'm not sure we really need to do this, though.

**Comment by iherman** [comment]
@gkellogg wrote:

> Properties and @type are vocabulary-relative, @id is document-relative. @id cannot take a term as a value, only a URI or prefixed name. Properties and @type can take a type (obviously, as intended for properties in particular), or a URI or prefixed name. A relative URL in property/@type is relative to @vocab, if defined. On @id it's relative to the document. For the details, see JSON-LD.

For our users the reference to JSON-LD does not help.

B.t.w., I am not even sure I understand. All these properties generate an absolute URL. That part is independent of compaction, it is done by the template expansion. The compaction should be restricted to the predefined prefixes that we have (we have no `@vocab`). So if the `@id` value is, by some coincidence, compacted with a prefix that happens to be predefined, so what? It is still correct, isn't it? In other words, I am not sure I follow your argumentation. But... see below

> As a result, a value of a property or @type can compact to a term, but not an @id (or other use of a valueUrl). That's just the way it is. We could of course, not compact to terms at all, in which case if we had http://www.w3.org/ns/csvw/Table, it would compact to 'Table:rather than justTable`, but that would be odd.

I presume what you mean by 'term' are the terms as defined in the metadata document (again, we have no notion of @vocab here, so that is the only one that makes sense). Let me then restrict this while issue to a simpler case:
- we do compaction on `propertyUrl`-s only (and we do not touch `aboutUrl` and `valueUrl`)
- compaction means replacing a URL with a prefixed case for all the prefixes defined in the initial context, and nothing else
- `rdf:type` is exchanged against `@type`

That covers, in my view, the basic situation whereby we get "proper" names in the pure JSON output; if the user uses aboutUrl and valueUrl, he/she counts on URL-s anyway, so that is it. The issue around `csvw:Table` does not really arise in practice; I do not expect anybody using `propertyUrl` for `csvw` terms, so it is not a real issues.

If we accept these restrictions, I maintain that compaction is something that other serializations can also use, so it is worth defining that in general.

**Comment by 6a6d74** [comment]
@gkellogg, @iherman ... it sounds sensible to have the URL compaction algorithm called out separately. If I follow, we're suggesting that URL compaction is limited to properties (like `schema:url` used in the [tree-ops-ext standard output example](http://w3c.github.io/csvw/csv2json/#example-tree-ops-ext-standard-json)) and values of `@type` (like `oa:Annotation` from the `notes` - also in the [tree-ops-ext standard output example](http://w3c.github.io/csvw/csv2json/#example-tree-ops-ext-standard-json)).

I'm happy with this.

**Comment by JeniT** [comment]
@gkellogg to update the metadata document with a definition of compaction that includes compaction to terms (and `rdf:type` to `@type`). @6a6d74 to update the mapping to JSON.

**Comment by 6a6d74** [comment]
awaiting addition of url compaction section in metadata doc - then I can reference this from the csv2json doc

**Comment by gkellogg** [comment]
In your hands now @6a6d74. Note PR #373 that includes the change to metadata.

**Comment by 6a6d74** [comment]
@gkellogg added some clarifications in PR #373 ... we're all good now. Closing issue.
