### ISSUE TITLE
Organization of the rows and cells in the metadata document

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#37]
At the moment, the organization of row and cell level metadata is organized as follows:

``` javascript
 "schema":
    "rows": [{
        "row": "index of row"
   ],[
       ...
  ]},
```

this structure seems to be very inefficient for implementations if the row level metadata array is very large and there are also a large number of rows in the data. Wouldn't it be more efficient to use something like:

``` javascript
"schema":
   "rows": {
     "index1" : { ... }
     "index2" : { ... }
   }
```

**Comment by JeniT** [comment]
At the October 2014 F2F at TPAC we decided not to support row-level metadata in the schema.
