### ISSUE TITLE
JSON transformation should use native datatypes where possible

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#370]
The current CSV2JSON algorithm does not consider the datatype of  value when generating output. When a numeric or boolean datatype is used, the value should use a native JSON representation.

**Comment by 6a6d74** [comment]
@gkellogg - I think this is covered. See section http://w3c.github.io/csvw/csv2json/#datatypes ... this is referenced from the section on processing cell values. Re-reading this, I have made the link from the processing of sequences of values clearer in the current version I am working on.

**Comment by gkellogg** [comment]
I believe you're right, it just wasn't called out using separate steps of the algorithm; I'm glad that's cleared up.

**Comment by 6a6d74** [comment]
no worries. speak tomorrow.
