### ISSUE TITLE
language setting in columns, rows, etc...

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#38]
At the moment it is possible to set "@language" in the context section. However, wouldn't it be necessary to be able to set "language" on the column, row, and cell level, too? A predominantly English table may have a column (or a row) in French...

**Comment by gkellogg** [comment]
It's also possible to set @language for a term, which would handle the column use-case as well. Row could possibly be handled (through JSON-LD), by creating an row-specific context setting @language; in JSON-LD, I believe, each row maps to a JSON-LD node definition, which can have it's own context with supplements the document-specific context..

**Comment by iherman** [comment]
On 12 Oct 2014, at 22:42 , Gregg Kellogg notifications@github.com wrote:

> It's also possible to set @language for a term, which would handle the column use-case as well. Row could possibly be handled (through JSON-LD), by creating an row-specific context setting @language; in JSON-LD, I believe, each row maps to a JSON-LD node definition, which can have it's own context with supplements the document-specific context..

First of all, is indeed possible to set a @context separately for rows and also for cells? If yes, I must say I wonder whether we should go down that route. The metadata document is already fairly complex for my taste, and this would add to the complication; I would like to see a real use case where this is really necessary.

Also: at the moment, language is set through @context/@language. Even if I go along what you say, eg, with a row level @context, I find it too complex for the user base. Just as it is possible to set a "datatype" for a row or a cell, I would expect to be able to do the same with "language".

(My issue clearly comes from the implementation that I am playing with. Locating a specific property for a cell is essential when generating a value for a cell, and the simpler we make it the better is...)

Thanks

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
GPG: 0x343F1A3D
WebID: http://www.ivan-herman.net/foaf#me

**Comment by JeniT** [comment]
The `@context` `@language` is for the default language within the metadata file, not for the language of the data within the CSV. The `language` property on table and on column descriptions provides the language of the content of the CSV.
