### ISSUE TITLE
name/title validation question

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#389]
The `name` property contains the following assertion:

> During validation, if there is no `title` property and the column already has a `title` annotation then validators **must** issue a warning if the existing `title` annotation does not match the `name` specified in the column description.

When validating, metadata has been merged, so knowing the difference between a property value and an annotation is quite difficult. Also, it is not clear how to compare a title annotation with a specified name; does this include unescaping name?

Perhaps this should say that there MUST be a title value in the merged metadata matching the the name property where the title is escaped prior to checking.

As an aside, I think many of our examples would result in a validation warning, as the name often does not directly correspond to a title. Perhaps we should re-think this requirement?

**Comment by iherman** [comment]
> On 22 Mar 2015, at 20:34 , Gregg Kellogg notifications@github.com wrote:
> 
> The name property contains the following assertion:
> 
> During validation, if there is no title property and the column already has a title annotation then validators must issue a warning if the existing title annotation does not match the name specified in the column description.
> 
> When validating, metadata has been merged, so knowing the difference between a property value and an annotation is quite difficult. Also, it is not clear how to compare a title annotation with a specified name; does this include unescaping name?

I am not sure what the origin is of this restriction. As a first reaction, I simply do not understand why we have it.

> Perhaps this should say that there MUST be a title value in the merged metadata matching the the name property where the title is escaped prior to checking.

Even this: why? Why isn't it perfectly o.k. to produce a metadata where a cell has a (set of) title(s), but the name is a different string? After all, the role of name in the metadata is some sort of a programming language variable, used by, eg, templates, and it does not really have a 'user facing' value (eg, for visualization). The only relationship between title and name is that the former produces a value for the latter in the default case.

I would reconsider any warning or error here.

> As an aside, I think many of our examples would result in a validation warning, as the name often does not directly correspond to a title. Perhaps we should re-think this requirement?

Case in point. The fact that our examples lead to warning question the requirement itself. In my view, we should remove it altogether.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
I think this is a hangover from before the approach was reframed to be about merging metadata. I believe that the validation around the titles is now done during the merge, such that this text can be simply dropped, and I propose that we do this.

**Comment by iherman** [comment]
> On 25 Mar 2015, at 15:18 , Jeni Tennison notifications@github.com wrote:
> 
> I think this is a hangover from before the approach was reframed to be about merging metadata. I believe that the validation around the titles is now done during the merge, such that this text can be simply dropped, and I propose that we do this.

+1

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704
