### ISSUE TITLE
What should be generated for a value with datatype in the case of JSON

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#39]
There are some alternatives.
1. either the datatype value is ignored, i.e., the original (string) value is used as a value
2. like before but an extra `@context` entry is generated denoting the datatype (but that may not work because a cell-level metadata may set a specific datatype for a cell, and a `@context` would be valid for all values for a given key)
3. a JSON object is generated of the form (borrowed from, and compatible with, JSON-LD):

``` javascript
"predicate" : { 
  "value" :  -- the original value of the cell as a string --
  "datatype: -- the datatype set for that specific cell --
}
```
1. One can also imagine a combination of alts. 2 and 3: set a generic value for a column as part of a `@context` structure, and then store the data as an object only if there is a deviation from the `@context`.

_Con alts. 2 or 3_. means that we make the `@context` structure as integral part of the output almost every time; for a non-RDF, i.e., non-JSON-LD usage that seems to be an overkill.

_Con alt. 3_. The generated JSON increases in size, which may be an issue for large tables.

Personally, I would propose to go with #3.

**Comment by JeniT** [comment]
Given that we're aiming for a simple JSON mapping for simple JSON users, I think the first option above is the right one: map to a simple string, number, boolean (or `null`) as appropriate for the datatype.

**Comment by iherman** [comment]
On 31 Oct 2014, at 15:56 , Jeni Tennison notifications@github.com wrote:

> Given that we're aiming for a simple JSON mapping for simple JSON users, I think the first option above is the right one: map to a simple string, number, boolean (or null) as appropriate for the datatype.

Agreed.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
GPG: 0x343F1A3D
WebID: http://www.ivan-herman.net/foaf#me

**Comment by iherman** [comment]
Put it on the agenda to close the issue formally.

**Comment by danbri** [comment]
See http://www.w3.org/2014/11/12-csvw-irc#T15-29-39

**Comment by 6a6d74** [comment]
Discussed in meeting 12-Nov-2014 ([Minutes](http://www.w3.org/2014/11/12-csvw-minutes.html)); summary ...

This issue is similar to #59 ...

RESOLUTION: for simple JSON we map to a simple string, number, boolean (or null) as appropriate for the datatype

Issue not closed as mapping doc not yet updated.

**Comment by 6a6d74** [comment]
csv2json doc now updated; only JSON primitives are used.
