### ISSUE TITLE
Alternative diagram for the datatypes?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#390]
Att: @JeniT  @gkellogg 

I must say I was always a bit bothered by the datatype diagram in the metadata document. It is a good idea to have a diagram for the datatypes instead of the long list we had, but the XML Schema diagram includes a bunch of (for us) irrelevant information that may be a problem for the reader (and the diagram is not really pretty).

I prepared an alternative diagram which we may want to use. It is in SVG. (Originally created by Mac Keynote, export into PDF and the PDF converted into SVG by Adobe. A bit convoluted flow, but I never found a better way:-(. It includes only those datatypes that we use, it includes the aliases that we defined, and the additional xml/json/html datatypes. And I believe it looks better...

I have put it up in a separate branch, you can have a look:

https://rawgit.com/w3c/csvw/datatype-diagram/metadata/index.html#datatypes

I have also removed part of the first bullet items in the explanation text which essentially listed what part of the original diagram was not relevant...

if you agree it is a better alternative, I can do a PR (or, well, you guys can just merge directly without a PR).

I was actually wondering whether some sort of a diagram for our metadata terms would not be useful... 

Actually, I was also wondering whether some kind of diagram

**Comment by 6a6d74** [comment]
@iherman - the new diagram looks nice and clean. +1 from me to include this in the metadata doc.

**Comment by gkellogg** [comment]
I think the diagram is much better. However, it leaves out NMTOKEN.

I'm +1 for a PR.

A diagram for metadata terms might be nice too! Too bad your tool-chain is so cumbersome; I could do one using OmniGraffle, which is probably an easier tool-chain.

**Comment by iherman** [comment]
> On 23 Mar 2015, at 22:52 , Gregg Kellogg notifications@github.com wrote:
> 
> I think the diagram is much better. However, it leaves out NMTOKEN.
> 
> I'm +1 for a PR.
> 
> A diagram for metadata terms might be nice too! Too bad your tool-chain is so cumbersome; I could do one using OmniGraffle, which is probably an easier tool-chain.

I think my own characterization was erroneous. I use Keynote as an editing tool because I am familiar with it. If I did the editing in Adobe Illustrator, then I would have a simple tool-chain; your comment pushed me to really try to learn AI! (I do not have OmniGraffle; I do not think my institute would pay for it while they put AI on my machine...)

I will take care of a newer version with NMTOKEN and a PR later today.

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
Diagrams have been now merged into the main branch. Closing the issue.
