### ISSUE TITLE
classification of metadata properties

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#391]
I have looked at the list of properties we define in the metadata. The document classifies these in Array, Link, URI Template, etc, categories. However, 
- It should be clearly said that this categorization is not relevant for the common properties or, put it another way, those properties should be considered as atomic in this respect
- `@context` is explicitly referred to as an array property, but there is no classification for `@id`, `@type`, `@language`, or `@base`. It is, sort of, o.k., because these are JSON-LD properties that we inherit, but it should be said...
- there are three properties that should say that they are atomic and, at this point, it is not in the text, namely `pattern`, `groupChar` and `decimalChar`

**Comment by gkellogg** [comment]
- Common Properties – Probably need to define it as an array type, similar to notes.
- Given the change to merging and normalization, I think we can change `@context` to an atomic property.
- `@id` should be a link property and `@type` an atomic property.
- It's probably not correct to describe `@language` and `@base` as properties, as they're part of `@context` and the normal rules don't apply. Perhaps we should change the _Top-Level Properties_ section to something about `@context`, as the really aren't properties in the same sense that others are.
- To describe `pattern, groupChar, and decimalChar` as properties would require defining the kind of object they're contained in. They are really part of the `format` property which is an atomic property. For this, we'd need to define a _format description object_ for just this purpose.

Many of these changes should probably wait until PR #376 is merged, as that affects some of the merge language.

**Comment by gkellogg** [comment]
Also `reference` property.

**Comment by JeniT** [comment]
`@language` and `@base` can be described as atomic properties, and should be added to the diagram.

**Comment by gkellogg** [comment]
Because the value space of _Common Properties_ is pretty wide open, categorizing it doesn't really help. In any case, they're well documented.

**Comment by iherman** [comment]
- Looking at the latest version (also at the basis of the new diagram): `@context` is still identified as an array property in the text (and in the diagram); hopefully that is all right. `@base` and `@language` also added
- I had to add a full block of properties on Datatype Description that was missing in the old diagram; that covers these missing ones

Handles via PR #407
