### ISSUE TITLE
ForeignKey referencing schema challenges

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#393]
If a foreignKey reference uses a tableSchema, the spec says to compare the tableSchema property values. However, during merging, the tableSchemas are normalized copying them into place thus requiring deep object comparison to determine if they are equal.

I suggest the following change: Schemas are compared using the `@id` property value of the schema. And, that when normalizing a tableSchema by dereferencing a link, that that link value be used as the value of `@id` (if not otherwise set) when creating the local version of the Schema. This would make comparison much easier.

**Comment by gkellogg** [comment]
Also, in the case of a Foreign Key, `tableSchema` is a _link property_ while everywhere else it is an _object property_. It might be better to re-name this to something like `schemaReference` as it should not be loaded when encountered, and can't be in an object form.

**Comment by iherman** [comment]
All these proposals seem to be fine to me.

Give me the word when the property diagram should be changed to add  `schemaReference` (as a link property).

**Comment by JeniT** [comment]
+1

**Comment by gkellogg** [comment]
We have the same problem with the `columns` property, which is different than in `Schema`. Without objection, I'll change this to `columnReference`.

/cc @iherman @JeniT

**Comment by iherman** [comment]
Changed the diagram to `schemaReference`. Handled via PR #407

**Comment by gkellogg** [comment]
The diagram still has an issue: the Foreign Key Definition lists `columns` and `reference`, and it should be `columnReference` and `reference` with `columnReference` being a _column reference property_ color.

**Comment by iherman** [comment]
Shoot! I missed that one.

The diagram has been updated in the main branch. Closing.

/Cc @gkellogg
