### ISSUE TITLE
Normalization needs to expand foreignKey resource & tableSchema

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#398]
The Normalization mechanism does not provide for normalizing foreignKey values as references is not any kind of defined property. Even if it were an _object property_, the algorithm doesn't provide for descending into it to normalize `resource` or `tableSchema`. As `foreignKeys` is an array property, it may be easiest to simply provide a special case for this in the algorithm.

**Comment by JeniT** [comment]
Agreed on telcon: normalisation language needs to include normalising properties of objects, including properties of objects in arrays.
