### ISSUE TITLE
RTL examples to the document

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#4]
Yakov collected some use cases for RTL type CSV files:

http://lists.w3.org/Archives/Public/public-csv-wg/2014Mar/0229.html
http://lists.w3.org/Archives/Public/public-csv-wg/2014Mar/0227.html

I believe these should be added to the Use Case document in some form. Also, these may have a direct effect on the model document, see:

http://lists.w3.org/Archives/Public/public-csv-wg/2014Mar/0232.html

**Comment by ericstephan** [comment]
Thank you Ivan!

Eric

**Comment by iherman** [comment]
The use case has been added, see:

http://w3c.github.io/csvw/use-cases-and-requirements/index.html#UC-SupportingRightToLeftDirectionality
