### ISSUE TITLE
(Proofreading) list of rows in the table?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#408]
[Section 3.2](http://w3c.github.io/csvw/syntax/index.html#tables) of the syntax document still lists:

> rows — the list of rows in the table

Isn't this a leftover from a previous state? We do not have separate rows in the annotations any more.

(I did not want to go ahead and change this one)

**Comment by iherman** [comment]
Actually, I see that 'cells' also appear in section 3.3, alongside source number, number, etc. Reading this let me revise my comment a little bit. What section 3 describes is the annotations that are _either_ explicitly given by the user _or_ that can be derived by a processor. rows, cells, etc, belong to the latter. And that is then fine, but maybe it is worth adding a note into this section to this effect, ie, that not all of these properties can be set explicitly by the metadata as specified in the metadata specification.

**Comment by gkellogg** [comment]
Yes, `rows`, and `cells` are part of the annotated table model. You're correct that annotations may be specified explicitly within the metadata, derived from the tabular data file, or determined through the course of processing. I'll add something to the introduction to section 3 about this, but @JeniT is really the keeper of the data model, and she'll have the final say.

**Comment by iherman** [comment]
Has been settled through merge of PR #417. Closing issue.
