### ISSUE TITLE
(Proofreading) "UM playing the role of UM"

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#409]
In [section 5.1](http://w3c.github.io/csvw/syntax/index.html#creating-annotated-tables) the second point for the process starting with the metadata file says:

> For each table in UM in order, run the steps for a tabular data file using the url from the table with UM playing the role of UM to create one or more annotated tables

I must admit I do not understand this; what does "UM playing the role of UM" means? Should be something like

"For each table in UM in order, run the steps for a tabular data file using the url from the table with the corresponding table description from within UM playing the rule of UM"

It still a bit messy. I would propose to use an UM<sub>T</sub> in the rest of steps 2.X

**Comment by iherman** [comment]
Also: the text in 2.X refers to `FM` without specifying it. yes, in the previous part (when starting with a file) `FM` is defined, but is it valid here? Actually, should it be included? Isn't the usage of `FM` here in contradiction with the Note at the end of the section (which says 'no other metadata files will be retrieved')?

**Comment by gkellogg** [comment]
Note that it's not just the table description from the original UM which is used as UM for the tabular data part, as a merge will end up re-creating a Table Group. I'll use subscripting to make the different roles clear.
