### ISSUE TITLE
GK read through of CSV2JSON

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#419]
- [x] Introduction should clarify that, while the resulting JSON has the form of JSON-LD, as there is no `@context`, it will not be interpreted that way unless one is provided to a JSON-LD processor. The intention is not to create JSON-LD through this conversion, but well-known forms are used.
- [x] I believe we decided to use references to the github version of the referenced file, and correct these when publishing. This allows all files viewed from gh-pages to consistently reference each other; it also ensure that Editors Drafts refer to Editors Drafts, rather than a (likely obsolete) TR version. This is the practice used in tabular-metadata and tabular-data-model.
- [x] aboutUrl, propertyUrl and valueUrl refer to the definition of the URI Template property for how they are evaluated, however this reference does not describe such evaluation. They should reference the property definition for each instead (e.g., <#cell-aboutUrl>.
- [x] I believe we stopped using the _CSV+_ designation, and instead use that _tabular data file_; this probably should have a definition in the model document.
- [x] _Readability_: The normal viewport of a browser does not show content without scrolling. This is likely due to examples when create long lines. Such examples should probably have their own scrollable region. (Note, this is a general problem across the specs, and I'll look for a generic solution).
- [x] There is an HTML syntax error on or about line 1220 where there are 12 columns and should be 11. There are numerous other warnings when a table row has 11 rows but the table was created with 12 rows.

**Comment by gkellogg** [comment]
Extra column solved in 26a60430e06402476afb0436b3091002922038b9.
Readability issues solved in f6911ce32eb6fca77a5b79d7d481491756a96f97

**Comment by iherman** [comment]
CSV+ issue handled through #423

**Comment by iherman** [comment]
@gkellogg on 

> aboutUrl, propertyUrl and valueUrl refer to the definition of the URI Template property for how they are evaluated, however this reference does not describe such evaluation. They should reference the property definition for each instead (e.g., <#cell-aboutUrl>.

I am not sure what you mean. The <#cell-aboutUrl> does not say anything on evaluation in the metadata document, only section 4.1.3 does, which is on the general URI Template property. This is what we refer to in the csv2\* documents...

/Cc @6a6d74 ; this is also valid for the companion issue #421

**Comment by iherman** [comment]
@gkellogg on

> Introduction should clarify that, while the resulting JSON has the form of JSON-LD, as there is no @context, it will not be interpreted that way unless one is provided to a JSON-LD processor. The intention is not to create JSON-LD through this conversion, but well-known forms are used.

I respectfully disagree. There is a note at the beginning of the document that says:

> The conversion of CSV content to JSON is intended for web developers who need not care about the complexities of RDF [rdf11-concepts]. Where the formality of RDF is required, [csv2rdf] provides the procedures for mapping from CSV content to RDF which may be serialized to [json-ld].

It is therefore clear that this conversion is irrelevant for the purpose of JSON-LD. I do not think any more disclaimer is necessary...

/Cc @6a6d74

**Comment by 6a6d74** [comment]
+1 to @iherman's comment about proposed changes to the introduction concerning JSON-LD  - I propose no change to the introduction.

**Comment by 6a6d74** [comment]
Having read @gkellogg's comment about the uri template properties & re-read the doc I think it was confusing. I've fixed this in PR #427 ... new text like:

**aboutUrl**
_aboutUrl_ is the evaluation of the <a href="http://www.w3.org/TR/tabular-metadata/#dfn-uri-template-property">URI template property</a> <a href="http://www.w3.org/TR/tabular-metadata/#cell-aboutUrl"><code>aboutUrl</code></a> for the current _cell_.

**Comment by 6a6d74** [comment]
> I believe we decided to use references to the github version of the referenced file, and correct these when publishing. This allows all files viewed from gh-pages to consistently reference each other; it also ensure that Editors Drafts refer to Editors Drafts, rather than a (likely obsolete) TR version. This is the practice used in tabular-metadata and tabular-data-model.

@gkellogg - I missed this agreement (!) ... so used the TR references. I'll change this back to Github references now ...

**Comment by 6a6d74** [comment]
Fixing references to github docs (not TR) in PR #428. Now we'll have to revert for publishing - but at least this will be consistent for all the docs.

**Comment by 6a6d74** [comment]
@gkellogg - are you satisfied regarding the "no-change to introduction" and that the other issues have been addressed. If so, please close this issue.

**Comment by gkellogg** [comment]
@iherman, that statement pretty much describes JSON-LD as well. The fact is, what we generate does look like JSON-LD, and it may confuse some into thinking that is the intent. However, if I'm the only one with this concern, then I won't press the issue.

**Comment by akuckartz** [comment]
If something looks like JSON-LD, then it should be JSON-LD. Was any reason given for a different view?

**Comment by iherman** [comment]
@akuckartz it is not incompatible with JSON-LD. Sorry for the double negative, but it is really the point. If an author wants JSON-LD: use the rdf conversion and serialize it in JSON-LD. The audience for the JSON conversion is different.

For example, the JSON conversion will drop a lot of 'knowledge' that is in the metadata but a plain JSON cannot express: datatypes and their intricacies, language tags, or differences between literals and URI-s.

**Comment by iherman** [comment]
@gkellogg this was the last checkbox; closing the issue.
