### ISSUE TITLE
Locating additional metadata when originally starting from a metadata document

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#42]
What should processors do if they have been passed a metadata file and located a CSV file from that metadata file. Should they still check for metadata files related specifically to the CSV file itself? For example, say that an application has been pointed at a metadata file at `http://example.org/metadata.json` which references `http://example.org/toilets.csv` but there is also a metadata file at `http://example.org/toilets.csv-metadata.json`. If the processor had been originally pointed to `http://example.org/toilets.csv` then it would have located the file-specific metadata at `http://example.org/toilets.csv-metadata.json`, but coming via `http://example.org/metadata.json` means that file-specific metadata is skipped.

**Comment by iherman** [comment]
That is the first time I hear from this "direction"... We always started (at least up to now) from a CSV file, not from a metadata file. Ie, one sees the metadata.json file, then it is up to the application to decide whether a full process of handling the CSV file is warranted (which will, hopefully, lead to the metadata.json file, too, eventually)...

**Comment by 6a6d74** [comment]
@iherman: this covers the case where a third party is publishing metadata about a resource (see [use case "making sense of other people's data"](http://w3c.github.io/csvw/use-cases-and-requirements/#UC-MakingSenseOfOtherPeoplesData))

In such a situation, the third party may wish consumers to override any metadata published locally with the data file (identified by relative path or http header etc.)

**Comment by iherman** [comment]
Ouch, you are right...

In that case, getting back to the original issue raised by @JeniT: I think what say is that, when we combine metadata files coming from different sources, the right side wins, right? I.e., let us say `m1.json` and `m2.json` are retrieved, as metadata, in this order. `m1.json` is: 

`{
"foo" : "foo-value1",
"bar": "bar-value"
}`

and  `m2.json` is:

`{
"foo" : "foo-value2",
"baz": "baz-value"
}`

then the combined metadata for the csv file is:

`{
"foo" : "foo-value2",
"bar" : "bar-value",
"baz": "baz-value"
}`

(I think we referred to [jQuery's extend](http://api.jquery.com/jQuery.extend/)) as an example.)

If the goal of starting with an external metadata to get to the data is what you describe in the use case, what this suggests is that the starting metadata is the last one to be used, overriding all local settings, if any.

**Comment by 6a6d74** [comment]
I think so ...

**Comment by JeniT** [comment]
This issue isn't about how to combine metadata files, it's about whether it should be specified that processors should look for other metadata files (ie those which would have been located if you'd started from the CSV file).

The possibilities are one of:
1. when you start from a metadata file, that (and anything explicitly imported) is the only metadata that you know about - that would mean that third parties would need to explicitly import any of the metadata that would otherwise be automatically found; or
2. when you start from a metadata file, processors must also follow the rules in the syntax document (ie HTTP Link header, URL hacking) to identify additional metadata for each referenced CSV file

My gut is to go with the first, but I don't have a particularly rational reason for that.

**Comment by iherman** [comment]
Actually, my gut goes more for the second option, in which case the issue of what priority the different metadata files have does arise... I am not sure why we would 'allow' to so dramatically override the author's metadata referred to through a Link header (which, I would expect, is the metadata very closely associated with the data itself).

B.t.w., I know we had a discussion on that at the TPAC but the current document do not have (yet?) any reference to that import of metadata. (Which I am not sure I like, but that is a different discussion...). This also influences the choice...

**Comment by 6a6d74** [comment]
My thought is that @JeniT's option number 1 is the most appropriate. The use case that we're trying to support is the publication of metadata by a third party. I think that it is reasonable to assume that this breaks the 'metadata-file-lookup-chain'; they will want to publish metadata that supports their perspective which is likely to be different to that of the original publisher.

Here's my rationale:
- if the third party _wants_ to include original metadata then they can explicitly import it - or copy parts of the original metadata into their metadata description
- the complexity of the metadata-file-lookup-chain is likely to lead to confusion from 3rd parties who are less aware of what the originator has published (e.g. "why does my metadata do _x_ when I specified _y_)
- [most important] the originator could republish their metadata resulting in unwanted side-effects for the third party

What ever the choice (& I think no. 1 is better), the REC needs to be clear on how a 'metadata-first' interaction works.

**Comment by iherman** [comment]
@6a6d74, you may be right. I yield to the 1st option.

**Comment by JeniT** [comment]
Things have changed a bit since we last discussed this, particularly wrt how the metadata documents are automatically collated and merged.

Proposed resolution: Starting from a metadata file is equivalent to having [Overriding metadata](http://w3c.github.io/csvw/syntax/#overriding-metadata). All the referenced resources are then taken as starting points to discover other metadata (based on the [existing description](http://w3c.github.io/csvw/syntax/#locating-metadata)) and these metadata documents are [merged](http://w3c.github.io/csvw/metadata/#merging-metadata) in order to process those resources.

**Comment by iherman** [comment]
@JeniT I do not follow this. Let us take it to the F2F...

**Comment by gkellogg** [comment]
+1 @JeniT; that's how my implementation works.

**Comment by iherman** [comment]
@JeniT, I am not sure whether what you say is the same as what @gkellogg and I have written down in issue #193, more specifically, in https://github.com/w3c/csvw/issues/193#issuecomment-73209713 (second part). But there is a clear proposal there.

**Comment by JeniT** [comment]
Resolved at Feb F2F: conceptually there is only one user-supplied metadata file, which implementations might generate from merging multiple metadata files, some of which may be provided by third parties. #193 covers what happens there.

Editor action: It would be good to use UCR eg 22 to illustrate the process of using a third-party metadata file, in an example.

**Comment by danbri** [comment]
See http://www.w3.org/2015/02/12-csvw-irc#T13-14-22
