### ISSUE TITLE
GK read through of CSV2RDF

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#421]
- [x] I believe we decided to use references to the github version of the referenced file, and correct these when publishing. This allows all files viewed from gh-pages to consistently reference each other; it also ensure that Editors Drafts refer to Editors Drafts, rather than a (likely obsolete) TR version. This is the practice used in tabular-metadata and tabular-data-model.
- [x] aboutUrl, propertyUrl and valueUrl refer to the definition of the URI Template property for how they are evaluated, however this reference does not describe such evaluation. They should reference the property definition for each instead (e.g., <#cell-aboutUrl>.
- [x] I believe we stopped using the _CSV+_ designation, and instead use that _tabular data file_; this probably should have a definition in the model document.

**Comment by iherman** [comment]
CSV+ issue handled through #423

**Comment by iherman** [comment]
> On 27 Mar 2015, at 24:18 , Gregg Kellogg notifications@github.com wrote:
> 
>   •  I believe we decided to use references to the github version of the referenced file, and correct these when publishing. This allows all files viewed from gh-pages to consistently reference each other; it also ensure that Editors Drafts refer to Editors Drafts, rather than a (likely obsolete) TR version. This is the practice used in tabular-metadata and tabular-data-model.

Did we really decide this? I do not remember. I am not sure I like it, though; it makes our publishing process more complicated and, mainly, error prone:-(

Is there a way to add a script respec that would do that when publishing?

Ivan

>   •  aboutUrl, propertyUrl and valueUrl refer to the definition of the URI Template property for how they are evaluated, however this reference does not describe such evaluation. They should reference the property definition for each instead (e.g., <#cell-aboutUrl>.
>   •  I believe we stopped using the CSV+ designation, and instead use that tabular data file; this probably should have a definition in the model document.
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
Fixed remaining two issues in PR #429 ... closing issue.

**Comment by gkellogg** [comment]
See the [publishing process](https://github.com/w3c/csvw/blob/gh-pages/publishing_process.md); this makes specs internally consistent and provides a single time to resolve references to /TR/. It could be made simpler if our directory structure matched /TR, but it's straightforward in any case.

**Comment by gkellogg** [comment]
I could help create a script to do this, as well as other necessary parts of creating a publishing snapshot.
