### ISSUE TITLE
IH Read through the Metadata document

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#426]
Cc @gkellogg @JeniT : here are the issues I've ran into.
- [x] [Section 3](http://w3c.github.io/csvw/metadata/#annotating-tables) says: "Metadata documents contain descriptions of groups of tables, tables, columns, rows, cells and regions". However, the document does _not_ talk about regions at all. (The word 'region' appears in this section only.) I would propose to remove any reference to regions.
- [x] [Section 3](http://w3c.github.io/csvw/metadata/#annotating-tables) includes Example 3 and it also says, after the example: "The datatype and format properties are inherited properties that affect the value of each cell in that column." But this is not clear at all from the example at this point of reading. We should probably have an extract of a schema with a column description that shows inheritance.
- [x] [Section 4](http://w3c.github.io/csvw/metadata/#metadata-format) says, in the second paragraph "A description object is a JSON object that describes a component of the tabular data model (a table group, a table, a column, a row or a cell) and has one or more properties are mapped into properties on that component.". This metadata specification does not define any JSON object to to describe a row or a cell. Somehow we should make a difference between what is _definable_ through a JSON object in the metadata file, and what is, conceptually, generated in the annotated table. This issue is similar to #408. 
- [x] [Section on naming properties](http://w3c.github.io/csvw/metadata/#names-of-common-properties) I wonder whether it is worth adding a note making it clear that the prefixes defined in the RDFa 1.1. Initial Context are periodically _extended_, and refer to that document for further details. Note that, at this moment, the prefix 'oa' is, formally, not yet part of the initial context but, eventually, it will be by virtue of becoming a Rec...
- [x] [Optional properties for table groups](http://w3c.github.io/csvw/metadata/#optional-properties), tableDirection: lots of details are glossed over here, for good reasons; I think it would be worth adding a reference to section 5.2.1 on bidirectional tables to see all the details.
- [x]  A general stylistic comment: in a sentence like "The value of this property becomes the value of the id annotation for the table group" the string 'id' refers to the model document's annotation. The current styling is a dotted underline which is hardly visible on the screen for such a short name, and one does not realize that this is a really an external definition. I wonder whether the style should not be changed to something more visible...
- [x]  A general organizational suggestion: At the moment, the order within section 4 is Table Groups, Tables, Dialect Description, Transformation Defininions, Schemas, Columns, Inherited properties, Datatypes. For me, it is more logical to have Shcemas and Columns (and maybe even Inherited properties) follow the Tables; These provide, in many respect, the "backbone" of the metadata. Dialects and Transformation definitions are somewhat second order (both are, after all, annotations for non-standard, non-specified features), so I would have expected to see those at the end of the the whole list of categories. I also wonder whether section 4.12 (Parsing Cells) should not be a top level section (ie, becoming section 5), so that section 4 cleanly defines the various metadata that we have.
- [x] Stylistic consistency: some of the lists have a full stop at the end of the various entries, e.g., in the dialect description; for some others, lists do not have a full stop, e.g., in 4.1.3 for the template variables. We should try to be consistent within the document (I do not really care which format we use.)
- [x] [Definition of textDirection in Section 4.10](http://w3c.github.io/csvw/metadata/#inherited-properties) something should be said if that flag is not present. I would think a reference to the relevant section in the model document may be enough on how the unicode thing works...
- [x] [Definition of datatype in Section 4.10](http://w3c.github.io/csvw/metadata/#inherited-properties) says: "it is a term defined in the default context representing a built-in datatype URL". For a non JSON-LD reader this is a bit cryptic. Isn't it simpler to say that if it is a string, it must be one of the terms defined in 4.11.1? The fact that the JSON-LD context trasnforms that into a URL is irrelevant for most; it can be a remark added to 4.11.1, in fact.
- [x] [Normalization examples](http://w3c.github.io/csvw/metadata/#examples-2) the text before Example 40 is a bit cryptic. I _guess_ what is meant is that if the original metadata is what is given in example 40, then the value of dc:title does not change, the only effect of the normalization is the disappearance of `@context`. This should be made more explicit I believe.
- [x] [Detailed merge example](http://w3c.github.io/csvw/metadata/#example-1) I wonder whether something can be done on the styling of the intended examples so that the 'EXAMPLE XXX' would not be on top of the left hand vertical bar... Note also that the opening and closing { and } characters (which are in the HTML source as far as I could see) are somehow swallowed, making those examples involid JSON:-(

**Comment by gkellogg** [comment]
@iherman I updated the externalDFN style (when it's in a "p" or "dd" block to make it stick). See if that helps; it's probably good to keep it somewhat distinct from an internal definition. An alternative to using italic would be to use a different color, or keep dotted, or both. Please feel free to experiment and suggest an alternative, or reference another spec which does this better.

**Comment by gkellogg** [comment]
I also sneaked in a correction to CSV Files in a Tabular Data Package in the model document when dealing with list end punctuation issues.
