### ISSUE TITLE
Examples use non-existent dc:keywords property

### ISSUE THREAD

**Issue by danbri** [w3c/csvw#437]
Chatting w/ @gkellogg and using his tool, ...

[
   a csvw:TableGroup;
   csvw:table [
     a csvw:Table;
     dc:title "Tree Operations"@en;
     dc:keywords "tree"@en,
       "street"@en,
       "maintenance"@en;

This should be dc:subject :)

**Comment by gkellogg** [comment]
The metadata document description on common properties uses `dcat:keyword`, which may be a better use than `dc:subject`.

**Comment by danbri** [comment]
FWIW http://schema.org/keywords is also available
