### ISSUE TITLE
Make `title` a required column?

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#440]
The [countries.json](https://github.com/w3c/csvw/blob/gh-pages/examples/countries.json) example appears to be incorrect in that it doesn't define a `title` for each column. This means, that when merging with embedded metadata, a validator will raise an error because the first column from the original- and embedded-metadata do not match. Because of our reduced metadata search, there really isn't a case where two metadata files would match on `name` and not also need to match on `title`; this basically means that declared metadata must have a `title` column.

Alternatively, we could match `name` against any `title` value in a language- and case-neutral way, which may be more intuitive. Here are some options:
- [ ] Make `title` a required column and column match _only_ on `title`
- [x] Continue to keep `title` optional, but require one or the other of `name` and `title` to be defined. Match columns where the `title` values intersect, the `name` values are the same, or `title` includes at least on value which matches a `name` value without considering language or case.
- [ ] ???

**Comment by gkellogg** [comment]
Personally, I think that option 2 provides the least surprise for authors. We could probably even remove the check for `name` values being the same.

**Comment by gkellogg** [comment]
The merge wording I'm trying in my implementation is the following:

> If there's a non-empty case-insensitive intersection between the `name` and `title` values for the column description at the same index within `A` and `B`, the column description from `B` is imported into the matching column description in `A`

**Comment by iherman** [comment]
I am in favour of this approach, but with a small caveat in the text: the intersection of a `title` value and `name` should be understood not only in terms of case-insensitive match but also the (possible) title value to be normalized, right? (I mean, %-encoded and all that ugly things).

Other than that, +1 for me.

**Comment by gkellogg** [comment]
I'm not sure the percent-encoding is necessary, as it's unlikely that someone would manually percent-encode the name; rather it would be the result of a transformation from a title, in which case we would match. Doing a percent-encode before trying to match would need to be careful not to percent-encode a percent, or things that would otherwise match, wouldn't any longer.

It seems like an extra complication that could result in a false-miss, and I don't see great benefit in it. Do you have a use case which could help prove this?

**Comment by iherman** [comment]
Yeah, I see your point. The issue I have is the (probably very frequent) case when a title has naturally spaces; but I guess the instinctive approach that people take when creating a name would be to replace the space characters by an underscore. However, normalization would not help on that.

Maybe we can leave the issue open for LCCR, while the changes would be made as proposed; maybe somebody will come up with a use case...

**Comment by gkellogg** [comment]
I think percent I escaping name for comparison could work, but really, if there are spaces, they will need to be in a title property for all practical purposes.

**Comment by iherman** [comment]
> On 02 Apr 2015, at 16:27 , Gregg Kellogg notifications@github.com wrote:
> 
> I think percent I escaping name for comparison could work, but really, if there are spaces, they will need to be in a title property for all practical purposes.

... and, separately, in a name for, say, template variables, probably using '_' for spaces...

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704
