### ISSUE TITLE
Row annotations in conversion specifications

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#445]
The model document states that **rows** can have annotations. (Though the metadata document doesn't provide any official mechanism for giving rows annotations, an implementation could build a model in which a row had annotations, eg by interpreting `notes`.)

I think the conversion specifications should state that in **standard mode**, all non-core row annotations are copied onto the **csvw:Row** objects in just the same way as non-core table annotations are copied onto tables.

**Comment by iherman** [comment]
@JeniT, just to understand: at the moment, the conversion specification does such a "bulk" copy for common properties and notes. Do you mean to say that if a row has such annotations, they should also be copied?

I see the point, but it is a bit misleading for the reader that we talk about such common properties (or notes) while the current metadata mechanism does not allow the user to specify those. Maybe we should complement the spec (possibly in the syntax document) with a remark making it clear that future versions of the specification may add explicit means to add such annotations, and a similar remark can be added to the conversion document (i.e., that the mechanism is built into the conversion although the current spec does not give explicit means to add those).

But maybe I misunderstood what you are considering...

**Comment by 6a6d74** [comment]
I could add a non-normative note that implementation-specific row-level annotations MAY be added to the csvw:Row object ... 

Let's talk at tomorrow's teleconf.

**Comment by iherman** [comment]
Discussed at telco: http://www.w3.org/2015/04/08-csvw-irc#T14-49-21
