### ISSUE TITLE
Inherited property annotations on columns

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#446]
There's currently inconsistency in which [inherited properties](http://w3c.github.io/csvw/metadata/#inherited-properties) are copied onto [columns](http://w3c.github.io/csvw/syntax/#columns) as annotations: only `datatype` becomes an annotation, and not, for example, `lang` or `null` or `default` or `separator`.

I think either all these properties should become core annotations on columns, or none.

Further, for the purposes of aiding data entry, I think it would be useful for columns to have all the inherited properties as core annotations. Note that the [URI template properties](http://w3c.github.io/csvw/metadata/#uri-template-properties) would have to turn into annotations whose values were URI template strings, not URIs.

**Comment by gkellogg** [comment]
+1
