### ISSUE TITLE
Is specifying default metadata necessary?

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#448]
See [locating metadata](http://w3c.github.io/csvw/syntax/#locating-metadata) in the model document where it says:

> If no metadata is supplied or found, then the following Metadata is used as the default for extracted embedded metadata:
> 
> ```
> {
>   "@type": "TableGroup",
>   "resources": []
> }
> ```

I'm not sure this is useful (for me it's just confusing). Can we remove it?

**Comment by gkellogg** [comment]
Basically, this is the minimum metadata required if none is specified. The rest of the steps cause for merging metadata. As `resources` is a required property, and merging always results in a TableGroup, this would essentially be the minimum metadata an implementation would need to work. The `@type` field could be removed.

**Comment by JeniT** [comment]
Surely if there's no metadata found then you just don't have any metadata to annotate the table with. Or you don't have anything that you have to merge with, so you just use the metadata that you have. A default that doesn't define any useful defaults (ie any actual values) doesn't seem to add any value.

**Comment by gkellogg** [comment]
@iherman was the one originally asking for default metadata. Note that the algorithm does say to find `UM<sub>M</sub>` and merge with `EM`. Do we need a wording change to account for there being no `UM<sub>M</sub>`?

I'll pass the baton to @iherman for his opinion.

**Comment by iherman** [comment]
I do not see harm having it, actually on the contrary. As @gkellogg's comment shows, if we allow for the situation where there is no annotation at all, then we have to revise the wording for all the various steps (merging, conversions, maybe others) to precisely account for a missing annotation altogether. I would prefer to leave it as is.

**Comment by JeniT** [comment]
OK, then perhaps we can change the wording. Is this the default embedded metadata or the default located metadata (ie if no Link-based, file-specific or directory-specific metadata is found), or both?

**Comment by iherman** [comment]
> On 06 Apr 2015, at 10:43 , Jeni Tennison notifications@github.com wrote:
> 
> OK, then perhaps we can change the wording. Is this the default embedded metadata or the default located metadata (ie if no Link-based, file-specific or directory-specific metadata is found), or both?

I believe it is both. Ie, if there is nothing else, this is what you get

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
I think this is the default located metadata; based on this you can extract embedded metadata, which may, itself, be empty. I can improve that definition.
