### ISSUE TITLE
What line endings should be expected?

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#45]
[Section 4.1.1 of RFC2046](http://tools.ietf.org/html/rfc2046#section-4.1.1) specifies that "The canonical form of any MIME "text" subtype must always represent a line break as a `CRLF` sequence. Similarly, any occurrence of `CRLF` in MIME "text" must represent a line break. Use of `CR` and `LF` outside of line break sequences is also forbidden."

Should we be defining `application/csv` instead, to prevent having to adhere to this rule, or should we stick to the `CRLF` rule?

**Comment by yakovsh** [comment]
RFC 2046 still applies for the "text" tree. If we want not to use CRLF, then a non-text registration would be needed.

**Comment by yakovsh** [comment]
For the updated version of RFC 4180, line endings are expected to stay the same - CRLF.  I am debating where the text from RFC 7230 (HTTP 1.1) would be applicable here:

"Although the line terminator for the start-line and header fields is
   the sequence CRLF, a recipient MAY recognize a single LF as a line
   terminator and ignore any preceding CR.
"

**Comment by JeniT** [comment]
I think that would be good if possible. There are a lot of CSV files with just `LF` line terminators.

**Comment by yakovsh** [comment]
Right now it says:

"As per section 4.1.1. of RFC 2046 [3], this media type uses CRLF
      to denote line breaks.  However, implementors should be aware that
      some implementations may use other values."

Is that sufficient?

**Comment by JeniT** [comment]
I think that's too loose. I'd prefer the HTTP-esque phrasing which explicitly states that consuming applications MAY also recognise LF on its own, rather than just "being aware" that other line terminators might be used.

**Comment by JeniT** [comment]
This is something for the RFC rather than CSVW.
