### ISSUE TITLE
Note in Grammar section in model spec

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#451]
@gkellogg should we remove the note in the [Grammar section](http://w3c.github.io/csvw/syntax/#ebnf) which says:

> We should probably place further restrictions on QCHAR and SCHAR to avoid control characters. If header weren’t optional, it would be better defined as in RFC4180, but if the syntax allows it to be optional, this would make it not an LL(1) grammar, which isn’t too much of an issue.

This reads more like an editorial note at the moment.

**Comment by iherman** [comment]
This seems to be solved, the remark is in a note now; can we close this?

**Comment by JeniT** [comment]
It's a note, yes. But other notes in the documents are important notes for the reader, whereas this note seems to be an editorial note flagging an issue in the document. If it stays as a note, it should be rephrased as a note for the reader.

**Comment by gkellogg** [comment]
I'm tied up today, but I'll take care of this, and other open issues tomorrow.
