### ISSUE TITLE
Removing header column count

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#453]
We currently have a **header column count** flag used when parsing tabular data (reflected by a `headerColumnCount` property on dialect descriptions). This seems irrelevant: we have no concept of row titles for example, so it currently has exactly the same effect as **skip columns**.

I propose we remove the **header column count** flag and the `headerColumnCount` property on the dialect description.

**Comment by gkellogg** [comment]
Are you not concerned that some dialect might be defined which would use row headers as annotations? That would seem to be the point about including row annotations in conversions, if they were added somehow.

**Comment by JeniT** [comment]
The only place the dialect description gets used is when parsing. Currently the parsing algorithm doesn't try to record the row headers because there's nowhere to put them in the generated embedded metadata document, which is the only source of metadata/annotations that we recognise.

If the parsing algorithm was rewritten to directly create the tabular data model then we could add them, but with the approach we have (of generating a metadata document for the embedded metadata) there's no scope for that. I don't see any scope for implementation defined behaviour that could use it.

**Comment by gkellogg** [comment]
Okay, +1.

**Comment by iherman** [comment]
For the records: +1

> On 06 Apr 2015, at 03:29 , Gregg Kellogg notifications@github.com wrote:
> 
> Okay, +1.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
I will regenerate the property diagram, but only when all issues are closed...

**Comment by iherman** [comment]
Diagram updated in commit https://github.com/w3c/csvw/commit/8f9cacabbd30efba96308b94f5cabfc6bd54a559. Closing.
