### ISSUE TITLE
Errors in metadata documents

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#462]
In [Annotating Tables](http://w3c.github.io/csvw/metadata/#annotating-tables) the metadata document makes some statements about validation of the metadata documents themselves:

> All compliant applications MUST create annotated tables based on the algorithm defined here. All compliant applications must generate errors if a metadata document does not conform to this specification, such as:
> - not being compliant with JSON syntax
> - using any JSON outside of the restrictions defined in section A. JSON-LD Dialect
> - not specifying a property that it is required to specify
> - including properties (aside from common properties) which are not defined in this specification
> - having invalid values for a given property

Should we say that all these are fatal errors and that applications must stop processing when they encounter such an error, or should some of them be recoverable, and if so how?

**Comment by akuckartz** [comment]
Using undefined properties is not an error - vor should not be.

**Comment by gkellogg** [comment]
+1, I understood that any invalid data in a metadata document is a fatal error. Tests for this are validation only. I interpret this to mean that any conversion would end in an error rather than incomplete or incorrect data.

It is validation of the data itself, such as foreign key errors, which is not fatal for a converter, but would be a validation error.

**Comment by iherman** [comment]
Referring back to @akuckartz's comment: is there any property that is _required_ to be specified (i.e., which is not covered by a possible default)? I had the impression that the processing steps plus the initial default provides a default for all of those, in which case that line should be removed from the bullet list...

**Comment by iherman** [comment]
Discussed on telco http://www.w3.org/2015/04/08-csvw-irc#T14-13-50

**Comment by JeniT** [comment]
RESOLVED that implementations SHOULD ignore unrecognised properties (with warning), invalid values use default (with warning)
