### ISSUE TITLE
Property values

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#463]
(@gkellogg particularly:) Having read through the metadata spec, I'm unclear about the role of [property value](http://w3c.github.io/csvw/metadata/#dfn-property-value). It seems to be similar to the value of the equivalent annotation in the data model. Would it be worth renaming _property value_ to _annotation value_ do you think?

**Comment by gkellogg** [comment]
Yes, I think that _annotation value_ captures the same meaning. Basically, the _property value_ was intended to be the resolved value of that property, considering defaults and so forth. References to the _property value\ can dir coyly reference to appropriate annotation in the model document.

**Comment by iherman** [comment]
> On 07 Apr 2015, at 22:00 , Jeni Tennison notifications@github.com wrote:
> 
> (@gkellogg particularly:) Having read through the metadata spec, I'm unclear about the role of property value. It seems to be similar to the value of the equivalent annotation in the data model. Would it be worth renaming property value to annotation value do you think?

+1

Ivan
