### ISSUE TITLE
Removing table group/table/column compatibility constraints for inherited properties

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#464]
When talking about [inherited properties](http://w3c.github.io/csvw/metadata/#inherited-properties) the spec says:

> Applications must raise an error if the value of a property in a table description is not compatible with the value of that property on the table group description it appears in. Applications must raise an error if the value of a property in a schema description is not compatible with the value of that property on the table description and table group description it appears in. Applications must raise an error if the value of a property in a column description is not compatible with the value of that property in the schema description, table description, and/or table group description it appears in.
> 
> A value for an inherited property on a column or table description is compatible with with an inherited value on the same property on a table or table group description if they are the same value or if the first value is a sub-value of the second value. The definitions of individual inherited properties indicate what values count as sub-values of others.

This was stuff I originally wrote. Having reflected, I propose that we remove these constraints: it should be possible for someone to define that all the values in a table are strings with the language `en` and then override just for individual columns, for example.

**Comment by iherman** [comment]
+1

Ivan

> On 07 Apr 2015, at 22:05 , Jeni Tennison notifications@github.com wrote:
> 
> When talking about inherited properties the spec says:
> 
> Applications must raise an error if the value of a property in a table description is not compatible with the value of that property on the table group description it appears in. Applications must raise an error if the value of a property in a schema description is not compatible with the value of that property on the table description and table group description it appears in. Applications must raise an error if the value of a property in a column description is not compatible with the value of that property in the schema description, table description, and/or table group description it appears in.
> 
> A value for an inherited property on a column or table description is compatible with with an inherited value on the same property on a table or table group description if they are the same value or if the first value is a sub-value of the second value. The definitions of individual inherited properties indicate what values count as sub-values of others.
> 
> This was stuff I originally wrote. Having reflected, I propose that we remove these constraints: it should be possible for someone to define that all the values in a table are strings with the language en and then override just for individual columns, for example.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
+1

**Comment by gkellogg** [comment]
+1
