### ISSUE TITLE
Trimming whitespace around cells

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#47]
When parsing, should we:
- always trim whitespace around cells?
- always create empty cells for missing cells?

**Comment by yakovsh** [comment]
For #1, in RFC 4180, specifically the ABNF grammar, it is assumed that the whitespace is part of a cell content

**Comment by gkellogg** [comment]
I think we need a way to at least specify that white-space is trimmed, if not default to trimming whitespace.

**Comment by JeniT** [comment]
Closing as we have both the `trim` property in [dialect descriptions](http://w3c.github.io/csvw/metadata/index.html#dialect-descriptions) and whitespace normalisation as part of [parsing cells](http://w3c.github.io/csvw/metadata/index.html#parsing-cells) based on their datatype.
