### ISSUE TITLE
"lang" annotation for rows and cells

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#472]
The current syntax document has an annotation for `lang` for columns, but not for rows and cells. It sounds like a good idea to have those (ie, application that set the annotations through some other means than our metadata document would be able to set the language for a row or for an individual cell...)

**Comment by 6a6d74** [comment]
ultimately `lang` is an inherited property - so it would make sense for it to be applicable to cells directly. At some point it may be possible to set it via a row too - so that also makes sense. 

Finally I can also see that one might set the data language for the entire dataset - by applying the annotation to the table.

**Comment by iherman** [comment]
Except that… There is actually no such thing as "inherited property" in the annotated data model! I was wondering about that, ie, whether this is something we should have. 

Conceptually, of course, it is not strictly necessary: for a cell, one can go 'up' to the row and the column level to locate a property, which is doing inheritance without naming it inherited property. Just like in the [XML Infoset](http://www.w3.org/TR/xml-infoset/): the [character encoding scheme] is defined for the "Document Information Item" only, and not for an "Element Information Item" although, semantically, the character encoding is obviously valid for the document as a whole.

But we may need some wording for this. If for no other reason than for making the conversion document wording a bit less convoluted if it is converted to the brave new world of table annotations instead of metadata properties...

**Comment by gkellogg** [comment]
I believe the cell language issue is fixed via 9bf2dc28d8fb31b2e43588d522b8d700beeb67d6. Both language and datatype as well as `list` are set on a `cell value` as appropriate during cell parsing. Having it on the cell makes it easier for conversion documents, as they don't need to repeat the interpretation of language, datatype, or sequence from the column, as it can vary depending on the datatype and if there is a valueUrl.

@iherman, close the issue if you think it complete.
