### ISSUE TITLE
Missing constraints on datatype facets in metadata document

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#478]
It used to be that it wasn't possible to have a metadata document contain something like:

```
"length": 5
"minLength": 10
```

but (unless I've missed something) the conditions that tested this seem to have been removed in the move of the datatype constraint descriptions to the model document. Should we add these back in?

**Comment by gkellogg** [comment]
If it was removed, it was certainly unintentional. I'll take care of it.
