### ISSUE TITLE
Using JSON-LD for the metadata document

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#48]
We are aiming for the JSON format to be interpretable as JSON-LD, but without any requirement to include context within the JSON itself (to save people from having to do boilerplate). We invite comments on the utility of this approach: is it useful for CSV metadata to be interpretable as JSON-LD? Is it helpful to be able to map it to RDF? Would it be better to rename some of the JSON-LD keywords, such as `@id` and `@type`?

**Comment by iherman** [comment]
I would prefer to keep the JSON-LD compatibility. (The `@context` can also be delivered through the HTTP response header, so the fact that it is not in the JSON itself is not a problem.) The fact that the metadata _can_ be seen as RDF, if needed, means that the metadata can be used as part of a larger linked data cloud even if the data itself is not in RDF and maybe too big to be transformed into RDF. In other words, the metadata is some sort of a "glue" to bind CSV data to Linked Data.

Ivan

**Comment by danbri** [comment]
It ought to be JSON-LD compatible but let's aim for "unobtrusive" (aka "half-hearted") JSON-LD, rather than the full glory. So let's try to avoid using too much clever stuff...

**Comment by iherman** [comment]
> On 11 Nov 2014, at 16:21 , danbri notifications@github.com wrote:
> 
> It ought to be JSON-LD compatible but let's aim for "unobtrusive" (aka "half-hearted") JSON-LD, rather than the full glory. So let's try to avoid using too much clever stuff...

I agree.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
As long as a conforming JSON-LD processor can access the data without special knowledge, I'm fine with that. I.e., delivering the context via a link header is fine. This requires using application/json, which I believe we were planning to do anyway.

**Comment by danbri** [comment]
Is there anything outstanding on this issue, w.r.t. needing telcon discussion?

**Comment by rufuspollock** [comment]
I'm +1 on least obtrusive - it would be great if people could produce this without _any_ JSON-LD knowledge (and up to the savvy to add it in the http header etc).

**Comment by danbri** [comment]
@rgrp if anecdata is submissible, I'm happy to relay experience from Google dealing with non-technical publishers, partners etc.; several colleagues have reported that people are having a lot less trouble getting JSON-LD right, as compared to Microdata/RDFa. This is for audiences that won't have heard of W3C RDF, ontologies, etc. etc. e.g. https://support.google.com/webmasters/answer/4620133?hl=en so semwebisms in the markup are pretty minimalistic. 

The "@" sign does look a bit odd from a pure JSON perspective, but can apparently be hidden away via use of @context. At Google we didn't do that and it doesn't seem to have been much of an issue in practice.

**Comment by rufuspollock** [comment]
@danbri this wasn't compared to microdata - this was just compared to plain JSON. agree it should be pretty simply :-)

**Comment by danbri** [comment]
Yeah. I guess I'm just saying that JSON-LD's design seems to have done a reasonable job of meeting the expectations of people looking for normal-ish JSON, rather than e.g. something like https://dvcs.w3.org/hg/rdf/raw-file/default/rdf-json/index.html which is quite clearly un-interesting to mainstream even if useful for those of us whose minds have been addled by RDF :)

**Comment by JeniT** [comment]
Closing as per http://www.w3.org/2014/11/12-csvw-minutes.html#item10 and http://www.w3.org/2013/csvw/track/actions/59
