### ISSUE TITLE
Define lexical form of non-core annotations

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#485]
Capturing issue left over from PR #474 ...

@gkellogg said:

> Perhaps we need something in the model document that says that non-core annotations MUST have the lexical form of our JSON-LD subset. That might require that the definition move to the model document.

**Comment by 6a6d74** [comment]
@JeniT then said:

> The model document already says "The values of these annotations may be lists, structured objects, or atomic values." This could be expanded if you like, though I'd suggest we don't focus on lexical forms within the abstract model.

and @iherman said:

> I agree with @JeniT that lexical details should not be part of the model (my mental analogy is the xml infoset document...). That is why I proposed to put some caveats in the conversion document.

Happy to close this issue if we have consensus on not modifying the model doc further.

**Comment by iherman** [comment]
I still believe there is something not entirely o.k. in the csv2\* document. The current text says, in item 3 of [Section 4.2](http://w3c.github.io/csvw/csv2rdf/#h-generating-rdf) (and elsewhere) that: 

> In **standard mode** only, emit the triples generated by running the algorithm specified in [section 6. JSON-LD to RDF](http://w3c.github.io/csvw/csv2rdf/#json-ld-to-rdf) over any notes and non-core annotations specified for the group of tables, with node G as an initial subject, the notes or non-core annotation as property, and the value of the notes or non-core annotation as value.

The text refers to the section on JSON-LD to RDF, which says:

> This section defines a mechanism for transforming the [json-ld] dialect used for non-core annotations and notes into RDF in a manner consistent with the Deserialize JSON-LD to RDF Algorithm defined in [json-ld-api]. Converters MAY use any algorithm which results in equivalent triples.

However the model document does _not_ say that the annotation is using a json-ld dialect. This is only true if the metadata document is used for the purpose of annotation. The model document allows, for example, for an API to use a full JSON-LD dialect, or to use Turtle, or any other syntax that will be defined next month.

That is why I think some sort of a caveat has to be put into the conversion document. E.g., the section above could be changed to something like:

> In **standard mode** only, if the notes and non-core annotations for the group of tables originate from the processing of metadata as defined in the [[!tabular metadata]] specification, emit the triples generated by running the algorithm specified in [section 6. JSON-LD to RDF](http://w3c.github.io/csvw/csv2rdf/#json-ld-to-rdf), with node G as an initial subject, the notes or non-core annotation as property, and the value of the notes or non-core annotation as value.

And add a note saying

> Applications may have other means to create annotated tables, e.g., through some application specific API-s, in which case the exact format for non-core annotations or notes may be different. Specifications for such annotation processes should specify how these annotations should be converted to JSON.

The caveat is that repeating this note to all occurrences of non-core annotations may be a bit of a drag; maybe a separate section on non-core annotations and refer to those in one place?

**Comment by 6a6d74** [comment]
@iherman - also note the definition of "prefixed name" in csv2rdf:

> A prefixed name is an abbreviation for a URI, in the syntax `prefix:name`. See [Names of Common Properties](http://w3c.github.io/csvw/metadata/#names-of-common-properties) in [tabular-metadata](http://w3c.github.io/csvw/csv2rdf/index.html#bib-tabular-metadata) for information on expansion.

This goes onto talk about the expansion of prefixed names a la JSON-LD. Feels like a similar issue to the one you cite above.

**Comment by iherman** [comment]
> @iherman - also note the definition of "prefixed name" in csv2rdf:
> 
> >    A prefixed name is an abbreviation for a URI, in the syntax prefix:name. See Names of Common Properties in tabular-metadata for information on expansion.
> 
> This goes onto talk about the expansion of prefixed names a la JSON-LD. Feels like a similar issue to the one you cite above.

Actually, I do not think so. The prefixed name in the csv2rdf document is an editorial thing: it essentially introduces an editorial pattern for the document itself but it does not influence the technical content of the conversion process. So referring to the metadata document in that context is fine; we could have referred to, say, the RDFa or the JSON-LD document as well.

This is in contrast with my other issue that does have an effect on the conversion itself.

**Comment by 6a6d74** [comment]
OK ...

**Comment by 6a6d74** [comment]
@iherman - I'm done making editorial changes. Just this one issue to consider now ...

**Comment by 6a6d74** [comment]
@iherman - what do you think of the proposal in PR #487? If you're content, please merge (else bin it!)

**Comment by 6a6d74** [comment]
closed via #487
