### ISSUE TITLE
Conformance Requirement on Column Reference Properties unclear

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#504]
The metadata document makes the following requirement:

> If the supplied value of a column reference property is not a string or array (eg if it is an integer), or if any of the values in the supplied array are not strings, or if any of the supplied strings do not reference one or more columns, compliant applications must issue a warning and proceed as if the property had been specified (which may mean that an error is issued, if the property was required).

It's not clear to me what property is specified and how it might be required. I _think_ it means that if a `primaryKey` has an improper value, or doesn't reference the defined columns it generates an error and acts as if the `primaryKey` weren't specified. In a `foreignKey`, the `columnReference` property appears in two places, both seem to be required. Therefor bad reference in either of these would be an error and applications MUST raise that error and stop processing.

**Comment by iherman** [comment]
Rigth. I believe that in

> If the supplied value of a column reference property is not a string or array (eg if it is an integer), or if any of the values in the supplied array are not strings, or if any of the supplied strings do not reference one or more columns, compliant applications must issue a warning and proceed as if the property had been specified (which may mean that an error is issued, if the property was required).

it should say "property had not been specified" instead of "property had been specified"
