### ISSUE TITLE
Relationships to RDB tables

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#506]
Comment of Ashok Malhotra [on the mailing list](https://lists.w3.org/Archives/Public/public-csv-wg/2015Apr/0034.html)

> Shouldn't it be possible to create Relational tables from tabular data?
> That is, after all, a popular use of tabular data.
> There are probably existing tools and standards to do this but I would
> think it was worth at least a mention.

The current thread includes:

Immediate responses from [@iherman](https://lists.w3.org/Archives/Public/public-csv-wg/2015Apr/0035.html), [@danbri](https://lists.w3.org/Archives/Public/public-csv-wg/2015Apr/0039.html), and [@gkellogg](http://www.w3.org/mid/A1FC472D-89D4-4A56-ABC3-54278D4D1C0D@greggkellogg.net). 

Ashok's latest reply:

> Ivan, Dan:
> Thank you for your replies.  I found the Wiki https://github.com/w3c/csvw/wiki/Deviations-from-the-charter
> very helpful.  Could some of the material be incorporated in the main spec?  By metadata do you mean
> column data types?  Couldn't these be specified by the user?

Note also Alex Russel's mail:

> I'm not sure I understand the question. Is the suggestion that this spec
> should cover relational operations over CSV data? Or more of an observation
> that it's possible? If it's the former, I'm inclined to suggest that it
> should remain out of scope for now. WebSQL died on this hill and if we're
> going to look at relational operations again, it should also likely include
> how to bring data stored in IndexedDB into the fold.

With Ashok's response

> Hi Alex: Several responses to your comment:
> 1.  My initial question was very simple.  The specs discuss mapping CSV to JSON and RDF, why not Relational tables, which would seem to be a natural.
> 2. WebSQL died because it was based on SQLite, a proprietary product that deviated from the SQL spec.  If you want to revisit this with an abstract spec that follows the SQL spec, I'm all for it.
> 3.  Berekely DB, Oracle's implementation of the IndexDB spec does, indeed have an SQL
>    interface.  I can send more details if you wish.

**Comment by iherman** [comment]
We are clearly not chartered to do that, nor do we have the expertise in the group. 

I guess that, technically, it is correct that table annotation can be converted in to RDB Schema(s) that, together with the raw CSV data, could be used to import the CSV file(s) into an RDB. This is a general statement that we can put into the model document. Although, we have to realize that we restricted the foreign keys due to the nature of CSV files (see [the comment on the wiki on this](https://github.com/w3c/csvw/wiki/Direct-mapping-vs.-CSV2RDF,-simple-case-with-foreign-keys)).

Another entry where a comment may be of use is the `transformation` facility. At this point, the definition says that the user may choose whether the transformation applies on the data or the RDF or JSON conversion result. Maybe we can extend this a bit saying that a transformation may be applied on the metadata file; a metadata->RDB Schema conversion may then be hooked at that point. (I am not 100% sure that is the best place, but I though flagging that for discussion may be worth.)

**Comment by gkellogg** [comment]
> Another entry where a comment may be of use is the transformation facility. At this point, the definition says that the user may choose whether the transformation applies on the data or the RDF or JSON conversion result. 

According to the `source` property definition: "If the source property is missing or null (the default) then the source of the transformation is the annotated tabular data model. No other values are valid." It seems to me that the data model provides everything that you might get from the metadata document, without binding tightly to that syntax or model representation. What it lacks is an API for accessing information from the data model, which makes it more difficult for someone to actually write an application to do this.

**Comment by iherman** [comment]
> On 20 Apr 2015, at 21:04 , Gregg Kellogg notifications@github.com wrote:
> 
> Another entry where a comment may be of use is the transformation facility. At this point, the definition says that the user may choose whether the transformation applies on the data or the RDF or JSON conversion result.
> 
> According to the source property definition: "If the source property is missing or null (the default) then the source of the transformation is the annotated tabular data model. No other values are valid." It seems to me that the data model provides everything that you might get from the metadata document, without binding tightly to that syntax or model representation. What it lacks is an API for accessing information from the data model, which makes it more difficult for someone to actually write an application to do this.

You are right, I missed that.

There is, however, a minor issue with this nevertheless. There is no standard format for the representation of the annotated table, which means that it seems difficult to produce an interoperable transformation based on it. I wonder whether having an input possibility for the raw csv data + the final metadata might be useful as a separate category.

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
We could describe a serialization of the annotated tabular data model back to something based on an extension of the Metadata format by adding rows and cells; my processor does this with the to_atd method. However, having the complete annotated tabular data model isn't typically as useful as the subset of that model that doesn't actually include cell data (and therefore rows and referenced rows). This becomes essentially a serialization of the merged metadata, which might be where you're pointing.

**Comment by iherman** [comment]
> On 21 Apr 2015, at 20:36, Gregg Kellogg notifications@github.com wrote:
> 
> We could describe a serialization of the annotated tabular data model back to something based on an extension of the Metadata format by adding rows and cells; my processor does this with the to_atd method. However, having the complete annotated tabular data model isn't typically as useful as the subset of that model that doesn't actually include cell data (and therefore rows and referenced rows). This becomes essentially a serialization of the merged metadata, which might be where you're pointing.
> 
> Exactly 

Ivan

**Comment by 6a6d74** [comment]
(also see ISSUE #510 for details about adding an [appendix to csv2rdf](http://w3c.github.io/csvw/csv2rdf/#relationship-to-rdb-direct-mapping) describing partial equivalence of CSV to RDF mapping and RDB to RDF **direct mapping**)

**Comment by iherman** [comment]
For the record, in closing this issue:
- [DanBri's formal answer to the commenter](http://www.w3.org/mid/CAK-qy=76dHononb2x8fXWU0RnwdgFxYCt2Qf-q-HcMR=PjxnPQ@mail.gmail.com)
- [Commenter's approval of the decision](http://www.w3.org/mid/553FAD7F.8020801@oracle.com)

**Comment by danbri** [comment]
Thanks Ivan. Also worth noting that #510 is now closed too, meaning that the actions we promised commenter have been completed too.
