### ISSUE TITLE
Clipboard format missing?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#507]
[Paul Libbrecht's comment](https://lists.w3.org/Archives/Public/public-csv-wg/2015Apr/0040.html)

> Dear Jeni and all,
> 
> do I mistake or there is nothing about clipboard formats in this set of
> specs?
> Ideally, such would be in a media-type-declaration but it seems like the
> one here would also be suited.
> Basically: it would be clipboard flavour names for windows and UTI for OSX).
> 
> The lack of such a convention  has made it that HTML tables are sniffed
> and partially successfully copy and pasted from some browsers to some
> spreadsheets (thus far: Firefox + Excel only)... This seems to be the
> only way thus far and, indeed, xls or csv exports are pretty common as
> an extra service of web applications whereas a selection, copy, and
> paste would widely more intuitive.

The thread includes mails from  @danbri, @yakovsh, and, @timbl.

**Comment by yakovsh** [comment]
Just to note that clipboard name and OSX UTI name are not things normally submitted in the media type registration. They seem to be extra items only found in some W3C-originated registrations. The IETF registrations guidelines do not require or mention them at all.

Some examples include:
https://www.iana.org/assignments/media-types/text/markdown
https://www.iana.org/assignments/media-types/message/global
https://www.iana.org/assignments/media-types/application/oxps
http://www.w3.org/TR/MathML3/appendixb.html

As per Ivan's email to me, not sure if there is a point for clipboard data for csvm+json since this is a metadata format. Regular CSV may benefit but that's a different discussion.

**Comment by iherman** [comment]
(Copying the end of a longer thread)

> Ivan and Jeni,
> 
> indeed, I had not caught that the media-type-declaration was only for the annotations.
> 
> I am not sure I am able to judge whether the annotations make sense to be exchanged between applications. I would feel it similar to the copy-style and paste-style functions we can find, e.g., in Apple's editors. I could imagine myself doing the same with datatypes of a cell or column... Thus, if this makes sense, please consider it.
> ...
> paul
> 
> > On 21/04/15 15:18, Ivan Herman wrote:
> > Paul,
> > 
> > I must admit I am not really familiar with the details of the clipboard format, so I am struggling to understand what is relevant to the work of this Working Group (for the tag list: the CSV on the Web Working Group).
> > 
> > The work in the group indeed includes a (still-to-be-registered) media type definition:
> > 
> >  http://www.w3.org/TR/2015/WD-tabular-metadata-20150416/#iana-considerations
> > 
> > which is for a special json format that is used for the metadata created for a specific CSV content. I am not sure how any clipboard action would be relevant for this: the metadata file is, essentially, oblivious to any browser action.
> > 
> > The example you refer to (HTML Tables possibly understood as spreadsheets or CSV files) seem to be more relevant to the specification of CSV per se. That definition is done at IETF:
> > 
> >  https://tools.ietf.org/html/rfc4180
> > 
> > the CSVW WG at W3C has been explicitly _not_ chartered to define the CSV format itself exactly because this work is happening at IETF, although the group is happy (and encouraged) to contribute to the IETF process (and Yakov has been an active part of the Working Group).
> > 
> > Can you tell me a bit more in details what you think this Working Group should do in terms of adding to, or modifying, the drafts?
> > 
> > Thank you
> > 
> > Ivan

**Comment by yakovsh** [comment]
My personal opinion is not to specify the clipboard formats on the csvm+json document as per Ivan's comment that it is not useful. If a new revision of RFC 4180 comes out, we should surely consider it.

**Comment by iherman** [comment]
Set the label to review and decide on the call. For the records, I agree with @yakovsh

**Comment by JeniT** [comment]
@JeniT to respond on list.

**Comment by danbri** [comment]
See http://www.w3.org/2015/04/22-csvw-irc#T14-25-22

**Comment by iherman** [comment]
@JeniT 's official answer to the commenter: http://www.w3.org/mid/etPan.5540cb55.79a1deaa.d2@jenit.local

**Comment by polx** [comment]
Do I understand that the group considers it inappropriate to copy-and-paste csvm ?
paul

**Comment by JeniT** [comment]
@polx I don't think we see any special handling for copy-and-paste csvm JSON over and above what's done for other kinds of JSON.

**Comment by polx** [comment]
Jeni,

JSON copy and paste, in a user-oriented-form, does not really exist as
far as I know (you could copy text but that is for developers).
The question is not whether you have a "special handling" but if you
think no handling makes sense.

Answering Yves, I've suggested that the feature that has been now
widespread on MacOSX to copy and paste styles seemed like it could be
done over a copy of paste of csvm. I could think of finding styles and
line's cells data types particularly interesting in one google doc and
want to apply it to my OpenOffice document. Nothing such thinkable?

paul

**Comment by JeniT** [comment]
@polx The question for the CSV on the Web Working Group is whether it is appropriate for the specification of this particular JSON vocabulary to include a specification of general JSON clipboard formats. I would argue that it is outside the scope of what this group should do.

That doesn't mean it's not needed, just that it's not something that this group has the remit or expertise to achieve. We can take the action to request the appropriate groups to take a look, and we can do that for CSV as well.

If you're not content with us saying nothing about clipboard formats for JSON, please could you provide some more specific recommendations about what you think we should say?

Thanks.

**Comment by polx** [comment]
Jenni,

> include a specification of general JSON clipboard formats

That is as irrealistic as defining a clipboard name or media type for
XML or byte-streams... it is too unspecified.

Maybe I should remind that, generally, content sniffing is not done or
is not possible with clipboard formats (particularly in the
drag-and-drop gesture), hence the content-type-name should be as precise
as possible to give a feedback to the user that a given transfer will
make sense.

Specifying a clipboard name and media-type for CSVM is completely
different, I had understood: it makes the application potential precise
and might give a useful feedback to users.

paul

**Comment by JeniT** [comment]
@polx OK. Can you tell me what text we should include in the media type registration to do this, or point to a media type registration in which you think that this has been done well so that we can copy that pattern?

**Comment by polx** [comment]
Hello Jeni,

Examples:
- SVG: http://www.w3.org/TR/SVG11/mimereg.html
- MathML: http://www.w3.org/TR/MathML3/appendixb.html

What you need:
- A MacOSX Uniform Type Identifier
- A Windows clipboard name

Here is my suggestion:
- MacOSX UTI: public.csvm conforms to public.json
- Windows clipboard name: CSVM

hope it helps.

paul

PS: as far as I know, Linux Window Managers use the media type for
clipboard formats. But I remember some people considered changing that.

**Comment by JeniT** [comment]
Thanks @polx - #533 follows what you suggested with slight amendments. Are you content with that change?

**Comment by polx** [comment]
Thank you Jeni,
I'm perfectly fine with [this addition](https://github.com/w3c/csvw/pull/533).
Tell me if I should report this agreement on the mailing-list.
paul
