### ISSUE TITLE
Comments on registration template for "application/csvm+json"

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#508]
([Comment submitted by @yakovsh](http://www.w3.org/mid/CAPQd5oTktV6E0ak=QmqJ05MTrFaS6hTJ3W84wYoBQkXSvBjMYA@mail.gmail.com))
1. "Encoding considerations", should read "binary" as per section 5 of
   the registration application (https://www.iana.org/form/media-types).
   I would suggest to change to "Binary as per section 3.1 of RFC 6839".
   - Another thing that may be useful to add here is that charset parameter is not used as per section 11 of RFC 7159.
   - There is also some curious discussion in RFC 7159, section 8.1 about not allowing a byte order mark in JSON.
2. "Security Considerations" - section 12 of RFC 7159 should be
   referenced instead of RFC 4627.
3. "Interoperability Considerations" - I would add a reference to RFC
   7159 here as well. Something like "Also see RFC 7159 for
   interoperability information of JSON".
4. "Applications that use this media type" - I think we can add that
   "It is expected that many applications and programming languages will
   be using this media type across many operating systems."
5. Additional information - this is where the clipboard name and UTI
   name should be added _IF_ we want to use them.

**Comment by iherman** [comment]
The final format of the registration template depends on issue #507; I have reopened the issue until that one is open. When closing it definitely, the action is on me to send the registration request to IANA

**Comment by iherman** [comment]
@yakovsh: can you check whether the current status of the media type registration is o.k. in the document? I can then start the official procedure...

**Comment by yakovsh** [comment]
Looks good to me, and sorry for the delay. I assume that clipboard formats are not being included because we do not have consensus on that issue?

**Comment by JeniT** [comment]
@yakovsh We have included clipboard format information for the JSON metadata media type. See #507.

**Comment by yakovsh** [comment]
Got it, somehow I missed it.
