### ISSUE TITLE
Add appendix to csv2rdf spec on RDB mapping

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#510]

**Comment by iherman** [comment]
The appendix has been added to the CSV2RDF document (merge from PR #517). I have made the merge right away to avoid getting into a complex merge hell; this portion is pretty much disjoint from anything else anyway.

@6a6d74 you may want to review it, salt 'n pepper it at wish; if you are o.k. with text, this issue could be closed.

**Comment by 6a6d74** [comment]
@iherman ... am reading through the Appendix. Generally good content - although I must declare that I've had no experience with _Direct Mapping_.

On reading through, [line 1452 of csv2rdf](https://github.com/w3c/csvw/blob/gh-pages/csv2rdf/index.html#L1452) was confusing - and contained a typo:

```
<li>There is no reason to use the URL for the table as a class for typing ny default, without any further information. That could lead to semantically incorrect situations.</li>
```

I was not able to discern your intent with that sentence. Can you take a look and fix please.

I've merged in a couple of editorial changes (see PR #519). I've left the branch `issue-510-appendix-for-direct-mapping` in place if you want to use that for fix to [line 1452](https://github.com/w3c/csvw/blob/gh-pages/csv2rdf/index.html#L1452).

Let me know when you're done. Happy to review again and close this issue.

**Comment by iherman** [comment]
I have changed the sentence to:

> <li>The <a>direct mapping</a> adds a "typing" triple to the <a>direct graph</a>, which may make sense because the table is part of a larger entity (i.e., the whole database). However there is no justification to do the same by default for a <a>tabular data mapping</a>; that could lead to semantically incorrect situations.</li>

I hope that is clearer. (I have simply made the change right away in the main branch.)

Thanks!

**Comment by 6a6d74** [comment]
@iherman - I have to say that that is still not entirely clear ... how about:

> The direct mapping adds a triple with predicate `rdf:type` to the direct graph. However, by default (e.g., without additional annotation), the tabular data mapping has insufficient information to make such an assertion. 

I've not added this to the repo. Am happy to do so if you agree.

**Comment by 6a6d74** [comment]
(PS: because this issue is flagged _For LCCR_ do we need to keep the issue open?)

**Comment by iherman** [comment]
> On 28 Apr 2015, at 12:52 , Jeremy Tandy notifications@github.com wrote:
> 
> @iherman - I have to say that that is still not entirely clear ... how about:
> 
> The direct mapping adds a triple with predicate rdf:type to the direct graph. However, by default (e.g., without additional annotation), the tabular data mapping has insufficient information to make such an assertion.
> 
> I've not added this to the repo. Am happy to do so if you agree.

Sounds good! Go ahead with it…

I

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
> On 28 Apr 2015, at 12:52 , Jeremy Tandy notifications@github.com wrote:
> 
> (PS: because this issue is flagged For LCCR do we need to keep the issue open?)
> 
> —
> Reply to this email directly or view it on GitHub.

No. We can search through the issues (yay, github!) if we need them, regardless on whether it is closed or not. And it helps our current processing to close them asap…

I.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
Done (see commit c4d2d33).
