### ISSUE TITLE
Remove requirement to merge metadata

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#511]
During the course of simplifying things subsequent to our London F2F, the role of metadata merging has narrowed to the point where it might make sense to remove it altogether.

Originally, the idea was that metadata for CSVs might be pulled from several different locations (user-specified, per-file, and per-directory), but issues #448, #314, #293, and #200).

Currently, the process involves either starting with metadata, in which case what is merged is the _embedded metadata_ along with user-specified options which typically just affect the _Dialect Description_, or start with a CSV, in which case the first Metadata file found relating to that CSV is used as if it were the specified metadata. With the normative rules for embedded metadata, the _embedded metadata_ ends up just being column title information, which needs to be specified either through `name` or `titles` in the metadata file in order to successfully use the CSV. This could be replaced by a mechanism which simply uses the found or specified metadata without merging _embedded metadata_ and simply ensuring that the CSV columns are compatible with the metadata columns using language from the existing merge rules.

Removing metadata merging is a substantial technical and conceptual simplification, and may simplify the steps required to create a conformant implementation.

This change would affect the following:
- [x] minor changes to _Locating Metadata_ in the model document.
  - [x] _Overriding Metadata_ changes to _Overriding Dialect Description_
  - [ ] _Embedded Metadata_ is removed and the discussing of embedded metadata is moved to say that such a definition would need to define how embedded metadata interacts with found/supplied metadata
- [x] Minor changes to _Processing Tables_ in the model document.
  - [x] Simplification of _Creating Annotated Tables_
- [x] Remove per-property discussion of merging metadata in the the metadata document
- [x] Separate _Normalization_ from _Merging Metadata in the the metadata document
  - [x] Describe _Normalization_ as a required step when processing a metadata file as part _Creating Annotated Tables_ in the model document.

I'll follow up with a description of how existing test results would be changed as a result of making such a change.

**Comment by iherman** [comment]
I am very much in favour of this change.

**Comment by danbri** [comment]
I also strongly support this simplification.

**Comment by rufuspollock** [comment]
+1 on removal of merge - I have flagged this before in January and think removal would be a very good simplification.

**Comment by 6a6d74** [comment]
I agree that the metadata merge is complex - even _after_ the simplification we applied. +1 to remove **unless** there are clear requirements indicating that this behaviour is necessary.

So ... having quickly skimmed throught the [use case and requirements doc](http://w3c.github.io/csvw/publishing-snapshots/WD-ucr-2014-07-01/Overview.html) I cannot find any specific requirements indicating that we need to compile metadata for a CSV file from multiple locations - with the **exception** of _titles_ from the header-row of the CSV file itself.

As @gkellogg stated above, dealing with _titles_ embedded within the header-row would become a special case.

The net result of removing this merge is that creation of a _complete_ metadata document becomes a precursor task to the processing of the CSV file - and is outside the scope of the CSVW specificaiton(s).

+1 to removal of this functionality and the resulting simplification.

**Comment by JeniT** [comment]
+1. Given we have enough +1s, I'm going to turn this into an editor action.

**Comment by gkellogg** [comment]
There is still a case for using titles from the CSV as embedded metadata if no other metadata is found, otherwise, embedded metadata becomes useful for the compatibility check, and not for merging.

The only information retrieved from the file which might affect the metadata, other than dialect information, is any language found in the HTTP headers, if it is not otherwise set.

**Comment by gkellogg** [comment]
I've updated my implementation, prior to updating the documents. All existing tests pass, except the following which are likely bugs in my implementation:
- test025: dialect: header=false and skipRows=1 - Ignore header uses column definitions from metadata
- test051: dialect: commentPrefix in header - Adds comments when found in `skipRows`
- test057: dialect as URL reference - Loads a `dialect description` if referenced using a URL

This implies that removing metadata merging has no discernible effect on the existing operation of anything we have a test for, to date.

Next step (after running down these errors) is to update the spec documents.

**Comment by iherman** [comment]
For the records, there are some additional (positive) votes on this issue on the WG mailing list, see the thread starting at: https://lists.w3.org/Archives/Public/public-csv-wg/2015Apr/0064.html

**Comment by danbri** [comment]
I have heard further encouraging voices too. Let's do it.

**Comment by iherman** [comment]
There is a pending pull request (#515); once that is done, we can close this issue, too.
