### ISSUE TITLE
Remove Link header referencing Turtle document in example

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#513]
See Twitter thread around https://twitter.com/edsu/status/591189629228965888

We need to remove cause for misconception that there's any reliance on RDF-based processing (except in the case, obviously, if you want to generate RDF).

**Comment by iherman** [comment]
Yes, I agree the turtle reference should be removed from the example. It doesn't bring anything valuable and clearly creates misconceptions...

Ivan
