### ISSUE TITLE
Should we check integrity of CSV files in some way

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#52]
Should we include properties that help in checking the integrity of the file: datapackage includes `bytes` and `hash`. We could reuse the [Subresource Integrity](http://www.w3.org/TR/SRI/) work here.

**Comment by JeniT** [comment]
Proposed resolution: We don't include any integrity checking.

**Comment by iherman** [comment]
It would be nice to have something like that, but I am a bit afraid we do not have the knowledge on what is happening out there in this area. And the sub resource integrity work seems to be in its fairly early stages... So yes, we should probably skip this issue for now.

**Comment by danbri** [comment]
See http://www.w3.org/2015/02/12-csvw-irc#T11-11-02

**Comment by JeniT** [comment]
Resolved at Feb F2F to not handle integrity. Editor action to remove the issue reference from the document.
