### ISSUE TITLE
Case-insensitive intersection between names & titles in tables

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#520]
Currently the matching between names & titles in the metadata and what appears within a CSV file is done on a case-insensitive basis: http://w3c.github.io/csvw/metadata/#schema-columns (This framing has been carried through into the definition of schema compatibility.)

This seems too lax to me. At the very least it should be case-sensitive. I think it should also take into account language of the title (ie look for an intersection within each language and the matching language and unknown language).

**Comment by iherman** [comment]
> Currently the matching between names & titles in the metadata and what appears within a CSV file is done on a case-insensitive basis: http://w3c.github.io/csvw/metadata/#schema-columns (This framing has been carried through into the definition of schema compatibility.)
> 
> This seems too lax to me. At the very least it should be case-sensitive. 

I agree

> I think it should also take into account language of the title (ie look for an intersection within each language and the matching language and unknown language).

I always understood this to be at least the intention. What is missing is a more precise definition of what intersection of natural language property annotation values mean.

(I must say I never liked the way the annotation values are defined. I believe it is way better to say that the annotation value of a natural language property is a collection of language tagged strings and stop there (the rest being implementation specific). If we do so, then the intersection becomes obvious.)

**Comment by JeniT** [comment]
RESOLVED: when titles are available, match case-sensitively based on language (with unk matching any language); when only name & title available, in non-validating mode match case-insensitively, when validating raise error
