### ISSUE TITLE
Add "Access-Control-Allow-Origin: *" to the JSON-LD context document response headers

### ISSUE THREAD

**Issue by hubgit** [w3c/csvw#529]
So that the context document can be loaded across domains into client-side tools such as the [JSON-LD playground](http://json-ld.org/playground/), please add `Access-Control-Allow-Origin: *` to the response headers of http://www.w3.org/ns/csvw and http://www.w3.org/ns/csvw.jsonld.

**Comment by gkellogg** [comment]
+1, I thought we had done so. There really should be an HTTP setting for /ns to set this header for all JSON and JSON-LD files, IMO, but do this one in any case.

**Comment by iherman** [comment]
I have done it for the jsonld file and, while I was at it, for the .ttl file.

I would prefer not to do it for the HTML. I am not familiar with the whole security aspect of it, and touching to the security areas surrounding an HTML file is something I would prefer to keep away from. Isn't the jsonld version enough?

Ivan

> On 01 May 2015, at 15:26 , Alf Eaton notifications@github.com wrote:
> 
> So that the context document can be loaded across domains into client-side tools such as the JSON-LD playground, please add Access-Control-Allow-Origin: \* to the response headers of http://www.w3.org/ns/csvw and http://www.w3.org/ns/csvw.jsonld.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by hubgit** [comment]
There are generally no security issues around adding `Access-Control-Allow-Origin: *` to any resource (unless it's using access control by IP address), but in this case adding the header to the JSON-LD is enough of a solution, thanks :)
