### ISSUE TITLE
Rework non-functional requirements in use case document

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#537]
Breaking up #205 - see http://w3c.github.io/csvw/use-cases-and-requirements/#can-req-non-func
- [ ] expand requirements descriptions
- [ ] have we met this requirement? either move into Accepted Requirements or flag as Deferred Requirements in GitHub

**Comment by 6a6d74** [comment]
Following review and update of requirements, non-functional requirements are all moved to the data model requirements category. See PR #808.
