### ISSUE TITLE
Rework requirements re data model in use case document

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#538]
Breaking up #205 - see http://w3c.github.io/csvw/use-cases-and-requirements/#data-model-req
- [x] expand requirements descriptions
- [x] have we met this requirement? either move into Accepted Requirements or flag as Deferred Requirements in GitHub

**Comment by 6a6d74** [comment]
Data model requirements expanded and categorized as accepted, partially accepted or deferred in PR #808 .
