### ISSUE TITLE
Rework deferred requirements in use case document

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#539]
Breaking up #205 - see http://w3c.github.io/csvw/use-cases-and-requirements/#deferred-req
- [x] expand requirements descriptions
- [x] have we met this requirement? move into Accepted Requirements if we have

**Comment by 6a6d74** [comment]
Following review of the [candidate requirements](http://w3c.github.io/csvw/use-cases-and-requirements/index.html#can-req), the following requirements are considered to be DEFERRED within the CSVW specifications:

**R-CsvToXmlTransformation
Ability to transform a CSV into XML**

[DEFERRED]
[The charter of the Working Group (http://www.w3.org/2013/05/lcsv-charter.html) includes a work item for CSV to XML conversion. Given that there is only a single use case providing motivation for this requirement, and that the Working Group was unable to find XML experts to assist in delivery of this work item, the Working Group were forced to abandon this deliverable.]

**R-ConditionalProcessingBasedOnCellValues
Ability to apply conditional processing based on the value of a specific cell**

> [DEFERRED]
> [comment on use of _transformation definitions_ that define how a script or template may be used to provide such conditional processing; also that the output from JSON or RDF transformation may be subjected to post-processing to achieve the desired outcome. Details of these transformation scripts / templates and post processing is outside the scope of this specification]

**R-CommentLines
Ability to identify comment lines within a CSV file and skip over them during parsing, format conversion or other processing**

> [DEFERRED … non-normative]
> [use of _comment prefix_ as specified within a _dialect description_; default is “#” … a _dialect description_ provides ‘hints’ to parsers about how to process the tabular data file]

**R-NonStandardCellDelimiter
Ability to parse tabular data with cell delimiters other than comma (,)**

> [DEFERRED … non-normative]
> [use of _delimiter_ as specified within a _dialect description_; default is “,” … a _dialect description_ provides ‘hints’ to parsers about how to process the tabular data file]

**R-CsvAsSubsetOfLargerDataset
Ability to assert how a single CSV file is a facet or subset of a larger dataset**

> [DEFERRED]
> [comment that this specification does not provide any description of the relationship between tables beyond their membership in a given _group of tables_; other specifications such as [RDF Data Cube] and [VoID] provide mechanisms to describe subsets of data that may be of use in meeting this requirement. Such descriptions can be included as metadata annotations in the form of _notes_ or _common properties_]

All other candidate requirements are accepted.

Finally, note that the requirement **R-UnitMeasureDefinition, _Ability identify/express the unit of measure for the values reported in a given column_** has been ACCEPTED even though there is no native support for describing units of measurement ... 

> [ACCEPTED]
> [comment that this specification provides no native mechanism for expressing the unit of measurement associated with values of cells in a column; for example, stating that the floating-point numbers in a column with name “distance” are provided in kilometers. However, annotations may be used to provide this additional information. The [CSVW Primer] provides examples of how this may be achieved (http://w3c.github.io/csvw/primer/#how-do-you-support-units-of-measure); from providing descriptive metadata to enabling transformation of cell values to structured data with unit of measurement statements. The [RDF Data Cube vocabulary] provides another alternative for annotations; structural metadata is used to provide metadata to interpret data values - such as the unit of measurement.]

**Comment by iherman** [comment]
Wow. We did pretty good then!

Ivan

> On 6 Feb 2016, at 17:26, Jeremy Tandy notifications@github.com wrote:
> 
> Following review of the candidate requirements http://w3c.github.io/csvw/use-cases-and-requirements/index.html#can-req, the following requirements are considered to be DEFERRED within the CSVW specifications:
> 
> R-CsvToXmlTransformation
> Ability to transform a CSV into XML
> 
> [DEFERRED]
> [The charter of the Working Group (http://www.w3.org/2013/05/lcsv-charter.html http://www.w3.org/2013/05/lcsv-charter.html) includes a work item for CSV to XML conversion. Given that there is only a single use case providing motivation for this requirement, and that the Working Group was unable to find XML experts to assist in delivery of this work item, the Working Group were forced to abandon this deliverable.]
> 
> R-ConditionalProcessingBasedOnCellValues
> Ability to apply conditional processing based on the value of a specific cell
> 
> [DEFERRED]
> [comment on use of transformation definitions that define how a script or template may be used to provide such conditional processing; also that the output from JSON or RDF transformation may be subjected to post-processing to achieve the desired outcome. Details of these transformation scripts / templates and post processing is outside the scope of this specification]
> 
> R-CommentLines
> Ability to identify comment lines within a CSV file and skip over them during parsing, format conversion or other processing
> 
> [DEFERRED … non-normative]
> [use of comment prefix as specified within a dialect description; default is “#” … a dialect description provides ‘hints’ to parsers about how to process the tabular data file]
> 
> R-NonStandardCellDelimiter
> Ability to parse tabular data with cell delimiters other than comma (,)
> 
> [DEFERRED … non-normative]
> [use of delimiter as specified within a dialect description; default is “,” … a dialect description provides ‘hints’ to parsers about how to process the tabular data file]
> 
> R-CsvAsSubsetOfLargerDataset
> Ability to assert how a single CSV file is a facet or subset of a larger dataset
> 
> [DEFERRED]
> [comment that this specification does not provide any description of the relationship between tables beyond their membership in a given group of tables; other specifications such as [RDF Data Cube] and [VoID] provide mechanisms to describe subsets of data that may be of use in meeting this requirement. Such descriptions can be included as metadata annotations in the form of notes or common properties]
> 
> All other candidate requirements are accepted.
> 
> Finally, note that the requirement R-UnitMeasureDefinition, Ability identify/express the unit of measure for the values reported in a given column has been ACCEPTED even though there is no native support for describing units of measurement ...
> 
> [ACCEPTED]
> [comment that this specification provides no native mechanism for expressing the unit of measurement associated with values of cells in a column; for example, stating that the floating-point numbers in a column with name “distance” are provided in kilometers. However, annotations may be used to provide this additional information. The [CSVW Primer] provides examples of how this may be achieved (http://w3c.github.io/csvw/primer/#how-do-you-support-units-of-measure http://w3c.github.io/csvw/primer/#how-do-you-support-units-of-measure); from providing descriptive metadata to enabling transformation of cell values to structured data with unit of measurement statements. The [RDF Data Cube vocabulary] provides another alternative for annotations; structural metadata is used to provide metadata to interpret data values - such as the unit of measurement.]
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/w3c/csvw/issues/539#issuecomment-180805149.

---

Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
Seems that way :-)

**Comment by 6a6d74** [comment]
All deferred requirements now updated. See PR #808.
