### ISSUE TITLE
Interlinking CSV and CSVW

### ISSUE THREAD

**Issue by dret** [w3c/csvw#542]
i am wondering whether for the tabular-metadata document, it would make sense to mention the possibility of interlinking those via the IANA-registered describes/describedby link relations. i am assuming CSVW-CSV often is a one-to-many relation, so maybe describedby is more often useful than the other way around. but in either case, maybe mentioning this could help people to better interlink those resources on the web. those relationships could for example be exposed in HTTP headers.

**Comment by gkellogg** [comment]
Hi @dret,

As you probably know, there is [provision](http://www.w3.org/TR/tabular-data-model/#link-header) for a CSV file to reference it's metadata using the `describedby` link relation. I think what your suggesting is that a Metadata file might also relate itself to the CSV files it describes through HTTP headers. This would be repeating information within the metadata file itself, so I'm not entirely sure how software might make use of this, but it wouldn't be inappropriate to use the `describes` relationship. So, in the [countries metadata example](https://raw.githubusercontent.com/w3c/csvw/gh-pages/examples/countries.json), a server might return the following headers:

```
Link: <http://example.org/countries.csv>; rel="describes"; type="text/csv"
Link: <http://example.org/country_slice.csv>; rel="describes"; type="text/csv"
```

**Comment by iherman** [comment]
@gkellogg I am not sure I understand your example. Shouldn't be something like

  Link: <http:

**Comment by iherman** [comment]
@gkellogg @dret : I would expect these to be non-normative. Ie, we could say something like a metadata file MAY include the `describes` return header. Many of our users may not be in position to influence the return headers, ie, a normative requirement would not be appropriate.

**Comment by dret** [comment]
yes, absolutely agree that this is a MAY. but maybe a useful MAY if people want to link things and wonder how to best do it.

**Comment by iherman** [comment]
@dret, are you o.k. closing this issue by virtue of #547 (the final text is [in the editors' draft](http://w3c.github.io/csvw/syntax/index.html#link-header))?

Thanks.

**Comment by dret** [comment]
absolutely. thanks for looking at this and using it!
