### ISSUE TITLE
Test requirements

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#545]
The following are classes of tests, either implemented, or needing implementation. When considering new tests, add them with an open checkbox to this element. When completed, mark off in the issue.
- [x] Simple Tests – no metadata
- Examples
  - [x] country-codes-and-names (test010)
  - [x] tree-ops (test011)
  - [x] countries (test030-031)
  - [x] events listing (test032-033)
  - [x] roles (test034-035)
  - [x] tree-ops-ext (test036-037)
- [x] Metadata location (test011-018)
  - [x] file-metadata with query component
  - [x] file-metadata not referencing file
  - [x] directory-metadata with query component
  - [x] directory-metadata not referencing file
  - [x] file-metadata not describing file skips metadata
  - [x] link-metadata not describing file skips metadata
  - [x] directory-metadata not describing file skips metadata
  - [x] user-metadata not describing file uses metadata
  - [x] link-metadata not describing file uses file-metadata
  - [x] file-metadata not describing file uses directory-metadata
- HTTP Headers
  - [x] text/csv;header=absent
- Dialect
  - [x] trim=start
  - [x] trim=end
  - [x] trim=true
  - [x] header=false
  - [x] header=false and headerRowCount=1
  - [x] header=false and skipRows=1
  - [x] delimiter
  - [x] commentPrefix in header
  - [x] commentPrefix in rows
  - [x] skipColumns
  - [x] skipBlankRows
  - [x] skipInitialSpace
  - [x] as URL reference
  - [x] table dialect vs tablegroup dialect
  - [x] invalid commentPrefix
  - [x] invalid delimiter
  - [x] invalid doubleQuote
  - [x] invalid encoding
  - [x] invalid header
  - [x] invalid headerRowCount
  - [x] invalid lineTerminators
  - [x] invalid quoteChar
  - [x] invalid skipBlankRows
  - [x] invalid skipColumns
  - [x] invalid skipInitialSpace
  - [x] invalid skipRows
  - [x] invalid trim
- Inherited properties
  - [x] propogation (test038)
  - [x] valid properties (test039)
  - [x] invalid null
  - [x] invalid lang
  - [x] invalid textDirection
  - [x] invalid separator
  - [x] invalid ordered
  - [x] invalid default
  - [x] invalid dataype
  - [x] invalid aboutUrl
  - [x] invalid propertyUrl
  - [x] invalid valueUrl
  - [x] required with empty column
  - [x] separator
- Table Groups
  - [x] no tables
  - [x] no url
  - [x] empty tables
  - [x] tableDirection
  - [x] invalid @id
  - [x] invalid @type
  - [x] inconsistent array values: tables
  - [ ] table group incompatibility
- Table
  - [x] tableDirection
  - [x] invalid @id
  - [x] invalid @type
  - [x] inconsistent array values: transformations
  - [x] invalid tableSchema
  - [x] invalid dialect
  - [x] table incompatibility
  - [x] When comparing URLs, processors MUST use Syntax-Based Normalization as defined in [[RFC3968]]. Processors   perform Scheme-Based Normalization for HTTP (80) and HTTPS (443)
- Schema
  - [x] invalid @id
  - [x] invalid @type
  - [x] inconsistent array values: columns
  - [x] inconsistent array values: foreignKeys
  - [x] invalid columnReference
  - [x] invalid primaryKey
  - [x] invalid reference
  - [x] foreign key referencing non-existant tables/columns (multiple scenarios)
  - [x] primary key uniqueness issues (multiple scenarios)
- Column
  - [x] invalid @id
  - [x] invalid @type
  - [x] titles with invalid language
  - [x] titles with non-string values
  - [x] titles with invalid value
  - [x] titles with non-string array values
  - [x] invalid suppressOutput
  - [x] invalid name
  - [x] invalid virtual
  - [x] non-unique column names
  - [x] invalid column name (multiple scenarios)
  - [x] name annotation from title percent encoded
  - [x] virtual only after non-virtual
- Dialect
  - [x] invalid @id
  - [x] invalid @type
- Template
  - [x] invalid @id
  - [x] invalid @type
- Datatype
  - [x] non-builtin datatype (multiple scenarios)
  - [x] datatype variations with patterns (multiple scenarios)
  - [x] length != minLength
  - [x] length != maxLength
  - [x] minLength/maxLength data violations
  - [x] length/minLength/maxLength with base not string, binary or subtype (many combinations)
  - [x] minInclusive and minExclusive
  - [x] maxInclusive and maxExclusive
  - [x] minimum != minInclusive
  - [x] maximum != maxExclusive
  - [x] minInclusive and maxInclusive are specified and maxInclusive is less than minInclusive
  - [x] maxExclusive <= minInclusive
  - [x] maxExclusive  <= minExclusive
  - [x] maxInclusive <=  minExclusive
  - [x] minimum, minInclusive, maximum, maxInclusive, minExclusive, or maxExclusive are specified and the base datatype is not a numeric, date/time, or duration type
  - [x] numeric value variations
  - [x] numeric value variations
  - [x] numeric values out of format
  - [x] date/time format variations, matching and not matching
  - [x] date/time format string errors
  - [x] duration format variations, matching and not matching
  - [x] duration format string errors
  - [x] datatype @id an absolute URL
  - [x] datatype @id that is that of a built-in datatype
  - [x] fractional seconds
- Common Properties
  - [x] context in common property
  - [x] @value value out of range
  - [x] @type out of range (in node and in value)
  - [x] @value with @language and @type
  - [x] @value with extra properties
  - [x] invalid @language in @value
  - [x] @type in node as array
  - [x] @id with bnode
  - [x] illegal @ keywords
  - [x] @list value
  - [x] @set value
- Other
  - [x] invalid @language
  - [x] invalid JSON
  - [x] undefined properties
  - [x] row titles
- CSVs
  - [x] same number of columns in each row
  - [x] name compat with title
  - [x] title compete with title with language wildcard
  - [x] title incompatible with title on case
  - [x] title incompatible with title on language
  - [x] title compatible with title on less specific language
    contain less).
- CSV2RDF
  - [x] If a Datatype has an `id` annotation, it is used in preference to `base`.

**Comment by gkellogg** [comment]
When #543 is accepted, we'll need a test on CSV2RDF to ensure that it uses the `id` annotation for datatypes literals, in preference to `base`.

**Comment by gkellogg** [comment]
@JeniT @iherman @6a6d74 Not clear if test128 should be fatal, issue a warning, or an error when validating only. It tests for duplicate column names, which indicates that it is invalid metadata, which in some cases prevents processing from continuing, and in others, issues a warning and causes the property to be ignored. For example, if the `name` was set to `1`, this would be ignored and a warning issued. We're not totally clear on when a processor (e.g., a converter) must halt when it detects invalid metadata, and when a processor simply ignores the value. As is, it is an error only when validating, but my thought is that it should probably halt processing in general. We should maybe consider this behavior for other properties which are simply ignored.

**Comment by iherman** [comment]
Multiple names can mess up with the conversion algorithms, namely when URI templates are used. My instinct says that the conversion algorithm should stop.

**Comment by gkellogg** [comment]
Yes, but the broader question is when is a problem in metadata fatal, and when is it ignored (when not validating)? And, do we need to add text to the metadata spec which clarifies this?

**Comment by iherman** [comment]
> On 29 May 2015, at 19:16 , Gregg Kellogg notifications@github.com wrote:
> 
> Yes, but the broader question is when is a problem in metadata fatal, and when is it ignored (when not validating)?

I would think when it leads to undecidable situation in the conversions. Multiple names are one of those; from the top of my head I do not know of any other.

> And, do we need to add text to the metadata spec which clarifies this?
