### ISSUE TITLE
In Media Type registration: 8bit compatibility

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#546]
Comment by Chris Lilley on IRC

```
[13:58]  <ChrisL>   ivan, "When JSON is written in UTF-8, JSON is 8bit
[13:58]  <ChrisL>   compatible ([RFC2045])"
[13:58]  <ChrisL>   so, 8bit not binary, since utf-8 is the default encoding
[13:59]  <ChrisL>   your media type registration says binary
[14:00]  <ChrisL>   rfc6839 (which you reference) says the above
```

**Comment by JeniT** [comment]
Not sure what to do here: [rfc7159](https://tools.ietf.org/html/rfc7159) says binary. I imagine IETF will push back if they think we've got it wrong.

**Comment by yakovsh** [comment]
I think this issue originates from the fact that JSON can be specified in UTF-8, UTF-16 or UTF-32, while for media types the choices are 7-bit, 8-bit or binary. Thus, UTF-16 and UTF-32 are automatically considered binary.

There seems to be a conflict also between RFC 7159 and RFC 6839. I look at the some recent registrations and they seem to go both ways.

**Comment by yakovsh** [comment]
I submitted an errata report to the RFC Editor on this:

http://www.rfc-editor.org/errata_search.php?rfc=6839

**Comment by yakovsh** [comment]
There is no consensus from the IETF, it seems that either approach is acceptable. Using the approach in 6839 may have other implication since UTF-8 has restrictions on line length as per RFC 2045.

**Comment by iherman** [comment]
(transcribing a [mail](http://www.w3.org/mid/CAPQd5oRqRcL=QJEOSHvLKhjNEMjzbf9OZHJ5CvmEcMMZdv+_aQ@mail.gmail.com) of @yakovsh to have it all at one place)

> Here is the reply from the IETF folks. Short summary is that the
> language in RFC 6839 should be followed instead of 7159. That means
> the encoding should read as follows:
> 
> > Encoding considerations:
> > 
> > As per section 3.1 of RFC 6839, when JSON is written in UTF-8,
> > encoding is 8-bit; when JSON is written in UTF-16 or UTF-32, encoding
> > is binary.

And his [own additional comment](http://www.w3.org/mid/CAPQd5oRP8WkuOFarXVsm=1nL6g2_K3sKrrrEfkBvhAydEfdLyg@mail.gmail.com):

> Followup on this:
> 
> It seems that either approach is fine. I am inclined to leave it as
> is, and if the media types list finds an issue, they will let us know.

**Comment by iherman** [comment]
Per [yakov's comment](http://www.w3.org/mid/CAPQd5oRP8WkuOFarXVsm=1nL6g2_K3sKrrrEfkBvhAydEfdLyg@mail.gmail.com) the issue is closed without further actions.
