### ISSUE TITLE
Minor grammatical error in 4.2 Tables

### ISSUE THREAD

**Issue by LJWatson** [w3c/csvw#548]
Tabular Data Model:

"suppress output — a boolean that indicates whether or not this table should be suppressed in any output generated from the converting the 
group of tables
 that this table belongs to into another format, as described in 
section 6.5 Converting Tables."

The words "... from the converting the..." cause the sentence to read badly.

**Comment by iherman** [comment]
Thanks @LjWatson, I have made the change (in #550). The sentence now reads:

> <li><dfn title="table suppress output">suppress output</dfn> &mdash; a boolean that indicates whether or not this table should be suppressed in any output generated from converting the <a>group of tables</a>, that this table belongs to, into another format, as described in [ref].</li>

If you agree with the change, can you either close the issue, or ping me to do it? 

Thanks!
