### ISSUE TITLE
Handling multiple titles

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#56]
Copying @gkellogg's comment from #53 into this new issue:

The extracted header rows are different from the name of the column. I guess this is most closely related to the `title` rather than the `name` metadata. However, it does come into play for an uninformed-mapping, where there is no metadata, and presumably the column header is used to construct the default `name`.

If we have a CSV with two header rows, such as the [Use Case #12](http://www.w3.org/TR/2014/WD-csvw-ucr-20140327/#UC-ChemicalStructures):

```
5
methane molecule (in angstroms)
C        0.000000        0.000000        0.000000
H        0.000000        0.000000        1.089000
H        1.026719        0.000000       -0.363000
H       -0.513360       -0.889165       -0.363000
H       -0.513360        0.889165       -0.363000
```

I think that this shows four columns where the first column is the only one with a header cell, which is the two values ["5", "methane molecule (in angstroms)"].

The metadata document states the following:

> If the column already has a title annotation (because a header row has been included in the original CSV file) then a validator must issue a warning if the existing title annotation is not the same as any of the possible column titles.

Is this one title or two? How must this correspond to `title` information from the metadata?

(This seems to be off-topic for this issue, but may need to be tracked someplace, anyway).

**Comment by JeniT** [comment]
I'd assume that this CSV file was processed with the dialect description:

```
{
  "headerRows": 2
}
```

so that the first two rows were recognised as header rows. Then yes, I think we would make it so that the column had two **title** annotations, and I think that the spec should say that every **title** annotation on the column (from the CSV file) has to have a matching **title** annotation in the metadata file. That would mean the column specification might look like:

```
{
  "name": "col1",
  "title": ["5", "methane molecule (in angstroms)"],
  ...
}
```

**Comment by JeniT** [comment]
@gkellogg does the above make sense?

@ericstephan perhaps this would make a good example to add to the metadata document?

**Comment by gkellogg** [comment]
Yes, but to maintain the sequence, we might need to define "title" as having `@container`: `@list`.

**Comment by 6a6d74** [comment]
Looking at this I'm not sure that `5` and `methane molecule (in angstroms)` are column titles ...
- `5` seems to be an indication of the number of atoms in the molecule - the number of rows in the table
- `methane molecule (in angstroms)` is a title for the entire table

I am interpreting this table as providing the relative positions of the 5 atoms of the methane molecule (carbon & 4 hydrogen atoms) relative to each other (carbon is at the origin) expressed as an [x, y, z] vector with units of angstroms.

Column 1 is the atom type, columns 2 - 4 provide the [x, y, z] position.

I think that there will be situations where there are multiple titles (e.g. to be extracted from multiple header rows) - but this is a bad example to express that. Also, I note that the 2nd line of a header often provides annotations (such as the unit of measure). 

We will need to determine how to identify annotations (such as table titles and units of measure) within the CSV file so that they can be processed accordingly.

**Comment by ericstephan** [comment]
Yes @jenitennison I agree it would be a good example.  

Are you adding the examples directly in the text of the document as well as providing a link to an actual example in github.

Thanks,

Eric

**Comment by ericstephan** [comment]
I see your point Jeremy.  The first two rows really represent what I might think of as a header block as opposed to the traditional column headers of the data itself.

Eric

**Comment by 6a6d74** [comment]
@ericstephan: agreed.

**Comment by ericstephan** [comment]
Use case #23 [1] might serve as a better example @jenitennison.  In this
example use of the double headers is clear.  This particular example
provides a non-language specific "key" in the first row and tags written in
a particular language on the second row.

What do you think?

Eric

.         100,          101,            A00
Location name,Location code,People affected
       Town A,     01000001,           2000
       Town B,     01000002,            750
       Town C,     01000003,           1920

References

[1] http://w3c.github.io/csvw/use-cases-and-requirements/#UC-CollatingHumanitarianResponseInformation

**Comment by JeniT** [comment]
@ericstephan yes, that's a good example

@gkellogg would you be willing to create and maintain a JSON-LD context document that contained things like `"title": { "@container": "@list" }`? (How does that interact with having multilingual titles?)

**Comment by gkellogg** [comment]
Sure, I'll create a default context. It should probably ultimately go at http://www.w3.org/ns/csvw and be served via content-negotiation, or explicit path including ".jsonld". I think we do this for /ns/json-ld right now.

The title definition you showed works with either a play value, or zero or more in an array. In the plain value case, it is not actually in a list, but will be interpreted property by conforming JSON-LD processors.

**Comment by JeniT** [comment]
Editor action: Add the above example with multiple headers to the spec to indicate how it's handled.
