### ISSUE TITLE
How should class level qualified properties be transformed to RDF

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#57]
Apart from a few cases ("title" and "language" at this moment), most of the generic, top level metadata are supposed to be qualified, meaning, are of the form `prefix:reference`. How should one transform this into proper URI-s for RDF? There seems to be two possibilities:
- require the presence of a `@context` in the metadata that defines a URI for the prefix and use that
- like before, but use also a set of predefined URI-s in case the prefix definition is missing.

For the second case, the predefined prefixes for the RDFa initial context[1] might be reused here.

[1] http://www.w3.org/2011/rdfa-context/rdfa-1.1

**Comment by JeniT** [comment]
@iherman The metadata document currently references the RDFa initial context, providing the only list of prefixes that should be recognised, and it's not possible to extend this list (as `@context` is highly restricted). Can this issue be closed?

**Comment by iherman** [comment]
Closing by virtue of the latest evolutions, i.e., reference to the RDFa initial context.
