### ISSUE TITLE
Can RDF data be generated from non UTF-8 encoded CSV data

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#575]
(Comment originally [posted by Steven Atkin](https://lists.w3.org/Archives/Public/public-csv-wg/2015Jun/0001.html))

4.2 Generating RDF
http://www.w3.org/TR/2015/WD-csv2rdf-20150416/#generating-rdf

There is no mention of whether or not CSV data must be encoded in UTF-8. The model for tabular data indicates that non UTF-8 CSV data should specify the charset in the Content-Type header. The specification should clearly indicate that a conversion to UTF-8 needs to be performed when the CSV data is not in Unicode.

See 7.2 Encoding http://www.w3.org/TR/2015/WD-tabular-data-model-20150416/#encoding

**Comment by JeniT** [comment]
I believe that this is fixed with #581

**Comment by iherman** [comment]
I agree. An additional remark, to the commenter: RDF 1.1 Concepts clearly says that literals in RDF are in Unicode, ie, starting from the datamodel no extra steps is required when generating RDF (the RDF conversion creates an abstract graph, not a specific serialization)

**Comment by JeniT** [comment]
responded to Steven https://lists.w3.org/Archives/Public/public-csv-wg/2015Jun/0026.html

**Comment by iherman** [comment]
Noting [Steven's positive reply](http://www.w3.org/mid/OFC54A4ED7.61760F1B-ON80257E60.0068C761-80257E60.0068F8D7@us.ibm.com)
