### ISSUE TITLE
Do Unicode Strings get normalized when placed into RDF

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#577]
(Comment originally [posted by Steven Atkin](https://lists.w3.org/Archives/Public/public-csv-wg/2015Jun/0002.html))

4.3 Interpreting datatypes
http://www.w3.org/TR/2015/WD-csv2rdf-20150416/#datatypes

When strings are parsed from the CSV data are they first normalized before being mapped to the xsd:string datatype? For example, are the strings normalized into Unicode Normal Form C.

It is recommended that text not be normalized if it is already in a Unicodeencoding. If the text is not in Unicode then a normalizing transcoder should be used and the Unicode Normal Form C should be used.

**Comment by JeniT** [comment]
I believe that this is fixed with #581, but could perhaps do with some clear text saying that there is no Unicode normalization performed in the csv2rdf conversion.

**Comment by iherman** [comment]
See also my comments in https://github.com/w3c/csvw/issues/575#issuecomment-108434857

**Comment by JeniT** [comment]
Responded to Steven https://lists.w3.org/Archives/Public/public-csv-wg/2015Jun/0029.html

**Comment by iherman** [comment]
Noting [Steven's positive reply](http://www.w3.org/mid/OF621A5788.758C0C4A-ON80257E60.006934DF-80257E60.00693DE2@us.ibm.com)
