### ISSUE TITLE
Can JSON data be generated from non UTF-8 encoded CSV data

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#579]
(Comment originally [posted by Steven Atkin](https://lists.w3.org/Archives/Public/public-csv-wg/2015Jun/0004.html))

4.2 Generating JSON
http://www.w3.org/TR/2015/WD-csv2json-20150416/#generating-json

There is no mention of whether or not CSV data must be encoded in UTF-8. The model for tabular data indicates that non UTF-8 CSV data should specify the charset in the Content-Type header. The specification should clearly indicate that a conversion to UTF-8 needs to be performed when the CSV data is not in Unicode.

See 7.2 Encoding
http://www.w3.org/TR/2015/WD-tabular-data-model-20150416/#encoding

**Comment by JeniT** [comment]
I believe that this is fixed with #581

**Comment by iherman** [comment]
I believe a remark in the csv2json document whereby the output should be encoded in UTF-8 is still necessary.

**Comment by iherman** [comment]
Actually, it is a little bit more complicated, see [DanBri's mail](

**Comment by iherman** [comment]
Reopened because the comment has to be circled back to Steven before closing

**Comment by iherman** [comment]
On https://github.com/w3c/csvw/issues/579#issuecomment-108438260: JSON is in UTF-8, so the remark is probably unnecessary

**Comment by 6a6d74** [comment]
See PR #600 which explicit notes that JSON conversion applies no further unicode normalization to the tabular data content.

JSON can be encoded in UTF-8, UTF-16, UTF-32 etc. ... but it supports any unicode character. So given that I have not included any statements about choice of encoding for the generated JSON: this would be an implementation decision.

@iherman - are you happy with this?

**Comment by iherman** [comment]
Fine with me. We still have to get back to Steven before closing the issue.

**Comment by JeniT** [comment]
Responded to Steven https://lists.w3.org/Archives/Public/public-csv-wg/2015Jun/0030.html

**Comment by iherman** [comment]
Noting [Steven's positive reply](http://www.w3.org/mid/OF1BF70002.4B353F29-ON80257E60.0069519B-80257E60.00695A34@us.ibm.com)
