### ISSUE TITLE
How should class level qualified properties be transformed to JSON

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#58]
Most of the top level metadata properties are defined to be qualified, i.e., `prefix:reference` format. Is the best way of converting this into pure JSON is to do it verbatim?

**Comment by JeniT** [comment]
Suggested resolution: Conversion to JSON should map prefixed properties verbatim rather than mapping them to full URLs.

**Comment by iherman** [comment]
I agree.

**Comment by JeniT** [comment]
Resolved at Feb F2F: In JSON output, we do not expand property names into URLs.

**Comment by 6a6d74** [comment]
csv2json doc now updated; it explicitly says that any prefixes used (e.g. from RDFa 1.1 Initial Context) are not expanded; implying that we treat these prefixed names just as "dumb" names in the JSON output.
