### ISSUE TITLE
length constraint confusion

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#588]
[Length constraints](http://w3c.github.io/csvw/syntax/#length-constraints) are described as using both the `cell string value` and the `cell value`, which differs if it is a binary type.

If we simply use `cell string value`, then calculating the length is much simpler, as it can be done prior to extracting the actual value and reduces the required logic.

**Comment by iherman** [comment]
See the separate issue #591 that is related to this (raised as a separate issue to make it clearer)

**Comment by JeniT** [comment]
Length constraints should only apply to the cell value. It might be simpler to apply the type constraints to the string value but it's inconsistent to do so given that the other constraints apply to the (semantic) values, and given that a cell can have multiple (semantic) values, each of which should adhere to the datatype.

For example, if I have:

```
"separator": " ",
"datatype": {
  "length": 1
}
```

then I should be able to have a cell whose string value is `"a b c"`, meaning its value is the sequence `["a", "b", "c"]` each of which are one-character strings.

**Comment by gkellogg** [comment]
@JeniT: looks like you clarified this in 2831ecba6458e28fe51348611d51a43d81e295bd, but I hadn't merged up to that point when I was looking at it. I'll clarify that if the value is an array, the constraint applies to each element in the array and update tests accordingly.

From what @iherman indicates this needs to be code points for strings, which I'll add.
