### ISSUE TITLE
Fraction of seconds to be recognized?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#595]
(copy if [issue](http://www.w3.org/mid/89610835-7BB4-41E1-AFC5-50A954E8AAB7@iris.washington.edu) coming in from Mike Stults, mike@iris.washington.edu, through the public comment list.)

> Hello,
> 
> I just discovered this CSV working group, so maybe you have already dealt with this, but for many data sets, fractions of seconds may be needed.
> 
> My naive suggestions is something like
> 
> HH:mm:ss.S e.g 15:02:37.246 or 15:02:37.2 or 15:02:37.246359
> 
> etc. for any occurrence of "ss" form.
> 
> Thank You,
> 
> Mike

/Cc @JeniT @gkellogg

**Comment by iherman** [comment]
The document refers to [the Unicode definitions](http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table) which does include the symbol `S` for fractional seconds. In other words, it seems to me that this is only an editorial issue: a reference to fractional seconds should be added to the second bullet item in the [relevant model document section](http://w3c.github.io/csvw/syntax/#formats-for-dates-and-times). 

It may require some more test cases...

@JeniT @gkellogg

**Comment by JeniT** [comment]
Responded at https://lists.w3.org/Archives/Public/public-csv-wg-comments/2015Jun/0004.html
