### ISSUE TITLE
rowTitles description in metadata vocab document

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#596]
I am belatedly adding support for row titles in the csv2\* documents. I see that the metadata document now has a property `rowTitles`, defined in [Section 5.5 Schemas](http://w3c.github.io/csvw/metadata/#schemas):

---

`rowTitles`

A column reference property that holds either a single reference to a column description 
object or an array of references. The value of this property determines the titles annotation 
for each row within a table that uses this schema. The titles annotation holds the list of 
the values of the cells in that row that are in the referenced columns; if the value is not a 
string or has no associated language, it is interpreted as a string with an undefined 
language (und).

---

I've got to say that this wording doesn't make a whole lot of sense to me. Furthermore, I may have missed the point, but why would `rowTitles` be a _column reference property_?

**Comment by 6a6d74** [comment]
I also note that `rowTitles` does not appear in the CSVW Namespace document.

**Comment by gkellogg** [comment]
Yes, I discovered that the ns doc needs to be updated yesterday and will get to it today.

Regarding rowTitles being a column reference property, this makes sense, as it identifies a column who's cell-values are used as the row title. I also need to implement that myself, and add a test or two.

The wording makes sense to me.

**Comment by 6a6d74** [comment]
@gkellogg - now that you've interpreted for me; yes, it makes sense. `rowTitles` identifies the columns where the the `titles` for a given row can be found. Within the csv2\* docs I don't need to worry about this because the `titles` annotation is already provided. See PR #597 for the solution there.
