### ISSUE TITLE
How should ``language`` be used in JSON mapping?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#60]
The question is whether there should be any reflection of the language tag for a specific literal. Proposal:
- because JSON does not have language information, the cell value is just copied verbatim.

Seems obvious, may be decided quickly either on email or on telco

**Comment by JeniT** [comment]
There are CSV files that contain columns with different languages per column (an example is the list of Welsh local authorities, which contains a column for the English name and a column for the Welsh name of the local authority). However, I think it's likely that in the JSON version the name of the property would be used to identify the language; using JSON-LD-like objects seems overkill.

Suggested resolution: The supplied language of a column is ignored when converting to JSON.

**Comment by JeniT** [comment]
Oh, see #59 where there's a resolution. This is resolved and is pending editor action.

**Comment by 6a6d74** [comment]
csv2json doc updated as per resolution in #59; language is ignored because JSON doesn't support it.
