### ISSUE TITLE
Editorial changes requested

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#602]
These editorial [comments](http://www.w3.org/mid/CACsW8eG-k-Tx7og3SjQFUopKwoZJMJiESe5AsuSU4Q5Vu270rA@mail.gmail.com) came through the mailing list:

> http://www.w3.org/TR/2015/WD-tabular-data-model-20150416/
> 1. `i.e.` and `e.g.` should be written as such
> 2. please use en-us spellings (W3C's official language is en-us)
>    (this means -ised -> -ized / -ising -> izing / -isation -> -ization /
>    -iour -> -ior / ...)
> 3. RTL, LTR, UTF are better written in uppercase (to indicate that
>    they're an abbreviation and not some random letters tossed into a
>    document)
> 
> Fig. 1 Diagram showing the built-in datatypes, based on [xmlschema11-2]; names in paranthesis [sic] denote aliases to the [xmlschema11-2] terms (see the diagram in SVG or PNG formats)
> 
> Implementations MUST also recognise date, time, and date/time formats that end with timezone markers consisting of between one and three xs or Xs, possibly after a single space.
> 
> It's better for spell checkers if `x`s and `X`s are written as such
> instead of as you've written them.

(I do not know who `timeless@gmail.com` stands for; he/she is the originator of the comments)

**Comment by JeniT** [comment]
Responded https://lists.w3.org/Archives/Public/public-csv-wg-comments/2015Jun/0003.html

**Comment by iherman** [comment]
Reopen until the we get a reply from the commenter

**Comment by iherman** [comment]
To be consistent, I close the issue while still waiting for the commenter's (hopefully positive) reply. If there is a reply, its reference should be added to the issue.
