### ISSUE TITLE
Use media types and not URLs to refer to formats in transformation descriptions

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#609]
The TAG indicated that while we could use URLs to refer to formats, there are advantages with using media types (eg standardised names) and the barriers are low (it takes an email; third parties can do it). Given that we really want to be referring to media types, they said we should use media types.

**Comment by akuckartz** [comment]
Is this already decided or still discussed?

**Comment by iherman** [comment]
Media types do not necessarily cover all our needs: there are transformations that do not have any. This means the `*format`would have to be defined as "either a standardized name or a URL". Of course this is doable, but I find it slightly more confusing than simply saying the value should be a URL.

So... 0 for me (ie I am neutral but not really positive about it)

**Comment by akuckartz** [comment]
Maybe something like http://www.w3.org/ns/formats/ or http://mediatypes.appspot.com/ can be used ;-)

**Comment by JeniT** [comment]
@akuckartz This is the TAG view. We can go back with arguments against if we have good ones.

@iherman If someone needs to use a format that hasn't got a media type, they can register it. No need to allow both URLs and media types.

**Comment by iherman** [comment]
> On 11 Jun 2015, at 07:53 , Jeni Tennison notifications@github.com wrote:
> 
> @akuckartz This is the TAG view. We can go back with arguments against if we have good ones.
> 
> @iherman If someone needs to use a format that hasn't got a media type, they can register it. No need to allow both URLs and media types.

@JeniT, I do not think it is realistic to expect that, say, mustache or my own transformation engine would be registered; the IETF procedure is just too complicated for many. We do need the URI-s to identify those.

**Comment by JeniT** [comment]
So @iherman says that registering is too hard, and @mnot says it's easy. I propose a test: I will attempt to register Mustache as a media type. Of we get it registered within a week then we use media types, if not then we stick with URLs. Does that sound fair?

**Comment by iherman** [comment]
> On 11 Jun 2015, at 09:29 , Jeni Tennison notifications@github.com wrote:
> 
> So @iherman says that registering is too hard, and @mnot says it's easy. I propose a test: I will attempt to register Mustache as a media type. Of we get it registered within a week then we use media types, if not then we stick with URLs. Does that sound fair?

:-)

Note that it would be even more fair if it was registered by John Doe, and not a person at the head of ODI:-)

Ivan

**Comment by iherman** [comment]
Discussed on telco (and proposed no change): http://www.w3.org/2015/07/01-csvw-irc#T14-51-39

**Comment by akuckartz** [comment]
:+1: for that decision.
