### ISSUE TITLE
What should be the mapping of an empty cell (both RDF and JSON)?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#61]
There seem to be two possibilities:
- issue a triple (resp. a k/v pair) with the simple ""
- not to output anything

At the F2F we decided that there is no difference between an empty cell and a string of value "". As a consequence, at the conversion level, we have no way of knowing whether the intention was to issue an empty string indeed. Ie, the first option seems to be right one.

**Comment by gkellogg** [comment]
It might be useful to have a column setting on how to interpret this. Certainly, if the field maps to a URI, then an empty (or relative) URI is probably not what I had in mind, and I'd rather see nothing emitted.

**Comment by stasinos** [comment]
If the empty cells are merged cells in a spreadsheet, then they should be
interpreted as "same as above", shouldn't they?

s

**Comment by iherman** [comment]
Stasinos,

> On 18 Nov 2014, at 20:57 , Stasinos Konstantopoulos notifications@github.com wrote:
> 
> If the empty cells are merged cells in a spreadsheet, then they should be 
> interpreted as "same as above", shouldn't they? 

By closing Issue #20 we decided that (in the simple case) we generate row-by-row, ie, the notion of "same as above" is not adopted and, probably, that could only be useful if the original spreadsheet merged cells vertically... 

Ivan

> s 
> 
> On 18 November 2014 20:30, Gregg Kellogg notifications@github.com wrote: 
> 
> > It might be useful to have a column setting on how to interpret this. 
> > Certainly, if the field maps to a URI, then an empty (or relative) URI is 
> > probably not what I had in mind, and I'd rather see nothing emitted. 
> > 
> > — 
> > Reply to this email directly or view it on GitHub 
> > https://github.com/w3c/csvw/issues/61#issuecomment-63520219. 
> > 
> > —
> > Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
> On 18 Nov 2014, at 19:30 , Gregg Kellogg notifications@github.com wrote:
> 
> It might be useful to have a column setting on how to interpret this. Certainly, if the field maps to a URI, then an empty (or relative) URI is probably not what I had in mind, and I'd rather see nothing emitted.

I think that makes sense. Of course, the question is: what is the default:-)

(There can be a table level default setting, too...)

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
Based on Gregg's comment I have added the 'metadata vocabulary document' label to this issue.

**Comment by JeniT** [comment]
I propose:
1. In the model document we say that an empty cell is always a null value (this is #40)
2. In the metadata we have an inherited `default` property that provides a default value to use if the value of a cell is `null`; if `default=null` (the default) then the conversion should not map the property/value pair at all, otherwise it should use the default value

So for example if you have:

```
id,postcode,latitude,longitude
1,,57.14416516,-2.114847768
2,AB106RN,,
```

and the metadata

```
"columns": [{
  "name": "id"
}, {
  "name": "postcode",
  "default": ""
}, {
  "name": "latitude",
  "datatype": "number"
}, {
  "name": "longitude",
  "datatype": "number"
}
```

then the mapping would be to something like:

```
[{
  "id": "1",
  "postcode": "",
  "latitude": 57.14416516,
  "longitude": -2.114847768
}, {
  "id": "2",
  "postcode": "AB106RN"
}]
```

Does that work?

**Comment by gkellogg** [comment]
+1

**Comment by iherman** [comment]
Works for me; and, to be very clear, a cell value "" is considered to be a null value, too. (By default, that is.)

I am not 100% sure how parsers behave with

2,AB106RN,,

as opposed to

2,AB106RN,"",

and how that ripples down to the various processors. But the explicit default=null may be used to control that on the author's side.

Ivan

> On 29 Nov 2014, at 13:58 , Jeni Tennison notifications@github.com wrote:
> 
> I propose:
> 
>   • In the model document we say that an empty cell is always a null value (this is #40)
>   • In the metadata we have an inherited default property that provides a default value to use if the value of a cell is null; if default=null (the default) then the conversion should not map the property/value pair at all, otherwise it should use the default value
> So for example if you have:
> 
> id,postcode,latitude,longitude
> 1,,57.14416516,-2.114847768
> 2,AB106RN,,
> 
> and the metadata
> 
> "columns": [{
>   "name": "id"
> }, {
>   "name": "postcode",
>   "default": ""
> }, {
>   "name": "latitude",
>   "datatype": "number"
> }, {
>   "name": "longitude",
>   "datatype": "number"
> }
> 
> then the mapping would be to something like:
> 
> [{
>   "id": "1",
>   "postcode": "",
>   "latitude": 57.14416516,
>   "longitude": -2.114847768
> }, {
>   "id": "2",
>   "postcode": "AB106RN"
> }]
> 
> Does that work?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by stasinos** [comment]
On 19 November 2014 at 11:34, Ivan Herman notifications@github.com wrote:

> > On 18 Nov 2014, at 20:57 , Stasinos Konstantopoulos notifications@github.com wrote:
> > 
> > If the empty cells are merged cells in a spreadsheet, then they should be
> > interpreted as "same as above", shouldn't they?
> 
> By closing Issue #20 we decided that (in the simple case) we generate row-by-row, ie, the notion of "same as above" is not adopted and, probably, that could only be useful if the original spreadsheet merged cells vertically...

I rember that email exchange, but I misunderstood this issue as a
continuation of that discussion. From subsequent emails I now see what
this issue is about.

Sorry for adding noise.

s

**Comment by JeniT** [comment]
Discussed on 14/1/2015 - editors on model/metadata document to:
- [x] add examples (to be basis for test cases)
- [x] add `default` property
- [x] work through what happens with sequences

editors on conversion documents to then update to provide consistency

**Comment by JeniT** [comment]
I think that the only remaining editor action is on the conversion documents now.

**Comment by 6a6d74** [comment]
csv2rdf and csv2json docs updated such that the conversions are based on the tabular data - so they don't care whether an empty string is quoted or not in the CSV+ file. In addition, cells with `null` values are ignored for the conversion.
