### ISSUE TITLE
Language metadata elsewhere than for columns

### ISSUE THREAD

**Issue by r12a** [w3c/csvw#618]
http://www.w3.org/TR/2015/WD-tabular-data-model-20150416/

It is possible to specify default language metadata for columns, but not for tables, rows or cells. It wasn't clear to me why.

A language declaration at the table level could serve as a default for all contained columns - saving some effort.

A language declaration on a cell could override the language declaration for a column, where needed.

**Comment by gkellogg** [comment]
@r12a, as `lang` is an Inherited property, setting it on a Table, does set it for the table, and everything it includes. It can be set on everything from a TableGroup to a Column.

As we don't have separate metadata descriptions for Rows or Cells, there isn't currently any way to set it on specifically for either of those, other than as is inherited from the Table, Schema or Column; this is due to the nature of the Metadata description.

Indeed, setting the `lang` of a Column overrides the `lang` of a Table or Schema. Setting it on the Table causes it to be inherited for the Schema and all Columns.

**Comment by r12a** [comment]
@gkellogg i couldn't find anywhere in the spec that described that `lang` could be set at the Table level. Could you point me to the right place?

**Comment by gkellogg** [comment]
It is described in the Inherited Properties section of the Metadata document:

> A cell may be assigned annotations based on properties on the description objects for the group of tables, table, schema, or column that it appears in. These properties are known as inherited properties and are listed below. To ascertain a value for certain annotations on cells, an application must identify the relevant property in the descriptions of the group of tables, table, schema, or column.

The "lang" property is an inherited property.

**Comment by r12a** [comment]
i see. What initially threw me was that lang is listed as a core annotation for columns (4.3) but not for tables (4.2). This seems inconsistent to me.

section 4.2 links to common properties in tabular-metadata, but not to inherited properties. It seems like that is an omission.  (which applies also to the other nearby sections).

**Comment by gkellogg** [comment]
Yes, that's true, the `lang` annotation is on Column and Cell; setting it as a property on Table, simply ensure that it is propagated. What do you believe a `lang` annotation on Table (or Group of Tables) would  provide for? It would have no effect on the converted output.

**Comment by JeniT** [comment]
In the model, the language only actually applies directly at the cell level: individual cell values have an associated language. That's determined by the `lang` property in the JSON metadata which can be specified within a column description or within a table or table group description. We also retain a **lang** annotation on the column to support data entry (ie to help when adding a new row into the table).

**Comment by JeniT** [comment]
In #639 I've added some notes about the role of inherited properties. This now waits on @r12a's review.

**Comment by r12a** [comment]
i think that's now ok. Thanks.
