### ISSUE TITLE
default value of direction

### ISSUE THREAD

**Issue by r12a** [w3c/csvw#619]
6.5.1 Bidirectional Tables
http://w3c.github.io/csvw/syntax/#bidirectional-tables
(no dated version link available)

"If direction is default then tables should be displayed with attention to the bidirectionality of the content of the file."

may i suggest changing this value to 'auto', in line with the HTML value for dir?  the 'default' direction is actually likely to be ltr.

**Comment by JeniT** [comment]
Thanks for the suggestion. The PR #626 changes `default` to `auto` for `tableDirection`.
