### ISSUE TITLE
Demonstrate independence of primaryKey, foreignKeys and urlTemplates

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#63]

**Comment by JeniT** [comment]
See http://w3c.github.io/csvw/metadata/#examples - is this enough?

**Comment by iherman** [comment]
Hey Jeni

All in all, this seems to be pretty clear, thanks. Some comments/questions:
- I presume it is true that the primary key actually does not play any role in this example. More exactly, a table checker should use that property to ensure that the there is only one row with the value of that key, but that is part of the checker and not, say, the converter. Just checking my understanding...
- We should think about what terms to use for the template. We will have templates used to generate the subject URI for a row, and templates to generate the object for a specific cell. The term "urlTemplate" that you use in the example is specifically used to link into this file from the outside, ie, that is a third possible usage for a template. I think it would be better to use three different names that also specifies what the role of that template is.
- Just thinking loud: this mechanism relies on the fact that a converter has access to the full metadata, ie, the metadata for both tables. What if one is missing, ie, in this example, if the schemas for 'countries.csv' is missing? Would the generation just ignore the foreign keys section altogether? Or is there some sort of a default mechanism? I am more in favour of the former, but we should decide this together...

Thanks!

Ivan

P.S. More generally: with the url template mechanism we discussed at TPAC it is true, isn't it, that the primary keys do not play any role in the conversion algorithms?

> On 26 Nov 2014, at 16:51 , Jeni Tennison notifications@github.com wrote:
> 
> See http://w3c.github.io/csvw/metadata/#examples - is this enough?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
@JeniT: in your example [3.8.1.1 Foreign Key Reference Between Resources](http://w3c.github.io/csvw/metadata/#foreign-key-reference-between-resources) the `primaryKey` specified for resource `https://example.org/countries.csv` is `country` ... I can't see a column name `country` - is this a typo & it should be `countryCode`?

**Comment by 6a6d74** [comment]
@JeniT: in [3.8 Schemas](http://w3c.github.io/csvw/metadata/#schemas) your definition of `foreignKey` is:

"""
An array of foreign key definitions that define how columns within this table link to columns within other tables.
""" 

I wonder if the definition is more like:

"""
An array of foreign key definitions that define how _the values from specified_ columns within this table link to _rows_ within _the same table or_ other tables.
"""

[Use Case #1 - Digital preservation of government records](http://w3c.github.io/csvw/use-cases-and-requirements/#UC-DigitalPreservationOfGovernmentRecords) describes how foreign keys are used to reference rows (records) from within the same CSV file.

**Comment by JeniT** [comment]
@6a6d74 thanks, I've made those changes, although now I think about it, you're actually potentially linking from multiple columns, as in #66 - so will continue discussion about that there.

@iherman:
- yes, the primary key is only used for checking and I don't think they're used in any conversion
- in my head then the ID that is used for the row (eg as the subject within an RDF version) and the ID that you point to for the row using a foreign key (eg as an object within an RDF version) are the same ID and both generated via the relevant `urlTemplate`. I agree that the URI template that you use when turning values in a particular column into URLs is different; I think this is done by specifying a `urlTemplate` on a column description rather than on the table description within the schema
- I think you can't generate links through the foreign key mechanism if you can't find a description of the primary key for the given CSV file for whatever reason

**Comment by JeniT** [comment]
The examples currently in the spec seem to have fulfilled the stated aim of this issue, so closing this, though others about primary keys & foreign key references such as #66 and #130 remain open.
