### ISSUE TITLE
Magic number for application/csvm+json media type registration

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/csvw#631]
> The IANA registration shows no Magic Number, but valid metadata
> documents MUST have the context "http://www.w3.org/ns/csvw”, which
> will typically (although not necessarily) appear at the beginning of
> the document. In fact, this is what my JSON-LD processor looks to to
> not treat it as JSON-LD, but as Tabular Metadata.

I think this is important to note in the IANA registration.  I would suggest adding something like the following:
http://w3c.github.io/csvw/metadata/#iana-considerations
[[
Magic number(s):
   An application/csvm+json document MUST contain a JSON property named "@context" whose value is either the string "http://www.w3.org/ns/csvw" or a JSON array whose first element is the string "http://www.w3.org/ns/csvw".  For parsers that are not JSON-aware, this means that an application/csvm+json document MUST contain the following two strings (including quotes), in order, separated by at least one character (not necessarily whitespace), somewhere in the document though usually near the beginning:

```
   "@context"
   "http://www.w3.org/ns/csvw"
```

]]

**Comment by gkellogg** [comment]
@yakovsh had [previously commented](https://github.com/w3c/csvw/issues/316) the following (issue #316):

> 1. Magic number(s): - I think that magic numbers are specific binary strings, what we are describing may be too vague.

I think this is the reason we didn't set a magic number.

According to [RFC4288](https://tools.ietf.org/html/rfc4288#section-4.11):

> Magic number(s) (length, octet values).  Magic numbers are byte sequences that are always present at a given place in the file and thus can be used to identify entities as being of a given media type.

As this is a JSON document, there is no guarantee that `@context` will even be the first entry in the object, or what the white-space used might be. A regular expression to find it would be fairly easy, but it's not clear that this is the intention of the magic number entry.

@JeniT set this up, and may have some additional thoughts for or against using this as a magic number.

**Comment by dbooth-boston** [comment]
I don't see that any harm could result from adding a magic number description, and it may be beneficial.  A magic number specification can be specified as a regex:
http://linux.die.net/man/5/magic

Now that I think of it, it might be good to include a regex in the description.

**Comment by dbooth-boston** [comment]
Here is another attempt at possible wording:
[[
Magic number(s):
An application/csvm+json document MUST contain a JSON property named "@context" whose value is either the string "http://www.w3.org/ns/csvw" or a JSON array whose first element is the string "http://www.w3.org/ns/csvw". For parsers that are not JSON-aware, this means that an application/csvm+json document MUST contain the following two strings (including quotes), in order, separated by at least one character (not necessarily whitespace), somewhere in the document though often near the beginning:

   "@context"
   "http://www.w3.org/ns/csvw"

In other words, every application/csvm+json document MUST match, somewhere in the document, the following POSIX Extended Regular Expression (regex):

   "@context".+"http://www.w3.org/ns/csvw"

NOTE 1: Although many applications using regular expressions treat a non-escaped period (".") as a special character that matches any non-null character _except_ a newline character, in the above regex the non-escaped period may may match _any_ non-null character (including newline), in accordance with POSIX.  

NOTE 2: The quote characters are a part of the above regex.  

NOTE 3: Because this pattern is not required to be at the beginning of the document, sniffers that limit their magic number checks to an initial portion of the document may fail to detect a match in a conforming application/csvm+json document.
]]

**Comment by yakovsh** [comment]
I don't think that Magic Number would the right place for this since it is constrainted by the IETF for a specific meaning. BUT, I don't think there is anything wrong with adding this information under "additional info"

**Comment by dbooth-boston** [comment]
@yakovsh there is some precedent for a looser interpretation of the Magic Number section.  For example, the XML media type registration says:
http://tools.ietf.org/html/rfc3023#section-3.1
[[
      `Magic number(s): None.`

```
     Although no byte sequences can be counted on to always be
     present, XML MIME entities in ASCII-compatible charsets
     (including UTF-8) often begin with hexadecimal 3C 3F 78 6D 6C
     ("<?xml"), and those in UTF-16 often begin with hexadecimal FE
     FF 00 3C 00 3F 00 78 00 6D 00 6C or FF FE 3C 00 3F 00 78 00 6D
     00 6C 00 (the Byte Order Mark (BOM) followed by "<?xml").  For
     more information, see Appendix F of [XML].
```

]]

and the RDF/XML media type registration says:
http://tools.ietf.org/html/rfc3870
[[
         `Magic number(s): none`

```
        Although no byte sequences can be counted on to consistently
        identify RDF, RDF documents will have the sequence
        "http://www.w3.org/1999/02/22-rdf-syntax-ns#" to identify
        the RDF namespace. This will usually be towards the top of
        the document.
```

]]

**Comment by akuckartz** [comment]
:-1: regarding a strict magic number due to the reason stated in https://github.com/w3c/csvw/issues/631#issuecomment-113965995

> there is no guarantee that @context will even be the first entry in the object,

I have no opinion regarding a "looser interpretation of the Magic Number section."

**Comment by dbooth-boston** [comment]
@yakovsh my rationale for putting it in the Magic Number section rather than the Additional Info section is that if someone wants to know how to sniff this file type, they will most likely look in the Magic Number section.

**Comment by gkellogg** [comment]
I created a branch containing possible wording for both `@context` array ordering and the note within the IANA magic number description with a simplified version of @dbooth-boston's suggestion, which should be sufficient for applications that choose to look for these character sequences without being overly prescriptive.

This still needs to be discussed and approved.

**Comment by iherman** [comment]
For reference, the text can be seen at: https://rawgit.com/w3c/csvw/issue-631-iana-magic-number/metadata/index.html#iana-considerations

I have no objections including this text.

**Comment by yakovsh** [comment]
I think it looks ok although I am not sure if "N/A" is needed

**Comment by gkellogg** [comment]
@yakovsh would "None" be better, just leave it blank? Other entries I saw use "None". What do you suggest?

**Comment by dbooth-boston** [comment]
I think "None" or blank would be better than "N/A", though I could live with "N/A".

Also, although the length of @gkellogg 's proposal is better than what I suggested, :) readers my think"followed by" means "_immediately_ followed by", which would not be correct.  I suggest further clarifying with something like:
[[
**Magic Number(s):**
  None.

  Although no byte sequence can be counted on at a specific location, a valid application/csvm+json document MUST somewhere contain the string "@context" (including quotes), followed by one or more characters, followed by the string "http://www.w3.org/ns/csvw" (including quotes). 
]]

**Comment by yakovsh** [comment]
@gkellogg either one is fine. If IANA isn't happy, they'll let us know.
