### ISSUE TITLE
Make the standard directory metadata filename more unique?

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/csvw#633]
I didn't see any response to my 19-Jun-2015 message about this:
https://lists.w3.org/Archives/Public/public-csv-wg/2015Jun/0076.html

The standard directory metadata filename is currently specified in 
section 5.4 as "metadata.json"
http://w3c.github.io/csvw/syntax/#standard-directory-metadata
This is a pretty generic name that someone may want to use for other 
purposes.   

To reduce the potential that someone might wish to use the filename "metadata.json" for some other kind of metadata, how about changing this to something that is more CSVW specific, such as "csv-metadata.json"?

A google search for "metadata.json" shows 55,800 hits, while a search 
for "csv-metadata.json" shows only 22 hits, and all but maybe one of 
those pertain to this CSVW work.

**Comment by gkellogg** [comment]
Relates to #555.

**Comment by gkellogg** [comment]
As you argue elsewhere, I'm not sure it's very important. If `metadata.json` doesn't describe a CSV in the same directory, it will be apparent. If it does, then there's no ambiguity. Changing it to `cvs-metadata.json` doesn't add much beyond that IMO. Also, if the starting tabular file is a `.tsv`, then wouldn't you expect `tsv-metadata.json` using the same logic? Better just keep it as is.

In any case, I personally favor staying with the resolution on #555 and using `.well-known/csvw` after adding suggestions on default caching of the response. This provides ultimate control, for those who can set it.

**Comment by dbooth-boston** [comment]
@gkellogg You're right about "csv-metadata.json" versus "tsv-metadata.json".  So, how about "tabular-metadata.json" instead?  A google search shows only two hits, neither of which actually matches that filename.

The purpose of using a more distinctive filename is not to prevent a CSVM processor from misinterpreting it.  As you point out, that is already prevented.  The purpose is merely to allow the filename "metadata.json" to be used for other purposes, in the same directory in which a standard CSV metadata file is used, because "metadata.json" is already in use for (apparently) a lot of other purposes, judging by the 55,000 google hits for that name.

**Comment by iherman** [comment]
> On 25 Jun 2015, at 21:16 , Gregg Kellogg notifications@github.com wrote:
> 
> As you argue elsewhere, I'm not sure it's very important. If metadata.json doesn't describe a CSV in the same directory, it will be apparent. If it does, then there's no ambiguity. Changing it to cvs-metadata.json doesn't add much beyond that IMO. Also, if the starting tabular file is a .tsv, then wouldn't you expect tsv-metadata.json using the same logic? Better just keep it as is.
> 
> In any case, I personally favor staying with the resolution on #555 and using .well-known/csvw after adding suggestions on default caching of the response. This provides ultimate control, for those who can set it.

Actually, and independently of the discussion on the TAG list, me too. I must admit I was reticent at the beginning, but the flexibility it offers in setting up a publication site is appealing; this issue on 'how to name the metadata file' is actually a typical example.

As for the metadata.json vs. tabular-metadata.json: this should be decided even if we keep to .well-known, because we also define a default. To be honest, this sounds like a bike-shadding issue to me, I do not have a strong feeling about it.

**Comment by dbooth-boston** [comment]
I don't think it's a bike shed issue.  I don't really care about the name per se.  I'm just looking at the numbers: 55,000 existing hits for "metadata.json" strongly suggests that people are already using that filename for many other purposes.

**Comment by JeniT** [comment]
+1 from me on making a change to the name of `metadata.json`. I think `csv-metadata.json` is fine (people call all sorts of things CSV and it's the usual case).

**Comment by gkellogg** [comment]
Okay, I agree with `cvs-metadata.json`. I'll do a PR for the model document and update tests accordingly.

**Comment by iherman** [comment]
To be on the safe side, maybe you should also change the .well-known version (the default setup), so that we would not forget it if that is the approach we take...

Thx

Ivan

---

Ivan Herman
+31 641044153

(Written on my mobile. Excuses for brevity and frequent misspellings...)

**Comment by gkellogg** [comment]
@iherman, agreed, I'll update that PR as well.
