### ISSUE TITLE
Suppression of columns in mapping 

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#64]
When mapping CSV to JSON or RDF, it may be desirable that not all the columns are included in the output. For example, in #54 we talk about recommending that an ISO 8601 date-time column is provided to complement 'naturally formatted' date time values (e.g. where year, month, day and time might be given in separate columns). We would only want to include the ISO 8601 value in the output, so we need a way to _suppress_ the column(s) with the 'naturally formatted' date time during the mapping (i.e. "don't include this column in the mapping").

The metadata vocabulary will need to include a mechanism to indicate this suppression. 

Suggest, for a column description, adding a boolean token, e.g.

```
"suppress-output": true
```

**Comment by JeniT** [comment]
Note that we did [resolve](http://www.w3.org/2014/11/05-csvw-minutes.html#item01) (in @6a6d74's absence) to not support the suppression of particular columns.

**Comment by 6a6d74** [comment]
OK - I see the discussion.

I agree that URL hacking to get data values is poor.

However, I think that constructing a URL from values in multiple fields is only one example. As discussed in #54 we might want to have an ISO 8601 date-time field alongside the locally formatted values (or even with the year, month & day split across multiple columns). In this case, we want to avoid publishing duplicated data ...

Without "suppression" I would get both versions of the date.

The implication is I'll need to do _templated_ mapping to deal with this issue.

For the time-being, we have bigger issues to resolve ... could we come back to this once we've got the simple mapping well documented?

**Comment by gkellogg** [comment]
See [Dave Lewis' comments](https://lists.w3.org/Archives/Public/public-csv-wg/2015Jan/0063.html) on the mailing list in support of omitting data.

**Comment by JeniT** [comment]
Resolved at Feb F2F. We will introduce a `suppressOutput` property, on individual resources or on columns, which would mean that no output was generated from that table or from that column during a conversion. This is not an inherited property.

example/possible def'n: - "this suppresses the conversion output from the thing that it is on".

**Comment by danbri** [comment]
See http://www.w3.org/2015/02/13-csvw-irc#T13-07-20
