### ISSUE TITLE
URL encoding of headers from CSV files

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#659]
Going through test009, I see that when lacking other metadata, if a header in a CSV file contains a space then the properties in the generated JSON are URL encoded eg like `Trim%20Cycle`.

I propose the JSON conversion URL decodes the names of columns so that people get `Trim Cycle`, which I think is what they'd expect.

**Comment by iherman** [comment]
(was just noise, bad issue. Sorry.)

**Comment by iherman** [comment]
Oops, sorry! My comment above was meant for the another issue! Will push it there

**Comment by iherman** [comment]
What this requires, in general, in 2.3.1 of the JSON conversion document, where it says now:

> Else, name N takes the value of the name annotation for the column associated with the cell.

This has to be changed to 

> Else, name N takes the URI Decoded value of the name annotation for the column associated with the cell. (Percent-decoding is necessary as name may have been encoded if taken from titles;)

(I reused, essentially, the description of the `_name` property in the metadata document.)

I am fine with that.

**Comment by 6a6d74** [comment]
+1 from me too. Unfortunately I can't make the change to the csv2json doc
myself as I am out of office for the next couple of days. Ivan?

BR. Jeremy

**Comment by iherman** [comment]
I am find doing these but... what is the fate of PR #638? I would hate to get into unnecessary merge conflicts...

Cc @gkellogg @JeniT

**Comment by JeniT** [comment]
@iherman I'm sure #638 will be merged when @gkellogg wakes up. You do not have to worry about merge issues with changes that affect completely separate documents (and rarely have to worry about merge issues on even the same document, unless they really do affect exactly the same text).

**Comment by iherman** [comment]
> On 07 Jul 2015, at 12:34 , Jeni Tennison notifications@github.com wrote:
> 
> @iherman I'm sure #638 will be merged when @gkellogg wakes up. You do not have to worry about merge issues with changes that affect completely separate documents (and rarely have to worry about merge issues on even the same document, unless they really do affect exactly the same text).

#638 has changed in the csv2json document, too. That is why I am worried.

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
PR #665 takes care of this, including the change in test009.json

**Comment by iherman** [comment]
@gkellogg if you agree with the change, #665 could be merged

**Comment by iherman** [comment]
I have also taken care of all the issue related json test outputs, per @JeniT's list (#664)

**Comment by gkellogg** [comment]
+1 I'll take care of it.
