### ISSUE TITLE
Composite primary keys and foreign key references

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#66]
Simple primary keys are easy to understand ... 

Example 22 from [3.8 Schemas](http://w3c.github.io/csvw/metadata/#schemas) shows:

```
      "foreignKeys": [{
        "columns": "countryRef",
        "reference": {
          "resource": "http://example.org/countries.csv",
          "columns": "countryCode"
        }
      }]
```

All nice and easy: the value from the single column `countryRef` is bound to the resource described by the _row_ that has the matching value in primary key column `countryCode` so that one can link the two tables together. 

However, Example 9 from [3.1 Property Syntax](http://w3c.github.io/csvw/metadata/#property-syntax) shows a composite primary key definition:

```
"primaryKey": [ "givenName", "familyName" ]
```

We know from this definition that there is a constraint such that the combination of `givenName` and `familyName` for a given row must be unique within the table.

But if I want to create a foreign key reference to a given row specified with a composite primary key, what would the _value_ in the referencing column (cell) look like? 

For example:

Table 1

<table>
  <tr><th>givenName</th><th>familyName</th><th>github-identifier</th></tr>
  <tr><td>Jeremy</td><td>Tandy</td><td>@6a6d74</td></tr>                
  <tr><td>Jeni</td><td>Tennison</td><td>@JeniT</td></tr>
  <tr><td>Ivan</td><td>Herman</td><td>@iherman</td></tr>
</table>

Table 2

<table>
  <tr><th>working-group</th><th>person</th></tr>
  <tr><td>CSV on the Web</td><td>Jeremy Tandy</td></tr>     
  <tr><td>Spatial Data on the Web</td><td>Jeremy Tandy</td></tr>
</table>

In this case I want to say that the value of `person` in table 2 maps on to the row with matching primary key from table 1. Somehow I need to map `"person": "Jeremy Tandy"` to `"givenName": "Jeremy", "familyName": "Tandy"`. 

It seems to me that we need to describe how the _value_ in table 2 `person` maps onto the columns in table 1. 

(I know this is a contrived example because all the github identifiers must be unique - but hey ...)

I wonder if we can use the URI Template syntax for this? e.g. for table 2 ... 

```
      "foreignKeys": [{
        "columns": "person",
        "reference": {
          "resource": "<table 1>",
          "primaryKey": "{givenName} {familyName}"
        }
      }]
```

Does it even make sense to have a foreign key reference from an _array_ of columns? I can't think where a foreign key reference _would not_ relate from the value in a single column. Should it be permissible to provide an array of columns in a foreign key definition (e.g. `foreignKeys/columns`)? Should we limit ourselves to a single column?

It might even make sense to define the primary key in the same way; e.g. for table 1

```
"primaryKey": "{givenName} {familyName}"
```

(Note that this also affects how the `@id` in mapped RDF is generated)

What do folks think?

**Comment by iherman** [comment]
Jeremy, the eagle-eye for problems... :-)
- I think using some sort of templates for the primary keys in the foreign key structure is the only thing we can do:-( In fact, these are simplified regex strings, right, providing names. (Do not get carried away, I know you like complex regular expressions:-)
- I think that, based on the use cases, it should be o.k. to restrict the use foreign keys by one per column. 
- Actually, to make the processing easier, I may prefer a structure of the sort:

```
  "foreignKeys" : {
    "person" : { "resource" : "<table 1>", "primaryKey" : "...."},
    "foo"    : { "..." }
  }
```

this has the same power of expression but makes all processing easier; one processes by advancing within a row with the column names, and going through the array of foreign keys all the time is an unnecessary steps if we can simply use the name as a key
- I am a bit neutral on the question whether the primary key specification (in table 1 of your example) should use templates or an array; consistency is certainly an argument.

**Comment by 6a6d74** [comment]
@iherman: thanks for the feedback ...

The reason that I suggested using the URI Template syntax for the primary key definition itself, in addition to consistency, is that we could then use this to define the URIs used when mapping entities to RDF.

However, I've just realised that this is what the `urlTemplate` property is doing :-) 

Still, consistency isn't a bad thing. 

The uniqueness constraints could still be assessed by evaluating the primary key template for every row ...

**Comment by JeniT** [comment]
Resolved at Feb F2F. If you want to match up columns that don't directly match up, you can't use `foreignKey`s, but you can use `aboutUrl` and `valueUrl` to create identifiers such that you get a linkage in any generated output.

**Comment by dbooth-boston** [comment]
If virtual columns are permitted (as a function of two or more other columns) then the problem of composite keys goes away.
