### ISSUE TITLE
Generated JSON has `table` not `tables` property

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#660]
Elsewhere when a property holds an array we have pluralised the name of the property. Should we do that here too?

**Comment by iherman** [comment]
I am o.k. with this. To make things quicker, I think the changes to be done are:
- In 4.2.2, point 4 defined `table`, that has to change to `tables`
- Change in the example 4, 8, 12, 23
- Interestingly example 17 has a 'bug' in the sense that it uses `tables` already!:-)
- An entry to be added to B.1

If we agree on email, I am happy to make the changes. Although it is better if the pending PR is accepted first to avoid possible merge conflicts

**Comment by JeniT** [comment]
@iherman don't worry about merge conflicts.

**Comment by JeniT** [comment]
Similarly the `title` property on each row should be called `titles` in the JSON output. I'd suggest that it standardises on emitting an array rather than emitting a string if there's only one value.

**Comment by iherman** [comment]
> On 07 Jul 2015, at 13:48 , Jeni Tennison notifications@github.com wrote:
> 
> Similarly the title property on each row should be called titles in the JSON output. I'd suggest that it standardises on emitting an array rather than emitting a string if there's only one value.

O.k.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
Actually, `title` vs. `titles` was a bug in the spec; all examples used `titles` already:-)

**Comment by iherman** [comment]
PR #666 takes care of that change.

@gkellogg if you agree with the change, this can be merged. However, I have not touched the tests on that one.

**Comment by JeniT** [comment]
I have changed the test files

**Comment by gkellogg** [comment]
Okay, it will take me some time to go through, update my implementation and the related tests; I'll try to do it today.

**Comment by gkellogg** [comment]
Change is merged, and I don't think it requires further discussion, although it is marked as such. @JeniT, close this if you agree.
