### ISSUE TITLE
Validators halting when encountering invalid metadata

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#662]
Looking carefully at the tests and at the text at http://w3c.github.io/csvw/syntax/#validating-tables it appears we have a situation where validators can continue to process CSV files (to create more errors) even when the metadata is invalid. I think we want validators to halt if the metadata is invalid, but to emit as many errors as they find when they are actually validating the CSV itself.

I propose amending the wording to say this. This might mean changing the classification of some of the tests (which I will try to highlight).

**Comment by iherman** [comment]
> On 07 Jul 2015, at 12:38 , Jeni Tennison notifications@github.com wrote:
> 
> Looking carefully at the tests and at the text at http://w3c.github.io/csvw/syntax/#validating-tables it appears we have a situation where validators can continue to process CSV files (to create more errors) even when the metadata is invalid. I think we want validators to halt if the metadata is invalid, but to emit as many errors as they find when they are actually validating the CSV itself.

+1

> I propose amending the wording to say this. This might mean changing the classification of some of the tests (which I will try to highlight).
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
The tests are a bit jumbled from what I can tell: most of the `negative` tests are halt-and-catch-fire errors with the metadata while the `invalid` ones are ones that processors could carry on from, but this isn't the case universally (ie when the `rdf` & `json` columns both hold `FALSE` and it's a `negative` test, that can sometimes mean simply that the data is invalid, not that the metadata is bad).

I'll try to fix this but I _am_ worried about merge conflicts on the manifest file because git doesn't seem to be handling them well.
