### ISSUE TITLE
Validation test issues

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#667]
- [x] test034 it's not immediately clear to me why this isn't valid; could something be added to the description to help people running the test to understand the error that should be generated? (Are you sure that there should be an error?)
- [x] test035 similarly
- [x] test091 tests (non-normative) parsing
- [ ] test109 should be either a warning or a negative test (since it's a problem with the metadata file, not the CSV file), and I think a warning
- [ ] test111 should similarly either be a warning or a negative test (and I think a warning)

**Comment by gkellogg** [comment]
test034 contains a reference using "xx", which makes this invalid; description updated to indicate this.

**Comment by gkellogg** [comment]
@JeniT, test109 is invalid as the bad language tag causes the entry to be ignored, thus there is no title, making the metadata incompatible with the CSV; when not validating, we can match on the `name` column, so those succeed. Do you still feel this should be a warning?

edit: same logic for test111.

**Comment by JeniT** [comment]
@gkellogg I agree that the spec doesn't make this explicit in describing natural language properties at http://w3c.github.io/csvw/metadata/#natural-language-properties where it says:

> If the supplied value of a natural language property is not a string, array or object (e.g. if it is an integer), compliant applications must issue a warning and proceed as if the property had been specified as an empty array. If the supplied value is an array, any items in that array that are not strings must be ignored. If the supplied value is an object, any properties that are not valid language codes as defined by [BCP47] must be ignored, as must any properties whose value is not a string or an array, and any items that are not strings within array values of these properties.

and doesn't say that in the latter case (invalid language tags) a warning must be issued. But the general text about conformance at http://w3c.github.io/csvw/metadata/#annotating-tables does say:

> If a property has a value that is not permitted by this specification, then if a default value is provided for that property, compliant applications must use that default value and must generate a warning. If no default value is provided for that property, compliant applications must generate a warning and behave as if the property had not been specified.

An object with properties that are not valid language codes is not a permitted value. No default value is provided for the `titles` property, so I think compliant applications must generate a warning.

**Comment by gkellogg** [comment]
@JeniT: so, your interpretation is that a warning is generated because of a bad value in `title`, which makes the metadata incompatible. But the fact that the metadata isn't compatible is not a validation error. That might be true if we were starting with the CSV, as we simply wouldn't find the metadata. But, in this case, we start with metadata only to find that it is incompatible with the CSV it references; it's hard to see how this is not invalid.

A warning is generated due to the bad `title`, but the result is that it is incompatible. We explicitly say the following:

> Verify that TM is compatible with EM using the procedure defined in Table Description Compatibility in [tabular-metadata]; if TM is not compatible with EM validators must raise an error, other processors must generate a warning and continue processing.

**Comment by JeniT** [comment]
@gkellogg OK. What I expect is:
1. When generating JSON/RDF (assuming no validation), for converters to issue a warning because of the bad language tag (not because of the missing `titles` property; because we're not validating the schemas aren't incompatible) and proceed with the conversion.
2. When validating, for validators to raise an error because the schemas aren't compatible.

Does this fit with your expectation as well?

Is it the case for all `invalid` tests that you expect the JSON/RDF conversion to generate a warning? This doesn't seem to be consistently true. For example, [test232](http://w3c.github.io/csvw/tests/#manifest-json#test232), which tests whether primary keys are unique, shouldn't generate a warning during conversion as far as I can tell, but it is also marked as `invalid`.

**Comment by gkellogg** [comment]
Okay, I can see that an error is generated and processing should proceed.

I do expect JSON/RDF to generate an error, but there's no logic to detect this, as there is a separate Warning class for validation, but not for RDF/JSON. To test for this, we'd need `ToRDFWithWarnings` and `ToJSONWithWarnings` classes. Presumably, if the test had 'warning' set, it would use appropriate classes to look for warnings for both JSON and RDF. If 'error', Negative tests all around, if 'invalid', warnings for RDF and JSON and negative for validation. Do you think it's worth defining these classes and being more explicit about looking for warnings (presence or absence) in transformation tests?

**Comment by JeniT** [comment]
I do think we should be testing whether warnings are generated during conversion, because of these subtleties.

As I said, I think there's some conflation of `invalid` as indicating warnings during conversion in some cases and not others. This might be solved without too much disruption by duplicating the relevant tests so that you have one version that gives positive (no warnings) conversion tests and doesn't generate a validation test, and another that just generates a negative validation test.

**Comment by gkellogg** [comment]
@JeniT: one complication is that if, say, linked metadata is incompatible with a table as it's `url` does not identify the file to which it is linked it becomes quite difficult to know how to proceed using that metadata anyway. As metadata may identify many tables, how can you know which one to associate the original file with? You'd need to special-case this failure. Better to either fail out entirely, or ignore the metadata and just interpret the input using embedded metadata.

This comes out of a corner-case we don't explore in depth in [Creating Annotated Tables](http://w3c.github.io/csvw/syntax/#creating-annotated-tables) step 3.5, where we say the when not validating to proceed processing with a warning if incompatible. We can special-case the metadata having a single incompatible table, but how would you proceed if it describes multiple? Some may reference, some may not. Which would be associated with the incompatible table description?

I don't think we have any tests which would probe this now, so taking the case of continuing if the metadata is incompatible and describes just a single table may be safest.

**Comment by gkellogg** [comment]
We also say explicitly for linked metadata and well-known metadata that it MUST be ignored if it does not describe the file, which would seem to mean that we can't proceed to use it, even though a warning may be generated. I would expect the output to just use embedded metadata, but include a warning about incompatible metadata.

This is still complicated because we can go through a series of metadata files which are incompatible and not issue warnings unless they're all incompatible. But, if there were no metadata files at all, no warning would be issued.

**Comment by gkellogg** [comment]
Test 121 has csv with user-specified metadata which references a different file. It is currently a positive test and uses the referenced, rather than the input file. However, this may be inconsistent with wanting to use the metadata, in spite of incompatibilities, with the input file. Note that this differs from linked- or site-wide metadata for which we explicitly state that it should be ignored.

**Comment by gkellogg** [comment]
@JeniT made numerous changes, mostly around compatibility issues. Test121 remains problematic for my implementation and needs some thought, and I continue to use my interpretation on expected results.

**Comment by JeniT** [comment]
@gkellogg I'm not suggesting that metadata be linked up with a table if the URLs don't match. The [text in the Model document](http://w3c.github.io/csvw/syntax/#link-header) says:

> so long as this referenced metadata file describes the retrieved tabular data file (ie, contains a table description whose `url` matches the request URL).

My expectation is that if the metadata includes a table description for the CSV (ie the URLs match) then (in the conversion case, and for the purpose of continuing validation) the column descriptions will be matched up one by one with the columns in the CSV file. Having thought it through, though, I'm happy with an interpretation that says the column descriptions are completely ignored in that case.

If there's anything specific that you'd like me to look over I'm happy to do so.

**Comment by gkellogg** [comment]
@JeniT I'd like your opinion on how to handle test121, otherwise, I think this is about done.

**Comment by JeniT** [comment]
test121 looks right to me: there's nothing that says to reject user-supplied metadata if it doesn't match the CSV file, so that metadata becomes the source for further processing.
