### ISSUE TITLE
Mark tests as "Accepted"

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#683]
This issue is to track the votes on making the current set of tests in the [Test Suite](http://w3c.github.io/csvw/tests/) as **Accepted**.

Votes received so far:

@gkellogg: +1 (https://lists.w3.org/Archives/Public/public-csv-wg/2015Jul/0053.html)
@6a6d74: +1 (https://lists.w3.org/Archives/Public/public-csv-wg/2015Jul/0056.html)
@danbri: +1 (https://lists.w3.org/Archives/Public/public-csv-wg/2015Jul/0057.html)
@yakovsh: +1 (https://lists.w3.org/Archives/Public/public-csv-wg/2015Jul/0058.html)

**Comment by gkellogg** [comment]
@JeniT, @iherman, your +1's would be enough to close this out, IMO.

**Comment by jumbrich** [comment]
+1

**Comment by iherman** [comment]
+1 from me, too

**Comment by JeniT** [comment]
+1
