### ISSUE TITLE
Number pattern clarification issues

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#685]
We should clarify, possibly just through tests the following:
- [ ]  the "#" preceding decimalChar do not limit the number of significant digits: [The number of # placeholder characters before the decimal do not matter, since no limit is placed on the maximum number of digits](http://www.unicode.org/reports/tr35/tr35-numbers.html#Number_Format_Patterns).
- [ ]  clarify the meaning of repeated "#" after the decimalChar or in the exponent to know if they are counted; my interpretation is that they are.
- [ ] "-" is not included as an allowable character in the pattern, although it is in UTS35.
- [ ] "+" seems to be limited to the exponent in UTS35, but may proceed the number in our spec.
- [ ] the position, or even presence of the groupChar is not significant in the pattern, and is simply removed.
- [ ] empty space is removed from a value before matching, and the value is up-cased (turning "e" to "E") per UTS35.

**Comment by gkellogg** [comment]
- [ ] does a negative number match only if the pattern starts with "-"? Does it match if it doesn't?
- [ ] ditto exponent.

**Comment by JeniT** [comment]
My understanding is:
- as you say, the `#` preceding decimalChar doesn't limit the number of integer digits
- the repeated `#` in the fractional part determines the maximum number of fraction digits; I'm not sure about the exponent but believe that the `#`s do determine the maximum size of the exponent
- `-` in the pattern does not have to be supported by implementations (although they may do so) so we shouldn't have any tests around it -- it's only used to significant effect in UTS35 when you're distinguishing between a positive and negative pattern
- `+` should only be used in the pattern in the exponent (to indicate that it has to have a `+` sign if it's positive)
  - the grouping separator is significant in the pattern: it determines the allowable grouping in the number (eg every three digits) - you have to use it to determine the primary and secondary grouping size, and the grouping size used in the fractional part
  - I agree that leading/trailing whitespace is removed before matching. Can you give a pointer to the upcasing? either way, I don't think that `e` should be allowed in the number pattern.
  - negative numbers match patterns that don't start with `-`, as do positive numbers
  - I'm not sure about exponents: I have made them required but they could be optional - I don't think UTS35 is clear

FWIW, my implementation is [here](https://github.com/theodi/csvlint.rb/blob/feature-csvw-validation/lib/csvlint/csvw_number_format.rb) and I did some [tests](https://github.com/theodi/csvlint.rb/blob/feature-csvw-validation/spec/csvw_number_format_spec.rb) which you might be able to adapt.

**Comment by gkellogg** [comment]
You're implementation is pretty impressive! [Mine](https://github.com/ruby-rdf/rdf-tabular/blob/develop/lib/rdf/tabular/metadata.rb#L2057-L2115) is decidedly more simplistic, but not necessarily from the LOC! I basically punt on the groupChar.

Maybe you can suggest some specific positive and negative tests from your suite that would be good to include. For example, I match '1,234' against '##0' due to eliminating the groupChar. I'll improve my implementation as necessary.

**Comment by JeniT** [comment]
Valid patterns & numbers from my tests:
- `##0`
  - `1`
  - `12`
  - `123`
  - `1234`
- `#,#00`
  - `12`
  - `123`
  - `1,234`
  - `1,234,567`
- `#,##,#00`
  - `12`
  - `123`
  - `1,234`
  - `12,34,567`
- `#0.#`
  - `1`
  - `1.2`
  - `1234.5`
- `#0.0`
  - `1.2`
  - `12.3`
  - `1234.5`
- `#0.0#`
  - `1.2`
  - `1.23`
- `#0.0#,#`
  - `12.3`
  - `12.34`
  - `12.34,5`
  - `12.34,56,7`

Invalid patterns & numbers from my tests:
- `##0`
  - `1,234`
  - `123.4`
- `#,#00`
  - `1`
  - `1234`
  - `12,34`
  - `12,34,567`
- `#,##,#00`
  - `1`
  - `1234`
  - `12,34`
  - `1,234,567`
- `#0.#`
  - `12.34`
  - `1,234.5`
- `#0.0`
  - `1`
  - `12.34`
- `#0.0#`
  - `1`
  - `12.345`
- `#0.0#,#`
  - `1`
  - `12.345`
  - `12.34,567`

**Comment by gkellogg** [comment]
Also embedded +/-:

Valid patterns:
- `0` # 
  - `1`
- `##0`
  - `+1`
  - `-12`

Invalid patterns:
- `0` 
  - `12`
- `.0#`
  - _pattern parse error_
- `0#`
  - _pattern parse error_
- `0E0`
  - _pattern parse error_

**Comment by gkellogg** [comment]
For `#0.0#,#`, `12.34,56,7` seems to be invalid, as it has more than the specified maximum number of digits. This is basically `/^\d{1,2}\.\d{1,2}(,\d{1})?$/` from my reading of the spec.

Edit: To be most accurate, it would be `/^\d{1,2}\.\d{1}(\d{1}(,\d{1})?)?$/`

**Comment by JeniT** [comment]
Agreed.

**Comment by gkellogg** [comment]
We should also consider if we want to use negative patterns; it's not too difficult in my implementation, but would require some re-factoring. How common is negative patterns such as `(1)` for negative 1?

**Comment by iherman** [comment]
Afaik, it is very widely used accounting... I do not know whether it is a UK thing, but I always saw it used when I had to handle budgetary issues with British friends

**Comment by JeniT** [comment]
As currently written, I believe that implementations may choose to support negative patterns but do not have to do so (as they do not have to support `;` which is used as the separator for negative patterns). I think it would be a technical change to say that implementations must support negative patterns.

**Comment by iherman** [comment]
> On 15 Sep 2015, at 21:55 , Jeni Tennison notifications@github.com wrote:
> 
> As currently written, I believe that implementations may choose to support negative patterns but do not have to do so (as they do not have to support ; which is used as the separator for negative patterns). I think it would be a technical change to say that implementations must support negative patterns.

That is correct

**Comment by gkellogg** [comment]
FYI, these [Ruby RSpec tests](https://github.com/ruby-rdf/rdf-tabular/blob/develop/spec/metadata_spec.rb#L1299-L1346) show the regular expressions generated for the various number patterns. The relevant code to generate them is [here](https://github.com/ruby-rdf/rdf-tabular/blob/develop/lib/rdf/tabular/uax35.rb#L162-L324).
