### ISSUE TITLE
text/tsv

### ISSUE THREAD

**Issue by dret** [w3c/csvw#687]
the model CR mentions "text/tsv" as a media type. it's not a registered one (but there is http://www.iana.org/assignments/media-types/text/tab-separated-values, which i've never seen used in the wild), and i am wondering whether that's just a typo (instead of text/csv)? if not, maybe explain what it is and that it's not a registered media type?

**Comment by dret** [comment]
since i am curious about this one, https://twitter.com/dret/status/621821923098386432 is where i have asked about current practice on the web.

**Comment by gkellogg** [comment]
It should be text/tab-separated-values; I'll update that in the spec. Google may have some information on mime-types sent along with .tsv files on the web, but I suspect it's typically application/octet-stream or text/plain.

Interestingly, GitHub gh-pages uses text/csv when retrieving http://w3c.github.io/csvw/tests/tree-ops.tsv, which is clearly wrong.
