### ISSUE TITLE
how would we describe a per-line-mixed charset file, if at all?

### ISSUE THREAD

**Issue by danbri** [w3c/csvw#699]
(and is there a charset for 'charset salad'?)

via https://twitter.com/kaiblin/status/633390944222617601 

> "Who creates CSV files with some fields in utf-8 and some in iso8859-1? WHO???"

Hopefully this is rare enough to be dismissed as a horrible cornercase...

**Comment by iherman** [comment]
I would definitely consider that as a horrible cornercase:-)

**Comment by danbri** [comment]
"We consider such files to be in undocumented non-CSV binary tabular formats, which would need custom/heuristic mapping into tabular datamodel instances."?

**Comment by JeniT** [comment]
Yes.

**Comment by danbri** [comment]
OK, I'll unclutter the in tray then. This wasn't CR feedback so closing unless you think there's editorial work worth doing.
