### ISSUE TITLE
Suggested form for provenance data in RDF & JSON

### ISSUE THREAD

**Issue by cgutteridge** [w3c/csvw#7]
See http://lists.w3.org/Archives/Public/public-csv-wg/2014May/0110.html for initial sketch of how to structure this.

**Comment by edsu** [comment]
I'm confused, I guess because I'm not a PROV expert by any stretch of the imagination. But is it the case that there isn't machinery in PROV for linking the assertions of provenance to the csv resources? Is `csv2rdf:describes` really necessary?

**Comment by cgutteridge** [comment]
anything with "csv2rdf:" in that example should ideally be replaced with an existing and established predicate. I'm not fully versed in all of prov so was busking the hard bits to finish the example. If there's interest then it's worth putting meat on the bones.

**Comment by iherman** [comment]
I would expect this to be relevant for the RDF mapping only, and not for pure JSON. The description seems to suggest that the RDF mapping would have to add a, more-or-less, mechanical piece of provenance information with some specific pieces to fill, so it is not a major issue in practice. 

(See http://lists.w3.org/Archives/Public/public-csv-wg/2014May/0110.html for what should be generated, if accepted.)

I put this as a possible decision to be made soon, it does not seem to interfere with other issues.

**Comment by iherman** [comment]
RESOLUTION[1] on 2014-11-5: An RDF conversion processor MUST generate provenance information of the form of the first snippet in http://lists.w3.org/Archives/Public/public-csv-wg/2014May/0110.html, and MAY generate richer provenance information

[1] http://www.w3.org/2014/11/05-csvw-minutes.html#res4

**Comment by danbri** [comment]
I believe this is now resolved and no longer in need of a telecon slot for discussion. 

( can you un-label it, I can't seem to do so?)

**Comment by 6a6d74** [comment]
Closing; other issues are covering the provenance information; e.g. #174.
