### ISSUE TITLE
Various improvements including greater alignment with Tabular Data Package and JSON Table Schema

### ISSUE THREAD

**Issue by rufuspollock** [w3c/csvw#702]
This issue suggests a variety of improvements to the current version of the specification. It is the result of substantial reflection on the current version of the spec. It is something of an "omnibus" issue and it could be broken up in more bite-sized chunks.

The various improvements are both made in themselves and also to seek greater alignment where possible with the [Tabular Data Package](http://dataprotocols.org/tabular-data-package/) and [JSON Table Schema](http://dataprotocols.org/json-table-schema/) specifications.

As people know, this spec was originally heavily based on Tabular Data Package. Over time it seems to have drifted somewhat. I would like to suggest various revisions to bring closer alignment. Why do this? If we can converge these specs then:
- it is possible for tooling to be easily reused between the two.
- it is possible that there could be complete convergence on all or parts of the spec that would allow for direct reuse and/or merge
- we reduce confusion amongst the community

In addition, i would note that Tabular Data Package has seen several years of real-world use and so reuse brings the benefits of that experience.
### General Metadata
- #712 - Rename `tables` attribute to `resources`
- #713 - Rename `tableSchema` to simple `schema`
#### Tables, Columns etc
- #715 Remove `aboutUrl` and `valueUrl`
- #716 `titles` -> `title` and require it to be single valued.
- `separator`: rather than allow this on column require it to be part of dialect
  - why specially move this up on to the column object - treat it like every other dialect property
- `columns` vs `fields` (JTS): this can be resolved by an upgrade in JTS to support `columns` name
- #720 - rework constraints into a dedicated property - this also makes datatype single valued again
- #721 - Make datatype single valued again
- #717 Alignment of datatypes between [JSON Table Schema](http://dataprotocols.org/json-table-schema/) and this schema
- Remove `rowTitles`
  - Dubious of need. We should always strive for parsimony.
  - Minor point
### Other Suggested Changes
- #718 - virtual columns: remove from spec.
- cf #715 - Remove explicit support for URI Templates
  - The purpose of these - as I understand it - is primarily to support URI generation in `aboutUrl`. As above this is of limited value and these add substantial implementational and cognitive complexity to the specification.
- #722 - Move transformation entirely out of the main spec
- #722 Keep transformation and conversion hints separate from the main spec
### Namespacing

I would recommend keeping namespacing to a minimum, at least in our examples for properties (e.g. `dc:title` vs `title`).

We can, and should, definitely allow namespacing - and it comes automatically really.

However, a key goal is simplicity and namespacing adds complexity (i have to work out what that `dc:` means ...)
### i18n

i18n is one of the more complex issues and presents real challenges for trading off expressiveness vs simplicity and ease of use. My sense is that the ultimate JSON-LD route is rather heavy-weight e.g.

```
`"title": {"@value": "The title of this Table", "@language": "en"}`
```

I would suggest the earlier JSON-LD approach of appending "@" to fields e.g.

```
`"title@en": "The title of this table"`
```

My preference for the latter is that it will be much easier to use and read for most non-expert users. I also think it "degrades" more nicely in that in the "title@lang" approach you do not have to change the default language value when you add new languages (this value is probably the one most important to most users - they may just ignore all other languages). That said, I acknowledge that either approach has challenges (e.g. this latter one means that parsing property values must be i18n aware). 
### Example

To illustrate some of the changes here is the current main example and then a rewritten version:

```
{
  "@context": ["http://www.w3.org/ns/csvw", {"@language": "en"}],
  "url": "tree-ops.csv",
  "dc:title": "Tree Operations",
  "dcat:keyword": ["tree", "street", "maintenance"],
  "dc:publisher": {
    "schema:name": "Example Municipality",
    "schema:url": {"@id": "http://example.org"}
  },
  "dc:license": {"@id": "http://opendefinition.org/licenses/cc-by/"},
  "dc:modified": {"@value": "2010-12-31", "@type": "xsd:date"},
  "tableSchema": {
    "columns": [{
      "name": "GID",
      "titles": ["GID", "Generic Identifier"],
      "dc:description": "An identifier for the operation on a tree.",
      "datatype": "string",
      "required": true
    }, {
      "name": "on_street",
      "titles": "On Street",
      "dc:description": "The street that the tree is on.",
      "datatype": "string"
    }, {
      "name": "species",
      "titles": "Species",
      "dc:description": "The species of the tree.",
      "datatype": "string"
    }, {
      "name": "trim_cycle",
      "titles": "Trim Cycle",
      "dc:description": "The operation performed on the tree.",
      "datatype": "string"
    }, {
      "name": "inventory_date",
      "titles": "Inventory Date",
      "dc:description": "The date of the operation that was performed.",
      "datatype": {"base": "date", "format": "M/d/yyyy"}
    }],
    "primaryKey": "GID",
    "aboutUrl": "#gid-{GID}"
  }
}
```

**Rewritten version**

```
{
  "url": "tree-ops.csv",
  "title": "Tree Operations",
  "keywords": ["tree", "street", "maintenance"],
  "publisher": {
    "name": "Example Municipality",
    "url": "http://example.org"
  },
  "license": "http://opendefinition.org/licenses/cc-by/",
  "modified": "2010-12-31",
  # note I would suggest always nesting this within a resources array but that's a bigger discussion
  "schema": {
    "columns": [{
      "name": "GID",
      "title": "Generic Identifier",
      "description": "An identifier for the operation on a tree.",
      "datatype": "string",
      "constraints": {
         "required": true
       }
    }, {
      "name": "on_street",
      "title": "On Street",
      "description": "The street that the tree is on.",
      "datatype": "string"
    }, {
      "name": "species",
      "title": "Species",
      "description": "The species of the tree.",
      "datatype": "string"
    }, {
      "name": "trim_cycle",
      "title": "Trim Cycle",
      "description": "The operation performed on the tree.",
      "datatype": "string"
    }, {
      "name": "inventory_date",
      "title": "Inventory Date",
      "description": "The date of the operation that was performed.",
      "datatype": "date",
      "format": "M/d/yyyy"
    }],
    "primaryKey": "GID",
  }
}
```

**Comment by rufuspollock** [comment]
I have refactored this issue by creating subissues for the most important items and then linking them.

**Comment by iherman** [comment]
Closing the issue by virtue of the [resolution of the WG Telco](http://www.w3.org/2015/09/23-csvw-minutes.html#res):

> RESOLUTION: We will close remaining technical issues (#702, #712, #713, #716, #717, #720, #721) that do not have wide support in the Working Group as continuing discussion will threaten eventual success of the group

**Comment by rufuspollock** [comment]
@iherman @JeniT  I should add a bit of context since unfortunately I could not make telco today due to prior commitments.

My understanding from conversation with Jeni last week, was the following:
- If we make "substantive" changes we will need to "reset" the clock and go back into a 6m process
- That it will be impossible - or at least very unlikely - to receive any extension on the WG's charter.

=> Changes at this point will put the "spec at risk"

In my conversation with Jeni I noted that:
- I think the spec could be substantially improved in several ways. Few of these involve actual removal or substantial alteration in features but more in a refactoring (and such refactoring would, in fact, take us back towards earlier versions)
- At the same time, if A. (some of) these changes would trigger a "reset" + B. extension is not possible => we run the risk of not reporting out a spec.
- Given that I would not want to jeopardize the efforts of the group, if it was truly the case that no extension was possible, then I accepted that we would have to leave these changes
  - At the same time, i think our ultimate commitment should be a great spec ... (but hard choices have to be made and Jeni made a good case for pragmatism)
  - I think it unfortunate we cannot secure some extension but understand the constraints that W3C operates under. I note also that more time would also provide more time for implementations to be trialled and feedback from that to be incorporated ...

Question of support for changes:
- In addition, there was a question of whether there was support for these items e.g. Jeni made good point that she wasn't sure that datatypes simplification was a good idea given desire/need to align with xsd etc
- We agreed it wasn't really clear how widely supported these changes were (given that attendance at telcos at present is limited to core members). To really know we'd have to consult more heavily and actively.
  - We'd also really need to prep two versions of the spec side by side (its almost impossible to compare individual issue by individual issue since many of the changes interact)
- However, as Jeni pointed out the very act of seeking to consult actively to find out how many others shared these views would not necessarily be helpful (e.g. it would stir up debate at a late stage - and what happened if there was support: we'd then be back at square one etc)
- I therefore understood that, at this point, we probably did not want to do the consultation to see if there was support, as that, in itself, could put the "spec at risk" (i.e. we would not ship on the required timeline or next February)

**Comment by akuckartz** [comment]
@rgrp I think it is sad that such decisions currently seen to be unavoidable. That will only change when much more resources can be put into developing such specifications (instead of developing manipulative software for cars etc.)
