### ISSUE TITLE
Warnings when metadata doesn't reference CSV file

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#711]
In the test suite, [test117](http://w3c.github.io/csvw/tests/#manifest-validation#test117), [test119](http://w3c.github.io/csvw/tests/#manifest-validation#test119) and [test120](http://w3c.github.io/csvw/tests/#manifest-validation#test120) are WarningValidationTests.

I thought that a warning was expected to alert the user to the fact that the CSV isn't described by the relevant metadata file, but there's no mention of needing to emit a warning in that case within the spec, and there's no warning generated for the similar tests [test122](http://w3c.github.io/csvw/tests/#manifest-validation#test122) and [test123](http://w3c.github.io/csvw/tests/#manifest-validation#test123).

What kind of warning should be issued in these cases, or is this a mistake in the test manifest and should test177, test119 and test120 be PositiveValidationTests?

**Comment by JeniT** [comment]
@gkellogg any thoughts on this?

**Comment by gkellogg** [comment]
117, 119, and 120 all have manifests that reference a (non-existing) CSV other than the one from which the metadata was found, so they should generate errors.

Test123 checks for finding the metadata in order, action.csv-metadata.json does not describe action.cv, but cvs-metadata.json does, so it is used and no warning is generated.

Test122 is missing the implicit file test122.csv-metadata.json. The linked metadata doesn't describe the CSV, but the file-specific metadata does, so this also does not generate a warning. I'll fix the manifest.

**Comment by JeniT** [comment]
@gkellogg I'm still unclear about why 117, 119 and 120 should generate warnings (and therefore what the content of the warning should be). It's not because they don't reference the relevant CSV files (since test122 & test123) don't generate warnings. Is it because after looking there's no schema file to validate the CSV against? But in that case why don't the simple tests that don't involve any metadata at all (eg test001) create warnings? Can you point to the parts of the spec that indicate that a warning should be generated in these cases?

**Comment by gkellogg** [comment]
test122 & test123 don't generate warnings as we eventually find metadata which is compatible with the files. For 117, 119, and 120, we don't find such a file. I'm using the interpretation of "Otherwise processors must attempt to locate the first metadata document from the Link header or the metadata located through site-wide configuration." that they find the first metadata which is compatible with the file, but we might not be clear on this regard, and compatibility has nothing to do with it. Taking that view, then they should all generate warnings: "validators must verify that the table group description within that metadata is compatible with that in the embedded metadata". This generates a warning (or error when validating) because of "Verify that TM is compatible with EM using the procedure defined in Table Description Compatibility in [tabular-metadata]; if TM is not compatible with EM validators must raise an error, other processors must generate a warning and continue processing."

If you think that finding the first metadata file doesn't consider compatibility, then indeed, 122 and 123 should generate warnings (errors) and not continue looking for metadata; output would be different due to choice of metadata, and having the extra files in the search path would serve no purpose.

**Comment by JeniT** [comment]
No, I agree that metadata files that don't reference the relevant CSV file should be ignored, and the processor should attempt to locate metadata that does reference the CSV, falling back through the methods to locate some.

The way I figure it, the fallback in each case happens as follows:
- test001: no user-supplied => no link => no file metadata => no directory metadata => **embedded metadata**
- test117: no user-supplied => no link => no matching file metadata => no directory metadata => **embedded metadata**
- test119: no user-supplied => no link => no file metadata => no matching directory metadata => **embedded metadata**
- test120: no user-supplied => no matching link => no file metadata => no directory metadata => **embedded metadata**
- test122: no user-supplied => no matching link => **file metadata**
- test123: no user-supplied => no link => no matching file metadata => **directory metadata**

test117, test119 & test120 all fall back to embedded metadata (which is of course compatible with the table from which it's generated), just like test001 (which doesn't generate a warning). They all hit some non-matching metadata files on the way, just like test122 & test123 (which don't generate warnings).

Is there something magical in the combination of ending up at embedded metadata after hitting other files along the way that means these tests should generate warnings? (That's how I've had to implement it to get the tests to pass.)

**Comment by gkellogg** [comment]
Good points. I consider embedded metadata to be different than discovered metadata. Then last metadata file found, which is not compatible, causes the warning to be generated.

Embedded metadata isn't like the others in the search path. But, I can see the viewpoint that the error would only be shown either when starting with metadata, or when user metadata is specified.

Perhaps we can discuss on the call, given time. I'll review the rules again.

**Comment by gkellogg** [comment]
@JeniT it would be good to close the loop on this one. Perhaps the best thing to do is to stop at the first metadata file found, whether or not it is compatible. Embedded is used only when no metadata is found. Thoughts?

**Comment by JeniT** [comment]
Yes, sorry we didn't get to it on the call.

I think that would comprise a technical change to the spec, which is quite clear (IMO) that a non-matching metadata file is ignored. What do you think, @iherman?

What isn't clear is whether any warning is issued to the user. I think that we should either always issue a warning if metadata (user-defined, link or file/directory/site) doesn't reference the CSV file you're trying to validate, or never do so. I prefer always doing so.

**Comment by iherman** [comment]
@JeniT I agree with you: changing the behaviour on a non-matching metadata file (ie, stopping) is a technical change in the spec and cannot be considered as a bug in the spec. Ie, it is not really the kind of change that is to be done on the PR transition. Unless this is really necessary (and I do not think it is), let us try to avoid doing that.

As for the original question: my preference would be to issue a warning. Actually, even if it is a validator I wonder whether we should keep it a warning and not an error, ie, processing should not stop (there may be good reasons why the user wants to put a CSV file, e.g., in a specific directory even if the directory metadata does not match and there is a fallback to the embedded metadata.)

**Comment by gkellogg** [comment]
Then, just make it so any encountered incompatible metadata issues a warning, so that 117, 119, and 120 become warning tests.

**Comment by JeniT** [comment]
+1
