### ISSUE TITLE
Rename `tables` to `resources`

### ISSUE THREAD

**Issue by rufuspollock** [w3c/csvw#712]
- This aligns with the entire Data Package family of specs. And allows for potential and extension and reuse of these types of specifications (e.g. much of the standard metadata makes sense here for a geo data package setup but obviously tables would not make sense there)
- This would also make the `resource` attribute on `foreignKeys` make more sense

Cost: very low

**Comment by JeniT** [comment]
-0

IIRC we decided to change to `tables` because `resources` was inappropriately generic for tabular metadata: unlike Data Package, we're only supporting tabular data files here, not general purpose resources. I'd be more inclined to change `resource` on `foreignKeys` to `table` to align the terminology internally. That said, I don't have any great objection (hence -0).

**Comment by rufuspollock** [comment]
@JeniT i understand but the point is that you then get a structure that _is_ compatible with more generic structures even if we are focused on tables here - just as Tabular Data Packages is CSV only but still uses `resources`.

**Comment by danbri** [comment]
Which sense of 'resource' is this? there's a usage where resource means essentially thing/entity.

e.g. https://en.wikipedia.org/wiki/Web_resource "The concept of a web resource has evolved during the web history, from the early notion of static addressable documents or files, to a more generic and abstract definition, now encompassing every 'thing' or entity that can be identified, named, addressed or handled, in any way whatsoever, in the web at large, or in any networked information system."

**Comment by rufuspollock** [comment]
@danbri i assume you've read the original (and current) Data Packages spec http://dataprotocols.org/data-packages/

As per there the resources are basically a list of the data files / objects that the Data Package "packages" - as such "thing / entity" with data in it would be a reasonable translation.

**Comment by iherman** [comment]
Closing the issue by virtue of the [resolution of the WG Telco](http://www.w3.org/2015/09/23-csvw-minutes.html#res):

> RESOLUTION: We will close remaining technical issues (#702, #712, #713, #716, #717, #720, #721) that do not have wide support in the Working Group as continuing discussion will threaten eventual success of the group
