### ISSUE TITLE
titles -> title and require it to be single valued

### ISSUE THREAD

**Issue by rufuspollock** [w3c/csvw#716]
Why make the change?

**Simplicity**

Making this multi-valued makes processing and use more complicated. The main purpose of the title that I can see is as a label in some kind of display. As such you really want one and only one value.

Also why make this value multi-valued and not other attributes e.g. description?

(One reason for multivalued could be i18n: but this is common across many attribute values and it would be best to address this in a standard way rather than special case `title`).

_Aside: One could invert the question and ask why make this multi-valued - given this was single valued at an earlier stage in the specs development ..._

**Comment by JeniT** [comment]
-1

Enabling multiple titles supports i18n. `titles` is the only built-in natural language property - the only one that requires i18n (common properties such as `dc:description` might be natural language properties but they aren't specified).

Enabling multiple titles also enables people to use the same schema against data with basically the same structure but eg accidental misspellings, including case mismatches.

A single value can still be supplied for `titles` by authors, so it doesn't add to authoring complexity.

**Comment by rufuspollock** [comment]
@JeniT how does it support i8n more than the existing method for doing i18n in other property values? I also don't get why the fact that dc:description may or may not be natural language would make any difference to wanting (at least in some circumstances) to i18n it - just like for the title (apologies i am being dense here!)

Re the same structure I don't understand: titles do not **have** to relate what is actually in the column heading do they?

Complexity: again by allowing the option of multiple values we do add to complexity - even if 99% of the time no-one uses it. If we are seeking simplicity and parsimony then we need to be vigilant against the feature creep that tends to occur in the spec design process.

**Comment by danbri** [comment]
-1 on removing the repeatability. Simplicity is like a lump in the carpet. If we make our format monolingual implementors will need to replicate the entire package just to add alternate titles.

-0.5 on 'titles' -> 'title', noting that we already map to 'csvw:title' in the JSON-LD context file which expands the JSON metadata into RDF triples:

http://www.w3.org/ns/csvw.jsonld 

```
"titles": {
  "@id": "csvw:title",
  "@container": "@language"
},
"title": {
  "@id": "csvw:title",
  "@container": "@language"
},
```

... it also appears that 'title' should already work, from a JSON-LD perspective. @gkellogg are there any test cases that would change if "title" were also indicated to be acceptable? Is the context file in sync with the view of the spec and tests on this matter?

**Comment by gkellogg** [comment]
The fact that `titles` and `title` alias to the same thing does _not_ imply that when parsing metadata you can use either. It is there because of the use of `csvw:title` in RDF output, to allow for compaction to `title`, but this is of dubious value. The original purpose for it has probably gone away.

Also, note that common properties cannot also be natural language properties, as the context is not set up to treat them this way. However, JSON-LD provides other mechanisms for repeating property values.

**Comment by rufuspollock** [comment]
@gkellogg very useful clarification. If the original reason for this change has gone away what about reverting to the original approach which was non-plural version `title`? (Also plus one on your point that JSON-LD has other mechanisms for repeating values).

**Comment by iherman** [comment]
Closing the issue by virtue of the [resolution of the WG Telco](http://www.w3.org/2015/09/23-csvw-minutes.html#res):

> RESOLUTION: We will close remaining technical issues (#702, #712, #713, #716, #717, #720, #721) that do not have wide support in the Working Group as continuing discussion will threaten eventual success of the group
