### ISSUE TITLE
Gathering constraints in one property on column

### ISSUE THREAD

**Issue by rufuspollock** [w3c/csvw#720]
Suggestion: collect all "data" constraints e.g. `minLength`, `maxLength` back into a dedicated `constraints` property on a column (at the moment they are primarily defined as subproperties of datatype property if i have read the spec correctly!).
- Keep constraints (which are primarily for validation) nicely contained and described
  - Aside: I do wonder whether constraints (and associated validation) are a separate mini-spec (based on experience with JSON Table Schema)
- Helps make datatype single valued again - see #721
  - Avoid having datatype behave differently depending on whether constraints are present - which makes processing more painful
- Align with JSON Table Schema

Additional points:
- `required`: move this down from column onto the `constraints` object
  - Why separate this from rest of constraints which are on datatype object

**Comment by JeniT** [comment]
-1

Datatypes are self-contained descriptions of values that could appear in any kind of content (within XML, within JSON, within RDF). See [XML Schema datatypes](http://www.w3.org/TR/xmlschema-2/#typesystem) for a conceptual description of what datatypes are. Datatypes in CSVW adhere to that characterisation: they have a lexical space, a value space, and a set of facets. I could create a datatype called "age" that was an integer between 0 and 120 and I could use that definition in CSV, in RDF, in XML and so on. I could test a string like "23" against the definition of the datatype age and it would either be valid against that datatype or not. I could reuse the datatype age in multiple CSV files. CSVW supports these self-contained definitions of datatypes (with the prospect of them being reusable across CSV files in the future).

Most of the constraints in JTS are equivalent to datatype facets. Some of them, such as `required` or `unique` are not. I could have a column that contains ages where the values were required; I could similarly have one where the values weren't required. They would both hold values of the datatype age. Similarly, I could have a column where all the ages needed to be unique, or I could have one where they didn't need to be.

**Comment by rufuspollock** [comment]
@JeniT can you walk me through how we anticipated these being reused? This seems to be pretty complex - how will parsers and processors handle this?

I think "specializing" datatypes like this is really of dubious use value for a lot of complexity. Constraints for validation make sense but reuse of rich datatype objects? In addition, we already have schema reuse support.

I think the point about required precisely illustrates why constraints should be outside of the type definition (yes, `required` is orthogonal to something being age, but so is `minLength` etc). I really struggle to see the distinction between a constraint like `required` and any of the others. If one can argue that `minLength` is actually part of a datatype then why not say that a column being required is part of that datatype ...

**Comment by iherman** [comment]
Closing the issue by virtue of the [resolution of the WG Telco](http://www.w3.org/2015/09/23-csvw-minutes.html#res):

> RESOLUTION: We will close remaining technical issues (#702, #712, #713, #716, #717, #720, #721) that do not have wide support in the Working Group as continuing discussion will threaten eventual success of the group
