### ISSUE TITLE
Make datatype single valued

### ISSUE THREAD

**Issue by rufuspollock** [w3c/csvw#721]
Make datatype single valued again by moving constraints out and format out to a separate property

`datatype` the single more useful thing in the spec. Let's keep it incredibly simple.

By allowing datatypes to be rich objects we make parsing more complicated.

Almost all the properties on the datatype can be moved off either into `format` or a constraints object - see #720 

(Only other two items are `@type and @id`. `@type` could just be omitted and @id could just be moved out to sit in parallel - perhaps with a rename)

**Comment by JeniT** [comment]
-1 See explanation for object datatypes in #720

**Comment by rufuspollock** [comment]
Discussed on call last week. No clear agreement as yet  on way forward. @JeniT and myself will meet next week to discuss further.

See also discussion in #720

**Comment by akuckartz** [comment]
Any results of the meeting?

**Comment by iherman** [comment]
Closing the issue by virtue of the [resolution of the WG Telco](http://www.w3.org/2015/09/23-csvw-minutes.html#res):

> RESOLUTION: We will close remaining technical issues (#702, #712, #713, #716, #717, #720, #721) that do not have wide support in the Working Group as continuing discussion will threaten eventual success of the group
