### ISSUE TITLE
Move transformation related work into a different section

### ISSUE THREAD

**Issue by rufuspollock** [w3c/csvw#722]
Move transformation related work into dedicated separate section of metadata spec
## Was previously this title and description

**Move transformation related work out of the metadata spec**

Suggestion: to consider moving transformation entirely out of the metadata spec and having it clearly separated in its own specification.

Why?

Transformation is a complex process and one often done in a variety of ways. Providing a specification for it is a substantial matter and also one that can be separated from that of providing a good descriptive metadata. This reduces complexity of the main spec, keeps it focused, and allows the transformation work to evolve separately if needed.

Addition (related):
- Keep transformation and conversion hints separate from the main spec
  - There are various points in the spec where transformation / conversion hints are alongside description metadata. For example:
    - The dialect description includes things like `skipRows`, `skipColumns` etc
    - `suppressOutput` in the table description
  - It would be better to clearly delimit this metadata so as to keep the spec conceptually clearer. Having all transformation information in a separate "transformation" properties would help here (and we already partly do this by having the `transformations` property separated out).

**Comment by iherman** [comment]
I think we should separate two different issues.
1. The metadata document is a specification. It has to be consistent, precise, etc. From a purely spec-writing point of view cutting that spec into two, putting what you call the 'transformation' aspects into a separate document (I would think that the primary targets would be the usage of URL patterns and the virtual columns) would be very complicated and would introduce the danger of inconsistencies between the two documents. It would also greatly complicate issues like precise conformance requirements, testing, etc. I would prefer not to go there; even if we were not at the end game of the group I would -1 this.
2. That being said, I understand the problem of complexity that may make the usage of the spec difficult for end users. Indeed, for very simple use cases those "transformation" features would probably be uninteresting and possibly confusing. However, I believe the right solution is what @JeniT referred to in another issue: it is extremely important to write a good primer to the metadata spec, where the simple use cases would be clearly separated from the more complex one. We clearly need this work item and, with the charter of this Group extended to the beginning of 2016, I believe this is doable.

**Comment by rufuspollock** [comment]
@iherman the point is a large number of potential users just don't care about transformation and we are burdening them. It seems to me that transformation is a classic extension (the dependency is one way). We already have separate "Model" and "Metadata" subspecs in this overall specification.

Whilst i think primers are good I think writing docs as way to solve a lack of simplicity / clarity is adding oil to the fire (you now need to read the primer _and_ the spec etc)

**Comment by iherman** [comment]
> @iherman the point is a large number of potential users just don't care about transformation and we are burdening them. It seems to me that transformation is a classic extension (the dependency is one way). We already have separate "Model" and "Metadata" subspecs in this overall specification.
> 
> Whilst i think primers are good I think writing docs as way to solve a lack of simplicity / clarity is adding oil to the fire (you now need to read the primer and the spec etc)

The pattern of writing a precise and complete specification and a separate Primer is ubiquitous. I do not think I have ever read the formal language specification of Python, although I have been using it for over 20 years, initially thanks to the tutorial written by the author of the language. Closer to home, we have this pattern for many of the W3C specifications; I do not think people learn HTML5 by just reading the specification...

**Comment by rufuspollock** [comment]
@iherman yes - i'm not saying it is super useful and valuable to have a primer - and it will be useful and valuable (even if we simplify!). I'm ++1 on a primer.

What I'm saying is that: "Well, we will write a good primer" may not be a sufficient response to complexity in the spec - if complexity really is an issue :-) (in a sense, it represents us patching the problem rather than solving it).

**Comment by danbri** [comment]
ping @rgrp - can we expect edits on this in the next week? otherwise the status quo will be the status quo...

**Comment by rufuspollock** [comment]
@danbri at this point likelihood is mixed. This was the least important of the changes in that it was editorial rather than substantive so if we don't see it we don't see it and it won't be the end of the world ;-0 (plus I imagine it will be fairly complex).

**Comment by danbri** [comment]
Ok, let's see what fortune brings in the next week, and remove this from the Proposed REC task list unless it happens. Thanks!

**Comment by JeniT** [comment]
As of 14th October, this hasn't happened, so we're closing the issue.
