### ISSUE TITLE
Need tests for valid durations & duration formats

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#731]
test194 tests for invalid durations (not matching the provided format), but there don't seem to be tests to ensure that normally formatted durations are OK. Need to add valid tests for:
- a variety of valid duration values
- a couple of valid duration formats

**Comment by gkellogg** [comment]
It looks like [test193](http://w3c.github.io/csvw/tests/#manifest-json#test193) was intended to do this, but doesn't actually. I'll just update that with format strings.

**Comment by JeniT** [comment]
Yes, you're right, test193 provides a variety of valid duration values, so I guess we also need some invalid duration values (without formats) in other tests.

**Comment by gkellogg** [comment]
I'll add some new tests.
