### ISSUE TITLE
Other tests (based on code coverage)

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#733]
I didn't manage to _completely_ implement using TDD, so there are some bits of the code in csvlint.rb that  need additional tests, as demonstrated by the [code coverage report](https://coveralls.io/builds/3466380). In particular:
- positive test: `@type` on a common property can be a built-in type (eg `Table`)
- positive test: `@type` on a common property can be a CURIE if the prefix is one of the built-in ones
- negative test: `@type` on a common property cannot be a CURIE if the prefix is not one of the built-in ones
- warning test: `null` contains an array of (valid) string & (invalid) numeric values
- positive test: `@id` on datatype is invalid (eg starts with `_:`)
- positive test: `base` missing on datatype (defaults to `string`)
- warning test: `format` for a boolean datatype is a string but in the wrong form (eg `YN`)
- warning test: `format` for a date/time datatype is a string but in the wrong format (eg `rubbish`)
- warning test: transformation includes an invalid property (eg `foo`)
- warning test: foreign key includes an invalid property (eg `dc:description`)
- warning test: foreign key reference includes an invalid property (eg `dc:description`)
- positive test: `@base` set in `@context` overriding eg CSV location
- negative test: `@context` object includes properties other than `@base` and `@language` (I think this is an error because allowing such properties would alter the way in which JSON-LD parsers understood the file)
- warning test: property acceptable on column appears on table group (eg `titles`)
- warning test: property acceptable on column appears on table (eg `titles`)
- warning test: property acceptable on table appears on column (eg `url`)
- negative test: CSV has more headers than there are columns in the metadata

@gkellogg are you up for adding some tests along these lines to the test suite?

**Comment by gkellogg** [comment]
Sure, I'll make some time to add them.

**Comment by gkellogg** [comment]
@JeniT: the third test is difficult, as you can't distinguish a missing prefix from a URL scheme. I.e., "foo:Bar" is a legitimate URI, just using an undefined scheme. Suggestions?

**Comment by JeniT** [comment]
No, no suggestions; you're right, I don't think we can test for that.

**Comment by gkellogg** [comment]
More observations:
- "positive test: @id on datatype is invalid (eg starts with _:)" should be a negative test.
- "warning test: format for a date/time datatype is a string but in the wrong format (eg rubbish)" Covered by test191
- "warning test: foreign key includes an invalid property (eg dc:description)" Spec gives no indication this is a warning, should it not be an error?
- (same for foreign key reference)
- "negative test: CSV has more headers than there are columns in the metadata" I think this is only negative when validating, and a warning otherwise.
