### ISSUE TITLE
Location of the standard file metadata

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#75]
The current text does say that the file metadata should be looked for only in case the data URI does not have a query component. However, it should also say that the concatenation with `-metadata.json` should happen after removing the possible fragment identifier from the data URI

**Comment by JeniT** [comment]
For simple edits like these it would be great to do a pull request.

**Comment by iherman** [comment]
Done (I hope)

Ivan

> On 29 Nov 2014, at 22:56 , Jeni Tennison notifications@github.com wrote:
> 
> For simple edits like these it would be great to do a pull request.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704
