### ISSUE TITLE
Link header (test014)

### ISSUE THREAD

**Issue by davideceolin** [w3c/csvw#759]
I suppose that I should get the Link header from the http header, and I use the link header explicitly provided in the test to simulate that. Am I right? Thanks.

**Comment by gkellogg** [comment]
In an ideal world, you would, indeed, get the link header from HTTP, however as the tests are served from GitHub, there's no provision to change the HTTP headers at all. That's why the [test manifest](http://w3c.github.io/csvw/tests/) has the following paragraph:

> Tests may be defined with processor options and expected HTTP headers which should be treated as if they were provided with the action file.
