### ISSUE TITLE
URIs & Namespaces (test030.json)

### ISSUE THREAD

**Issue by davideceolin** [w3c/csvw#765]
In test030.json, some URIs are prefixed (schema:), some not (geonames, etc.). Is there any specific reason for this? And for not indicating the namespace definition? Thanks.

**Comment by gkellogg** [comment]
Prefixes are used only for terms defined in the [csvw namespace](http://www.w3.org/ns/csvw), which are based on those in the [RDFa Initial Context](http://www.w3.org/2011/rdfa-context/rdfa-1.1), which does not include genomes. Arguably, it should, would should also cause the CSVW namespace to be updated eventually. If this happened, then then test030.json would generate different output. As a result, we may want to change this test (and others, if they exist), to not use a vocabulary which may eventually become included in the namespace.

Note the the RDF/Turtle output does use `geo`, as that happens to be included in the serializer's default set of vocabularies. It doesn't effect the comparison using RDF isomorphism, however, as the triples are isomorphic.

**Comment by davideceolin** [comment]
I see. I had just found that indeed. And yes, I didn't have issues with the Turtle conversion, but I did not consider namespaces in json so far (just treated the keys as simple strings). Thanks!
