### ISSUE TITLE
Editorial: Clarifying metadata location options and warning of trade-offs in using .well-known

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/csvw#769]
This editorial issue has not yet been addressed:
https://lists.w3.org/Archives/Public/public-csv-wg/2015Oct/0025.html

To address it, I have improved the proposed wording changes and created a corresponding pull request:
https://github.com/w3c/csvw/pull/768

**Comment by iherman** [comment]
I have already expressed my (negative) opinion on the proposed changes in:

https://lists.w3.org/Archives/Public/public-csv-wg/2015Oct/0026.html https://lists.w3.org/Archives/Public/public-csv-wg/2015Oct/0026.html

I believe the current editors' draft is adequate.

Ivan

> On 28 Oct 2015, at 23:26, David Booth notifications@github.com wrote:
> 
> This editorial issue has not yet been addressed:
> https://lists.w3.org/Archives/Public/public-csv-wg/2015Oct/0025.html https://lists.w3.org/Archives/Public/public-csv-wg/2015Oct/0025.html
> To address it, I have improved the proposed wording changes and created a corresponding pull request:
> #768 https://github.com/w3c/csvw/pull/768
> —
> Reply to this email directly or view it on GitHub https://github.com/w3c/csvw/issues/769.

---

Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
Closing this issue, because the discussion is happening on the relevant PR request #768.
