### ISSUE TITLE
Base64 encoded Link support

### ISSUE THREAD

**Issue by rodionos** [w3c/csvw#783]
One of the challenges of implementing Linked metadata on the server-side is the need to support asynchronous loading of metadata. This applies to applications where the schema of each response is dynamic. One such example would be a web-based SQL console that allows an end-user to execute SQL queries against a relational database and export the resultset in CSV format. Since each SQL query is unique the server application would have to persist unique metadata files and expose them at unique URIs for subsequent access. The same behavior can be imaged for any application that exposes the list of selected columns, filters and calculations to end-users. To overcome this complication, I recommend adding support for base64 data-encoded metadata in the Link header.

http://www.w3.org/TR/tabular-data-model/#link-header

```
Link: <data:application/csvm+json;base64,ewogICJAdHlwZSI6ICJUYWJsZSIsCiAgInVybCI6ICJodHRwOi8vZXhhbXBsZS5vcmcvdHJlZS1vcHMuY3N2IiwKICAidGFibGVTY2hlbWEiOiB7CiAgICAiY29sdW1ucyI6IFsKICAgICAgeyJ0aXRsZXMiOiBbICJHSUQiIF19LAogICAgICB7InRpdGxlcyI6IFsgIk9uIFN0cmVldCIgXX0sCiAgICAgIHsidGl0bGVzIjogWyAiU3BlY2llcyIgXX0sCiAgICAgIHsidGl0bGVzIjogWyAiVHJpbSBDeWNsZSIgXX0sCiAgICAgIHsidGl0bGVzIjogWyAiSW52ZW50b3J5IERhdGUiIF19CiAgICBdCiAgfQp9>; rel="describedBy"; type="application/csvm+json"
```

This would be equivalent to URI Links:

```
Link: <metadata.json>; rel="describedBy"; type="application/csvm+json"
```

This approach is preferable over introducing additional headers other than Link. It also ensures that Processors obtain schema and the data itself in one request minimizing the overhead on server applications and thus increasing adoption of the tabular data models in the community of practitioners.

**Comment by iherman** [comment]
Sergei,

I have looked at the data model document and my reading is that, although the usage of a 'data' scheme is not explicitly called out in the text, it is not disallowed either. The standard only refers to the `Link` header as defined for HTTP, without resticting to `HTTP(S)`. In other words, any URI that is allowed by the HTTP standard works which includes, I believe, your `data:` example.

It is another matter whether implementations would do this or not, and whether our tests should include a test case for this; I let @JeniT and @gkellogg react on this.

(There is also a very administrative aspect to all this; forgive me if I add this argument, but it is my job to do so. The model document has recently be published as a Proposed Recommendation, meaning that its content is frozen and is being voted on by the W3C membership. Any new feature would, at this point, be postoponed to a second version of the Recommendation, which may be several years down the road, if it ever happens...)

**Comment by rodionos** [comment]
Thank you. Yes, it appears that Link URI can be a valid RFC 3986 URI, which includes URLs as a subset, which in turn allow for RFC 2397 `data` scheme. Examples would be useful to have in the 2nd version, if/when it comes to that. Please feel free to close the issue.
