### ISSUE TITLE
Geometry datatype with tabular data metadata file

### ISSUE THREAD

**Issue by palmerj** [w3c/csvw#795]
Has any consideration been given to supporting geometry datatypes (points, lines, polygons + spatial reference system) within the standards for CSV on the web? Either using GeoJSON or OGC WKT geometry encoding formats would be good.

I know there is a Spatial Data on the Web Working Group, but I couldn't find any commentary about this issue.

**Comment by JeniT** [comment]
@palmerj I've added a section in the primer to do this, in the PR #822. Would you look that over to see if it addresses your question?

**Comment by palmerj** [comment]
@JeniT Thanks I've provided some comments. I've also asked a few others who have a deeper understanding of spatial datatypes specifications to comments.
