### ISSUE TITLE
Take security issues in account for CSV conversions in general

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#8]
Issue raised on the mailing list by Yakov, see:

http://lists.w3.org/Archives/Public/public-csv-wg/2014May/0126.html

for more details

**Comment by JeniT** [comment]
@iherman what's the appropriate mechanism for highlighting this issue? Is it a separate "Security Considerations" section in the metadata document ala RFCs (which is where the references to extension templates are) or to put a note in the section that talks about extension templates?

**Comment by iherman** [comment]
There is no fixed rule. Ie, any of those would work, whichever fits the overall flow better. I have the (personal) feeling that the former approach is better, though.

Ivan

On 31 Oct 2014, at 14:39 , Jeni Tennison notifications@github.com wrote:

> @iherman what's the appropriate mechanism for highlighting this issue? Is it a separate "Security Considerations" section in the metadata document ala RFCs (which is where the references to extension templates are) or to put a note in the section that talks about extension templates?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
GPG: 0x343F1A3D
WebID: http://www.ivan-herman.net/foaf#me
