### ISSUE TITLE
JSON-LD context for metadata documents

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#80]
We need a JSON-LD context for metadata documents.

We also need to give some guidance to people about how that context is referenced, the options being:
1. explicitly include a `@context` property within the metadata documents; this could equally act as a way of indicating eg the version of the metadata document
2. get publishers to indicate the JSON-LD context through a `Link` header
3. say nothing and guess that JSON-LD-aware crawlers will adapt to automatically recognising CSV metadata documents as being JSON-LD

**Comment by JeniT** [comment]
This follows on from #48

**Comment by gkellogg** [comment]
Nothing to say that a document served as application/json can't also have an `@context`. If so, the Link header probably isn't required. However, clients must know to interpret the metadata JSON file as JSON-LD.

**Comment by iherman** [comment]
> On 30 Nov 2014, at 17:46 , Jeni Tennison notifications@github.com wrote:
> 
> We need a JSON-LD context for metadata documents.
> 
> We also need to give some guidance to people about how that context is referenced, the options being:
> 
>   • explicitly include a @context property within the metadata documents; this could equally act as a way of indicating eg the version of the metadata document

To make it clear, though: a @context would not (necessarily) mean the inclusion of a bunch of JSON statement as we have currently in our examples; rather, it could simply be a "@context" : "URI", where URI is the reference to the context that Gregg has said he would do and would be stored at W3C. Ie, asking authors to do that is not as bad as it sounds... Or is this a 4th option?

>   • get publishers to indicate the JSON-LD context through a Link header
>   • say nothing and guess that JSON-LD-aware crawlers will adapt to automatically recognising CSV metadata documents as being JSON-LD

I think all four are possible. We would have to give a 'good practice' advise, however; my gut feeling is that advising them to do a '@context' : 'URI' is probably the simplest.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
See 18dbe3a239a038a236951b2429ab47e00d0ccd26 for context, and tools to create.

**Comment by JeniT** [comment]
@gkellogg's latest changes make it mandatory for authors to supply the context URL explicitly (either through `@context` or through a `Link` header) but then say processors should just assume it's there if it's missing. Experience from other languages (notably HTML) is that there's no point in making something mandatory for authors unless processors are also going to treat it as mandatory (ie error if it's not there). So I think the choices are:
1. insist that metadata files explicitly indicate the JSON-LD context file (have processors give an error if they don't); or
2. make supplying the context optional, only recommended for JSON-LD compatibility

I'd favour the second option because this is less work for authors.

**Comment by gkellogg** [comment]
Schema.org faced a similar issue when recommending the use of JSON-LD in for schema.org markup, and settled on mandating the use of `"@context": "http://schema.org"` for the same reason we should: Otherwise, there is no interoperability with JSON-LD tool chains. I'm worried that "JSON-LD Lite" taken too far, will only encourage non-interoperability with tool sets. Given a choice between the options you present above, I would have stay with the MUST about including this in the `@context`.

The motivation for also having CSVW-aware processors supply it if it _is_ found missing, is a nod to Postel's law about being lax about what you interpret, but this would only be for CSVW-aware processors, not general JSON-LD processors.

Including `@context` also is a great signal that this _is_ a JSON-LD document (even though many processing chains won't make use of the algorithms). This becomes more important if other keywords are aliased, and relates to the format of common properties as discussed in #142.

I suggest we leave in the requirement about using a Link header or an explicit `@context` and seek feedback referencing this document to see if developers really find it to be a burden.

**Comment by iherman** [comment]
Although I have not completely made up my mind where I stand in this, I must note that the comparison to schema.org may be misleading. People producing JSON(-LD) for schema.org are those who want their content to be used and managed by the search engines, ie, they have an extra motivation to produce their data in a way that would work for schema.org. There is a big carrot there. However, in the case of CSV data, I believe there will be many content authors who would primarily rely on simple JSON engines, or possibly CSVW engines for (meta-)data processing, and the extra plus of JSON-LD, ie, to incorporate the metadata into the Linked Data world, would be irrelevant at best. (And, if required to do an extra step then, alas!, irritating at worst:-(.

I agree we may want to put that as an explicit issue in the document for now, but I would rather not put it as a requirement at a present stage.

Ivan

> On 04 Jan 2015, at 01:28 , Gregg Kellogg notifications@github.com wrote:
> 
> Schema.org faced a similar issue when recommending the use of JSON-LD in for schema.org markup, and settled on mandating the use of "@context": "http://schema.org" for the same reason we should: Otherwise, there is no interoperability with JSON-LD tool chains. I'm worried that "JSON-LD Lite" taken too far, will only encourage non-interoperability with tool sets. Given a choice between the options you present above, I would have stay with the MUST about including this in the @context.
> 
> The motivation for also having CSVW-aware processors supply it if it is found missing, is a nod to Postel's law about being lax about what you interpret, but this would only be for CSVW-aware processors, not general JSON-LD processors.
> 
> Including @context also is a great signal that this is a JSON-LD document (even though many processing chains won't make use of the algorithms). This becomes more important if other keywords are aliased, and relates to the format of common properties as discussed in #142.
> 
> I suggest we leave in the requirement about using a Link header or an explicit @context and seek feedback referencing this document to see if developers really find it to be a burden.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
See also https://github.com/w3c/csvw/pull/169#discussion_r23227464

**Comment by danbri** [comment]
See http://www.w3.org/2015/01/28-csvw-irc#T15-13-18

**Comment by gkellogg** [comment]
RESOLUTION: #80 JSON-LD must contain EITHER a string “http:/www.w3.org/ns/csvw” OR an array of the string “http://www.w3.org/ns/csvw” followed by an object which MAY contain @language and @base and no other values
