### ISSUE TITLE
How to handle mixed rows in HTML tables?

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#802]
The HTML Note says that rows containing just `th` are header rows and those containing just `td` are data rows. I think that _all_ rows other than header rows should be data rows. Whether a cell is a `th` or a `td` in a data row is irrelevant.

**Comment by gkellogg** [comment]
It was written to allow for simple XPath expressions to extract data. In ruby, Header rows are extracted as follows:

```
    tab.xpath('.//tr').each do |row|
      row.xpath('th').map(&:content).each_with_index do |value, index|
        ...
      end
    end
```

Data rows as follows:

```
    tab.xpath('.//tr').map do |row|
      data = row.xpath('td').map(&:content)
    end
```

This is intended to keep it simple. Would you take ever child of a `tr` that isn't a `th` as being a data value? Does this solve real-world problems?

**Comment by JeniT** [comment]
I frequently use `th` elements within rows to highlight what we would otherwise indicate are row titles
