### ISSUE TITLE
what is the correct reference for the CSVW primer

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#809]
The UCR doc references the primer as providing example mechanisms to describe units of measurement. What is the correct reference to use in the local-biblio for the primer?

**Comment by iherman** [comment]
Looking at the primer (and the html note) documents, I added entries to the local biblio.js file for `tabular-data-primer` and `csvw-html` for the two new notes, although, formally, we will have to vote for this next week and get it approved by the INK Domain Lead. I have also added the reference to the UCR document, ie, @6a6d74  you are all set! 

Closing the issue by virtue of https://github.com/w3c/csvw/commit/e54573d367c2f3adec0eedd975e5be1a885cdef3

/Cc @gkellogg @JeniT

**Comment by 6a6d74** [comment]
@iherman: thank you.
