### ISSUE TITLE
Annotation example in the primer

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#817]
There are some issues with the example on annotation in the primer. We may decide to skip over those and simply emphasize the fact that the Annotation vocabulary is still a moving target and its exact usage must be checked. But maybe we can do better.

The current example (number 16) used the OA vocabulary as follows:

``` json
{
    "@type": "oa:Annotation",
    "oa:hasTarget": { "@id": "countries.csv#cell=2,6-*,7" },
    "oa:hasBody": { "oa:text": "These locations are of representative points." },
    "oa:motivatedBy": { "@id": "oa:commenting" }
}
```

The code is a proper, JSON-LD representation of the _OA Vocabulary_[1]. However, the WA Working Group has now two documents in the making (hopefully to be published soon): [1] for the vocabulary, and a separate, JSON representation of the model which tries to hide, as much as it can, the RDF/JSON-LD heritage[2]. If we use the latter, the code would be different:

``` json
{
   "@context": "http://www.w3.org/ns/anno.jsonld",
   "type" : "Annotation",
   "target" : { "id" : "countries.csv#cell=2,6-*,7" },
   "body" : "These locations are of representative points.",
   "motivation" : "commenting"
}
```

Is it o.k. to use this? It would be better, because a user would probably use [2] for a specific annotation, ie, this is what he/she would produce.

However... does our metadata syntax allow an "internal" `@context` setting this way? I have not seen any explicit statement in our spec that would forbid this (we are not talking about changing/extending the top level `@context` file which is explicitly disallowed). How would our processors react on it?

(As an aside, if that kind of internal `@context` is not allowed, that may be considered an erratum...)

By the way, strictly speaking, the code within the current primer is also incorrect _at this moment_. Indeed, the csvw namespace does not include `oa`, which is the way it should be, because the spec refers to the RDFa initial context document for the list of predefined prefixes. However, `oa` is not _yet_ on it, because it is not yet a Recommendation. Of course, that is only a matter of time...
- [1] https://w3c.github.io/web-annotation/vocabulary/wd/ 
- [2] https://w3c.github.io/web-annotation/model/wd/

Cc: @JeniT @gkellogg

**Comment by JeniT** [comment]
@iherman the spec does explicitly forbid an internal `@context` in [Appendix A](https://www.w3.org/TR/tabular-metadata/#json-ld-dialect) where it says:
- A metadata document must not add a new context (i.e. include a @context property except at the top level), or extend the top-level context in anyway other than as specifically allowed in section 5.2 Top-Level Properties.

This was an intentional decision because we didn't want to place the burden on CSVW processors of being full JSON-LD processors and would take more than an erratum to change.

The `oa` prefix is defined within the CSVW context; it's listed in [the namespace document](https://www.w3.org/ns/csvw), defined as a prefix despite the lack of current Recommendation.

Given those things, do you still think the example has to change?

**Comment by iherman** [comment]
> @iherman the spec does explicitly forbid an internal @context in Appendix A where it says:
> 
> A metadata document must not add a new context (i.e. include a @context property except at the top level), or extend the top-level context in anyway other than as specifically allowed in section 5.2 Top-Level Properties.
> This was an intentional decision because we didn't want to place the burden on CSVW processors of being full JSON-LD processors and would take more than an erratum to change.
> 
> The oa prefix is defined within the CSVW context; it's listed in the namespace document, defined as a prefix despite the lack of current Recommendation.
> 
> Ah. What led me astray is that this is not part of the HTML description, only in the json file. It should then be made explicit in the HTML file, too. @gkellogg ?
> 
> Given those things, do you still think the example has to change?
> 
> The example is then fine per se, but I believe some sort of warning should be added that the JSON 'serialization' of the annotation should _not_ be used, only the RDF vocabulary in JSON-LD encoding. 

Ivan

**Comment by akuckartz** [comment]
> The example is then fine per se, but I believe some sort of warning should be added that the JSON 'serialization' of the annotation should _not_ be used, only the RDF vocabulary in JSON-LD encoding.

To me that reads like: "the syntax is somewhat broken for some people, but for others the semantics is usable."

**Comment by gkellogg** [comment]
> Ah. What led me astray is that this is not part of the HTML description, only in the json file. It should then be made explicit in the HTML file, too. @gkellogg ?

The HTML vocabulary document is built from the same source as the JSON, and it does describe the `oa` prefix. I don't recall right now why it's in there given that it's not in the RDFa initial context, but no harm done, and it may be useful.

> The example is then fine per se, but I believe some sort of warning should be added that the JSON 'serialization' of the annotation should _not_ be used, only the RDF vocabulary in JSON-LD encoding.

I'm not sure what warning you'd like to see. As long as the annotation uses the `oa` prefix, it should work just fine.

**Comment by iherman** [comment]
> On 14 Feb 2016, at 22:17, Gregg Kellogg notifications@github.com wrote:
> 
> Ah. What led me astray is that this is not part of the HTML description, only in the json file. It should then be made explicit in the HTML file, too. @gkellogg https://github.com/gkellogg ?
> 
> The HTML vocabulary document is built from the same source as the JSON, and it does describe the oa prefix. I don't recall right now why it's in there given that it's not in the RDFa initial context, but no harm done, and it may be useful.
> 
> I agree that there is absolutely no harm, ie, I agree having it defined.

And I now found out where my 'mistake' was. If I look at the namespace document, the 'oa' (and the other predefined prefixes) are listed under the heading 'Term Definitions', ie, section 6, alongside things like 'lang' or 'maxExlusive'. This is very misleading for me; isn't it possible to pull out the namespace prefixes from that lot to make it clearer to the reader?

> The example is then fine per se, but I believe some sort of warning should be added that the JSON 'serialization' of the annotation should not be used, only the RDF vocabulary in JSON-LD encoding.
> 
> I'm not sure what warning you'd like to see. As long as the annotation uses the oa prefix, it should work just fine.

Here is the scenario I envisage: lambda user wants to add OA annotations to the csvw metadata. She will try to find information on OA, and will stumble on two documents: the OA Model, which is in JSON[1], and the OA Vocabulary[2], which is an abstract, syntax-less formal RDF definition of the vocabulary. Moreover, if the OA WG ever produces a primer, you bet it will be in that JSON format. Those JSON examples are all using a slightly different term names than the RDF vocabulary (`body` instead of the `oa:hasBody`) and they all include a reference to the OA context file. Guess what this lambda user will attempt to put into the CSVW metadata? I am almost sure that choice will be the syntax I quoted in this issue.

What I therefore means is that the primer should include a warning _not_ to do what I just describe, and that the user **must** refer to the vocabulary terms defined in [2], suitable prefixed with the `oa` prefix.
- [1] https://w3c.github.io/web-annotation/model/wd/ https://w3c.github.io/web-annotation/model/wd/
- [2] https://w3c.github.io/web-annotation/vocabulary/wd/

**Comment by JeniT** [comment]
There is nothing in the CSV specs that says that an implementation couldn't recognise:

```
{
   "type" : "Annotation",
   "target" : { "id" : "countries.csv#cell=2,6-*,7" },
   "body" : "These locations are of representative points.",
   "motivation" : "commenting"
}
```

as an annotation with an implicit context. I don't think we need to add any warnings since we don't say anything about how `notes` should be interpreted.

**Comment by iherman** [comment]
> On 15 Feb 2016, at 18:36, Jeni Tennison notifications@github.com wrote:
> 
> There is nothing in the CSV specs that says that an implementation couldn't recognise:
> 
> {
>    "type" : "Annotation",
>    "target" : { "id" : "countries.csv#cell=2,6-*,7" },
>    "body" : "These locations are of representative points.",
>    "motivation" : "commenting"
> }
> as an annotation with an implicit context. I don't think we need to add any warnings since we don't say anything about how notes should be interpreted.
> 
> True. In which case the example in the Primer should be changed to this one. 

Ivan
