### ISSUE TITLE
ePub version of UCR Note needs generating

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#836]
The [UCR Note](http://w3c.github.io/csvw/publishing-snapshots/NOTE-ucr-2016-02-25/Overview.html) is finally ready for publication. One last thing ... the ePub version needs to be regenerated.

**Comment by iherman** [comment]
Done per https://github.com/w3c/csvw/commit/cdc05625b065d4adbf1c40a8f51e8c4f5cfc9787
