### ISSUE TITLE
[csvw] instance definitions for direction

### ISSUE THREAD

**Issue by r12a** [w3c/csvw#839]
5 Instance Definitions
https://www.w3.org/ns/csvw#instance-definitions

typos 'Determins' and 'Indiects'

> Indicates text should be processed left to right
> is not very clear. It should not be taken to mean that the text viewed when displayed is processed in any way by reading characters from left to right.  What i think it should say is "Indicates that the base direction for the text is left to right."  

Base direction is the term used to describe the direction-specific context which determines how the Unicode Bidi Algorithm will display a unidirectional logical sequence of characters in memory when the text is rendered.  It doesn't order all characters left to right, but rather orders directional runs of similarly typed characters left to right.
(If you want to understand that better, see https://www.w3.org/International/articles/inline-bidi-markup/uba-basics)

Similar comment, of course, apply for `rtl`.

**Comment by iherman** [comment]
@r12a, would you mind indicating exactly where you found this bug? I do not find it...

**Comment by iherman** [comment]
cc: @gkellogg @JeniT ?

Should we make a direct editing (we can, it is not a TR document) or we just label is as an erratum?

**Comment by gkellogg** [comment]
It's generated from a spreadsheet (of course). I can do a PR with the spelling corrections. The text is taken from the metadata definition, but it is no longer in sync with that from [tableDirection](http://www.w3.org/TR/tabular-metadata/#table-group-direction). Text from there now is:

> Indicates whether the tables in the group should be displayed with the first column on the right, on the left, or based on the first character in the table that has a specific direction.

It think it best to simply update the namespace documents in place.

**Comment by danbri** [comment]
Yeah +1 for editing ns docs in place for simple mistakes like this. We're not ISO.

**Comment by iherman** [comment]
Works for me

Ivan

> On 20 May 2016, at 19:16, Gregg Kellogg notifications@github.com wrote:
> 
> It's generated from a spreadsheet (of course). I can do a PR with the spelling corrections. The text is taken from the metadata definition, but it is no longer in sync with that from tableDirection http://www.w3.org/TR/tabular-metadata/#table-group-direction. Text from there now is:
> 
> Indicates whether the tables in the group should be displayed with the first column on the right, on the left, or based on the first character in the table that has a specific direction.
> 
> It think it best to simply update the namespace documents in place.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub https://github.com/w3c/csvw/issues/839#issuecomment-220665383

---

Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
For the records: two merged PR-s (#840, #841) solved the issue in the repo, and the corresponding files in http://www.w3.org/ns have been updated.
