### ISSUE TITLE
Tabular JSON format for Wikipedia collaboration

### ISSUE THREAD

**Issue by nyurik** [w3c/csvw#842]
Hi, I am currently developing a tabular data format for Wikipedia (ability to store tables of data on Wiki pages), and you might be interested in participating. Thanks!

https://phabricator.wikimedia.org/T134426

cc: @iherman @6a6d74

**Comment by nichtich** [comment]
This can be closed, the result is at <https://www.mediawiki.org/wiki/Help:Tabular_Data>, obviously not CSVW JSON because of different requirements.
