### ISSUE TITLE
Common property names

### ISSUE THREAD

**Issue by pdw-mb** [w3c/csvw#843]
[Section 5.8 of the Tabular Metadata spec](https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#common-properties) states:

> "Descriptions of groups of tables, tables, schemas and columns may contain any common properties whose names **are either absolute URLs or prefixed names**."

Section 5.8.1 then states:

> "The names of common properties **are prefixed names**, in the syntax prefix:name."

The latter appears contradict the former by omitting the possibility that they may be absolute URLs.

**Comment by iherman** [comment]
@gkellogg or @JeniT : if this is justified, you should change the label to Errata, to be listed in the [official errata collection](https://www.w3.org/2013/csvw/errata/).

**Comment by gkellogg** [comment]
That's correct, absolute URLs or prefixed names can be used for common properties.

**Comment by iherman** [comment]
Summary: section 5.8.1. should indeed say "URLs or prefixed names".

**Comment by gkellogg** [comment]
@iherman can we close this now? What is the remaining action?

**Comment by iherman** [comment]
No remaining action...
