### ISSUE TITLE
"refered" should be "referred"?

### ISSUE THREAD

**Issue by shujikamitsuna** [w3c/csvw#844]
Thank you for the useful specification.
I found a typo in the Web Annotation Protocol document.
- In the first paragraph of the section 3.2, "refered" should be "referred".

**Comment by gkellogg** [comment]
@shujikamitsuna This issue seems to be for [Web Annotations](https://github.com/w3c/web-annotation/issues), not CSV on the Web.

**Comment by shujikamitsuna** [comment]
Sorry. I'm new to GitHub.
