### ISSUE TITLE
"ot" should be "to"? 

### ISSUE THREAD

**Issue by shujikamitsuna** [w3c/csvw#845]
Thank you for the useful specification.
I found a typo in the Web Annotation Protocol document.
- In the third paragraph of the section 3.2, "ot" should be "to".

**Comment by gkellogg** [comment]
@shujikamitsuna This issue seems to be for [Web Annotations](https://github.com/w3c/web-annotation/issues), not CSV on the Web.

**Comment by shujikamitsuna** [comment]
Sorry. I'm new to GitHub.
