### ISSUE TITLE
"to that classify" should be "to classify"?

### ISSUE THREAD

**Issue by shujikamitsuna** [w3c/csvw#846]
Thank you for the useful specification.
I found a typo in the Web Annotation Vocabulary document.
- In the section 2.3.3, "to that classify" should be "to classify".

**Comment by gkellogg** [comment]
@shujikamitsuna This issue seems to be for [Web Annotations](https://github.com/w3c/web-annotation/issues), not CSV on the Web.

**Comment by shujikamitsuna** [comment]
Sorry. I'm new to GitHub.
