### ISSUE TITLE
Is the inherited property `null` an array property?

### ISSUE THREAD

**Issue by xrotwang** [w3c/csvw#851]
Reading the [spec](http://w3c.github.io/csvw/metadata/#cell-null), it wasn't clear to me, whether `null` is supposed to be an array - but I guess it must be, right? If so, the docs should be more explicit.

**Comment by gkellogg** [comment]
The definition for `null` describes it as being an _Atomic Property_ The definition for [atomic property](http://w3c.github.io/csvw/metadata/#dfn-atomic-property) describes the legitimate values:

* numbers
* booleans
* strings
* objects
* arrays of any of the above.

Therefore both `"NULL"` and `["NULL"]` would be acceptable. This seems reasonably explicit to me.

**Comment by xrotwang** [comment]
I agree; I think I was confused by the - for me more explicit - specification for [lineTerminators](http://w3c.github.io/csvw/metadata/#dialect-lineTerminators), which mentions arrays - but I see now that this is a different context.
