### ISSUE TITLE
Wrong version of namespace documents published

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#853]
It looks like https://www.w3.org/ns/csvw was published from the source documents, not the publication snapshot; due to ReSpec changes, the document doesn't load properly. Can you republish from https://github.com/w3c/csvw/tree/gh-pages/publishing-snapshots/ns-2017-06.

cc/ @danbri

**Comment by danbri** [comment]
Thanks. I also reported this to W3C webmaster team. I'm sure that page worked recently. Are we loading respect from volatile URLs instead of an encapsulated bundle?

**Comment by gkellogg** [comment]
Best practice is to use ReSpec from https://www.w3.org/Tools/respec/respec-w3c-common, but we should not be publishing ReSpec source. I'm sure the update in May/June was just taken from the wrong place, there is a snapshot [Overview.html](http://w3c.github.io/csvw/publishing-snapshots/ns-2017-06/Overview.html) in https://github.com/w3c/csvw/tree/gh-pages/publishing-snapshots/ns-2017-06

**Comment by iherman** [comment]
I have no idea what happened, but anyway... I have refreshed csvw.html from the publishing snapshot, and it works in my Safari, Firefox, and Vivaldi (i.e., Chromium).

@gkellogg, @danbri, can you check and, if its fine, close this issue?

**Comment by gkellogg** [comment]
Thanks, Ivan. Looks good now.

**Comment by danbri** [comment]
NS looks good again, thanks both!
