### ISSUE TITLE
ErratumRaised: Wrong ORCiD for Robert Sanderson, Web Annotation Data Model spec editor

### ISSUE THREAD

**Issue by lambart** [w3c/csvw#858]
Robert Sanderson is the first editor listed for the Web Annotation Data Model document at https://www.w3.org/TR/annotation-model/

Like the other editors, his name is followed by his employer's name and an email address.

Unlike the others, it is followed by an "iD" icon linked to the following ORCiD page http://orcid.org/0000-0003-0782-2704

Following that link leads to an ORCiD page for Ivan Herman, whose name is listed in the Acknowledgements section, but not as an editor, which suggests to me that this link was made in error.

A simple search on orcid.org for "Robert Sanderson" leads to this result, which appears to be the correct page for the individual in question: http://orcid.org/0000-0003-4441-6852

**Comment by iherman** [comment]
Closing; this is the repository for the CSV on the Web Working Group, not the Web Annotation Working Group. Erratum has been added to the relevant repository (https://github.com/w3c/web-annotation/issues/435).

**Comment by lambart** [comment]
I remember thinking the repo name seemed odd, but saw that at least it was w3c. Not sure how I ended up here. Sorry about that!
