### ISSUE TITLE
schema term ambigious

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#86]
The Metadata document describes `schema` as an object property referencing a Schema definition. However, we also import terms from the RDFa Initial Context, including the use of `schema` as a prefix definition for `http://schema.org/`. Given that abbreviations such as `schema:name` may easily be used, we should consider changing the name of the `csvm:schema` term to something like `hasSchema`, although this will change other naming conventions.

**Comment by 6a6d74** [comment]
@gkellogg: how about `tableSchema`?

**Comment by iherman** [comment]
> On 04 Dec 2014, at 15:01 , Jeremy Tandy notifications@github.com wrote:
> 
> @gkellogg: how about tableSchema?

+1

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
+1

**Comment by 6a6d74** [comment]
Let's put it to the vote then at the next teleconference.

**Comment by iherman** [comment]
I just realized that, at the moment, the metadata document is inconsistent as a consequence. The document (and the namespace document) uses the `sch` prefix for schema.org terms. On the other hand, the text also says:

> The same prefixes are pre-defined as for [rdfa-core] within the RDFa 1.1 Initial Context and must not be overridden.

Meaning that `schema` as a prefix _is_ defined for the metadata by virtue of referring to the RDFa Initial Context. I guess this really means we should use a different term (and blame the schema.org guys for the choice of the term:-)

**Comment by gkellogg** [comment]
> I just realized that, at the moment, the metadata document is inconsistent as a consequence. The document (and the namespace document) uses the sch prefix for schema.org terms...

I raised this in issue #86, along with some concerns about `title` in issue #87. 

Given how widely the `schema:` prefix is understood in the community to refer to http://schema.org/, and it's use within the RDFa Initial Context, maybe we need to bend. I'd rather see us change from using `schema` to reference a `csvw:Schema`, to something else, such as `hasSchema` or `tableSchema` to avoid some inevitable clashes.

**Comment by gkellogg** [comment]
RESOLUTION: #86 change ‘schema’ to ‘tableSchema’ to avoid conflict with schema: prefix
