### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by CecilWard** [w3c/csvw#861]
I think you mean 'precede' instead of 'proceed' at one point in the html spec.

**Comment by iherman** [comment]
@CecilWard, thank you. Can you be more specific, ie, in which document and which section?

**Comment by gkellogg** [comment]
I think the issue identified is in https://www.w3.org/TR/csvw-html/ in Best Practice 5:

> **Best Practice 5: Header rows proceed content rows**

I'll correct and prepare an update.
