### ISSUE TITLE
title term ambiguous

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#87]
The `title` vocabulary term is used both in a Template Description and a Column Description with different meanings:

For Template:

> A natural language property that describes the format that will be generated from the transformation. This is useful if the target format is a generic format (such as application/json) and the transformation is creating a specific profile of that format.

For Column:

> A natural language property that provides possible alternative names for the column.

Perhaps we need to just settle on a more generic description, such as "A name given to the resource." from dc:terms. We could also simply not define our own term and use `title` as an alias for `dc:title`. Same could be said of `name` for `dc:source`.

**Comment by JeniT** [comment]
I think the only place that the fact these have different descriptions matters is in the official vocabulary documentation (ie I wouldn't dumb down the descriptions in the metadata document).

Proposed resolution: We define `title` as equivalent to `dc:title`.

@gkellogg if you want to push to say `name` is equivalent to `dc:source`, open another issue. I will argue against it :)

**Comment by gkellogg** [comment]
So, we could update the namespace to map these accordingly, although unless we're outputting that as column metadata, it probably doesn't really matter. It was just that the descriptions were getting wonky. I'm happy to leave this as it is.
