### ISSUE TITLE
minor omission in primer/#example-55

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/csvw#874]
https://w3c.github.io/csvw/primer/#example-55:
```json
"schema:name": ["Belgium", "Belgique", "Belgien"]
```

Shouldn't this include the lang tags as in example 56?

**Comment by VladimirAlexiev** [comment]
I see that the metadata (https://w3c.github.io/csvw/primer/#example-54) fixes the lang tags.
But doesn't the JSONLD output above lose that info?

**Comment by gkellogg** [comment]
The JSON format doesn't preserve language tags, and is not actually JSON-LD. Note that you could serialize the RDF output as JSON-LD, which would preserve the language tags.

**Comment by VladimirAlexiev** [comment]
I see my mistake: somehow I assumed that JSON output is JSONLD
