### ISSUE TITLE
Add more tools with brief summary / assessment

### ISSUE THREAD

**Issue by RickMoynihan** [w3c/csvw#882]
Here are some tools I discovered -- though I haven't actually looked at or tried any to any sufficient depth yet:

- https://csvw.opendata.cz/validation 
- http://rdf.greggkellogg.net/distiller?command=serialize 
- Adrian Gschwend / Zazuko https://github.com/rdf-ext/rdf-parser-csvw
- https://github.com/GSS-Cogs/csvw-check from ONS team

At some point it would be worth assessing them for completeness etc before offering recommendations or guidance.

Perhaps we could use the wiki to maintain an adhoc list more easily; and use the site as a promoted / vetted list eventually?

**Comment by gkellogg** [comment]
Well, I can vouch for the rdf.greggkellogg.net/distiller implementation, which is based on rdf-tabulary, which listed in the [implementation report](https://rubygems.org/gems/rdf-tabular).

It is certainly not too late to get more implementation reports, as we can update the implementation report on an on-going basis.

Please feel free to submit a PR suggest an entry for the Wiki.

**Comment by RickMoynihan** [comment]
🤣 Sorry @gkellogg I accidentally posted this issue to the wrong repository; as I had this github repo open to file issue #881 and an internal one with a similar name.  

Whilst you're here though, the internal repo has literally just gone public and you might be interested in a sneak peak.  Basically it's an attempt to build more of a user/developer focussed site around CSVW, with the ultimate aim of increasing adoption and tooling around CSVW.

We (at Swirrl) were going to start making some low key announcements anyway to sollicit feedback from the w3c mailing lists etc, but given that I made this embarassing mistake I may as well start with you :-) 

Please see:

https://csvw.org/

And the now [public git repository here](https://github.com/Swirrl/csvw.org/).

We would genuinely love to hear any comments you have, and as an aside if you happened to have any thoughts on #881 I'd love to hear them 🙇 .

**Comment by RickMoynihan** [comment]
Moved issue here https://github.com/Swirrl/csvw.org/issues/5

**Comment by gkellogg** [comment]
Hi @RickMoynihan, that's a fantastic site (https://csvw.org/) and initiative (@danbri, you should take note). I'll spend more time going through the details.

**Comment by danbri** [comment]
That is fantastic - nice work Swirrl!!! /Cc @Jeni Tennison
***@***.***>
