### ISSUE TITLE
Suspected error in csvw.jsonld for groupChar definition

### ISSUE THREAD

**Issue by RickMoynihan** [w3c/csvw#889]
In the published JSONLD vocabulary definition here: 

https://www.w3.org/ns/csvw.jsonld

We see the following definition for `groupChar`: 

https://github.com/w3c/csvw/blob/195b01a59c49b196bf9a233d7292e029a7c720f5/ns/csvw.jsonld#L167-L170

I'm not 100% sure but I believe that `"NumericFormat,xsd:string"` is a mistake, and that it should instead be expressed as an array like this: `["NumericFormat", "xsd:string"]`.

**Comment by gkellogg** [comment]
[From Tabular Data Model](https://www.w3.org/TR/2015/REC-tabular-data-model-20151217):

> **[groupChar](https://www.w3.org/TR/2015/REC-tabular-data-model-20151217/#dfn-datatype-format-groupchar)**
  A string whose value is used to group digits within the number. The default value is null. If the supplied value is not a string, implementations must issue a warning and proceed as if the property had not been specified.

Examples are '.', and ','.

**NumericFormat** is defined only in the [vocabulary definition](https://www.w3.org/ns/csvw) is in the domain of `groupChar`, not in the range.

Additionally, as pointed out, the "NumericFormat,xsd:string" , while a valid string, is clearly inappropriate as an `@type`. The proposed solution is to update the namespace document to have the value be simply `xsd:string`.

**Comment by RickMoynihan** [comment]
Ah yes that makes much more sense!  I didn't look too much at what the intention was supposed to be; it was a more immediate practical problem where the CSVW vocabulary definition actually failed to parse as JSON-LD in [titanium](https://github.com/filip26/titanium-json-ld).

Thanks again 🙇

**Comment by barthanssens** [comment]
Hmz, it looks like the published context is still (or again ?) the older version: https://www.w3.org/ns/csvw.jsonld has the incorrect groupChar type ...

**Comment by gkellogg** [comment]
@iherman this was merged from #890 into gh-pages, but never seems to have been pushed to /ns. Can you take care of this?

**Comment by iherman** [comment]
Done.
