### ISSUE TITLE
Context: different expansion of "datatype" and "base" ?

### ISSUE THREAD

**Issue by barthanssens** [w3c/csvw#897]
Hi,

as I'm trying to write a CVSW to RDF parser, I've a question on the JSON-LD context. 

For a built-in datatype, one can simply use the "datatype" property

```
    "datatype": {
      "@id": "csvw:datatype",
      "@type": "@vocab"
    },
```
So a JSON-LD processor will expand `"integer"` to `http://www.w3.org/2001/XMLSchema#integer`
Which works great

But for a derived datatype, one has to use 'base' property, which is defined as an ordinary string
```
   "base": {
      "@id": "csvw:base",
      "@language": null
    }
```

I'm probably missing something, but this doesn't seem to get expanded to an IRI by the JSON-LD parser (at least not by the JSON-LD playground).

Is this the intended behavior ? 
I.e. it seems that, for a derived datatype, a CSVW-parser has to do additional processing to get the IRI of the base datatype (instead of just relying on the expansion by a JSON-LD processor) ?

Thanks

**Comment by gkellogg** [comment]
The default context doesn't define `@vocab`, so in the case of "datatype", "integer" will only expand as you describe if you add a default vocabulary to the context such as the following:

```json
{
  "@context": ["http://www.w3.org/ns/csvw", {"@vocab": "http://www.w3.org/2001/XMLSchema#"}],
  "datatype": "integer"
}
```

But, you're correct, that `base` is defined without `@type`: `@vocab`. As defined in the context "An atomic property that contains a single string: a term defined in the default context representing a built-in datatype URL, as listed above.", so you must specify the complete URI string.

Per the above, and the spec, it is intended to be a a string for one of the [Built-in Datatypes](https://www.w3.org/TR/tabular-metadata/#built-in-datatypes) (e.g., "date"). A JSON-LD processor will only expand this to the string "date", but a CSVW processor needs to do more. For example, you can see [my own implementation](https://github.com/ruby-rdf/rdf-tabular/blob/9f7b6a7e69bc84f44d81c32144df14a1e5f463be/lib/rdf/tabular/metadata.rb#L1138-L1145): 

        when :atomic
          case key
          when :minimum, :maximum, :minInclusive, :maxInclusive, :minExclusive, :maxExclusive
            # Convert to a typed literal based on `base`. This will be validated later
            RDF::Literal(value, datatype: DATATYPES[self.base.to_sym])
          else
            value
          end

Where `DATATYPES` is a map from that string to the associated URI.

At this point, the decision process is so far in the past that it would be pretty difficult to understand the group's reasoning behind this choice, although carefully combing through the repository issues and commits could maybe yield something.

**Comment by barthanssens** [comment]
Ok, thanks for the info
