### ISSUE TITLE
Locating data region(s) within a CSV file

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#9]
[Use Case #2 - Publication of National Statistics](http://w3c.github.io/csvw/use-cases-and-requirements/#UC-PublicationOfNationalStatistics)

Do we want to be able to assert within the CSV+ metadata that the "data" exists at a particular region within the CSV? When talking about multiple tables within a single CSV file, AndyS stated:

"Maybe put the location of the data table within a single CSV file into the associated metadata: a package description for a single file."

**Comment by afs** [comment]
Related: Jeni's message: http://lists.w3.org/Archives/Public/public-csv-wg/2014Jun/0012.html

**Comment by 6a6d74** [comment]
Also see Issue 3 from the [Annotated Tabular Data Model](http://w3c.github.io/csvw/syntax/index.html#annotated-tabular-data-model)

"""
Issue 3

It might be useful to define annotated regions as follows:

An annotated table may also contain a number of annotated regions. Regions are themselves tabular structures comprised of selected rows and columns and the cells within those rows for those columns. Annotated regions are regions that have annotations associated with them. Annotated columns and annotated rows are special types of annotated regions where the region is the entirety of a single column or single row. 

But it's not currently clear that there are use cases or examples that justify it. Input is welcome on this.
"""

**Comment by davideceolin** [comment]
Not sure if this is what you were looking for, but in [Use Case 18](http://w3c.github.io/csvw/use-cases-and-requirements/index.html#UC-SupportingSemantic-basedRecommendations),  having the possibility to annotate regions of CSV files (and possibly access them directly) would facilitate the computation.

**Comment by yakovsh** [comment]
Isn't this already covered here:

http://tools.ietf.org/html/rfc7111#section-2.4

**Comment by dret** [comment]
yes, RFC 7111 does define one way of how fragments can be identified. but there could be other ways to do it, and it should be up to the data model to decide what kind of "fragment model" it supports. RFC 7111 would be one possibility, but there are many others.

**Comment by hubgit** [comment]
It might also be worth asking [the Open Annotation Community Group](http://www.w3.org/community/openannotation/) whether they looked at CSV files (or other tabular data) when creating [their (extensible) model for annotation target selectors](http://www.openannotation.org/spec/core/specific.html).

**Comment by dret** [comment]
Afaict, they just created a way how to represent the fragment identifier part of a URI, but the interpretation then still depends on the media type. This may not be perfect, but it's how the current Web works.

**Comment by hubgit** [comment]
> Afaict, they just created a way how to represent the fragment identifier part of a URI

As well as the fragment selector, there are other types of selectors in the Open Annotation model, such as ranges (which have start and end points) and shapes (as SVG). It may be that one of those - or something else entirely - is a more appropriate representation of a "data region" (and can probably still be serialised into a fragment as a string, if needed).

**Comment by dret** [comment]
> It may be that one of those - or something else entirely - is a more appropriate representation of a "data region"

More appropriate than what? Like I said, RFC 7111 is just one possible way to identify CSV fragments, and it of course has limitations. Other possible ways would have other limitations. My only intent was to point out that the data model probably should be accompanied by a fragment model.

**Comment by hubgit** [comment]
> More appropriate than what?

In the context of this ticket, I was looking at RFC 7111 - particularly the way that it defines the fragment selector using numeric indices - and thinking that there may be a way of pointing to a "data region" that is less specific to a CSV grid and would survive column or row re-ordering.

On the other hand, this ticket is specifically about identifying regions within a CSV file, and the data model currently says that the rows and columns mustn't be re-ordered, so maybe it's irrelevant…

**Comment by dret** [comment]
> In the context of this ticket, I was looking at RFC 7111 - particularly the way that it defines the fragment selector using numeric indices - and thinking that there may be a way of pointing to a "data region" that is less specific to a CSV grid and would survive column or row re-ordering.

I don't want to say that RFC 7111 is the way to go. It may be too simple or just the wrong approach. But I have a hard time imagining how to abstract away the fact that CSV essentially is nothing but a grid. That is, unless you layer something on top of it that turns it into something richer (such as some identifier concept established by embedding or associating identifiers). That would be one way to go, but then it's really quite different from raw CSV.

**Comment by JeniT** [comment]
It looks like @yakovsh won't be defining a new media type for the update of CSV, so RFC7111 will still apply to the `text/csv` that's being published, and annotations could use RFC7111 to refer to rows/columns/cells through fragment identifiers. We'll probably remove that section in the Model document once there's a I-D or RFC we can point to.

There are separate issues about how to best refer to columns/rows/cells in the tabular data model as opposed to the original CSV file it's created from: see #32 and #50.

**Comment by JeniT** [comment]
Actually that comment more applies to #24.

At the [October 2014 F2F at TPAC](http://www.w3.org/2014/10/28-csvw-minutes.html#meta) to include properties in the metadata that enable the metadata author to skip rows/columns to identify the data within the CSV file. That's in the [section on dialect descriptions](http://w3c.github.io/csvw/metadata/#dialect-descriptions): you can use `skipRows` and `skipColumns` as well as `headerRowCount` and `headerColumnCount`.

Should there also be a way of explicitly selecting a region through a RFC7111 fragment identifier on the CSV file? That would enable us to better support CSV files that contain multiple tables.

(Note that the dialect description acts as a processing hint and the section is non-normative.)

**Comment by JeniT** [comment]
Suggested resolution: we do not support referencing areas within CSV files through a RFC7111 fragid; the existing dialect description properties are sufficient.

**Comment by iherman** [comment]
I agree.

**Comment by edsu** [comment]
@iherman can you characterize what changed since [this message](https://lists.w3.org/Archives/Public/public-openannotation/2015Jan/0008.html)?

I'm interested in locating regions of a CSV in order to create [csvw:notes](https://w3c.github.io/csvw/metadata/index.html#table-notes) using Open Annotation. It seems to me that [dialect description properties](https://w3c.github.io/csvw/metadata/index.html#dialect-encoding) are intended for understanding how to parse the CSV, not to locate regions in the CSV. Can someone please clarify?

**Comment by iherman** [comment]
Hm. Good you ask @edsu because I am now officially messed up:-) My interpretation is that RFC7111 can still be used for annotation, but the application has to use the dialect values in the metadata file to ensure that the right region is selected. @JeniT, is that correct?

**Comment by dret** [comment]
i am confused as to how it is even possible for resources on the web to not support a media type's fragment identification method. of course one can ignore fragment identifiers and assume that any reference to a resource fragment is essentially treated as a reference to the complete resource. but that's entirely up to the client (the entity handling those references). i must be missing something essential here, since i thought this is about how to represent CSV on the web, and defining how to deal with it.

**Comment by iherman** [comment]
(In preparation for the F2F meeting...)

I wonder, @JeniT, whether the original issue is fully be covered by [your proposal](https://github.com/w3c/csvw/issues/9#issuecomment-72837994). My understanding of the original issue is whether we can have one metadata that describes, logically, several tables within the same CSV files, and then these tables would be identified (in the metadata) via RFC7111 or whether the dialect descriptions are enough even for that case. Actually, the question that arises in the first place whether we want to deal with the case where a CSV file would contain several tables.

Note that if we go down that line, this influences the way the processing is described, i.e., issue #193.

**Comment by danbri** [comment]
See http://www.w3.org/2015/02/12-csvw-irc#T11-06-59

**Comment by JeniT** [comment]
Resolved to close at Feb F2F. Editor action to put in note re multiple tables in single file not being handled by dialect description in metadata document.

**Comment by edsu** [comment]
@danbri W3C Sorry, Insufficient Access Privileges.

**Comment by edsu** [comment]
So I guess the ability to be able to identify regions in a csv in order to attach notes to it is a separate (perhaps unraised) issue? Is it still ok to think about using RFC7111 to identify regions in a csv for that purpose?

**Comment by danbri** [comment]
See http://www.w3.org/2015/02/12-csvw-irc#T15-53-24

**Comment by edsu** [comment]
@danbri I am unable to see that. Is that for the WG only?

**Comment by iherman** [comment]
I am sorry, Ed, forgot to set the ACL. It should be o.k. now.

Ivan

> On 12 Feb 2015, at 15:55 , Ed Summers notifications@github.com wrote:
> 
> @danbri I am unable to see that. Is that for the WG only?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by edsu** [comment]
@iherman thanks, enjoy dinner :-)

**Comment by JeniT** [comment]
@edsu Yes, it's still OK to use RFC7111 to reference regions on the original CSV file to add annotations to those regions; we discussed that at the F2F too and think it's the only way to do it (see resolution of #24).
