### ISSUE TITLE
Amend metadata doc to remove prefixes from properties not in RDFa 1.1 Initial Context

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#92]
The [metadata vocab doc section 3.3 Common Properties](http://w3c.github.io/csvw/metadata/#common-properties) states that:

"""
[...] prefixes are pre-defined as for [rdfa-core] within the [RDFa 1.1 Initial Context](http://www.w3.org/2011/rdfa-context/rdfa-1.1) and must not be overridden. Properties from other vocabularies must be defined using full URLs.
"""

And yet in the same section we see `dc:description`, `dcat:keyword` and `schema:copyrightHolder`.

Only DCAT (in the above examples) is in the RDFa 1.1 Initial Context ...

Suggest that the metadata document is updated so that its examples conform to the requirement to only use prefixes from RDF 1.1 Initial Context.

**Comment by iherman** [comment]
> On 04 Dec 2014, at 12:26 , Jeremy Tandy notifications@github.com wrote:
> 
> The metadata vocab doc section 3.3 Common Properties states that:
> 
> """
> [...] prefixes are pre-defined as for [rdfa-core] within the RDFa 1.1 Initial Context and must not be overridden. Properties from other vocabularies must be defined using full URLs.
> """
> 
> And yet in the same section we see dc:description, dcat:keyword and schema:copyrightHolder.
> 
> Only DCAT (in the above examples) is in the RDFa 1.1 Initial Context ...

Nop, the others are there, too. Scroll down the (HTML) page to get the additional entries

Ivan

> Suggest that the metadata document is updated so that its examples conform to the requirement to only use prefixes from RDF 1.1 Initial Context.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
My bad. I assumed that there was just one table :-) ... but I did think it odd that `dc:` was missing. Thanks.

**Comment by 6a6d74** [comment]
( @iherman: I see you wrote the RDFa 1.1 Initial Context doc ... not surprising you corrected me!)

**Comment by gkellogg** [comment]
I also noted in a separate email that the "schema" prefix conflicts with our own use of "schema" as a vocabulary term in the CSVM namespace. This will likely lead to problems.
