### ISSUE TITLE
Making `schema` property mandatory for table description objects & explicit identification of schemas

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#94]
I've been trying to get my head around how one would process metadata with _table group descriptions_, so I began to unpack @JeniT's [Use Case 4: Publication of public sector roles and salaries](http://w3c.github.io/csvw/use-cases-and-requirements/#UC-OrganogramData). But having looked at this, .

Looking at [attempt 2](https://github.com/w3c/csvw/tree/gh-pages/examples/tests/scenarios/uc-4/attempts/attempt-2) I noticed that it did not now follow the specification in the [metadata vocabulary document](http://w3c.github.io/csvw/metadata/). To clear things up (in my mind) I listed out the resources and schema used in the metadata descriptions. They are structured as follows:

```
metadata.json
  table-group:
    schema: "gov.uk/schema.json"
    resources: 
      organisation @id: "hefce.gov.uk/organisation.csv"
      units @id: "hefce.gov.uk/units.csv"
      job-titles @id: "hefce.gov.uk/job-titles.csv"
      junior-grades @id: "hefce.gov.uk/junior-grades.csv"
      senior-data @id: "source/HEFCE_organogram_senior_data_31032011.csv"
      junior-data @id: "source/HEFCE_organogram_senior_data_31032011.csv"

gov.uk/schema.json
  table-group:
    resources:
      departments @id: “departments.csv"
        columns: department
      grades @id: "grades.csv"
        columns: grade
      professions @id: “professions.csv"
        columns: profession
      organisation
        columns: organisation, department
      units
        columns: unit, organisation
      job-titles
        columns: job-title
      junior-grades
        columns: grade, minimum-pay, maximum-pay
      senior-data
        columns: id, name, grade: reference “grades#grade”, job-title, job-function, unit: reference “units#unit”, phone, email, reports-to: reference senior-data#id, salary-of-reports, fte, pay-floor, pay-ceiling, profession: reference “professions#profession”, notes, valid
      junior-data
        columns: unit, reporting-to: reference senior-data#id, grade: reference “junior-grades#grade”, job-title: reference “job-titles#job-title”, posts, profession: reference “professions#profession" 
```

Here are the problems I discovered based on what the [metadata spec](http://w3c.github.io/csvw/metadata/) currently states:

1) table descriptions cannot include column description objects; columns must be defined within a schema description object
2) `resources` arrays cannot include schema description objects; an array of schema objects can be included within a table group description
3) the relationship between a schema and a given table is inferred because they share the same `name` property - but `name` is not a permitted property for schema descriptions nor table descriptions ... and that inference seems dodgy to me.

I propose that:
- tables **must** explicitly define a schema object or import schema descriptions by reference; therefore **`schema` becomes a mandatory property within the table description**
- to import a schema definition we need to reference it by URL; therefore **the `@id` property must be permissible in schema descriptions** (it currently is not) - allowing schemas that are reused to be referenced via that identifier

With these changes in mind, I have revised how the metadata descriptions for UC4 attempt 2 could be structured:

```
metadata.json
  table-group:
    resources: 
      organisation @id: "hefce.gov.uk/organisation.csv"
        schema: "gov.uk/schema.json#organisation"
      units @id: "hefce.gov.uk/units.csv"
        schema: "gov.uk/schema.json#units"
      job-titles @id: "hefce.gov.uk/job-titles.csv"
        schema: "gov.uk/schema.json#job-titles"
      junior-grades @id: "hefce.gov.uk/junior-grades.csv"
        schema: "gov.uk/schema.json#junior-grades"
      senior-data @id: "source/HEFCE_organogram_senior_data_31032011.csv"
        schema: "gov.uk/schema.json#senior-data"
      junior-data @id: "source/HEFCE_organogram_senior_data_31032011.csv"
        schema: "gov.uk/schema.json#junior-data"

gov.uk/schema.json
  table-group:
    resources:
      departments @id: "departments.csv"
        schema:
          columns: department
      grades @id: "grades.csv"
        schema:
          columns: grade
      professions @id: “professions.csv"
        schema:
          columns: profession
    schema:
      @id: "#organisation"
        columns: organisation, department
      @id: "#units"
        columns: unit, organisation
      @id: "#job-titles"
        columns: job-title
      @id: "#junior-grades"
        columns: grade, minimum-pay, maximum-pay
      @id: "#senior-data"
        columns: id, name, grade: reference { “resource”: “grades.csv”, “columns”: “grade” }, job-title, job-function, unit: reference { “schema”: “#units”, “columns”: “unit” }, phone, email, reports-to: reference { “schema”: “#senior-data”, “columns”: “id” }, salary-of-reports, fte, pay-floor, pay-ceiling, profession: reference { “resource”: “professions.csv”, “columns”: “profession” }, notes, valid
      @id: "#junior-data"
        columns: unit, reporting-to: reference { “schema”: “#senior-data”, “columns”: “id” }, grade: reference { “schema”: “#junior-grades”, “columns”: “grade” }, job-title: reference { “schema”: “#job-titles”, “columns”: “job-title” }, posts, profession: reference { “resource”: “professions.csv”, “columns”: “profession” }
```

A few points to note:
- both metadata files provide table group description
- the 'top-level' schema import in `metadata.json` is now replaced by individual imports for each resource
- in `gov.uk/schema.json` where columns were defined in table descriptions, these are now done within structures schema description objects
- in `gov.uk/schema.json` resources that did not refer to data are provided as schema descriptions
- see the use of #-fragment identifiers where multiple schema are defined in a single file; and 
- in the case of the foreign-key references, we are consistently using the `@id` identifier for both (table) resources and schema.

**Comment by gkellogg** [comment]
Perhaps the RDF description of `csvm:schema` (or `csvm:tableSchema`) should have an OWL restriction with cardinality=1?

**Comment by iherman** [comment]
Jeremy,

forgive me... but would it be possible to explain the issue using a much simpler example? I must admit I am a bit lost, not having such an intimate knowledge of all the data files involved...

Ivan

> On 04 Dec 2014, at 17:36 , Jeremy Tandy notifications@github.com wrote:
> 
> I've been trying to get my head around how one would process metadata with table group descriptions, so I began to unpack @JeniT's Use Case 4: Publication of public sector roles and salaries. But having looked at this, .
> 
> Looking at attempt 2 I noticed that it did not now follow the specification in the metadata vocabulary document. To clear things up (in my mind) I listed out the resources and schema used in the metadata descriptions. They are structured as follows:
> 
> metadata.json
>   table-group:
>     schema: "gov.uk/schema.json"
>     resources:
>       organisation @id: "hefce.gov.uk/organisation.csv"
>       units @id: "hefce.gov.uk/units.csv"
>       job-titles @id: "hefce.gov.uk/job-titles.csv"
>       junior-grades @id: "hefce.gov.uk/junior-grades.csv"
>       senior-data @id: "source/HEFCE_organogram_senior_data_31032011.csv"
>       junior-data @id: "source/HEFCE_organogram_senior_data_31032011.csv"
> 
> gov.uk/schema.json
>   table-group:
>     resources:
>       departments @id: “departments.csv"
>         columns: department
>       grades @id: "grades.csv"
>         columns: grade
>       professions @id: “professions.csv"
>         columns: profession
>       organisation
>         columns: organisation, department
>       units
>         columns: unit, organisation
>       job-titles
>         columns: job-title
>       junior-grades
>         columns: grade, minimum-pay, maximum-pay
>       senior-data
>         columns: id, name, grade: reference “grades#grade”, job-title, job-function, unit: reference “units#unit”, phone, email, reports-to: reference senior-data#id, salary-of-reports, fte, pay-floor, pay-ceiling, profession: reference “professions#profession”, notes, valid
>       junior-data
>         columns: unit, reporting-to: reference senior-data#id, grade: reference “junior-grades#grade”, job-title: reference “job-titles#job-title”, posts, profession: reference “professions#profession"
> 
> Here are the problems I discovered based on what the metadata spec currently states:
> 
> 1) table descriptions cannot include column description objects; columns must be defined within a schema description object
> 2) resources arrays cannot include schema description objects; an array of schema objects can be included within a table group description
> 3) the relationship between a schema and a given table is inferred because they share the same name property - but name is not a permitted property for schema descriptions nor table descriptions ... and that inference seems dodgy to me.
> 
> I propose that:
> 
>   • tables must explicitly define a schema object or import schema descriptions by reference; therefore schema becomes a mandatory property within the table description
>   • to import a schema definition we need to reference it by URL; therefore the @id property must be permissible in schema descriptions (it currently is not) - allowing schemas that are reused to be referenced via that identifier
> With these changes in mind, I have revised how the metadata descriptions for UC4 attempt 2 could be structured:
> 
> metadata.json
>   table-group:
>     resources:
>       organisation @id: "hefce.gov.uk/organisation.csv"
>         schema: "gov.uk/schema.json#organisation"
>       units @id: "hefce.gov.uk/units.csv"
>         schema: "gov.uk/schema.json#units"
>       job-titles @id: "hefce.gov.uk/job-titles.csv"
>         schema: "gov.uk/schema.json#job-titles"
>       junior-grades @id: "hefce.gov.uk/junior-grades.csv"
>         schema: "gov.uk/schema.json#junior-grades"
>       senior-data @id: "source/HEFCE_organogram_senior_data_31032011.csv"
>         schema: "gov.uk/schema.json#senior-data"
>       junior-data @id: "source/HEFCE_organogram_senior_data_31032011.csv"
>         schema: "gov.uk/schema.json#junior-data"
> 
> gov.uk/schema.json
>   table-group:
>     resources:
>       departments @id: "departments.csv"
>         schema:
>           columns: department
>       grades @id: "grades.csv"
>         schema:
>           columns: grade
>       professions @id: “professions.csv"
>         schema:
>           columns: profession
>     schema:
>       @id: "#organisation"
>         columns: organisation, department
>       @id: "#units"
>         columns: unit, organisation
>       @id: "#job-titles"
>         columns: job-title
>       @id: "#junior-grades"
>         columns: grade, minimum-pay, maximum-pay
>       @id: "#senior-data"
>         columns: id, name, grade: reference { “resource”: “grades.csv”, “columns”: “grade” }, job-title, job-function, unit: reference { “schema”: “#units”, “columns”: “unit” }, phone, email, reports-to: reference { “schema”: “#senior-data”, “columns”: “id” }, salary-of-reports, fte, pay-floor, pay-ceiling, profession: reference { “resource”: “professions.csv”, “columns”: “profession” }, notes, valid
>       @id: "#junior-data"
>         columns: unit, reporting-to: reference { “schema”: “#senior-data”, “columns”: “id” }, grade: reference { “schema”: “#junior-grades”, “columns”: “grade” }, job-title: reference { “schema”: “#job-titles”, “columns”: “job-title” }, posts, profession: reference { “resource”: “professions.csv”, “columns”: “profession” }
> 
> A few points to note:
> 
>   • both metadata files provide table group description
>   • the 'top-level' schema import in metadata.json is now replaced by individual imports for each resource
>   • in gov.uk/schema.json where columns were defined in table descriptions, these are now done within structures schema description objects
>   • in gov.uk/schema.json resources that did not refer to data are provided as schema descriptions
>   • see the use of #-fragment identifiers where multiple schema are defined in a single file; and
>   • in the case of the foreign-key references, we are consistently using the @id identifier for both (table) resources and schema.
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
I've made a note to add one later. I don't have the head space for that right now :-)

**Comment by JeniT** [comment]
Discussed at Feb F2F. I will update this example based on current spec.

**Comment by JeniT** [comment]
@6a6d74 I think the examples that you've created for the conversion specifications provide all that's needed for this now and we can close the issue. Do you agree?

**Comment by 6a6d74** [comment]
Am happy to close this. (and am now doing so!)
