### ISSUE TITLE
Is it still true that conversion specifications must use the name of a column as the basis for naming machine-readable fields in the target format?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#95]
The [metadata vocabulary doc section 4.3 Converting Tables](http://w3c.github.io/csvw/metadata/#converting-tables) states:

"""
_Conversion specifications must use the name of a column as the basis for naming machine-readable fields in the target format, such as the name of the equivalent element or attribute in XML, property in JSON or property URI in RDF._
"""

Is this still true given our addition of the `predicateURL` property that will override `name` if set?

**Comment by iherman** [comment]
Yep, I think this sentence should be updated (or simply removed) from that document.

> On 05 Dec 2014, at 24:10 , Jeremy Tandy notifications@github.com wrote:
> 
> The metadata vocabulary doc section 4.3 Converting Tables states:
> 
> """
> Conversion specifications must use the name of a column as the basis for naming machine-readable fields in the target format, such as the name of the equivalent element or attribute in XML, property in JSON or property URI in RDF.
> """
> 
> Is this still true given our addition of the predicateURL property that will override name if set?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704
