### ISSUE TITLE
Should the cell-value URI Template be treated as a datatype?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#96]
At the F2F / TPAC, we talked about using URI Templates for cell-level values.

See [line 36, example url templates](https://gist.github.com/JeniT/147021e4408db090326f#file-example-url-templates-L36) from @JeniT's gist.

The object in this example defined as follows:

```
{
      "name": "species",
      "title": "Species",
      "dc:description": "The species of the tree.",
      "subjectUrl": "http://example.org/{GID}",
      "predicateUrl": "http://example.org/ns/species",
      "urlTemplate": "http://example.org/species/{species}",
      "datatype": "string"
}
```

I propose that instead of creating an additional metadata property `subjectUrl`, we use the `datatype` and add the URI Template in the accompanying `format` property ...

```
{
      "name": "species",
      "title": "Species",
      "dc:description": "The species of the tree.",
      "predicateUrl": "http://example.org/ns/species",
      "urlTemplate": "http://example.org/species/{species}",
      "datatype": "uriTemplate",
      "format": "http://example.org/{GID}"
}
```

Thoughts and comments. Seems a reasonable fit to me.

(I also note that this example includes the property `predicateUrl` - which is also not mentioned in the metadata vocabulary - but that's a discussion for another issue)

**Comment by iherman** [comment]
I do not understand...
1. My understanding was that the subject's URI template is such that it sets a common subject for the whole row. In other words, this entry is relevant for the "schema" (whatever the term will be) and not for an individual cell.
2. Your example does not make sense to me. If, for a column, `urlTemplate` is used, this means that the subject (in RDF parlance) is a URIRef which does not have a datatype. In other words, the `datatype` should not occur or, at best, it should be ignored.
3. Finally, I do not understand what you propose. Why is it simpler to use this `format` plus `datatype` combination? `datatype` refers to the value of the cell and its representation; reusing the term for a very different purpose seems to be an error prone thing to me...

Sorry:-)

Ivan

**Comment by 6a6d74** [comment]
I see your confusion. We talked about using URI Templates in three places:

1) to identify the row 
2) for the value of a cell
3) for the `predicateUrl` (see your [ACTION-44](https://www.w3.org/2013/csvw/track/actions/44))

In this particular case I am talking about number 2. You, I think, are talking about number 1.

**Comment by iherman** [comment]
> On 05 Dec 2014, at 11:05 , Jeremy Tandy notifications@github.com wrote:
> 
> I see your confusion. We talked about using URI Templates in three places:
> 
> 1) to identify the row
> 2) for the value of a cell
> 3) for the predicateUrl (see your ACTION-44)
> 
> In this particular case I am talking about number 2. You, I think, are talking about number 1.

Correct. But why would you have 2 in the first place? Did we agree to do that?

Even so, I do not understand your proposal:-(

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
We have number 2 so that we can bind simple string values (which may represent code-list items) in a CSV file to web-resources that are identified by URL. 

I've just noticed that I made a little error in my proposed reworking of the example; I replaced `subjectUrl` instead of `urlTemplate`. Forgive me, it was late.

It should say:

```
{
      "name": "species",
      "title": "Species",
      "dc:description": "The species of the tree.",
      "subjectUrl": "http://example.org/{GID}",
      "predicateUrl": "http://example.org/ns/species",
      "datatype": "uriTemplate",
      "format": "http://example.org/species/{species}"
}
```

(I'm still ignoring `predicateUrl` and `subjectUrl` for now)

So let's say that a row of my tree data says:

```
GID,On Street,Species,Trim Cycle,Inventory Date
1,ADDISON AV,Celtis australis,Large Tree Routine Prune,10/18/2010
{snip}
```

then evaluating the URI Template `http://example.org/species/{species}` gives me `http://example.org/species/Celtis%20australis` which, in my make believe world, is a definition for the species "Celtis australis" (commonly known as the european nettle tree - says Google!).

See requirement [R-AssociationOfCodeValuesWithExternalDefinitions](http://w3c.github.io/csvw/use-cases-and-requirements/#R-AssociationOfCodeValuesWithExternalDefinitions) and its dependent requirement [R-URIMapping](http://w3c.github.io/csvw/use-cases-and-requirements/#R-URIMapping).

**Comment by iherman** [comment]
Ok. Now I understand what you want and... I do not agree:-( I do not agree because I am trying to be awfully pedantic on the RDF site.
- The "datatype" - "format" pair is used to generate RDF Literals.
- The "objectURI", or "urlTemplate", or however we call it, means: (1) the object is _not_ a literal but a URI Reference and (b) this is how you generate the URI for the URI reference

Because RDF makes a strong differentiation between a literal and a URI Reference, I do not think we should mix up these.

What your example does raise, though, is that the following pair might make sense:

"datatype" : "anyURI",
"format"   : "http://example.org/species/{species}"

which yields:

http://example.org/SpecificGID http://example.org/ns/species "http://example.org/species/SpecificSpecies"^^xsd:anyURI .

ie, the uri template may play the role of a picture string, like for dates.

Ivan

> On 05 Dec 2014, at 11:22 , Jeremy Tandy notifications@github.com wrote:
> 
> We have number 2 so that we can bind simple string values (which may represent code-list items) in a CSV file to web-resources that are identified by URL.
> 
> I've just noticed that I made a little error in my proposed reworking of the example; I replaced subjectUrl instead of urlTemplate. Forgive me, it was late.
> 
> It should say:
> 
> {
>       "name": "species",
>       "title": "Species",
>       "dc:description": "The species of the tree.",
>       "subjectUrl": "http://example.org/{GID}",
>       "predicateUrl": "http://example.org/ns/species",
>       "datatype": "uriTemplate",
>       "format": "http://example.org/species/{species}"
> }
> 
> (I'm still ignoring predicateUrl and subjectUrl for now)
> 
> So let's say that a row of my tree data says:
> 
> GID,On Street,Species,Trim Cycle,Inventory Date
> 1,ADDISON AV,Celtis australis,Large Tree Routine Prune,10/18/2010
> {snip}
> 
> then evaluating the URI Template http://example.org/species/{species} gives me http://example.org/species/Celtis%20australis which, in my make believe world, is a definition for the species "Celtis australis" (commonly known as the european nettle tree - says Google!).
> 
> See requirement R-AssociationOfCodeValuesWithExternalDefinitions and its dependent requirement R-URIMapping.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
Note to self: where `separator` property indicates that a cell value shall be parsed into a list of items, `datatype` applies to each item in the list. However, a URI Template can operate on a whole list. Need to work out if these special cases make life too complex.

**Comment by 6a6d74** [comment]
@iherman: I like your use of anyURI. Using the URI Template like a picture string was what I was trying to say ... only not nearly so succinctly as you ;-)

**Comment by iherman** [comment]
> On 05 Dec 2014, at 11:41 , Jeremy Tandy notifications@github.com wrote:
> 
> @iherman: I like your use of anyURI. Using the URI Template like a picture string was what I was trying to say ... only not nearly so succinctly as you ;-)

Yes but that means we need both. anyURI + format, as well as urlTemplate. Is this your understanding, too?

ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
Put the URI Template into the `format` property? As illustrated below:

```
{
      "name": "species",
      "title": "Species",
      "dc:description": "The species of the tree.",
      "datatype": "anyURI",
      "format": "http://example.org/species/{species}"
}
```

**Comment by iherman** [comment]
I do not really understand the question. To make my point clear:

If the template is: 

```
{
      "name": "species",
      "title": "Species",
      "dc:description": "The species of the tree.",
      "datatype": "anyURI",
      "format": "http://example.org/species/{species}"
}
```

The generated RDF Triple is

```
<SomeSubject> <somepredicate> "http://example.org/species/specific-species"^^xsd:anyURI
```

If the template is:

```
{
      "name": "species",
      "title": "Species",
      "dc:description": "The species of the tree.",
      "URLTemplate" : "http://example.org/species/{species}"
}
```

The generated RDF Triple is

```
<SomeSubject> <somepredicate> <http://example.org/species/specific-species>
```

Is this what you mean?

Ivan

**Comment by JeniT** [comment]
The `format` property is usually used to test the format of a cell value, eg holding a regular expression or picture string. It doesn't make sense to me to reuse it as a way of mapping a value to something else entirely. I would only use `datatype` as `anyURI` if the value in the cell was a URI.

Hence the need for a separate property, `urlTemplate` for generating a URI from a value in a cell, when that value might have a whole other datatype such as number or date.

**Comment by gkellogg** [comment]
Just for reference, the Hydra community group is also working on URI templating ([Templated Links](http://www.hydra-cg.com/spec/latest/core/#templated-links)]. This includes both the RFC6570 template string, along with a mapping from variables to RDF properties.

```
{
  "@context": "http://www.w3.org/ns/hydra/context.jsonld",
  "@type": "IriTemplate",
  "template": "http://api.example.com/issues{?q}",
  "mapping": [
    {
      "@type": "IriTemplateMapping",
      "variable": "q",
      "property": "hydra:freetextQuery",
      "required": true
    }
  ]
}
```

**Comment by 6a6d74** [comment]
Interesting stuff. Thanks for the pointer.

**Comment by iherman** [comment]
I just labelled this issue as also relevant to the CSV to RDF mapping. Indeed, the latest version (Dec. 17) of the RDF mapping document does not make the differentiation yet. Indeed, in 4.1.3, I believe that
- when describing the effect of `anyURI`, then the `format` property should be mentioned as a possible way to generate a URI via a template, but it should be clear that the output is still a datatypes string
- when describing the effect of `urlTemplate` then it should be clear that the resulting URI should be used to generate an _RDF URI Resource_, rather than a literal.

**Comment by gkellogg** [comment]
This issue also relates to the contradiction in the use of `urlTemplate` in the metadata and conversion documents. The metadata document describes it as a property of Schema used for creating the unique row identifier. The conversion documents as a Column property to create the object as a URL rather than a Literal.

I propose to follow @iherman's suggestion (essentially), and have three Column properties `subjectUrl`, `predicateUr`l, and `objectUrl`, all of which are _URI Template_ properties. Furthermore, `subjectUrl' replaces`urlTemplate` as a Schema property (or becomes an inherited property).

**Comment by iherman** [comment]
> On 21 Jan 2015, at 18:55 , Gregg Kellogg notifications@github.com wrote:
> 
> This issue also relates to the contradiction in the use of urlTemplate in the metadata and conversion documents. The metadata document describes it as a property of Schema used for creating the unique row identifier. The conversion documents as a Column property to create the object as a URL rather than a Literal.
> 
> I propose to follow @iherman's suggestion (essentially), and have three Column properties subjectUrl, predicateUrl, and objectUrl, all of which are URI Template properties. Furthermore, subjectUrl' replacesurlTemplate` as a Schema property (or becomes an inherited property).

I essentially agree with some minor additional comments.
- We had a discussion at the F2F whether predicateUrl should be a simple string or a template. I think the current decision is the former for a lack of proper use case to turn it into a template. All that being said, it is also a matter of consistency to have all the xxxUrl behave as templates, so I am in favour of that for that reason.
- I think it is by far the simplest approach to consider these as inherited properties. It also allows some shorthands for the metadata authors (ie, to set the objectUrl as a general pattern on the schema level).
- Re-reading the whole issue, I have also spotted a mistake in the csv2rdf document; maybe it is not necessary to get a separate issue. At the moment, the text says, in 4.1.3: "Where the datatype is specified as anyURI, the cell value is inferred to provide a URI (as described in [rfc3986]) rather than a literal value." This could be misunderstood, from an RDF point of view, as if the object would then be a URI reference, ie, not a Literal. This is in contradiction with what we discussed as part of this issue. If one wants to use the cell value as a URI reference, then the metadata should say:
  
  objectUrl = "{col_name}";

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
+1 to everything @iherman said.

**Comment by JeniT** [comment]
Can we use different words for these things please. Most people aren't familiar with the RDF notions of subject, predicate and object. Maybe use `aboutUrl`, `propertyUrl` and `valueUrl`. I also don't understand where it's proposed that these properties sit - on the schema or within a column description? Seems to me that in most cases you'd want the `aboutUrl` to sit on the schema, but you might want to override it for a given column. Does that make sense?

**Comment by iherman** [comment]
> On 28 Jan 2015, at 14:33 , Jeni Tennison notifications@github.com wrote:
> 
> Can we use different words for these things please. Most people aren't familiar with the RDF notions of subject, predicate and object. Maybe use aboutUrl, propertyUrl and valueUrl.

Those are fine with me.

> I also don't understand where it's proposed that these properties sit - on the schema or within a column description? Seems to me that in most cases you'd want the aboutUrl to sit on the schema, but you might want to override it for a given column. Does that make sense?

The natural place for the 'propertyUrl' is probably on the column. If we define it on a schema level (it is a template after all) we may have to define some more 'pseudo' variables for the templates, just as we already have the '_row' variable. Thinks like:
    - '_col' the column number where it is used
    - '_name' the column name where it is used
Maybe these two are enough. If these are defined, then it makes sense to have it defined on the schema, too (and being overwritten by a column)

The natural place for the 'aboutUrl' is the schema. If we defined it for a column, that may mean that a triple for a specific column (or an object for the JSON case) have a different subject, something that we, hitherto, have not considered... I would leave it as a schema and schema-only property for now.

As for the 'valueUrl' it is a bit the same, in this sense, as the 'propertyUrl', ie, it is naturally on a column, but we can extend it to a schema with those additional pseudo variables...

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
I agree that `propertyUrl` and `valueUrl` would be on the column. I think we did discuss at the last F2F how enabling `subjectUrl` to be different for different columns would be useful to add structure to CSV files. I think it's a simple way to do that and we should support it.

**Comment by iherman** [comment]
> On 28 Jan 2015, at 15:18 , Jeni Tennison notifications@github.com wrote:
> 
> I agree that propertyUrl and valueUrl would be on the column. I think we did discuss at the last F2F how enabling subjectUrl

you mean 'aboutUrl' :-)

> to be different for different columns would be useful to add structure to CSV files. I think it's a simple way to do that and we should support it.

O.k.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
Actually... this has effects on the JSON/RDF conversions in a not-absolutely-trivial manner.

The current structure in, say, JSON, is something like:

```
{
"url: "data.csv",
"row" : [
  {
    "url" : "whatever the aboutUrl template expands to",
    "GID" : "1",
    "on_street" : "ADDISON AV",
    etc.
  }
  {
    ... data for second row...
  }
...
  }]
}
```

This structure is then distorted if, say, there is a separate `aboutUrl` for the column with name `GID`. Or would we consider them as being separate 'rows'? Or should we remove the usage for the "row" structure in the first place?

(The RDF structure is similar...).

Ie, I am slightly less convinced than I was 10 minutes ago:-)

Ivan

> On 28 Jan 2015, at 15:40 , Ivan Herman ivan@w3.org wrote:
> 
> > On 28 Jan 2015, at 15:18 , Jeni Tennison notifications@github.com wrote:
> > 
> > I agree that propertyUrl and valueUrl would be on the column. I think we did discuss at the last F2F how enabling subjectUrl
> 
> you mean 'aboutUrl' :-)
> 
> > to be different for different columns would be useful to add structure to CSV files. I think it's a simple way to do that and we should support it.
> 
> O.k.
> 
> Ivan
> 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> ---
> 
> Ivan Herman, W3C
> Digital Publishing Activity Lead
> Home: http://www.w3.org/People/Ivan/
> mobile: +31-641044153
> ORCID ID: http://orcid.org/0000-0003-0782-2704

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
> On 28 Jan 2015, at 15:49 , Ivan Herman ivan@w3.org wrote:
> 
> Actually... this has effects on the JSON/RDF conversions in a not-absolutely-trivial manner.
> 
> The current structure in, say, JSON, is something like:
> 
> ```
> {
> "url: "data.csv",
> "row" : [
>  {
>    "url" : "whatever the aboutUrl template expands to",
>    "GID" : "1",
>    "on_street" : "ADDISON AV",
>    etc.
>  }
>  {
>    ... data for second row...
>  }
> ...
>  }]
> }
> ```
> 
> This structure is then distorted if, say, there is a separate `aboutUrl` for the row with name `GID`. Or would we consider them as

Doh, sorry. 'row' -> 'column'

> being separate 'rows'? Or should we remove the usage for the "row" structure in the first place?
> 
> (The RDF structure is similar...).
> 
> Ie, I am slightly less convinced than I was 10 minutes ago:-)
> 
> Ivan
> 
> > On 28 Jan 2015, at 15:40 , Ivan Herman ivan@w3.org wrote:
> > 
> > > On 28 Jan 2015, at 15:18 , Jeni Tennison notifications@github.com wrote:
> > > 
> > > I agree that propertyUrl and valueUrl would be on the column. I think we did discuss at the last F2F how enabling subjectUrl
> > 
> > you mean 'aboutUrl' :-)
> > 
> > > to be different for different columns would be useful to add structure to CSV files. I think it's a simple way to do that and we should support it.
> > 
> > O.k.
> > 
> > Ivan
> > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > 
> > ---
> > 
> > Ivan Herman, W3C
> > Digital Publishing Activity Lead
> > Home: http://www.w3.org/People/Ivan/
> > mobile: +31-641044153
> > ORCID ID: http://orcid.org/0000-0003-0782-2704
> 
> ---
> 
> Ivan Herman, W3C
> Digital Publishing Activity Lead
> Home: http://www.w3.org/People/Ivan/
> mobile: +31-641044153
> ORCID ID: http://orcid.org/0000-0003-0782-2704

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by danbri** [comment]
See http://www.w3.org/2015/01/28-csvw-irc#T15-49-40

**Comment by gkellogg** [comment]
RESOLUTION: adopt three separate Url properties (about/property/value), editor to suggest exactly how that works within a PR

**Comment by gkellogg** [comment]
I've taken a stab at updating metadata and csv2rdf docs to handle aboutUrl, propertyUrl and valueUrl. Note that to hang to gather, we probably also need to consider supporting _phantom columns_ so that cells having different subjects can be related with each other.

For JSON, I think that the row object is defined based on the first cell, and cells having a different aboutUrl value are nested, something like the following:

```
{
  "url": "tree-ops",
  "distribution": {
    "downloadURL": "http://example.org/tree-ops.csv"
  },
  "dc:title": "Tree Operations",
  "dc:keywords": ["tree", "street", "maintenance"],
  "dc:publisher": [{
    "schema:name": "Example Municipality",
    "schema:web": "http://example.org"
  }],
  "dc:license": "http://opendefinition.org/licenses/cc-by/",
  "dc:modified": "2010-12-31",
  "row": [{
    "url": "http://example.org/tree-ops.csv#gid-1",
    "GID": "1",
    "on-street": "ADDISON AV",
    "species": {
      "url": "http://example.org/spiecies#gid-1",
      "value": "Celtis australis"
    },
    "trim-cycle": "Large Tree Routine Prune",
    "inventory-date": "10/18/2010"
  },{
    "url": "http://example.org/tree-ops.csv#gid-2",
    "GID": "2",
    "on-street": "EMERSON ST",
    "species": {
      "url": "http://example.org/spiecies#gid-2",
      "value": "Liquidambar styraciflua"
    },
    "trim-cycle": "Large Tree Routine Prune",
    "inventory-date": "6/2/2010"
  },{
    "url": "http://example.org/tree-ops.csv#gid-3",
    "GID": "3",
    "on-street": "EMERSON ST",
    "species": {
      "url": "http://example.org/spiecies#gid-3",
      "value": "Liquidambar styraciflua"
    },
    "trim-cycle": "Large Tree Routine Prune",
    "inventory-date": "6/2/2010"
  }],
  "describedBy": "http://example.org/tree-ops.csv-metadata.json"
}
```

**Comment by iherman** [comment]
The only open issue in this thread is the issue of 'phantom' columns. I have created a separate issue for that one, namely, #179 and this issue can now be closed as soon as the editorial work is completed.

**Comment by gkellogg** [comment]
Closing as #179 is now closed.
