### ISSUE TITLE
What should the name of the property be that relates rows to the table?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#97]
A property is needed to relate rows to tables in both JSON and CSV mapping. `row` is one option; `hasRow` is another.

Whichever, I think the property name is singular (e.g. `row` not `rows`) because it’s the relationship between the table and an individual row - it just happens that, say, JSON syntax allows duplicate keys to be bundled up into an array.

Thoughts?

**Comment by gkellogg** [comment]
`csvm:hasRow` seems reasonable in an RDF transformation, or alternatively, relate each row with the table it comes from to the `csvm:Table` resource using something like `csvm:inTable`.

For JSON, clearly we will link Table to Row, and `row` sounds better in that context than `hasRow`.

**Comment by JeniT** [comment]
@6a6d74 I think this has been resolved? Can you close?

**Comment by danbri** [comment]
See http://www.w3.org/2015/02/12-csvw-irc#T17-29-05
